/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  l1edps_SCH_TX_SIMULT_02.h
 *
 * Project:
 * --------
 *   MOLY
 *
 * Description:
 * ------------
 *  Parameters define value between SS and UE
 *
 * Author:
 * -------
 * -------
 *
 * ==========================================================================
 * $Log$
 *
 * 06 09 2015 david.tang
 * [MOLY00112427] [MT6291][E1EVB][EL1S] Update l1edps files from CBr4
 * .[l1edps] update l1edps from cbr
 *
 ****************************************************************************/



#ifndef _L1EDPS_SCH_TX_01_H
#define _L1EDPS_SCH_TX_01_H

#include "l1edps_common_parameters.h"

#undef DL_EARFCN_BTS1
#undef MIB_DL_BANDWIDTH_BTS1
#undef SIB2_UL_BANDWIDTH_BTS1 
#undef SIB1_SUBFRAME_ASSIGNMENT_BTS1
#undef SIB1_SPECIAL_SUBFRAME_PATTERN_BTS1

#undef RRC_SETUP_PUCCH_FORMAT_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_0_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_1_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_2_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_3_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_0_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_1_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_2_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_3_BTS1
#undef RRC_SETUP_SIMULTANEOUS_PUCCH_PUSCH_BTS1
#undef RRC_RECONFIG_PUCCH_FORMAT_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_0_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_1_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_2_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_3_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_0_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_1_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_2_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_3_BTS1
#undef RRC_RECONFIG_SIMULTANEOUS_PUCCH_PUSCH_BTS1
#undef SIB2_DELTA_PUCCH_SHIFT_BTS1
#undef SIB2_NRB_CQI_BTS1
#undef SIB2_NCS_AN_BTS1
#undef SIB2_N1PUCCH_AN_BTS1
#undef RRC_SETUP_SR_PUCCH_RESOURCE_INDEX_BTS1
#undef RRC_SETUP_CQI_REPORT_PERIODIC_SETUP_BTS1
#undef RRC_SETUP_CQI_PUCCH_RESOURCE_INDEX_BTS1
#undef RRC_SETUP_SIMULTANEOUS_ACK_NACK_AND_CQI_BTS1
#undef RRC_SETUP_CQI_PMI_CONFIG_INDEX_BTS1
#undef RRC_SETUP_CQI_FORMAT_INDICATOR_PERIODIC_BTS1
#undef RRC_SETUP_BETA_OFFSET_ACK_INDEX_BTS1
#undef RRC_SETUP_BETA_OFFSET_RI_INDEX_BTS1
#undef RRC_SETUP_BETA_OFFSET_CQI_INDEX_BTS1




#define DL_EARFCN_BTS1 38450
#define MIB_DL_BANDWIDTH_BTS1 BW_100_RB
#define SIB2_UL_BANDWIDTH_BTS1 BW_100_RB
#define SIB1_SUBFRAME_ASSIGNMENT_BTS1 SUBFRAME_ASSIGNMENT_sa1
#define SIB1_SPECIAL_SUBFRAME_PATTERN_BTS1 SPECIAL_SUBFRAME_PATTERN_ssp6

#define RRC_SETUP_PUCCH_FORMAT_BTS1 0xFF //0:FMT3; 1:CS
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_0_BTS1	7
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_1_BTS1	8
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_2_BTS1	9
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_3_BTS1	10
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_0_BTS1	11
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_1_BTS1	12
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_2_BTS1	13
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_3_BTS1	14
#define RRC_SETUP_SIMULTANEOUS_PUCCH_PUSCH_BTS1 L1S_SETUP
#define RRC_RECONFIG_PUCCH_FORMAT_BTS1 0xFF //0:FMT3; 1:CS
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_0_BTS1  7
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_1_BTS1  8
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_2_BTS1  9
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_3_BTS1  10
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_0_BTS1  11
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_1_BTS1  12
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_2_BTS1  13
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_3_BTS1  14
#define RRC_RECONFIG_SIMULTANEOUS_PUCCH_PUSCH_BTS1 L1S_SETUP
#define SIB2_DELTA_PUCCH_SHIFT_BTS1 1
#define SIB2_NRB_CQI_BTS1 1
#define SIB2_NCS_AN_BTS1 6
#define SIB2_N1PUCCH_AN_BTS1 15
#define RRC_SETUP_SR_PUCCH_RESOURCE_INDEX_BTS1 1
#define RRC_SETUP_CQI_REPORT_PERIODIC_SETUP_BTS1 L1S_SETUP
#define RRC_SETUP_CQI_PUCCH_RESOURCE_INDEX_BTS1 0
#define RRC_SETUP_SIMULTANEOUS_ACK_NACK_AND_CQI_BTS1 1
#define RRC_SETUP_CQI_PMI_CONFIG_INDEX_BTS1 5
#define RRC_SETUP_CQI_FORMAT_INDICATOR_PERIODIC_BTS1 CQI_FORMAT_INDICATOR_PERIODIC_widebandCQI
#define RRC_SETUP_BETA_OFFSET_ACK_INDEX_BTS1 10
#define RRC_SETUP_BETA_OFFSET_RI_INDEX_BTS1 12
#define RRC_SETUP_BETA_OFFSET_CQI_INDEX_BTS1 15

#endif

