/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  l1edps_SCH_MBMS_MCCH_02.h
 *
 * Project:
 * --------
 *   UMOLY
 *
 * Description:
 * ------------
 *  Parameters define value between SS and UE
 *
 * Author:
 * -------
 * -------
 *
 * ==========================================================================
 * $Log$
 *
 * 02 23 2016 panu.peisa
 * [MOLY00147611] MT6292 EL1 code merge from UMOLY_92L1Dev CBr to UMOLY
 * Integrated mcu/common, mcu/make and mcu/pcore changes from  2084256 to 2095461 ( swrd part )..
 *
 * 10 14 2015 david.tang
 * [MOLY00145122] [MT6291][E1EVB][EL1S] Update l1edps mbms header files
 * . update mbms header file
 *
 * 10 13 2015 david.tang
 * [MOLY00145122] [MT6291][E1EVB][EL1S] Update l1edps mbms header files
 * . mbms config
 *
 * 08 11 2015 david.tang
 * [MOLY00136416] [MT6291][E1EVB][EL1S] Update l1edps files and add mbms test cases support
 * .[l1edps] update mbms header files
 *
 * 08 10 2015 david.tang
 * [MOLY00136416] [MT6291][E1EVB][EL1S] Update l1edps files and add mbms test cases support
 * [l1edps] update header files.
 *
 * 05 04 2015 david.tang
 * [MOLY00109013] [MT6291][E1EVB][EL1S] Update l1edps files from CBr
 * .[l1edps] update l1edps from cbr - evb.v3
 *
 ****************************************************************************/



#ifndef _L1SS_SCH_MBMS_MCCH_02_H
#define _L1SS_SCH_MBMS_MCCH_02_H

#include "l1edps_common_parameters.h"

#undef DL_EARFCN_BTS1
#undef DL_EARFCN_BTS2
#undef MIB_DL_BANDWIDTH_BTS1
#undef MIB_DL_BANDWIDTH_BTS2	
#undef SIB1_SUBFRAME_ASSIGNMENT_BTS1
#undef SIB1_SPECIAL_SUBFRAME_PATTERN_BTS1
#undef SIB1_SI_WINDOW_LENGTH_BTS1 
#undef SIB1_SI1_PERIODICITY_BTS1 
#undef SIB1_SI2_PERIODICITY_BTS1 
#undef SIB2_UL_BANDWIDTH_BTS1 
#undef SIB2_DEFAULT_PAGING_CYCLE_BTS1
#undef SIB2_NB_BTS1
#undef PAGING_IMSI

#undef SIB2_MBSFN_SUBFRAME_CONFIG_LIST_BTS1
#undef SIB2_MBSFN_SUBFRAME_CONFIG_LIST_1_RADIOFRAME_ALLOCATION_PERIOD_BTS1
#undef SIB2_MBSFN_SUBFRAME_CONFIG_LIST_1_RADIOFRAME_ALLOCATION_OFFSET_BTS1
#undef SIB2_MBSFN_SUBFRAME_CONFIG_LIST_1_SUBFRAME_ALLOCATION_LENGTH_BTS1
#undef SIB2_MBSFN_SUBFRAME_CONFIG_LIST_1_SUBFRAME_ALLOCATION_PATTERN_BTS1

#undef SIB13_MBSFN_1_AREA_ID_BTS1
#undef SIB13_MBSFN_1_NON_MBSFN_REGION_LENGTH_BTS1
#undef SIB13_MBSFN_1_NOTIFICATION_INDICATOR_BTS1
#undef SIB13_MBSFN_1_MCCH_REPETITION_PERIOD_BTS1
#undef SIB13_MBSFN_1_MCCH_OFFSET_BTS1
#undef SIB13_MBSFN_1_MCCH_MODIFICATION_PERIOD_BTS1
#undef SIB13_MBSFN_1_MCCH_SF_ALLOC_INFO_BTS1
#undef SIB13_MBSFN_1_MCCH_SIGNALLING_MCS_BTS1
#undef SIB13_MBMS_NOTIFICATION_REPETITION_COEFF_BTS1
#undef SIB13_MBMS_NOTIFICATION_OFFSET_BTS1
#undef SIB13_MBMS_NOTIFICATION_SF_INDEX_BTS1
#undef RRC_RECONFIG_SCELL_PHYSICAL_CONFIG_DEDICATED_CCS_CONFIG_BTS1
#undef RRC_RECONFIG_SCELL_PHYSICAL_CONFIG_DEDICATED_CCS_CONFIG_OTHER_SCHEDULING_CELLID_BTS1
#undef RRC_RECONFIG_SCELL_PHYSICAL_CONFIG_DEDICATED_CCS_CONFIG_OTHER_PDSCH_START_BTS1
#undef RRC_SETUP_CIF_PRESENCE_BTS1
#undef RRC_SETUP_PUCCH_FORMAT_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_0_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_1_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_2_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_3_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_0_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_1_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_2_BTS1
#undef RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_3_BTS1
#undef RRC_RECONFIG_PUCCH_FORMAT_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_0_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_1_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_2_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_3_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_0_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_1_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_2_BTS1
#undef RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_3_BTS1

#undef MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_PERIOD_BTS1
#undef MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_1_FRAME_ALLOC_PERIOD_BTS1
#undef MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_1_FRAME_ALLOC_OFFSET_BTS1
#undef MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_1_SUBFRAME_ALLOCATION_LENGTH_BTS1
#undef MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_1_SUBFRAME_ALLOCATION_PATTERN_BTS1
#undef MCCH_MSG_MBSFN_AREA_CONFIGURATION_PMCH_INFO_1_PMCH_CONFIG_SF_ALLOC_END_BTS1
#undef MCCH_MSG_MBSFN_AREA_CONFIGURATION_PMCH_INFO_1_PMCH_CONFIG_DATA_MCS_BTS1
#undef MCCH_MSG_MBSFN_AREA_CONFIGURATION_PMCH_INFO_1_PMCH_CONFIG_MCH_SCHEDULING_PERIOD_BTS1


#define DL_EARFCN_BTS1 38450
#define DL_EARFCN_BTS2 38648
#define MIB_DL_BANDWIDTH_BTS1 BW_100_RB
#define MIB_DL_BANDWIDTH_BTS2 BW_100_RB
#define SIB1_SUBFRAME_ASSIGNMENT_BTS1 SUBFRAME_ASSIGNMENT_sa1
#define SIB1_SPECIAL_SUBFRAME_PATTERN_BTS1 SPECIAL_SUBFRAME_PATTERN_ssp6
#define SIB1_SI_WINDOW_LENGTH_BTS1 SI_WINDOW_LENGTH_ms20
#define SIB1_SI1_PERIODICITY_BTS1 SI_PERIODICITY_rf16
#define SIB1_SI2_PERIODICITY_BTS1 SI_PERIODICITY_rf32
#define SIB2_UL_BANDWIDTH_BTS1 BW_100_RB
#define SIB2_DEFAULT_PAGING_CYCLE_BTS1 DEFAULT_PAGING_CYCLE_RF128
#define SIB2_NB_BTS1 NB_oneEightT
#define PAGING_IMSI 8

#define SIB2_MBSFN_SUBFRAME_CONFIG_LIST_BTS1 L1S_SETUP
#define SIB2_MBSFN_SUBFRAME_CONFIG_LIST_1_RADIOFRAME_ALLOCATION_PERIOD_BTS1 RADIOFRAME_ALLOCATION_PERIOD_n1
#define SIB2_MBSFN_SUBFRAME_CONFIG_LIST_1_RADIOFRAME_ALLOCATION_OFFSET_BTS1 0
#define SIB2_MBSFN_SUBFRAME_CONFIG_LIST_1_SUBFRAME_ALLOCATION_LENGTH_BTS1 SUBFRAME_ALLOCATION_LENGTH_ONE_FRAME
#define SIB2_MBSFN_SUBFRAME_CONFIG_LIST_1_SUBFRAME_ALLOCATION_PATTERN_BTS1 (MBSFN_SF3|MBSFN_SF4|MBSFN_SF8|MBSFN_SF9) /* TDD CFG2 */

#define SIB13_MBSFN_1_AREA_ID_BTS1 0
#define SIB13_MBSFN_1_NON_MBSFN_REGION_LENGTH_BTS1 MBSFN_NON_MBSFN_REGION_LENGTH_s2
#define SIB13_MBSFN_1_NOTIFICATION_INDICATOR_BTS1 0 //(0..7)
#define SIB13_MBSFN_1_MCCH_REPETITION_PERIOD_BTS1 MCCH_REPETITION_PERIOD_rf32 //(0..7)
#define SIB13_MBSFN_1_MCCH_OFFSET_BTS1 0 //(0..10)
#define SIB13_MBSFN_1_MCCH_MODIFICATION_PERIOD_BTS1 MCCH_MODIFICATION_PERIOD_rf1024 //(0..7)
#define SIB13_MBSFN_1_MCCH_SF_ALLOC_INFO_BTS1 MBSFN_SF3
#define SIB13_MBSFN_1_MCCH_SIGNALLING_MCS_BTS1 MCCH_SIGNALLING_MCS_n19
#define SIB13_MBMS_NOTIFICATION_REPETITION_COEFF_BTS1 MBMS_NOTIFICATION_REPETITION_COEFF_n4
#define SIB13_MBMS_NOTIFICATION_OFFSET_BTS1 0 //0..10
#define SIB13_MBMS_NOTIFICATION_SF_INDEX_BTS1 1 //1..6
#define RRC_RECONFIG_SCELL_PHYSICAL_CONFIG_DEDICATED_CCS_CONFIG_BTS1 L1S_SETUP
#define RRC_RECONFIG_SCELL_PHYSICAL_CONFIG_DEDICATED_CCS_CONFIG_OTHER_SCHEDULING_CELLID_BTS1 0
#define RRC_RECONFIG_SCELL_PHYSICAL_CONFIG_DEDICATED_CCS_CONFIG_OTHER_PDSCH_START_BTS1 3
#define RRC_SETUP_CIF_PRESENCE_BTS1 KAL_TRUE	
#define RRC_SETUP_PUCCH_FORMAT_BTS1 1 //0:FMT3; 1:CS
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_0_BTS1	101
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_1_BTS1	102
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_2_BTS1	103
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_0_3_BTS1	104
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_0_BTS1	105
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_1_BTS1	106
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_2_BTS1	107
#define RRC_SETUP_N1_PUCCH_AN_CS_LIST_1_3_BTS1	108
#define RRC_RECONFIG_PUCCH_FORMAT_BTS1 1 //0:FMT3; 1:CS
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_0_BTS1  101
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_1_BTS1  102
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_2_BTS1  103
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_0_3_BTS1  104
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_0_BTS1  105
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_1_BTS1  106
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_2_BTS1  107
#define RRC_RECONFIG_N1_PUCCH_AN_CS_LIST_1_3_BTS1  108

#define MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_PERIOD_BTS1 MBMS_CSA_PERIOD_n8
#define MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_1_FRAME_ALLOC_PERIOD_BTS1 RADIOFRAME_ALLOCATION_PERIOD_n1
#define MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_1_FRAME_ALLOC_OFFSET_BTS1 0
#define MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_1_SUBFRAME_ALLOCATION_LENGTH_BTS1 SUBFRAME_ALLOCATION_LENGTH_ONE_FRAME
#define MCCH_MSG_MBSFN_AREA_CONFIGURATION_CSA_1_SUBFRAME_ALLOCATION_PATTERN_BTS1 (MBSFN_SF3|MBSFN_SF4|MBSFN_SF8|MBSFN_SF9) /* TDD CFG2 */
#define MCCH_MSG_MBSFN_AREA_CONFIGURATION_PMCH_INFO_1_PMCH_CONFIG_SF_ALLOC_END_BTS1 31
#define MCCH_MSG_MBSFN_AREA_CONFIGURATION_PMCH_INFO_1_PMCH_CONFIG_DATA_MCS_BTS1 19
#define MCCH_MSG_MBSFN_AREA_CONFIGURATION_PMCH_INFO_1_PMCH_CONFIG_MCH_SCHEDULING_PERIOD_BTS1 MBMS_MSP_PERIOD_n8

#endif



