/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 *
 * Filename:
 * ---------
 *   c2k_custom_rf_tas_tst.h
 *
 * Project:
 * --------
 *   MT6293
 *
 * Description:
 * ------------
 *   C2K  TAS TST
 *
 * Author:
 * -------
 *
 *
 *******************************************************************************/

#ifndef  _C2K_CUSTOM_RF_TAS_TST_Set3_H_
#define  _C2K_CUSTOM_RF_TAS_TST_Set3_H_
/* ------------------------------------------------------------------------- */

#define C2K_TAS_TST_CONFIG_ENABLE_Set3 C2K_TAS_TST_DISABLE

#define C2K_TAS_TST_BAND_A_STATE0_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_A_STATE1_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_A_STATE2_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_A_STATE3_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_A_STATE4_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_A_STATE5_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_A_STATE6_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_A_STATE7_Set3 C2K_TAS_DISBLE

#define C2K_TAS_TST_BAND_B_STATE0_Set3 C2K_TAS_ENABLE
#define C2K_TAS_TST_BAND_B_STATE1_Set3 C2K_TAS_ENABLE
#define C2K_TAS_TST_BAND_B_STATE2_Set3 C2K_TAS_ENABLE
#define C2K_TAS_TST_BAND_B_STATE3_Set3 C2K_TAS_ENABLE
#define C2K_TAS_TST_BAND_B_STATE4_Set3 C2K_TAS_ENABLE
#define C2K_TAS_TST_BAND_B_STATE5_Set3 C2K_TAS_ENABLE
#define C2K_TAS_TST_BAND_B_STATE6_Set3 C2K_TAS_ENABLE
#define C2K_TAS_TST_BAND_B_STATE7_Set3 C2K_TAS_ENABLE

#define C2K_TAS_TST_BAND_C_STATE0_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_C_STATE1_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_C_STATE2_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_C_STATE3_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_C_STATE4_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_C_STATE5_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_C_STATE6_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_C_STATE7_Set3 C2K_TAS_DISBLE

#define C2K_TAS_TST_BAND_D_STATE0_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_D_STATE1_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_D_STATE2_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_D_STATE3_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_D_STATE4_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_D_STATE5_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_D_STATE6_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_D_STATE7_Set3 C2K_TAS_DISBLE

#define C2K_TAS_TST_BAND_E_STATE0_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_E_STATE1_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_E_STATE2_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_E_STATE3_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_E_STATE4_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_E_STATE5_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_E_STATE6_Set3 C2K_TAS_DISBLE
#define C2K_TAS_TST_BAND_E_STATE7_Set3 C2K_TAS_DISBLE

#define C2K_TAS_TST_BAND_A_Set3 SYS_BAND_CLASS_0
#define C2K_TAS_TST_BAND_B_Set3 SYS_BAND_CLASS_1
#define C2K_TAS_TST_BAND_C_Set3 SYS_BAND_CLASS_10
#define C2K_TAS_TST_BAND_D_Set3 SYS_BAND_CLASS_NOT_USED
#define C2K_TAS_TST_BAND_E_Set3 SYS_BAND_CLASS_NOT_USED
#endif
