/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/


/*****************************************************************************
 *
 * Filename:
 * ---------
 *   intrCtrl_ELBRUS_SW_Handle.h
 *
 * Project:
 * --------
 *   ELBRUS
 *
 * Description:
 * ------------
 *   This file define software interrupt handler.
 *
 * Author:
 * -------
 * -------
 *
 * ==========================================================================
 * $Log$
 *
 * 02 22 2016 i-chun.liu
 * [MOLY00165445] [MT6292][FPGA][Phone Call][4G FDD][Critical] Information about spurious interrupt lost with SST exception flow
 * MDCIRQ driver update.
 * SW_TRIGGER_CODE43-SW_TRIGGER_CODE54 is in the start to prevent SW_HANDLE_END small than SW_TRIGGER_CODEX
 *
 * 02 04 2016 i-chun.liu
 * [MOLY00140199] MT6292 MDCIRQ and GIC driver implementation
 * add CIRQ SW trigger interrupts .
 *
 * 10 26 2015 i-chun.liu
 * [MOLY00140199] MT6292 MDCIRQ and GIC driver implementation
 * MDCIRQ SW trigger driver update.
 *
 * 09 30 2015 i-chun.liu
 * [MOLY00135941] UMOLY Trunk merge back for ELBRUS
 * update ELBRUS IRQID table .
 *
 * 08 24 2015 i-chun.liu
 * [MOLY00135941] UMOLY Trunk merge back for ELBRUS
 * fixed CIRQ related build error for ELBRUS.
 *
 * 07 29 2014 linson.du
 * [MOLY00070793] [TK6291]: CIRQ driver update
 * irq id and prority update.
 *
 * 04 24 2014 da.wang
 * [MOLY00062016] Fix build error of porting for TK6291
 * Update internal PMU & SW LISR naming.
 *
 * 07 03 2013 chin-chieh.hung
 * [MOLY00027330] [ARM7toMOLY] ARM7 Build/SYSGEN/Functions Update to TRUNK
 * .
 *
 * 06 04 2013 mogens.christiansen
 * [MOLY00024323] [MT7208][NW-UE SIM][MOLY Regression][TC 6.2.3.31] Assert fail: m14999.c line 1022
 * Fixed SW interrupt mapping in UESIM project
 *
 * 05 24 2013 chin-chieh.hung
 * [MOLY00023372] [MT6290][NW-UE SIM] UESIM MOLY Migration - UESIM related changes submission
 * fix UESIM config error in target build
 *
 * 05 23 2013 chin-chieh.hung
 * [MOLY00023372] [MT6290][NW-UE SIM] UESIM MOLY Migration - UESIM related changes submission
 * UESIM, cirq support
 *
 * 03 25 2013 chin-chieh.hung
 * [MOLY00011352] [Driver] Update for common devdrv driver
 * add sw trigger interrupts
 *
 * 02 04 2013 chin-chieh.hung
 * [MOLY00009725] MT7208 rename to MT6290 - basic platform module
 * chip rename:MT7208 to MT6290
 ****************************************************************************/


/* Add SW handler mapping:
      1st parameter: The name of software handler
      2nd parameter: The software handler number
      3th parameter: The mapping of software handler to hardware interrupt code
   __CR4__ User:
      SW_TRIGGER_CODE1 = Max Weng
      SW_TRIGGER_CODE2 = Max Weng
      SW_TRIGGER_CODE3 = Max Weng
      SW_TRIGGER_CODE4 = Max Weng
      SW_TRIGGER_CODE5 = Max Weng
      SW_TRIGGER_CODE6 = Chuansheng Zhang
      SW_TRIGGER_CODE7 = Chuansheng Zhang
      SW_TRIGGER_CODE8 = Chuansheng Zhang
      SW_TRIGGER_CODE9 = Ivan Hu
      SW_TRIGGER_CODE10 = Kathie Ho
      SW_TRIGGER_CODE11 = Dennis Chueh
      SW_TRIGGER_CODE12 = Dennis Chueh
      SW_TRIGGER_CODE13 = Dennis Chueh
      SW_TRIGGER_CODE14 = Dennis Chueh
      SW_TRIGGER_CODE15 = Dennis Chueh
      SW_TRIGGER_CODE16 = Dennis Chueh
      SW_TRIGGER_CODE17 = Dennis Chueh
      SW_TRIGGER_CODE18 = Crilit Tu
      SW_TRIGGER_CODE19 = Crilit Tu
      SW_TRIGGER_CODE20 = Yung-Chang Chen
      SW_TRIGGER_CODE21 = Chuansheng Zhang
      SW_TRIGGER_CODE22 = Crilit Tu (exception usage)
      SW_TRIGGER_CODE23 = Carl Kao (ADT)
      SW_TRIGGER_CODE24 = Qmei Yang (exception usage)
      SW_TRIGGER_CODE25-42 = Jun-Ying Huang (CCIRQ)
      SW_TRIGGER_CODE43 = HC Yang (dummy lisr)
      SW_TRIGGER_CODE44 = HC Yang (dummy lisr)
      SW_TRIGGER_CODE45 = HC Yang (dummy lisr)
      SW_TRIGGER_CODE46 =
      SW_TRIGGER_CODE47 =
      SW_TRIGGER_CODE48 =
      SW_TRIGGER_CODE49 =
      SW_TRIGGER_CODE50 =
      SW_TRIGGER_CODE51 =
      SW_TRIGGER_CODE52 =
      SW_TRIGGER_CODE53 =
      SW_TRIGGER_CODE54 =
 */
#if (defined(__CR4__) || defined(__MIPS_IA__))
//SW_TRIGGER_CODE43-SW_TRIGGER_CODE54 is in the start to prevent SW_HANDLE_END small than SW_TRIGGER_CODEX
X_SW_HANDLE_CONST(SW_TRIGGER_CODE43, IRQ_SW_LISR25_CODE, IRQ_SW_LISR25_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE44, IRQ_SW_LISR26_CODE, IRQ_SW_LISR26_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE45, IRQ_SW_LISR27_CODE, IRQ_SW_LISR27_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE46, IRQ_SW_LISR28_CODE, IRQ_SW_LISR28_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE47, IRQ_SW_LISR29_CODE, IRQ_SW_LISR29_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE48, IRQ_SW_LISR30_CODE, IRQ_SW_LISR30_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE49, IRQ_SW_LISR31_CODE, IRQ_SW_LISR31_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE50, IRQ_SW_LISR32_CODE, IRQ_SW_LISR32_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE51, IRQ_SW_LISR33_CODE, IRQ_SW_LISR33_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE52, IRQ_SW_LISR34_CODE, IRQ_SW_LISR34_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE53, IRQ_SW_LISR35_CODE, IRQ_SW_LISR35_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE54, IRQ_SW_LISR36_CODE, IRQ_SW_LISR36_CODE)

X_SW_HANDLE_CONST(SW_TRIGGER_CODE1, IRQ_SW_LISR1_CODE, IRQ_SW_LISR1_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE2, IRQ_SW_LISR2_CODE, IRQ_SW_LISR2_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE3, IRQ_SW_LISR3_CODE, IRQ_SW_LISR3_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE4, IRQ_SW_LISR4_CODE, IRQ_SW_LISR4_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE5, IRQ_SW_LISR5_CODE, IRQ_SW_LISR5_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE6, IRQ_SW_LISR6_CODE, IRQ_SW_LISR6_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE7, IRQ_SW_LISR7_CODE, IRQ_SW_LISR7_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE8, IRQ_SW_LISR8_CODE, IRQ_SW_LISR8_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE9, IRQ_SW_LISR9_CODE, IRQ_SW_LISR9_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE10, IRQ_SW_LISR10_CODE, IRQ_SW_LISR10_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE11, IRQ_SW_LISR11_CODE, IRQ_SW_LISR11_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE12, IRQ_SW_LISR12_CODE, IRQ_SW_LISR12_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE13, IRQ_SW_LISR13_CODE, IRQ_SW_LISR13_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE14, IRQ_SW_LISR14_CODE, IRQ_SW_LISR14_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE15, IRQ_SW_LISR15_CODE, IRQ_SW_LISR15_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE16, IRQ_SW_LISR16_CODE, IRQ_SW_LISR16_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE17, IRQ_SW_LISR17_CODE, IRQ_SW_LISR17_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE18, IRQ_SW_LISR18_CODE, IRQ_SW_LISR18_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE19, IRQ_SW_LISR19_CODE, IRQ_SW_LISR19_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE20, IRQ_SW_LISR20_CODE, IRQ_SW_LISR20_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE21, IRQ_SW_LISR21_CODE, IRQ_SW_LISR21_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE22, IRQ_SW_LISR22_CODE, IRQ_SW_LISR22_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE23, IRQ_SW_LISR23_CODE, IRQ_SW_LISR23_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE24, IRQ_SW_LISR24_CODE, IRQ_SW_LISR24_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE25, IRQ_RESERVED_FOR_CC_IRQ_0_CODE, IRQ_RESERVED_FOR_CC_IRQ_0_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE26, IRQ_RESERVED_FOR_CC_IRQ_1_CODE, IRQ_RESERVED_FOR_CC_IRQ_1_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE27, IRQ_RESERVED_FOR_CC_IRQ_2_CODE, IRQ_RESERVED_FOR_CC_IRQ_2_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE28, IRQ_RESERVED_FOR_CC_IRQ_3_CODE, IRQ_RESERVED_FOR_CC_IRQ_3_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE29, IRQ_RESERVED_FOR_CC_IRQ_4_CODE, IRQ_RESERVED_FOR_CC_IRQ_4_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE30, IRQ_RESERVED_FOR_CC_IRQ_5_CODE, IRQ_RESERVED_FOR_CC_IRQ_5_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE31, IRQ_RESERVED_FOR_CC_IRQ_6_CODE, IRQ_RESERVED_FOR_CC_IRQ_6_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE32, IRQ_RESERVED_FOR_CC_IRQ_7_CODE, IRQ_RESERVED_FOR_CC_IRQ_7_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE33, IRQ_RESERVED_FOR_CC_IRQ_8_CODE, IRQ_RESERVED_FOR_CC_IRQ_8_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE34, IRQ_RESERVED_FOR_CC_IRQ_9_CODE, IRQ_RESERVED_FOR_CC_IRQ_9_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE35, IRQ_RESERVED_FOR_CC_IRQ_10_CODE, IRQ_RESERVED_FOR_CC_IRQ_10_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE36, IRQ_RESERVED_FOR_CC_IRQ_11_CODE, IRQ_RESERVED_FOR_CC_IRQ_11_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE37, IRQ_RESERVED_FOR_CC_IRQ_12_CODE, IRQ_RESERVED_FOR_CC_IRQ_12_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE38, IRQ_RESERVED_FOR_CC_IRQ_13_CODE, IRQ_RESERVED_FOR_CC_IRQ_13_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE39, IRQ_RESERVED_FOR_CC_IRQ_14_CODE, IRQ_RESERVED_FOR_CC_IRQ_14_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE40, IRQ_RESERVED_FOR_CC_IRQ_15_CODE, IRQ_RESERVED_FOR_CC_IRQ_15_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE41, IRQ_RESERVED_FOR_CC_IRQ_16_CODE, IRQ_RESERVED_FOR_CC_IRQ_16_CODE)
X_SW_HANDLE_CONST(SW_TRIGGER_CODE42, IRQ_RESERVED_FOR_CC_IRQ_17_CODE, IRQ_RESERVED_FOR_CC_IRQ_17_CODE)

#else
#error "No CPU version select. Need to specify CPU version in project ELBRUS for MDSYS."
#endif

