/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#ifndef  __D2AM_STRUCT_H__
#define  __D2AM_STRUCT_H__

#include "kal_general_types.h"
#include "kal_public_defs.h"
#include "ps_public_enum.h"

#define D2AM_REQ_LOCAL_PARA_HDR     LOCAL_PARA_HDR
#define D2AM_CNF_LOCAL_PARA_HDR     LOCAL_PARA_HDR

typedef enum {
    D2AM_MDALLOW_USER_AP,
    D2AM_MDALLOW_USER_XCAP,
    D2AM_MDALLOW_USER_INVALID,
} d2am_mdallow_user_enum;

typedef enum {
    D2AM_MDALLOW_ACTION_BOOK,
    D2AM_MDALLOW_ACTION_UNBOOK,
} d2am_mdallow_action_enum;

// MSG_ID_D2AM_MDALLOW_REQ
typedef struct {
    D2AM_REQ_LOCAL_PARA_HDR

    d2am_mdallow_action_enum action;
    d2am_mdallow_user_enum user;
} d2am_mdallow_req_struct;

// MSG_ID_D2AM_MDALLOW_CNF
typedef struct {
    D2AM_CNF_LOCAL_PARA_HDR

    kal_bool is_success;
    ps_cause_enum err_cause;
} d2am_mdallow_cnf_struct;

// MSG_ID_D2AM_EAPNABORT_REQ
typedef struct {
    D2AM_REQ_LOCAL_PARA_HDR
} d2am_eapnabort_req_struct;

#endif
