/*!
 *  @file ufpm_enum.h
 *  @author Bo-Kai Huang <bo-kai.haung@mediatek.com>
 *  @version 1.0
 *  @section LICENSE
 *
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of MediaTek Inc. (C) 2005
 *
 *  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 *  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
 *  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 *  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 *  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 *  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
 *  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
 *  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
 *  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 *  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 *  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
 *  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
 *  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
 *  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
 *  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
 *  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
 *
 *  @section DESCRIPTION
 *  This file provides main definitions of usbcore
 */

#ifndef _UFPM_ENUM_H
#define _UFPM_ENUM_H

#include "hif_mw_msgid.h"
#include "kal_public_api.h"

/**************************************
 * UFPM ENUM and Types
 **************************************/

// UFPM state machine 
typedef enum _ufpm_func_state {
    UFPM_FUNC_SM_UNINIT    =   0,
    UFPM_FUNC_SM_DEACTIVATE,
    UFPM_FUNC_SM_ACTIVATE,
} ufpm_func_state_e;

typedef enum _ufpm_usb_state {
    UFPM_USB_SM_RESET   =   0,
    UFPM_USB_SM_CONFIG,
} ufpm_usb_state_e;

// UFPM function events
typedef enum ufpm_usbclass_notify {
    UFPM_USBCLASS_NOTIFY_NONEED =   0,
    UFPM_USBCLASS_NOTIFY_TO_RESET,
    UFPM_USBCLASS_NOTIFY_TO_DETACHED,
    UFPM_USBCLASS_NOTIFY_TO_CONFIG,
} ufpm_usbclass_notify_e;

typedef enum _ufpm_func_mode {
    UFPM_FUNC_MODE_TETHER   =   0,
    UFPM_FUNC_MODE_LOG,
    UFPM_FUNC_MODE_MAX_NUM,
} ufpm_func_mode_e;

typedef enum _ufpm_bus_state {
    UFPM_BUS_STATE_SUSPEND  =   0,
    UFPM_BUS_STATE_RESUME,
    UFPM_BUS_STATE_RESET,
} ufpm_bus_state_e;

#endif  // _UFPM_ENUM_H

