/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2014
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *     dcl_pmic6351_sw.h
 *
 * Project:
 * --------
 *     MOLY Software
 *
 * Description:
 * ------------
 *     This file is for PMIC 6351
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 * HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __DCL_PMIC6351_SW_H_STRUCT__
#define __DCL_PMIC6351_SW_H_STRUCT__

#include "dcl_pmic_features.h"

#ifdef PMIC_6351_REG_API

// Combinational functions
extern void pmic6351_customization_init(void);

typedef enum
{
    MT6351_HWCID,
    MT6351_SWCID,
    MT6351_RG_VPA_MODESET,
    MT6351_BUCK_VMODEM_EN_CTRL,
    MT6351_BUCK_VMODEM_VOSEL_CTRL,
    MT6351_BUCK_VMODEM_EN,
    MT6351_DA_QI_VMODEM_EN,
    MT6351_BUCK_VMODEM_VOSEL,
    MT6351_BUCK_VMODEM_VOSEL_ON,
    MT6351_BUCK_VMODEM_VOSEL_SLEEP,
    MT6351_DA_NI_VMODEM_VOSEL_SYNC,
    MT6351_BUCK_VMD1_EN_CTRL,
    MT6351_BUCK_VMD1_VOSEL_CTRL,
    MT6351_BUCK_VMD1_EN,
    MT6351_DA_QI_VMD1_EN,
    MT6351_BUCK_VMD1_VOSEL,
    MT6351_BUCK_VMD1_VOSEL_ON,
    MT6351_BUCK_VMD1_VOSEL_SLEEP,
    MT6351_DA_NI_VMD1_VOSEL_SYNC,
    MT6351_BUCK_VSRAM_MD_EN_CTRL,
    MT6351_BUCK_VSRAM_MD_VOSEL_CTRL,
    MT6351_BUCK_VSRAM_MD_EN,
    MT6351_DA_QI_VSRAM_MD_EN,
    MT6351_BUCK_VSRAM_MD_VOSEL,
    MT6351_BUCK_VSRAM_MD_VOSEL_ON,
    MT6351_BUCK_VSRAM_MD_VOSEL_SLEEP,
    MT6351_DA_NI_VSRAM_MD_VOSEL_SYNC,
    MT6351_BUCK_VPA_EN_CTRL,
    MT6351_BUCK_VPA_VOSEL_CTRL,
    MT6351_BUCK_VPA_EN_SEL,
    MT6351_BUCK_VPA_VOSEL_SEL,
    MT6351_BUCK_VPA_EN,
    MT6351_BUCK_VPA_VOSEL,
    MT6351_BUCK_VPA_VOSEL_ON,
    MT6351_BUCK_VPA_VOSEL_SLEEP,
    MT6351_DA_NI_VPA_VOSEL_SYNC,
    MT6351_DA_QI_VPA_DVS_EN,
    MT6351_BUCK_VPA_VSLEEP_EN,
    MT6351_BUCK_VPA_R2R_PDN,
    MT6351_BUCK_VPA_VSLEEP_SEL,
    MT6351_RG_VA18_MODE_CTRL,
    MT6351_RG_VA18_ON_CTRL,
    MT6351_RG_VA18_SRCLK_MODE_SEL,
    MT6351_DA_QI_VA18_MODE,
    MT6351_RG_VTCXO24_MODE_SET,
    MT6351_RG_VTCXO24_EN,
    MT6351_RG_VTCXO24_MODE_CTRL,
    MT6351_RG_VTCXO24_ON_CTRL,
    MT6351_RG_VTCXO24_SWITCH,
    MT6351_RG_VTCXO24_SRCLK_MODE_SEL,
    MT6351_DA_QI_VTCXO24_MODE,
    MT6351_RG_VTCXO24_STBTD,
    MT6351_RG_VTCXO24_SRCLK_EN_SEL,
    MT6351_DA_QI_VTCXO24_EN,
    MT6351_RG_VTCXO28_MODE_SET,
    MT6351_RG_VTCXO28_EN,
    MT6351_RG_VTCXO28_MODE_CTRL,
    MT6351_RG_VTCXO28_ON_CTRL,
    MT6351_RG_VTCXO28_SRCLK_MODE_SEL,
    MT6351_DA_QI_VTCXO28_MODE,
    MT6351_RG_VTCXO28_STBTD,
    MT6351_RG_VTCXO28_SRCLK_EN_SEL,
    MT6351_DA_QI_VTCXO28_EN,
    MT6351_DA_QI_VTCXO28_OCFB_EN,
    MT6351_RG_VCAMA_ON_CTRL,
    MT6351_RG_VCAMA_OCFB_EN,
    MT6351_DA_QI_VCAMA_OCFB_EN,
    MT6351_RG_VSIM1_MODE_SET,
    MT6351_RG_VSIM1_EN,
    MT6351_RG_VSIM1_MODE_CTRL,
    MT6351_RG_VSIM1_ON_CTRL,
    MT6351_RG_VSIM1_SRCLK_MODE_SEL,
    MT6351_RG_VSIM1_STBTD,
    MT6351_RG_VSIM1_SRCLK_EN_SEL,
    MT6351_RG_VSIM1_OCFB_EN,
    MT6351_DA_QI_VSIM1_OCFB_EN,
    MT6351_RG_VSIM2_MODE_SET,
    MT6351_RG_VSIM2_EN,
    MT6351_RG_VSIM2_MODE_CTRL,
    MT6351_RG_VSIM2_ON_CTRL,
    MT6351_RG_VSIM2_SRCLK_MODE_SEL,
    MT6351_RG_VSIM2_STBTD,
    MT6351_RG_VSIM2_SRCLK_EN_SEL,
    MT6351_RG_VSIM2_OCFB_EN,
    MT6351_DA_QI_VSIM2_OCFB_EN,
    MT6351_RG_VIBR_MODE_SET,
    MT6351_RG_VIBR_EN,
    MT6351_RG_VIBR_MODE_CTRL,
    MT6351_RG_VIBR_ON_CTRL,
    MT6351_RG_VIBR_THER_SDN_EN,
    MT6351_RG_VIBR_OCFB_EN,
    MT6351_RG_VIBR_DUMMY_LOAD,
    MT6351_DA_QI_VIBR_DUMMY_LOAD,
    MT6351_RG_VCAMD_MODE_SET,
    MT6351_RG_VCAMD_EN,
    MT6351_RG_VCAMD_STBTD,
    MT6351_DA_QI_VCAMD_STB,
    MT6351_DA_QI_VCAMD_EN,
    MT6351_DA_QI_VCAMD_OCFB_EN,
    MT6351_RG_VCAMD_DUMMY_LOAD_SRCLKEN_SEL,
    MT6351_RG_VRF18_MODE_SET,
    MT6351_RG_VRF18_EN,
    MT6351_RG_VRF18_MODE_CTRL,
    MT6351_RG_VRF18_ON_CTRL,
    MT6351_RG_VRF18_SRCLK_MODE_SEL,
    MT6351_DA_QI_VRF18_MODE,
    MT6351_RG_VRF18_STBTD,
    MT6351_RG_VRF18_SRCLK_EN_SEL,
    MT6351_DA_QI_VRF18_STB,
    MT6351_DA_QI_VRF18_EN,
    MT6351_RG_VRF12_MODE_SET,
    MT6351_RG_VRF12_EN,
    MT6351_RG_VRF12_MODE_CTRL,
    MT6351_RG_VRF12_ON_CTRL,
    MT6351_RG_VRF12_SRCLK_MODE_SEL,
    MT6351_DA_QI_VRF12_MODE,
    MT6351_RG_VRF12_STBTD,
    MT6351_RG_VRF12_SRCLK_EN_SEL,
    MT6351_DA_QI_VRF12_EN,
    MT6351_RG_VMIPI_MODE_SET,
    MT6351_RG_VMIPI_EN,
    MT6351_RG_VMIPI_MODE_CTRL,
    MT6351_RG_VMIPI_ON_CTRL,
    MT6351_RG_VMIPI_SRCLK_MODE_SEL,
    MT6351_DA_QI_VMIPI_MODE,
    MT6351_RG_VMIPI_STBTD,
    MT6351_RG_VMIPI_SRCLK_EN_SEL,
    MT6351_DA_QI_VMIPI_EN,
    MT6351_DA_QI_VMIPI_OCFB_EN,
    MT6351_RG_VTCXO28_VOSEL,
    MT6351_RG_VTCXO24_VOSEL,
    MT6351_RG_VSIM1_VOSEL,
    MT6351_RG_VSIM2_CAL,
    MT6351_RG_VSIM2_VOSEL,
    MT6351_RG_VSIM2_STB_SEL,
    MT6351_RG_VSIM2_OC_TRIM,
    MT6351_RG_VEFUSE_CAL,
    MT6351_RG_VEFUSE_STB_SEL,
    MT6351_RG_VEFUSE_OC_TRIM,
    MT6351_RG_VRF18_VOSEL,
    MT6351_RG_VRF12_VOSEL,
    MT6351_RG_VMIPI_VOSEL,
    MT6351_BIF_TEST_MODE0,
    MT6351_BIF_TEST_MODE4,
    MT6351_BIF_TEST_MODE5,
    MT6351_BIF_BAT_LOST_SW,
    MT6351_BIF_IRQ,
    MT6351_BIF_TIMEOUT,
    MT6351_AUXADC_ADC_OUT_CH7_BY_MD,
    MT6351_AUXADC_ADC_RDY_CH7_BY_MD,
    MT6351_AUXADC_ADC_OUT_CH4_BY_MD,
    MT6351_AUXADC_ADC_RDY_CH4_BY_MD,
    MT6351_AUXADC_ADC_OUT_CH0_BY_MD,
    MT6351_AUXADC_ADC_RDY_CH0_BY_MD,
    MT6351_AUXADC_ADC_OUT_CH1_BY_MD,
    MT6351_AUXADC_ADC_RDY_CH1_BY_MD,
    MT6351_AUXADC_ADC_OUT_DCXO_BY_MD,
    MT6351_AUXADC_ADC_RDY_DCXO_BY_MD,
    MT6351_AUXADC_RQST_CH0_BY_MD,
    MT6351_AUXADC_RQST_CH1_BY_MD,
    MT6351_AUXADC_RQST_CH4_BY_MD,
    MT6351_AUXADC_RQST_CH7_BY_MD,
    MT6351_AUXADC_RQST_DCXO_BY_MD,
    MT6351_AUXADC_RQST1_SET,
    MT6351_AUXADC_RQST1_CLR,
}PMIC6351_FLAGS_LIST_ENUM;

#endif // #ifdef PMIC_6351_REG_API
#endif // #ifndef __DCL_PMIC6351_SW_H_STRUCT__

