/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#include "module_msg_range.h"

#ifndef _D2_MSGID_H
#define _D2_MSGID_H

MODULE_MSG_BEGIN( MSG_ID_D2_CODE_BEGIN )
    MSG_ID_ATP_D2AT_MSG_FROM_ATP_BEGIN,
        // intercept CMD to D2
        MSG_ID_ATP_D2AT_CFUN_REQ,
        MSG_ID_ATP_D2AT_EFUN_REQ,
        MSG_ID_ATP_D2AT_CGACT_REQ,
        MSG_ID_ATP_D2AT_CGDCONT_REQ,
        MSG_ID_ATP_D2AT_CGAUTH_REQ, 
        MSG_ID_ATP_D2AT_CGPADDR_REQ, 
        MSG_ID_ATP_D2AT_CGCONTRDP_REQ,
        MSG_ID_ATP_D2AT_EGPCORDP_REQ,
        MSG_ID_ATP_D2AT_BGPCORDP_REQ,
        MSG_ID_ATP_D2AT_CGEREP_REQ,
        MSG_ID_ATP_D2AT_EAPNLOCK_REQ,
        MSG_ID_ATP_D2AT_EAPNSET_REQ,
        MSG_ID_ATP_D2AT_EAPNACT_REQ,
        MSG_ID_ATP_D2AT_EAPNRESV_REQ,
        MSG_ID_ATP_D2AT_EIF_REQ,
        MSG_ID_ATP_D2AT_EPDN_REQ,
        MSG_ID_ATP_D2AT_EGFB_REQ,
        MSG_ID_ATP_D2AT_EDRETRY_REQ,
        MSG_ID_ATP_D2AT_EAID_REQ,
        MSG_ID_ATP_D2AT_EIAAPN_REQ,
        MSG_ID_ATP_D2AT_CGPIAF_REQ,

        MSG_ID_ATP_D2AT_CGDSCONT_REQ,
        MSG_ID_ATP_D2AT_CGTFT_REQ,
        MSG_ID_ATP_D2AT_CGQREQ_REQ,
        MSG_ID_ATP_D2AT_CGQMIN_REQ,
        MSG_ID_ATP_D2AT_CGEQREQ_REQ,
        MSG_ID_ATP_D2AT_CGEQMIN_REQ,
        MSG_ID_ATP_D2AT_CGCMOD_REQ,
        MSG_ID_ATP_D2AT_CGSCONTRDP_REQ,
        MSG_ID_ATP_D2AT_CGTFTRDP_REQ,
        MSG_ID_ATP_D2AT_CGEQOS_REQ,
        MSG_ID_ATP_D2AT_CGEQOSRDP_REQ,
        MSG_ID_ATP_D2AT_ACTTEST_REQ,

        MSG_ID_ATP_D2AT_EDALLOW_REQ,
        MSG_ID_ATP_D2AT_CGANS_REQ,
        MSG_ID_ATP_D2AT_CGEQNEG_REQ,
        MSG_ID_ATP_D2AT_CGDATA_REQ,
        MSG_ID_ATP_D2AT_CGSDATA_REQ,
        MSG_ID_ATP_D2AT_CGDEL_REQ,
        MSG_ID_ATP_D2AT_EGACT_REQ,
        MSG_ID_ATP_D2AT_EGDCONT_REQ,
        MSG_ID_ATP_D2AT_EGDELPF_REQ,
        MSG_ID_ATP_D2AT_EGLD_REQ,
        MSG_ID_ATP_D2AT_EGLNKPF_REQ,
        MSG_ID_ATP_D2AT_EGPAU_REQ,
        MSG_ID_ATP_D2AT_ESIMMAP_REQ,
        MSG_ID_ATP_D2AT_EPSMAP_REQ,
        MSG_ID_ATP_D2AT_LGDCONT_REQ,
        

        
        //DDM -> D2AT
        MSG_ID_D2AT_DDM_CMD_CNF,
        MSG_ID_D2AT_DDM_CGDSCONT_IND,
        MSG_ID_D2AT_DDM_CGTFT_IND,
        MSG_ID_D2AT_DDM_CGQREQ_IND,
        MSG_ID_D2AT_DDM_CGQMIN_IND,
        MSG_ID_D2AT_DDM_CGEQREQ_IND,
        MSG_ID_D2AT_DDM_CGEQMIN_IND,
        MSG_ID_D2AT_DDM_CGSCONTRDP_IND,
        MSG_ID_D2AT_DDM_CGTFTRDP_IND,
        MSG_ID_D2AT_DDM_CGEQOS_IND,
        MSG_ID_D2AT_DDM_CGEQOSRDP_IND,

        MSG_ID_D2AT_DDM_CGACT_IND,
        MSG_ID_D2AT_DDM_CGDCONT_IND,
        MSG_ID_D2AT_DDM_CGAUTH_IND,
        MSG_ID_D2AT_DDM_CGCONTRDP_IND,
        MSG_ID_D2AT_DDM_CGPADDR_IND,

        MSG_ID_D2AT_DDM_EGPCORDP_IND,
        MSG_ID_D2AT_DDM_CGEQNEG_IND,
        MSG_ID_D2AT_DDM_CGDEL_IND,
        MSG_ID_D2AT_DDM_EGDELPF_IND,
        MSG_ID_D2AT_DDM_EGLNKPF_IND,


        // AT respone to D2
        MSG_ID_ATP_D2AT_L4_CMD_CGATT_RSP,
        MSG_ID_ATP_D2AT_L4_CMD_EGTYPE_RSP,
        MSG_ID_ATP_D2AT_L4_CMD_ICCID_RSP,
        MSG_ID_ATP_D2AT_L4_CMD_ICCID_OK_RSP,
        MSG_ID_ATP_D2AT_L4_CMD_EGREA_RSP,

        // notify URC to D2
        MSG_ID_ATP_D2AT_L4_URC_ESIMS_IND,
        MSG_ID_ATP_D2AT_L4_URC_EGREG_IND,
        MSG_ID_ATP_D2AT_L4_URC_EUSIM_IND,
        MSG_ID_D2AM_D2_CMD_RETRY_IND,
    MSG_ID_ATP_D2AT_MSG_FROM_ATP_END,

   // DDM to D2
    MSG_ID_D2PM_DDM_MSG_FROM_DDM_BEGIN,
#if 0
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif
        MSG_ID_D2AM_DDM_DEFINE_ATTACH_PDN_IND,
#if 0
/* under construction !*/
/* under construction !*/
#endif
    MSG_ID_D2PM_DDM_MSG_FROM_DDM_END,

    // IMSM to D2
    MSG_ID_IMSM_D2_MSG_FROM_IMSM_BEGIN,
        MSG_ID_IMSM_D2CM_ACT_DATA_CALL_REQ, 
        MSG_ID_IMSM_D2CM_DEACT_DATA_CALL_REQ, 
        MSG_ID_IMSM_D2CM_ACT_DATA_CALL_RSP, 
        MSG_ID_IMSM_D2CM_DEACT_DATA_CALL_RSP, 
        MSG_ID_IMSM_D2CM_ABORT_DATA_CALL_REQ, 
        MSG_ID_IMSM_IMSM_GET_CELL_INFO_REQ,
    MSG_ID_IMSM_D2_MSG_FROM_IMSM_END, 
// D2 to IMSM
    MSG_ID_IMSM_D2_FROM_D2_BEGIN,
        MSG_ID_IMSM_D2CM_ACT_DATA_CALL_CNF, 
        MSG_ID_IMSM_D2CM_DEACT_DATA_CALL_CNF, 
        MSG_ID_IMSM_D2CM_ACT_DATA_CALL_IND, 
        MSG_ID_IMSM_D2CM_DEACT_DATA_CALL_IND, 
        MSG_ID_IMSM_D2CM_MOD_DATA_CALL_IND, 
        MSG_ID_IMSM_D2CM_ABORT_DATA_CALL_CNF, 
        MSG_ID_IMSM_IMSM_GET_CELL_INFO_CNF,
        MSG_ID_IMSM_D2CM_EAPNLOCK_IND,
        MSG_ID_IMSM_DAST_EAPNLOCK_IND,
    MSG_ID_IMSM_D2_FROM_D2_END,
    // ATP to IMSM
    MSG_ID_ATP_IMSM_FROM_ATP_BEGIN,
        //AT indication to IMSM
        MSG_ID_ATP_IMSM_L4_CMD_INT,
        //AT respone to IMSM
        MSG_ID_ATP_IMSM_L4_CMD_RSP,
        //AT cmd to IMSM
        MSG_ID_ATP_IMSM_EIMSPDN_RSP,
        //AT cmd to IMSM 
        MSG_ID_ATP_IMSM_EWIFIASC_IND,
        MSG_ID_ATP_IMSM_MTU_SIZE_IND,
        //AT cmd to IMSM
        MSG_ID_ATP_IMSM_CLEAN_UNUSED_PDN_IND,
        //AT cmd to IMSM
        MSG_ID_ATP_IMSM_EWOPDNOOS_IND,
    MSG_ID_ATP_IMSM_FROM_ATP_END,

    // D2APN
    MSG_ID_D2APN_BEGIN,
        MSG_ID_D2APN_SET_APN_SETTING_REQ, 
        MSG_ID_D2APN_SET_APN_SETTING_CNF, 
        MSG_ID_D2APN_GET_APN_SETTING_REQ, 
        MSG_ID_D2APN_GET_APN_SETTING_IND, 
        MSG_ID_D2APN_GET_APN_SETTING_CNF, 
        MSG_ID_D2APN_RESET_APN_SETTING_REQ, 
        MSG_ID_D2APN_RESET_APN_SETTING_CNF, 
        MSG_ID_D2APN_APN_SETTING_CHG_IND, 	
    MSG_ID_D2APN_END, 

    // D2CM
    MSG_ID_D2CM_BEGIN,
        MSG_ID_D2CM_GET_PDN_PROFILE_REQ, 
        MSG_ID_D2CM_GET_PDN_PROFILE_IND, 
        MSG_ID_D2CM_GET_PDN_PROFILE_CNF, 
        MSG_ID_D2CM_ACT_DATA_CALL_REQ, 
        MSG_ID_D2CM_ACT_DATA_CALL_CNF, 
        MSG_ID_D2CM_ACT_DATA_CALL_IND, 
        MSG_ID_D2CM_ACT_DATA_CALL_RSP, 
        MSG_ID_D2CM_DEACT_DATA_CALL_REQ, 
        MSG_ID_D2CM_DEACT_DATA_CALL_CNF, 
        MSG_ID_D2CM_DEACT_DATA_CALL_IND, 
        MSG_ID_D2CM_DEACT_DATA_CALL_RSP, 
        MSG_ID_D2CM_ABORT_DATA_CALL_REQ, 
        MSG_ID_D2CM_ABORT_DATA_CALL_CNF, 
        MSG_ID_D2CM_ABORT_DATA_CALL_IND, 
        MSG_ID_D2CM_MOD_DATA_CALL_IND, 
        MSG_ID_D2CM_HO_IND, 
        MSG_ID_D2CM_DATA_CALL_INFO_IND, 
        MSG_ID_D2CM_GET_RETRY_TMR_REQ, 
        MSG_ID_D2CM_GET_RETRY_TMR_CNF, 
        MSG_ID_D2CM_RESET_RETRY_TMR_REQ, 
        MSG_ID_D2CM_RESET_RETRY_TMR_CNF, 
        MSG_ID_D2CM_RESET_RETRY_TMR_IND, 
        MSG_ID_D2CM_NETIF_CONTEXT_DUMP_IND,
        MSG_ID_D2CM_EVENT_IND, 
        MSG_ID_D2CM_BYPASS_REQ, 
        MSG_ID_D2CM_BYPASS_CNF, 
        MSG_ID_D2CM_BYPASS_IND, 
        MSG_ID_D2CM_BYPASS_RSP,
        MSG_ID_D2CM_NETIF_SEND_IMSM_INTERMEDIATE_CNF,
    MSG_ID_D2CM_END, 

// D2RM
    MSG_ID_D2RM_BEGIN,
        MSG_ID_ATP_D2RM_EWIFIEN_REQ,
        MSG_ID_ATP_D2RM_EIFCONFIG_REQ,
        MSG_ID_ATP_D2RM_EIF_HO_REQ,
    MSG_ID_D2RM_END, 

    //D2PM -> D2RM
    MSG_ID_D2PM_D2RM_APNCAPA_UPDATE_REQ,
    MSG_ID_D2PM_D2RM_ACT_DATA_CALL_REQ,
    MSG_ID_D2PM_D2RM_DEACT_DATA_CALL_REQ,
    MSG_ID_D2PM_D2RM_ABORT_DATA_CALL_REQ,
    MSG_ID_D2PM_D2RM_MOD_DATA_CALL_REQ,
    MSG_ID_D2PM_D2RM_GET_DATA_CALL_LIST_REQ,
    MSG_ID_D2PM_D2RM_GET_DYNAMIC_PARAM_REQ,
    MSG_ID_D2PM_D2RM_GET_PDP_ADDRESS_REQ,
    MSG_ID_D2PM_D2RM_GET_SECONDARY_DYNAMIC_PARAM_REQ,
    MSG_ID_D2PM_D2RM_GET_QOS_REQ,
    MSG_ID_D2PM_D2RM_GET_TFT_REQ,
    MSG_ID_D2PM_D2RM_SET_PACKET_FILTER_REQ,
    MSG_ID_D2PM_D2RM_GET_PACKET_FILTER_REQ,
    MSG_ID_D2PM_D2RM_GET_PDN_PROFILE_RSP,
    MSG_ID_D2PM_D2RM_GET_PDN_PROFILE_REJECT_RSP,
    MSG_ID_D2PM_D2RM_GET_RETRYTMR_REQ,
    MSG_ID_D2PM_D2RM_SET_RETRYTMR_REQ,
    MSG_ID_D2PM_D2RM_VZWAPNETMR_REQ,
    MSG_ID_D2PM_D2RM_VZWAPNE_REQ,

    //IWLAN -> D2RM
    MSG_ID_D2RM_IWLAN_WANS_RPL_UPDATE_IND,

    //D2PM <- D2RM
    MSG_ID_D2PM_D2RM_ACT_DATA_CALL_CNF,
    MSG_ID_D2PM_D2RM_ABORT_DATA_CALL_CNF,
    MSG_ID_D2PM_D2RM_ACT_DATA_CALL_REJECT_CNF,
    MSG_ID_D2PM_D2RM_DEACT_DATA_CALL_CNF,
    MSG_ID_D2PM_D2RM_DEACT_DATA_CALL_REJECT_CNF,
    MSG_ID_D2PM_D2RM_ABORT_DATA_CALL_REJECT_CNF,
    MSG_ID_D2PM_D2RM_MOD_DATA_CALL_CNF,
    MSG_ID_D2PM_D2RM_GET_DATA_CALL_LIST_CNF,
    MSG_ID_D2PM_D2RM_GET_DYNAMIC_PARAM_CNF,
    MSG_ID_D2PM_D2RM_GET_PDP_ADDRESS_CNF,
    MSG_ID_D2PM_D2RM_GET_SECONDARY_DYNAMIC_PARAM_CNF,
    MSG_ID_D2PM_D2RM_GET_QOS_CNF,
    MSG_ID_D2PM_D2RM_GET_TFT_CNF,
    MSG_ID_D2PM_D2RM_GET_PACKET_FILTER_CNF,
    MSG_ID_D2PM_D2RM_SET_PACKET_FILTER_CNF,
    MSG_ID_D2PM_D2RM_GET_RETRYTMR_CNF,
    MSG_ID_D2PM_D2RM_SET_RETRYTMR_CNF,
    //MSG_ID_D2PM_D2RM_VZWAPNETMR_CNF,
    //MSG_ID_D2PM_D2RM_VZWAPNE_CNF,
    MSG_ID_D2PM_D2RM_ACT_DATA_CALL_IND,
    MSG_ID_D2PM_D2RM_PDN_NW_ACT_IND,
    MSG_ID_D2PM_D2RM_PDN_NW_DEACT_IND,
    MSG_ID_D2PM_D2RM_MOD_DATA_CALL_IND,
    MSG_ID_D2PM_D2RM_URC_CGEV_IND,
    MSG_ID_D2PM_D2RM_GET_DATA_CALL_LIST_IND,
    MSG_ID_D2PM_D2RM_GET_DYNAMIC_PARAM_IND,
    MSG_ID_D2PM_D2RM_GET_PDP_ADDRESS_IND,
    MSG_ID_D2PM_D2RM_GET_SECONDARY_DYNAMIC_PARAM_IND,
    MSG_ID_D2PM_D2RM_GET_QOS_IND,
    MSG_ID_D2PM_D2RM_GET_TFT_IND,
    MSG_ID_D2PM_D2RM_GET_PACKET_FILTER_IND,
    MSG_ID_D2PM_D2RM_GET_PDN_PROFILE_IND,
    MSG_ID_D2PM_D2RM_PDN_HO_NOTIFY_IND,
    MSG_ID_D2PM_D2RM_RST_RETRYTMR_IND,

    //D2RM -> D2RM
    MSG_ID_D2RM_D2RM_WANS_RPL_UPDATE_IND,

// D2AM
    MSG_ID_D2AM_BEGIN,
        MSG_ID_D2AM_MDALLOW_REQ,
        MSG_ID_D2AM_MDALLOW_CNF,
        MSG_ID_D2AM_EAPNABORT_REQ,
        MSG_ID_D2_CLEAN_UNUSED_PDN,
        MSG_ID_D2RM_D2AM_HANDOVER_ATTACH_REQ,
        MSG_ID_D2RM_D2AM_HANDOVER_ATTACH_CNF,
    MSG_ID_D2AM_END,

    //D2CM -> IPCORE
    MSG_ID_D2CM_IPCORE_INFO_IND,
    // D2
    MSG_ID_D2_BEGIN,
        MSG_ID_D2_GET_PDN_RAN_REQ,
        MSG_ID_D2_GET_PDN_RAN_IND,
        MSG_ID_D2_GET_PDN_RAN_CNF,
    MSG_ID_D2_END,

MODULE_MSG_END( MSG_ID_D2_CODE_TAIL )

#endif /* _DDM_MSGID_H */
