/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#include "module_msg_range.h"

#ifndef _DDM_MSGID_H
#define _DDM_MSGID_H
#if 0
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif
MODULE_MSG_BEGIN( MSG_ID_DDM_CODE_BEGIN )
    //DAST to DDM
    MSG_ID_D2_DDM_MSG_FROM_DAST_BEGIN,
        MSG_ID_D2IA_DDM_DEFINE_ATTACH_PDN_RSP,
        MSG_ID_D2IA_DDM_EDALLOW_REQ,
        MSG_ID_D2AM_DDM_EVZWAPFCIA_REQ,
        MSG_ID_D2PM_DDM_SET_SBP_ID_REQ,
        MSG_ID_D2AM_DDM_PS_TYPE_CONFIG_REQ,
        MSG_ID_D2AM_DDM_PS_REATTACH_CONFIG_REQ,
        MSG_ID_D2AM_DDM_EUTRAN_DISABLE_CHECK_RSP, /*D2AM -> DDM -> NWSEL : RSP*/
    MSG_ID_D2_DDM_MSG_FROM_DAST_END,
    //D2RM to DDM
    MSG_ID_D2RM_DDM_MSG_FROM_D2RM_BEGIN,
        MSG_ID_D2RM_DDM_ACT_DATA_CALL_REQ,
        MSG_ID_D2RM_DDM_DEACT_DATA_CALL_REQ,
        MSG_ID_D2RM_DDM_GET_DYNAMIC_PARAM_REQ,
        MSG_ID_D2RM_DDM_GET_DATA_CALL_LIST_REQ,
        MSG_ID_D2RM_DDM_GET_PDP_ADDRESS_REQ,
        MSG_ID_D2RM_DDM_GET_SECONDARY_DYNAMIC_PARAM_REQ,
        MSG_ID_D2RM_DDM_GET_QOS_REQ,
        MSG_ID_D2RM_DDM_GET_TFT_REQ,
        MSG_ID_D2RM_DDM_SET_PACKET_FILTER_REQ,
        MSG_ID_D2RM_DDM_GET_PACKET_FILTER_REQ,
        MSG_ID_D2RM_DDM_MODIFY_DATA_CALL_REQ,
        MSG_ID_D2RM_DDM_ABORT_DATA_CALL_REQ,
        MSG_ID_D2RM_DDM_GET_RETRYTMR_REQ,
        MSG_ID_D2RM_DDM_SET_RETRYTMR_REQ,
        MSG_ID_D2RM_DDM_GET_EPDG_INFO_REQ,
        MSG_ID_D2RM_DDM_VZWAPNETMR_REQ,
        MSG_ID_D2RM_DDM_VZWAPNE_REQ,
    MSG_ID_D2RM_DDM_MSG_FROM_D2RM_END,

    //DDM to DAST
    MSG_ID_D2_DDM_MSG_FROM_DDM_BEGIN,
        MSG_ID_D2IA_DDM_DEFINE_ATTACH_PDN_IND,
        MSG_ID_D2IA_DDM_NEED_DETACH_PDN_IND,
        MSG_ID_D2IA_DDM_ATTACHED_RAT_IND,
        MSG_ID_D2IA_DDM_ATTACH_PDN_ACTIVATE_SUCCESS_IND,
        MSG_ID_D2IA_DDM_ATTACH_PDN_ACTIVATE_FAILURE_IND,
        MSG_ID_D2AM_DDM_ECNCFG_REQ_IND,
        MSG_ID_D2AM_DDM_EVZWAPFCIA_IND,
        MSG_ID_D2IA_DDM_EDALLOW_CNF,
        MSG_ID_D2PM_DDM_ACT_DATA_CALL_CNF,
        MSG_ID_D2PM_DDM_GET_DYNAMIC_PARAM_CNF,
        MSG_ID_D2PM_DDM_GET_DATA_CALL_LIST_CNF,
        MSG_ID_D2AM_DDM_EVZWAPFCIA_CNF,
        MSG_ID_D2PM_DDM_URC_CGEV_IND,
        MSG_ID_D2AM_DDM_PS_TYPE_CONFIG_CNF,
        MSG_ID_D2AM_DDM_RELEASE_FB_CID_IND,
        MSG_ID_D2AM_DDM_EUTRAN_DISABLE_CHECK_IND, /*NWSEL -> DDM -> D2AM : IND*/
    MSG_ID_D2_DDM_MSG_FROM_DDM_END,

    //DDM to D2RM
    MSG_ID_D2RM_DDM_MSG_FROM_DDM_BEGIN,
        MSG_ID_D2RM_DDM_ACT_DATA_CALL_CNF,
        MSG_ID_D2RM_DDM_DEACT_DATA_CALL_CNF,
        MSG_ID_D2RM_DDM_ABORT_DATA_CALL_CNF,
        MSG_ID_D2RM_DDM_GET_DYNAMIC_PARAM_CNF,
        MSG_ID_D2RM_DDM_GET_DATA_CALL_LIST_CNF,
        MSG_ID_D2RM_DDM_GET_PDP_ADDRESS_CNF,
        MSG_ID_D2RM_DDM_GET_SECONDARY_DYNAMIC_PARAM_CNF,
        MSG_ID_D2RM_DDM_GET_QOS_CNF,
        MSG_ID_D2RM_DDM_GET_TFT_CNF,
        MSG_ID_D2RM_DDM_SET_PACKET_FILTER_CNF,
        MSG_ID_D2RM_DDM_GET_PACKET_FILTER_CNF,
        MSG_ID_D2RM_DDM_MODIFY_DATA_CALL_CNF,
        MSG_ID_D2RM_DDM_GET_RETRYTMR_CNF,
        MSG_ID_D2RM_DDM_SET_RETRYTMR_CNF,
        MSG_ID_D2RM_DDM_GET_EPDG_INFO_CNF,
        //MSG_ID_D2RM_DDM_VZWAPNETMR_CNF,
        //MSG_ID_D2RM_DDM_VZWAPNE_CNF,
        MSG_ID_D2RM_DDM_URC_CGEV_IND,
        MSG_ID_D2RM_DDM_ACT_DATA_CALL_IND,
        MSG_ID_D2RM_DDM_GET_DATA_CALL_LIST_IND,
        MSG_ID_D2RM_DDM_GET_DYNAMIC_PARAM_IND,
        MSG_ID_D2RM_DDM_GET_PDP_ADDRESS_IND,
        MSG_ID_D2RM_DDM_GET_SECONDARY_DYNAMIC_PARAM_IND,
        MSG_ID_D2RM_DDM_GET_QOS_IND,
        MSG_ID_D2RM_DDM_GET_TFT_IND,
        MSG_ID_D2RM_DDM_GET_PACKET_FILTER_IND,
        MSG_ID_D2RM_DDM_MOD_DATA_CALL_IND,
        MSG_ID_D2RM_DDM_RST_RETRYTMR_IND,
        MSG_ID_D2RM_DDM_GET_EPDG_INFO_IND,
    MSG_ID_D2RM_DDM_MSG_FROM_DDM_END,
    //ATP to DDM
    MSG_ID_ATP_DDM_FROM_ATP_BEGIN,
        MSG_ID_ATP_DDM_CGDCONT_REQ,
        MSG_ID_ATP_DDM_CGDSCONT_REQ,
        MSG_ID_ATP_DDM_CGTFT_REQ,
        MSG_ID_ATP_DDM_CGQREQ_REQ,
        MSG_ID_ATP_DDM_CGQMIN_REQ,
        MSG_ID_ATP_DDM_CGEQREQ_REQ,
        MSG_ID_ATP_DDM_CGEQMIN_REQ,
        MSG_ID_ATP_DDM_CGEQNEG_REQ,
        MSG_ID_ATP_DDM_CGACT_REQ,
        MSG_ID_ATP_DDM_CGCMOD_REQ,
        MSG_ID_ATP_DDM_CGDATA_REQ,
        MSG_ID_ATP_DDM_CGPADDR_REQ,
        MSG_ID_ATP_DDM_CGAUTO_REQ,
        MSG_ID_ATP_DDM_CGANS_REQ,
        MSG_ID_ATP_DDM_CGEREP_REQ,
        MSG_ID_ATP_DDM_CGCONTRDP_REQ,
        MSG_ID_ATP_DDM_CGSCONTRDP_REQ,
        MSG_ID_ATP_DDM_CGTFTRDP_REQ,
        MSG_ID_ATP_DDM_CGEQOS_REQ,
        MSG_ID_ATP_DDM_CGEQOSRDP_REQ,
        MSG_ID_ATP_DDM_CGDEL_REQ,
        MSG_ID_ATP_DDM_CGAUTH_REQ,
        MSG_ID_ATP_DDM_ECNCFG_REQ,
        MSG_ID_ATP_DDM_EGDCONT_REQ,
        MSG_ID_ATP_DDM_VZWAPNETMR_REQ,
        MSG_ID_ATP_DDM_VZWAPNE_REQ,
        MSG_ID_ATP_DDM_EGPAU_REQ,
        MSG_ID_ATP_DDM_EGACT_REQ,
        MSG_ID_ATP_DDM_CGSDATA_REQ,
        MSG_ID_ATP_DDM_ACTTEST_REQ,
        MSG_ID_ATP_DDM_PSBEARER_REQ,
        MSG_ID_ATP_DDM_EGFB_REQ,
        MSG_ID_ATP_DDM_EGLD_REQ,
        MSG_ID_ATP_DDM_EGDELPF_REQ,
        MSG_ID_ATP_DDM_EGLNKPF_REQ,
        MSG_ID_ATP_DDM_EGPCORDP_REQ,
        MSG_ID_ATP_DDM_EDALLOW_REQ,
        MSG_ID_ATP_DDM_EDRETRY_REQ,
        MSG_ID_ATP_DDM_EIMSCFG_REQ,
        MSG_ID_ATP_DDM_EGQOS_REQ,
        //AT respone to DDM
        MSG_ID_ATP_DDM_L4_CMD_CGATT_RSP,
    MSG_ID_ATP_DDM_FROM_ATP_END,
        
        //D2AT -> DDM
    MSG_ID_ATP_DDM_FROM_D2AT_BEGIN,
        MSG_ID_D2AT_DDM_CGDSCONT_REQ,
        MSG_ID_D2AT_DDM_CGTFT_REQ,
        MSG_ID_D2AT_DDM_CGQREQ_REQ,
        MSG_ID_D2AT_DDM_CGQMIN_REQ,
        MSG_ID_D2AT_DDM_CGEQREQ_REQ,
        MSG_ID_D2AT_DDM_CGEQMIN_REQ,
        MSG_ID_D2AT_DDM_CGEREP_REQ,
        MSG_ID_D2AT_DDM_CGSCONTRDP_REQ,
        MSG_ID_D2AT_DDM_CGTFTRDP_REQ,
        MSG_ID_D2AT_DDM_CGEQOS_REQ,
        MSG_ID_D2AT_DDM_CGEQOSRDP_REQ,
        MSG_ID_D2AT_DDM_CGCMOD_REQ,
        MSG_ID_D2AT_DDM_CGPADDR_REQ,

        MSG_ID_D2AT_DDM_CGACT_REQ,
        MSG_ID_D2AT_DDM_CGDCONT_REQ,
        MSG_ID_D2AT_DDM_CGAUTH_REQ,
        MSG_ID_D2AT_DDM_CGCONTRDP_REQ,

        MSG_ID_D2AT_DDM_EDALLOW_REQ,
        MSG_ID_D2AT_DDM_EGPCORDP_REQ,
        MSG_ID_D2AT_DDM_ACTTEST_REQ,
        MSG_ID_D2AT_DDM_CGANS_REQ,
        MSG_ID_D2AT_DDM_CGEQNEG_REQ,
        MSG_ID_D2AT_DDM_CGDATA_REQ,
        MSG_ID_D2AT_DDM_CGSDATA_REQ,
        MSG_ID_D2AT_DDM_CGDEL_REQ,
        MSG_ID_D2AT_DDM_EGACT_REQ,
        MSG_ID_D2AT_DDM_EGDCONT_REQ,
        MSG_ID_D2AT_DDM_EGDELPF_REQ,
        MSG_ID_D2AT_DDM_EGLD_REQ,
        MSG_ID_D2AT_DDM_EGLNKPF_REQ,
        MSG_ID_D2AT_DDM_EGPAU_REQ,

    MSG_ID_ATP_DDM_FROM_D2AT_END,

        //DDM to IMSM
    MSG_ID_IMSM_DDM_MSG_FROM_DDM_BEGIN,
        MSG_ID_IMSM_DDM_PCO_UPDATE_IND,
        MSG_ID_IMSM_DDM_FALLBACK_IPV4_IND,
    MSG_ID_IMSM_DDM_MSG_FROM_DDM_END,
        //DDM to VDM
    MSG_ID_VDM_DDM_MSG_FROM_DDM_BEGIN,
        MSG_ID_VDM_DDM_PCO_UPDATE_IND,
    MSG_ID_VDM_DDM_MSG_FROM_DDM_END, 

        //NWSEL to DDM
    MSG_ID_DDM_NWSEL_MSG_FROM_DDM_BEGIN,
        MSG_ID_DDM_NWSEL_EUTRAN_DISABLE_CHECK_IND,
    MSG_ID_DDM_NWSEL_MSG_FROM_DDM_END,
  
MODULE_MSG_END( MSG_ID_DDM_CODE_TAIL )

#endif /* _DDM_MSGID_H */
