/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************

  FILE NAME:  do_rmc_msgid.h

  DESCRIPTION:

    This file contains the defenitions of all the RMC msg id's.

*****************************************************************************/

#ifndef _DO_RMC_MSGID_H_
#define _DO_RMC_MSGID_H_

/*----------------------------------------------------------------------------
 Include Files
----------------------------------------------------------------------------*/
#include "module_msg_range.h"

#undef MSGID_SET
#undef MSGID_NEXT




/* Messages handled by RMC task
   NOTE: Following messages are processed by RMC but defined as MPA messages(in MpaCmdIdT)
         since they are used also by L1D
   MPA_RF_ANTENNA_RELEASE_REQ_MSG,
   MPA_RF_ANTENNA_ASSIGN_MSG,
*/
MODULE_MSG_BEGIN(MSG_ID_RMC_CODE_BEGIN)


    /* RMC segment */
    MSG_ID_RMC_INSP_PILOT_ACQ_MSG = MSG_ID_RMC_CODE_BEGIN,
    MSG_ID_RMC_INSP_1XASSIST_DOACQ_MSG,
    MSG_ID_RMC_ALMP_NETWORK_RESET_MSG,
    MSG_ID_RMC_RESERVED1_MSG,  //Place-holder for a deprecated msg. Ensures succeeding MSGIDs  dont change numeric values. Can be used for adding new MSG in the future
    MSG_ID_RMC_MPA_RF_PREEMPT_REQ_MSG,
    MSG_ID_RMC_MPA_RF_SHUTOFF_REQ_MSG,
    MSG_ID_RMC_FMP_MODE_CHANGE_MSG,
    MSG_ID_RMC_HSC_RXACTIVATE_MSG,
    MSG_ID_RMC_HSC_STOP_CMD_MSG,
    MSG_ID_RMC_RF_DIV_REQ_MSG,
    MSG_ID_RMC_INSP_NETWORK_RESET_MSG,
    MSG_ID_RMC_INSP_POWER_DOWN_IND,
    MSG_ID_RMC_RESERVED2_MSG,  //Place-holder for a deprecated msg. Ensures succeeding MSGIDs  dont change numeric values. Can be used for adding new MSG in the future
    MSG_ID_RMC_RUP_RXDEACTIVATE_MSG,
    MSG_ID_RMC_RUP_RXACTIVATE_MSG,
    MSG_ID_RMC_ETS_PREEMPT_MSG,
    MSG_ID_RMC_ETS_RXACTIVATE_MSG,
    MSG_ID_RMC_HSC_STOP_TX_MSG,
    MSG_ID_RMC_HWD_RESET_ACK_MSG,
    MSG_ID_RMC_RSSI_REPORT_ACK_MSG,
    MSG_ID_RMC_IDP_DDL_CHANGE_MSG,
    MSG_ID_RMC_RUP_DDL_CHANGE_MSG,
    MSG_ID_RMC_FH_RAKE_DDL_DONE_MSG,
    /* ON_PC */
    MSG_ID_RMC_TEMP_ADJ_UPDATE_MSG,
    MSG_ID_RMC_FREQ_ADJ_UPDATE_MSG,

    MSG_ID_RMC_LEC_MOBSYSTEMOFFSET_QUERY_MSG,
    MSG_ID_RMC_HSC_SLEEP_OVER_MSG,
    MSG_ID_RMC_TOP_CMD_MSGID_LAST,
    /* MTK_DEV_RF_CUSTOMIZE */
    MSG_ID_RMC_RX_DIV_CTRL_AFTER_RF_CUST_GET_MSG,

    /*IRAT*/
    MSG_ID_RMC_RUP_DFS_INFO_MSG,
    MSG_ID_RMC_IRATM_CCELL_MEAS_REQ,
    MSG_ID_RMC_IRATM_SYNC_MSG,
    MSG_ID_RMC_IRATM_ACQ_CGI_REQ,
    MSG_ID_RMC_IRATM_SET_RAT_REQ,
    MSG_ID_RMC_CLC_IDLE_MODE_CFG_MSG,
    MSG_ID_RMC_IDP_ACCESS_PROTECTION_MSG,
    MSG_ID_RMC_IDP_TRAFFIC_PROTECTION_MSG,

    /* SCH segment */
    MSG_ID_SCH_RUP_SEARCHPARMS_UPDATE_MSG, /*_MsgStruct SchParmUpdateMsgT*/
    MSG_ID_SCH_RUP_PILOT_UPDATE_MSG,       /*_MsgStruct SchPilotUpdateMsgT*/

    /* SYS_OPTION_SINGLECHIP_MULTIMODE, ASPEN IRAT LTE Idle and Active DO measurement */
    MSG_ID_RMC_IRAT_DO_EARLY_WAKEUP_REQ,
    MSG_ID_RMC_IRAT_SRCH_CFG_MSG,
    MSG_ID_RMC_CDMAL1_DOMEAS_ABORT_REQ,
    MSG_ID_RMC_IRAT_DOMEAS_ABORT_CNF,
    MSG_ID_RMC_IRAT_DO_INACTIVATE_REQ,

    /* FMP segment */
    MSG_ID_FMP_INSP_SYNC_MSG,
    MSG_ID_FMP_ALMP_CONNECTION_CLOSED_MSG,
    MSG_ID_FMP_CCM_CCSHORTPKTIND_MSG,
    MSG_ID_RMC_SH_FINGER_RESET_MSG,
    MSG_ID_RMC_SH_RAKE_FNG_CFG_DONE_MSG,
    MSG_ID_RMC_SH_DRC_CHTYPE_ESTIMATE_MSG,
    MSG_ID_RMC_BRP_DRC_RATE_DETERMINATE_MSG,
    MSG_ID_RMC_FH_RAT_UPDATE_MSG,
    MSG_ID_RMC_FH_DFS_PILOT_UPDATE_MSG,
    MSG_ID_RMC_SH_SCH_START_IND,
    MSG_ID_RMC_RUP_DFS_CFG_MSG,
    MSG_ID_RMC_RUP_DFS_ABORT_MSG,
    MSG_ID_RMC_RUP_INTER_HO_MSG,    
    MSG_ID_RMC_IDP_INTER_HO_CMD_MSG,
    MSG_ID_RMC_RCP_ACCESS_START_IND_MSG,
    MSG_ID_RMC_RCP_RTAP_CFG_MSG,
    MSG_ID_RMC_FCP_FTAP_CFG_MSG,
    MSG_ID_RMC_FH_MODEM_STATE_UPDATE_MSG,
    MSG_ID_RMC_FCP_FTM_STATE_UPDATE_MSG,
    MSG_ID_RMC_FCP_DRC_ACTIVE_MSG,
    MSG_ID_RMC_FCP_DRC_DEFAULT_ATTRI_UPDATE_MSG,
    MSG_ID_RMC_FCP_DRC_ENHANCE_ATTRI_UPDATE_MSG,
    MSG_ID_DRC_CSM_CELL_SWITCH_REQED_MSG,
    MSG_ID_DRC_CSM_CELL_SWITCH_OCCUR_MSG,

    /* RUP segment */
    MSG_ID_RUP_SCH_RESULT_RPT_MSG,          /*_MsgStruct RupSearchResultRptMsgT*/
    MSG_ID_RUP_OMP_UPDATE_CMD_MSG,         /*_MsgStruct RupOmpUpdatedMsgGT*/
    MSG_ID_RUP_OMP_SNROUTEUPDATE_CMD_MSG,
    MSG_ID_RUP_ACM_TXSTART_CMD_MSG,
    MSG_ID_RUP_ACM_TXEND_CMD_MSG,
    MSG_ID_RUP_ALMP_ACTIVATE_CMD_MSG,           /*_MsgStruct RupAlmpActiveMsgGT*/
    MSG_ID_RUP_ALMP_DEACTIVATE_CMD_MSG,
    MSG_ID_RUP_ALMP_CLOSE_CMD_MSG,
    MSG_ID_RUP_CSP_CLOSE_CMD_MSG,
    MSG_ID_RUP_IDP_CONNST_TMSTATE_CMD_MSG,
    MSG_ID_RUP_IDP_FREEZE_MSG,
    MSG_ID_RUP_IDP_THAW_MSG,
    MSG_ID_RUP_RTM_LINKACQ_CMD_MSG,
    MSG_ID_RUP_TIMER_EXPIRED_CMD_MSG,
    MSG_ID_RUP_RMC_CAMP_ON_CHANNEL_COMPLETE_MSG,
    MSG_ID_RUP_RMC_INTER_HO_NOTIFY_MSG,

    MSG_ID_RUP_SCP_RECONFIGURED_MSG,
    MSG_ID_RUP_SCP_COMMITTED_MSG,
    MSG_ID_RUP_ACM_ACCESS_HO_ENABLE_MSG,
    MSG_ID_RUP_ACM_ACCESS_HO_DISABLE_MSG,

    MSG_ID_RUP_IDP_STOP_REM_MSG,
    MSG_ID_RUP_OMP_IHO_ENABLED_MSG,
    MSG_ID_RUP_IDP_FORCE_IHO_REQ_MSG,

    MSG_ID_RUP_IRAT_CUR_SYS_MEAS_REQ,
    MSG_ID_RUP_IRAT_RAT_SIG_MON_REQ,
    MSG_ID_RUP_RCP_ACCESS_INITIATE_MSG,

    /*IRAT*/
    MSG_ID_RMC_CMD_MSGID_RUP_LAST,

    MSG_ID_RMC_RF_DIV_RELEASE_MSG,

    MSG_ID_RMC_CSS_DOSCAN_SLOTNUM_IND,
    MSG_ID_RUP_IDP_DFS_START_MSG,
    MSG_ID_RUP_IDP_DFS_ABORT_MSG,
    MSG_ID_RUP_CLC_DFS_SETTINGS_MSG,
    MSG_ID_RUP_IOP_GET_DFS_INFO_MSG,

    /* LL1A segment */
    MSG_ID_EVSTANDBY_LL1A_GAP_NOTIFY_IND_MSG,
    MSG_ID_EVSTANDBY_LL1A_GAP_STOP_REQ_MSG,
    MSG_ID_EVSTANDBY_LL1A_AUTO_GAP_CNF_MSG,
    MSG_ID_EVSTANDBY_LL1A_AUTO_GAP_STOP_IND_MSG,
    MSG_ID_RUP_IRATM_CUR_SECTOR_MEAS_REQ,
    MSG_ID_RUP_IRATM_CUR_SECTOR_SIG_MON_REQ,
    MSG_ID_RUP_IRATM_DFS_FREQ_NUM_SENT_REQ,
    MSG_ID_RUP_CSS_IHO_DISABLE_REQ,
    MSG_ID_RUP_CSS_IHO_ENABLE_REQ,

    /** RTBA Segment.*/
    MSG_ID_RMC_RTBA_RF_RESERVE_END_IND_MSG,

    /* EVDO RMC Signals --do_rmcapi.h */
    MSG_ID_RMC_TASK_SIGNAL,
    MSG_ID_RMC_SRCH_RESULTS_RDY_SIGNAL,
    MSG_ID_RMC_GENERATE_DECIMATED_TRACE_INFO_SIGNAL,
    MSG_ID_RMC_PROC_DELAYED_SCH_RESULT_SIGNAL,
    MSG_ID_RMC_GENERATE_DECIMATED_TRACE_INFO1_SIGNAL,
    MSG_ID_RMC_SCH_LOGIQ_SIGNAL,
    MSG_ID_RMC_IDP_IHO_WAKE_REDUCTION_STATE_REQ_MSG,

    MSG_ID_RMC_CMD_MSGID_LAST,

    /*---------------*/
    /* SCH Test Msgs */
    /*---------------*/
    MSG_ID_RMC_TEST_MSGID_START,
    MSG_ID_SCH_ETS_CAPTURE_INPUT_BUFFER_MSG = MSG_ID_RMC_TEST_MSGID_START, //MSG_ID_RMC_TEST_MSGID_START,
    MSG_ID_SCH_MINIACQ_WINSIZE_MSG,

    /*---------------*/
    /* RFC Test Msgs */
    /*---------------*/
    /*---------------*/
    /* FMP Test Msgs */
    /*---------------*/
    MSG_ID_FMP_TEST_HWTESTMODE_MSG,
    MSG_ID_FMP_TEST_UPDATEFINGERS_MSG,
    MSG_ID_FMP_TEST_UPDATEMACFINGERS_MSG,
    MSG_ID_FMP_TEST_INSP_SYNC_MSG,
    MSG_ID_FMP_TEST_SCHPROC_MSG,
    MSG_ID_FMP_TEST_SCHPROGFNG_CALLBK_MSG,
    MSG_ID_FMP_TEST_SLOTFOUND_MSG,
    MSG_ID_FMP_TEST_UPDATEPWR_MSG,
    MSG_ID_FMP_TEST_UPDATEFNGPOS_MSG,
    MSG_ID_FMP_TEST_INITACQFNGASSIGN_CALLBK_MSG,
    MSG_ID_FMP_TEST_CONNSETUP_CALLBK_MSG,
    MSG_ID_FMP_TEST_FNHW_MSG,
    MSG_ID_FMP_FNALGOPARMS_GET_CMD,
    MSG_ID_FMP_FNALGOPARMS_SET_CMD,
    MSG_ID_FMP_FINGER_SCAN_CMD,
    MSG_ID_FMP_FINGER_COMB_CFG_CMD,
#if defined(MTK_CBP) && (!defined(MTK_PLT_ON_PC))
    MSG_ID_FMP_FINGER_ANTCOMB_CFG_CMD,
#endif
    MSG_ID_FMP_EQFNALGOPARMS_SET_CMD,
    MSG_ID_FMP_EQFEATURE_SET_CMD,
    MSG_ID_FMP_EQ_MANUAL_ASSIGN_CMD,

    /*-------------------------------*/
    /* FMP MMSE MRC Ctrl Config Cmds */
    /*-------------------------------*/
    MSG_ID_CP_RMC_MAC_TARGET_TEST_CMD,


    /*---------------*/
    /* RUP Msgs */
    /*---------------*/
    MSG_ID_RUP_ETS_TCA_MSG,
    MSG_ID_RUP_ETS_SET_SUPPORT_CDMACHAN_MSG,
    MSG_ID_RUP_ETS_SET_SIMPLE_ATTR_MSG,
    MSG_ID_RUP_ETS_SET_SEARCH_PARM_MSG,
    MSG_ID_RUP_ETS_SET_MANCHAN_PARM_MSG,
    MSG_ID_RUP_ETS_OTA_MSG,
    MSG_ID_RUP_TST_SN_TCA_MSG,
    MSG_ID_RUP_SNROUTEUPDATE_CMD_MSG,
    MSG_ID_RUP_ETS_SET_PNPHASE,
    MSG_ID_RUP_ETS_SET_MAC_PARM,

    MSG_ID_RMC_TEST_RMC_DEACTIVATE_CMD,
    MSG_ID_RMC_TEST_RMC_SPY_DECI_CMD,
    MSG_ID_RMC_TEST_DO_DFS_CMD,
    MSG_ID_RMC_TEST_CTRL,
    MSG_ID_RMC_TST_UT_REQ,
#ifdef MTK_CBP
    MSG_ID_RMC_TEST_DO_DFS_SERVCH_CMD,
    MSG_ID_RMC_TEST_FMP_MD_CHG_AFT_RXDEACT_CMD,
    MSG_ID_RMC_TEST_DO_SET_DFS_CHCNT_CMD,
#if defined (MTK_DEV_C2K_IRAT) && defined (MTK_DEV_C2K_SRLTE_L1)
    MSG_ID_RMC_TEST_DO_DFS_MEET_1X_WAKEUP_CMD,
#endif
#endif
    /*---------------*/
    /* RMC IMD Msgs */
    /*---------------*/
    MSG_ID_CP_RMC_IMD_CONFIG_SET_MSG,
    MSG_ID_CP_RMC_IMD_CONFIG_GET_MSG,

    /*---------------*/
    /* RMC EQ Msgs */
    /*---------------*/
    MSG_ID_CP_RMC_EQ_W_WL_SELECT_SET_MSG,
    MSG_ID_CP_RMC_EQ_W_WL_SELECT_GET_MSG,

    /*---------------*/
    /* MBP Msgs */
    /*---------------*/
    MSG_ID_MBP_ETS_PROC_MCD_RPC_TH,
    MSG_ID_MBP_ETS_PROC_MCD_RPC_TH_C2I,

    /*-----Adaptive RX power mode ----*/
    MSG_ID_RMC_ETS_DO_ADAPTIVE_RX_CFG_CMD,

    MSG_ID_RMC_AFC_ON_MSG,
    MSG_ID_RMC_AFC_STATE_SET_MSG,
    MSG_ID_RMC_AFC_FNG_FOE_UPDATE_MSG,
    MSG_ID_RMC_VAL_DO_RX_TX_TIME_INFO_DATA_REQ,
    MSG_ID_VAL_RMC_DO_RX_TX_TIME_INFO_DATA_RSP,
    MSG_ID_FH_MODE_CHANGE_REQ,
    MSG_ID_FH_STB_MEAS_IND_MSG,
    MSG_ID_RMC_TEST_MSGID_LAST,
    MSG_ID_RMC_VAL_DO_DAT_CFG_MSG,


MODULE_MSG_END(MSG_ID_RMC_CODE_TAIL)


/*****************************************************************************
* End of File
*****************************************************************************/
#endif
