/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************

  FILE NAME:  do_sec_msgid.h

  DESCRIPTION:

    This file contains the defenitions of all the SEC msg id's.

*****************************************************************************/
/*----------------------------------------------------------------------------
Include Files
----------------------------------------------------------------------------*/
#ifndef _DO_SEC_MSGID_H_
#define _DO_SEC_MSGID_H_


#include "module_msg_range.h"


#undef MSGID_SET
#undef MSGID_NEXT

#define MSGID_SET(name, val) MSG_ID_##name = val
#define MSGID_NEXT(name) MSG_ID_##name

MODULE_MSG_BEGIN(MSG_ID_SEC_CODE_BEGIN)

   /* SEC AKA segment*/
    MSGID_SET(SEC_AKA_AUTH_REQ_MSG, MSG_ID_SEC_CODE_BEGIN),
    MSGID_NEXT(SEC_AKA_DERIVEMK_REQ_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEREAUTHXKEY_REQ_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEMSK_REQ_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEMAC_REQ_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEPMK_REQ_MSG),
    MSGID_NEXT(SEC_AKA_AESCRYPT_REQ_MSG),
    MSGID_NEXT(SEC_AKA_AUTH_REQ_TEST_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEMK_REQ_TEST_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEREAUTHXKEY_REQ_TEST_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEMSK_REQ_TEST_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEMAC_REQ_TEST_MSG),
    MSGID_NEXT(SEC_AKA_DERIVEPMK_REQ_TEST_MSG),
    MSGID_NEXT(SEC_AKA_AESCRYPT_REQ_TEST_MSG),
    MSGID_NEXT(SEC_AKA_PRIME_SQN_INIT_MSG),

    /* SEC AKA PRIME MSg */
    MSGID_NEXT(SEC_AKA_PRIME_DERIVEMK_REQ_MSG),
    MSGID_NEXT(SEC_AKA_PRIME_DERIVEREAUTHMK_REQ_MSG),
    MSGID_NEXT(SEC_VAL_AESCRYPT_REQ_MSG),
    MSGID_NEXT(SEC_CMD_MSGID_NUM),

    /* SEC SPY ON PC UT */
    MSGID_NEXT(SEC_AKA_AUTH_SPY_MSG),
    MSGID_NEXT(SEC_AKA_DERIVE_MK_SPY_MSG),
    MSGID_NEXT(SEC_AKA_DERIVE_REAUTHXKEY_SPY_MSG),
    MSGID_NEXT(SEC_AKA_DERIVE_MSK_SPY_MSG),
    MSGID_NEXT(SEC_AKA_DERIVE_MAC_SPY_MSG),
    MSGID_NEXT(SEC_AKA_DERIVE_PMK_SPY_MSG),
    MSGID_NEXT(SEC_AKA_AES_CRYPT_SPY_MSG),

MODULE_MSG_END(MSG_ID_SEC_CODE_TAIL)

/*****************************************************************************
 * End of File
*****************************************************************************/
#endif
