//below are EL1 IPC messages sent from AP
MSG_ID_IPC_EL1_CONSYS_ALLOW_TX_NTF,        // is not used
MSG_ID_IPC_EL1_CONSYS_DEFAULT_PARAM_NTF,
MSG_ID_IPC_EL1_CONSYS_OPER_FREQ_NTF,
MSG_ID_IPC_EL1_CONSYS_FREQ_IDX_TABLE_NTF,  // is not used
MSG_ID_IPC_EL1_CONSYS_PROFILE_NTF,         // is not used

//below are EL1 messages sent to AP
MSG_ID_IPC_EL1_LTE_DEFAULT_PARAM_IND,
MSG_ID_IPC_EL1_LTE_CA_OPER_FREQ_IND,
MSG_ID_IPC_EL1_LTE_WIFI_PWR_IND,           // is not used
MSG_ID_IPC_EL1_LTE_TX_IND,                 // is not used
MSG_ID_IPC_EL1_LTE_CONNECTION_STATUS_IND,  // is not used

//below are EL1 IPC messages sent from AP
MSG_ID_IPC_EL1_CONSYS_PIN_TYPE_NTF,       // is not used

//below are EL1 messages sent to AP
MSG_ID_IPC_EL1_LTE_HW_INTERFACE_IND,      // is not used

//below are EL1 IPC messages sent from AP
MSG_ID_IPC_EL1_CONSYS_TDM_ASSIT_INFO_NTF,

//below are EL1 messages sent to AP
MSG_ID_IPC_EL1_LTE_DRX_RPT_CFG_IND,       // is not used
MSG_ID_IPC_EL1_LTE_DRX_PATTERN_IND,
MSG_ID_IPC_EL1_LTE_DRX_MAPPING_IND,
MSG_ID_IPC_EL1_LTE_R11_IDC_PARAM_IND,
MSG_ID_IPC_EL1_LTE_IDC_INFO_IND,
MSG_ID_IPC_EL1_LTE_WIFIBT_UNSAFE_FREQ_BMP_IND,
MSG_ID_IPC_EL1_LTE_WIFIBT_FREQ_IDX_IND,  // is not used

//below are EL1 IPC messages sent from AP
MSG_ID_IPC_EL1_CONSYS_MAX_PWR_BACKOFF_NTF,

//below are reserved EL1 messages
MSG_ID_EL1_DUMMY22_IND,
MSG_ID_EL1_DUMMY23_IND,
MSG_ID_EL1_DUMMY24_IND,
MSG_ID_EL1_DUMMY25_IND,
MSG_ID_EL1_DUMMY26_IND,
MSG_ID_EL1_DUMMY27_IND,
MSG_ID_EL1_DUMMY28_IND,
MSG_ID_EL1_DUMMY29_IND,
MSG_ID_EL1_DUMMY30_IND,
MSG_ID_MD_CONSYS_VERIFICATION_IND,
MSG_ID_MD_CONSYS_VERIFICATION_REQ,
