/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   errc_msgid.h
 *
 * Project:
 * --------
 *   MOLY
 *
 * Description:
 * ------------
 *   LTE Layer 1 and Protocol Stack related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 * ==========================================================================
 * $Log$
 *
 * 12 11 2019 srihari.maddipati
 * [MOLY00435323] [B190414-819]???????????????450 (????????????)
 * .
 *
 * 09 16 2019 yung-chun.lin
 * [MOLY00436796] [Gen93] DSDA-like feature check in
 * 	
 * 	Sync from [MOLY00403889], CL 8115837
 * 	
 * 	[Gen95][L+L] DSDA-like feature (Reduce peer SIM data connection interruption when VoLTE MT) (OA)
 * 	 - DSDA Feature
 * 	 - disable api for A2
 *
 * 08 22 2019 aaroh.yang
 * [MOLY00432994] [ERRC Main][Ben190604-039][FT-India-Mumbai][PD1917F_EX_A_1.3.0][Jio Vo-WiFi][System Function] DUT slot 1 not register in VoWiFi after Hot swap
 * 	
 * 	[LR12A.R3.MP][ERRC/SPV] Occupy CS during IPv6 RS/RA procedure - main part (OA)
 *
 * 07 12 2019 aaroh.yang
 * [MOLY00421181] [ERRC Interface][B190614-1550]¡i¥«?§ë?-PS¡j[FT-¦¿?][²¾?+²¾?]?¥d§¡´¡¤J²¾?4G¥d¡A¥D¥d?4G±¼EÊI?¡A?­P?ªk¤WÊI¡]¦bÉÝ±`¦a?100%¡^Paging + local release + TAU
 * 	
 * 	[LR12A.R3.MP][ERRC/SPV] Add PROTECT_TAU_SERVICE_REQ interface and ERRC_API for HPS status query (OA)
 *
 * 03 14 2019 yung-chun.lin
 * [MOLY00390383] [Gemini][L+L][Gen93][sync R2 to R3] A2 trigger network release (ERRC part)
 * 	
 * 	[vivo sync back][OA] ERRC-part 
 * 	
 * 	[93][ERRC][MOB] new ERRC MSG_ID for TRIGGER_RELEASE A2 triggering Connection Release
 * 	- EPS Bearer Info
 * 	- NAS trigger CONN REL NTF
 *
 * 10 25 2018 yl.chang
 * [MOLY00359195] [B180719-543]¡i¥«?§ë?¡j[FT-ºÖ«Ø¬u¦{]¤âÉó¥d1¥d2§¡ª`?CMCC 4GÊI?¡A«ÝÉó5¤À?¥ª¥k¡A°Æ¥d°µ³Q¥s?ªk©I¤J¡]20/30¡^
 * [R3] AFC - OA
 *
 * 07 13 2018 aaroh.yang
 * [MOLY00335484] [R3][ERRC] MPS enhancement (occupy HPS for SMS over IMS) - interface
 * [R3.MP][ERRC/SPV] SMS over IMS occupy HPS - interface part (OA)
 *
 * 06 20 2018 peter.chien
 * [MOLY00334080] [ERRC][SSI][MT6763][Bianco][O1][MP2][AT&T][simulator-P18_1][in-house][R&S][ATTACH/RESTART][LTE-BTR-1-8268] UE failed at step15; RRCConnectionRequest TimeOut
 * 	
 * 	.
 *
 * 04 27 2018 otto.liu
 * [MOLY00322463] [Gen93] AT cmd for HPUE, TM9, UL64QAM and DL256QAM
 * 	
 * 	.
 *
 * 02 12 2018 aaroh.yang
 * [MOLY00307326] [R3][Volunteer Patch][IMS]Dual IMS registration enhacement
 * 	
 * 	[R3][ERRC/SPV] Occupy HPS/CS during IMS Service, Occupy CS during ESM Service - interface part (OA)
 *
 * 02 12 2018 aaroh.yang
 * [MOLY00307326] [R3][Volunteer Patch][IMS]Dual IMS registration enhacement
 * 	
 * 	[R3][ERRC/SPV] Occupy HPS/CS during IMS Service, Occupy CS during ESM Service - interface part (OA)
 *
 * 02 12 2018 aaroh.yang
 * [MOLY00307326] [R3][Volunteer Patch][IMS]Dual IMS registration enhacement
 * [R3][ERRC/SPV] Occupy HPS/CS during IMS Service, Occupy CS during ESM Service - interface part (OA)
 *
 * 01 16 2018 aaroh.yang
 * [MOLY00302107] [MT6763][Bianco][N1][India FT][Chennai][WW FT][RCOM][TATA DOCOMO][TC_MTK_P1_4G_Gemini_13] [MP1.5] DUT long SMS to sim2 fails (ERRC part)
 * [R3][ERRC][SPV] SMS procedure with CS semaphore - EVAL/ERRC Interface (OA).
 *
 * 12 11 2017 morton.lin
 * [MOLY00295077] [Gen93][ERRC][RCM] LTE support band and CA combination customization re-arch
 * Common IF and MRS part (LR12A.R3.MP) (Not in V-List)
 *
 * 12 08 2017 charley-cc.cheng
 * [MOLY00294013] [ERRC][CHM] UT Test Code
 * 	
 * 	@R3 [CHM UT Test Code] New Proposal - CHM self-contained, edit and execute with one single primitive (OA domain)
 *
 * 12 07 2017 ke-ting.lee
 * [MOLY00294778] [Sylvia][O1][SRLTE][CT 6M C][VoLTE][FT][GZ][HW][CAT][Fatal error(buf)] err_code1:0x00000823 err_code2:0x00004000 err_code3:0xCCCCCCCC MD Offender:ERRC
 * -SI sharing
 *
 * 11 29 2017 tereasa.huang
 * [MOLY00290347] 238721ï¿½iï¿½~??ï¿½Oï¿½jï¿½d1?ï¿½H4Gï¿½nï¿½Jï¿½ï¿½?ï¿½ï¿½??„Â??ï¿½{ï¿½ï¿½ï¿½n?ï¿½cï¿½X?ï¿½I?460ï¿½n5sï¿½ï¿½ï¿½kï¿½ï¿½ï¿½`???2ï¿½xï¿½ï¿½A2ï¿½x3ï¿½ï¿½ï¿½ï¿½?ï¿½@ï¿½X?16ï¿½ï¿½?(ERRC Interface)
 * R3 Interface (OA Domain).
 *
 * 11 29 2017 shih-chieh.liao
 * [MOLY00292082] [Gen93][TMO] 2G disable with ecc enable
 * .
 *
 * 11 28 2017 yung-chun.chang
 * [MOLY00287784] [MT6295] tstm_meta development
 * TSTM_META rcm oa part
 *
 * 11 21 2017 aaroh.yang
 * [MOLY00289523] [Zion][N1][Free Test][MCD][TEMoving]make a vilte call,the picture is unclear(5/5)
 * [ERRC/SPV] add MSG_ID_EVAL_ERRC_IMS_STATUS_UPDATE_REQ MSG ID
 *
 * 11 02 2017 aaroh.yang
 * [MOLY00286082] [6293 Gemini][All  .h file]: New Semaphore "MPS" for MO data & Solution for TAU ping-pong
 * [ERRC/SPV] add MSG_ID_EMM_ERRC_DATA_ALLOW_REQ msg ID for MedPS
 *
 * 10 17 2017 bo-yao.tsai
 * [MOLY00281973] ï¿½iTOPï¿½jï¿½iï¿½s?ï¿½wï¿½{ï¿½j?ï¿½d?ï¿½qï¿½Aï¿½d2ï¿½Dï¿½dï¿½A?ï¿½ï¿½Zï¿½`?3Gï¿½Aï¿½`?4Gï¿½Aï¿½ï¿½ï¿½ï¿½?ï¿½{ï¿½ï¿½ï¿½Sï¿½^ï¿½ï¿½3Gï¿½I?ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½`4Gï¿½]3\10ï¿½^
 *
 * 09 20 2017 lawrence.chen
 * [MOLY00278366]LPP OTDOA new procedure architecture development.
 *
 * 09 14 2017 tereasa.huang
 * [MOLY00277986] [UMOLYA][MOB][Code]SRVCCï¿½ï¿½ï¿½ï¿½
 *
 * 08 22 2017 adeline.chang
 * [MOLY00269598] [Gen93]TPB/Mobility Ctrl patch check in
 * .
 *
 * 08 17 2017 emily.lu
 * [MOLY00271227] [UMOLYA] [Rose][Vinson][N1]The ECC call will can't be dial out success.(5/5)
 * 	
 * 	. code sync CL4160021
 *
 * 07 07 2017 cynthia.chen
 * [MOLY00261827] [UMOYLA] LPPe development - ERRC part @OA
 *
 * 05 31 2017 vivian.chen
 * [MOLY00217129] [MT6293] code sync from UMOLY (Phase4)
 * .sync[MOLY00248424]CL#3883171.add msg_id MSG_ID_ERRC_EL1_GAP_STATUS_IND
 *
 * 04 19 2017 louis.lu
 * [MOLY00243476] [MT6293]Rel-12 WLAN offload ERRC patch due to L4 M3 modification
 * 	
 * 	Rel-12 LWI modification due to L4 M3 patch (OA domain)
 *
 * 03 02 2017 maruco.tu
 * [MOLY00226504] [ERRC][LCEL] LCEL enhancement after code presentation
 * remove unused LCEL_EM_UPDATE_REQ
 *
 * 02 17 2017 ke-ting.lee
 * [MOLY00196550] [6293] ERRC CSR development
 * - Remove msg_sibx_stored_data
 *
 * 02 09 2017 dennis.weng
 * [MOLY00228585] [MT6293][ERRC/CEL] Gemini suspend cmpl_subband improvement
 * add carrier_search_status_ind msgid
 *
 * 01 19 2017 rainee.yeh
 * [MOLY00207311] [MT6293][ERRC][CONN] UMOLY sync to UMOLYA
 * -CL 3370203, (L+L) add SIM_SWITCH_REQ message
 *
 * 12 14 2016 louis.lu
 * [MOLY00211184] [6293] LWA phase2 design
 * 	
 * 	Check -in interface for MSG_ID_ERRC_CONN_MOB_WLAN_LOST_IND,OA Domain part
 *
 * 12 08 2016 shih-chieh.liao
 * [MOLY00217129] [MT6293] code sync from UMOLY (Phase4)
 * .
 *
 * 11 09 2016 jed.lee
 * [MOLY00210762] [MT6293][ERRC][CONN] UMOLY sync to UMOLYA
 * -CL2683928.
 *
 * 11 08 2016 menghau.wu
 * [MOLY00211184] [6293] LWA phase2 design
 * add MSG_ID_IWLAN_ERRC_WLAN_CAPABILITY_REQ related processing (OA domain)
 *
 * 11 07 2016 shih-chieh.liao
 * [MOLY00211184] [6293] LWA phase2 design
 * .
 *
 * 11 04 2016 tsung-ming.lee
 * [MOLY00210784] [MT6293] code sync form UMOLY
 * 	CR [MOLY00193300] Porting of NW BAND Info from LR9 to LR11 TC01
 * 	CL2706217
 * 	CL2704969.
 *
 * 11 03 2016 danny.kuo
 * [MOLY00193300] Porting of NW BAND Info from LR9 to LR11 TC01
 * .
 *
 * 11 03 2016 danny.kuo
 * [MOLY00193300] Porting of NW BAND Info from LR9 to LR11 TC01
 * .
 *
 * 11 03 2016 louis.lu
 * [MOLY00211184] [6293] LWA phase2 design
 * 	.
 * 	Introduce new msg MSG_ID_ERRC_CHM_MOB_LWA_CFG_IND (OA domain)
 *
 * 11 02 2016 cynthia.chen
 * [MOLY00211038] [MT6293][ERRC][CONN] UMOLY sync to UMOLYA
 * -CL2925236 in OA
 *
 * 11 02 2016 emily.lu
 * [MOLY00210784] [MT6293] code sync form UMOLY
 * [MOLY00093206][C90] new AT command (AT%PGCHECK)
 *
 * 11 01 2016 jed.lee
 * [MOLY00210762] [MT6293][ERRC][CONN] UMOLY sync to UMOLYA
 * CL2683928.
 *
 * 11 01 2016 jed.lee
 * [MOLY00210762] [MT6293][ERRC][CONN] UMOLY sync to UMOLYA
 * CL2683928.
 *
 * 10 31 2016 menghau.wu
 * [MOLY00207053] [MT6293] code sync form UMOLY
 * L+L/M-PS/R-SIM interface
 *
 * 10 20 2016 rachel.liu
 * [MOLY00208519] [MT6293][VzW]LTE SIB8/16 for AGPS fine time aiding (code sync from UMOLY)
 *
 * 10 19 2016 vivian.chen
 * [MOLY00207053] [MT6293] code sync form UMOLY
 * .[MOLY00193868] [MT6292][New feature][R12][VzW] VZ_REQ_LTEDATARETRY_39861 - ERRC implementation. CL2655445
 *
 * 10 18 2016 peter.chien
 * [MOLY00207197] [MT6293][ERRC] UMOLY sync to UMOLYA
 * .
 *
 * 10 17 2016 ke-ting.lee
 * [MOLY00207053] [MT6293] code sync form UMOLY - MOLY00186029-CL2632451 errc_msgid.h
 *
 * 09 26 2016 shih-chieh.liao
 * [MOLY00205093] [UMOLYA] merge CR from mw.hsu CBr
 * .
 *
 * 08 09 2016 adeline.chang
 * [MOLY00194730] [UMOLYA][6293] ERRC CHM MBMS re-arc itmes
 * .
 *
 * 08 09 2016 maruco.tu
 * [MOLY00196065] [MT6293][folder structure] Move EL1/EL2 files from LTE domain to SWRD domain
 * [LCEL re-arch](CONFIG files) (OA domain)
 * 	1.modify SAP file 
 * 	2.Add new message for dhl/mcddll
 * 	3.disable LCEL in las_create.c
 * 	4.check in el1/errc/las_msgid.h
 * 	5.Remove las/lcel path and add errc/lcel path in lte_def.mak
 *
 * 07 27 2016 jui-chih.chin
 * [MOLY00193618] [6293][LMOB Removel] Code Merge from CBr to UMOLYA TRUNK and UMOLYA PS DEV
 * 	
 * 	LMOB removal (OA)
 *
 * 06 27 2016 jui-chih.chin
 * [MOLY00183642] new task EL1_MPC definition for 6293
 * 	
 * 	.
 *
 * 06 27 2016 dennis.weng
 * [MOLY00183642] new task EL1_MPC definition for 6293
 * specific measure cnf
 *
 * 06 27 2016 dennis.weng
 * [MOLY00183642] new task EL1_MPC definition for 6293
 * .
 *
 * 06 24 2016 ke-ting.lee
 * [MOLY00185901] UMOLYA errc relevant latest code sync from UMOLY- errc_msgid.h merge
 *
 * 06 20 2016 elle.sun
 * [MOLY00184906] [MOB][VzW EM] MDMI EM code check-in
 * 	
 * 	.
 *
 * 06 14 2016 antti.kaisto
 * [MOLY00180588] [MT6292][New feature] RRC for LWA
 * ERRC CHM changes to 'LTE - WLAN Aggregation'.
 *
 * 06 14 2016 ivy.wang
 * [MOLY00165236] [PH1_VZW][FLD][Radio_Protocol] VZ_REQ_LTEDATA_37821 Autonomous Gaps
 * .
 *
 * 05 23 2016 antti.karjalainen
 * [MOLY00180588] [MT6292][New feature] RRC for LWA:
 * L4C-ERRC interface
 *
 * 05 23 2016 gui-liu.wang
 * [MOLY00180690] [MT6755][Jade L6][MP2][RTD][34G][Performance Index][19][4G3 Reselection]
 * 	
 * 	.
 *
 * 05 17 2016 mark.ng
 * [MOLY00179023] Allowable Registration Area List Feature V2 Check In
 * ARAL 2.0 interface
 *
 * 04 26 2016 chih-chien.lin
 * [MOLY00167983] [MT6755][Jade L6][MP2][CSFB DSDS][HSR][FDD][HSR][4G_Moving][Case Fail][LAT2]PLMN List time is lose to reference phone
 * fast list
 *
 * 04 26 2016 ming.shen
 * [MOLY00150211] [VzW][VZ_REQ_LTEMMO_38695] LTE Scanning Enhancement
 * .
 *
 * 04 26 2016 ming.shen
 * [MOLY00144447] Operator Feature/Requirement
 * 	
 * 	.
 *
 * 04 15 2016 yi-han.chung
 * [MOLY00165778] [ERRC][CEL] Add stop control for specific measure req  - interface (oa domain)
 *
 * 04 01 2016 ming.shen
 * [MOLY00142775] [ERRC][CEL] LTE code sync
 * .
 *
 * 03 17 2016 kun-lin.wu
 * [MOLY00167477] [PH1_VZW][joint-camp][Radio_Protocol][eMBMS] VZW LC TC 2.5 - eMBMS Channel Capacity
 *
 * 03 16 2016 bo-yao.tsai
 * [MOLY00164081] ï¿½iCAï¿½jï¿½bï¿½tï¿½mï¿½ï¿½?ï¿½iï¿½Eï¿½Xï¿½ï¿½?ï¿½ï¿½???ï¿½uï¿½I?ï¿½A???ï¿½ï¿½ï¿½M?ï¿½ï¿½4G+
 * OPPO 4G+ icon
 * - add MSG_ID_ERRC_EMAC_CA_ACTIVATE_IND
 *
 * 03 15 2016 tereasa.huang
 * [MOLY00167830] [MT6291][VoLTE][SRVCC] SRVCC CDRX Enhancement Patch - ERRC Enhancement 2G Priority
 * .
 *
 * 03 10 2016 morton.lin
 * [MOLY00165954] [6291 HSR] Protocol / Lower Layer Common Header/Interface
 * CMCC requirement: HSFR CTRL (L1 PS Header / Interface)
 *
 * 03 10 2016 morton.lin
 * [MOLY00165947] [6291 HSR] Protocol Enhancement (Header/Interface)
 * CMCC requirement: HSFR CTRL (SBP, NVRAM and MRS) (Protocol Header / Interface)
 *
 * 03 10 2016 chester-zd.huang
 * [MOLY00165954] [6291 HSR] Protocol / Lower Layer Common Header/Interface-ERRC COMMON Part(UMOLY).
 *
 * 03 09 2016 sabrina.hsu
 * [MOLY00155801] [CA] Enable/Disable CA by AT+ECASW (ERRC)
 * merge UMOLY version
 *
 * 03 03 2016 ethan.han
 * [MOLY00166584] LTE code sync 2016
 * 	
 * 	.
 *
 * 02 17 2016 sabrina.hsu
 * [MOLY00156230] [6292] ERRC code sync LR11 to UMOLY
 * [ERRC][RCM] Inject fake UE EUTRA Capability phase-in
 *
 * 02 17 2016 sam.tsai
 * [MOLY00156025] MOB/LMOB code sync from LR11 to UMOLY
 *
 * 02 17 2016 sam.tsai
 * [MOLY00156025] MOB/LMOB code sync from LR11 to UMOLY
 * .[MOLY00156440] [LGE request] Signal Strength Monitoring Across Threshold
 *
 * 02 17 2016 sam.tsai
 * [MOLY00156025] MOB/LMOB code sync from LR11 to UMOLY
 * .[MOLY00153524] [6291] Vivo BlackList feature
 * .[ERRC][MOB] Clear black cell list.
 *
 * 02 17 2016 sam.tsai
 * [MOLY00156025] MOB/LMOB code sync from LR11 to UMOLY
 * .[MOLY00149628] MD1/MD3 power down procedure - AS workaround handshake flow
 *
 * 02 16 2016 nicky.chou
 * [MOLY00160414] [ERRC][CONN] sync from LR11 to UMOLY
 * [CL1959167][MOLY00154368] [MT6755][L+W][Overnight][FDD][MTBF][L1CORE] Assert fail: errc_conn_main.c 849 0x22 0x0 0x0 V ERRC.
 *
 * 02 15 2016 kun-lin.wu
 * [MOLY00144901] [ERRC] bCSFB feature check-in for TMO-US
 *
 * 11 27 2015 ville.pukari
 * [MOLY00150835] ML1S Test Environment Support:
 * 	
 * 	ERRC support for ML1S Test Mode
 *
 * 09 25 2015 mark.ng
 * [MOLY00143156] [MT6755][E1][GCF][Anite][3G][FDD][CSG][6.3.1.1] Test Fail
 * manual csg search on UMOLY
 *
 * 09 15 2015 yenchih.yang
 * [MOLY00099648] [VoLTE] Voice quality patch - ERRC
 * .
 *
 * 09 10 2015 panu.peisa
 * [MOLY00141214] DE6 code merge from LR11_VzW CBr to UMOLY trunk
 * 	[MOLY00141214] DE6 code merge form LR11_VzW CBr to UMOLY trunk
 * 	Integrated CL 1584603 from VzW CBr.  SWRD domain changes needed by ERRC_SYS for Extended Access Barring.
 * 	CL have dependency to lte_sec part.
 *
 * 09 04 2015 ethan.han
 * [MOLY00139861] [MT6291][SBM] New Feature : Disable LTE B41 for roaming out side of Japan.
 * 	.
 *
 * 08 21 2015 sheng-lung.liu
 * [MOLY00097009] [WFC][Volunteer patch] LTECSR_network init
 * Roll back for ERRC not ready call drop enhancement, keep RoHC confidence enable
 *
 * 08 21 2015 henry.lai
 * [MOLY00138170] [MT6291] MBMS Scell Self-Finding Mechanism
 * 	.
 *
 * 08 20 2015 sheng-lung.liu
 * [MOLY00097009] [WFC][Volunteer patch] LTECSR_network init
 * Enable RoHC confidence, ERRC Notify
 *
 * 08 12 2015 roland.li
 * [MOLY00129071] [ERRC][RCM] Dynamic SBP
 * .
 * fix code gen error
 *
 * 08 04 2015 roland.li
 * [MOLY00129071] [ERRC][RCM] Dynamic SBP
 * .
 *
 * 06 17 2015 esko.oikarinen
 * [MOLY00118255] [MT6291] ERRC message identifier for DABUWAN code merge
 *
 * 06 16 2015 henry.lai
 * [MOLY00113082] [MT6291] ERRC CEL development
 * .
 *
 * 06 05 2015 morton.lin
 * [MOLY00095623] [eRRC] Gemini virtual mode
 * [6291][ERRC][SPV] eMBMS Gemini 2PS feature improvements
 *
 * 06 01 2015 henry.lai
 * [MOLY00092508] [MT6291][LTE-C2K] AS Inter RAT feature
 * .
 *
 * 05 22 2015 chun-fan.tsai
 * [MOLY00098916] [MT6291] MBMS reception on SCELL
 * eRRC CONN MBMS on SCELL (Phase 1)(OA Domain)
 *
 * 05 19 2015 cooper.lin
 * [MOLY00114149] [MT6291][L234 NW-UE SIM][4G][LTE-A MDT] FDD MDT 8.6.2.3a failed due to RRCConnectionSetupComplete content mismatch
 * Add loggedMeasCfg MSG ID for EVTH to use
 *
 * 04 28 2015 george.chang
 * [MOLY00109714] [6291] MOB MDT check in to UMOLY TRUNK
 * 	.
 *
 * 04 16 2015 doug.shih
 * [MOLY00092508] [MT6291][LTE-C2K] AS Inter RAT feature
 * Merge C2K AS IRAT - CEL Part (OA domain).
 *
 * 04 09 2015 chun-fan.tsai
 * [MOLY00098916] [MT6291] MBMS reception on SCELL
 * CONN/CEL new interface - MBMS_SCELL_REQ/CNF
 *
 * 04 09 2015 chun-fan.tsai
 * [MOLY00098916] [MT6291] MBMS reception on SCELL
 * ERRC/EL1 new interface - SCELL_FOUND_IND
 *
 * 04 07 2015 ming.shen
 * [MOLY00106111] [6291] Sync MOLY to UMOLY - SPV W1510-13
 *
 * 03 09 2015 cooper.lin
 * [MOLY00090532] [MT6291] Change Feature Check-in
 * EM, Mode Switch interface check-in
 *
 * 03 09 2015 george.chang
 * [MOLY00098177] [6291] MDT check in to UMOLY TRUNK
 * 	.
 *
 * 02 16 2015 tereasa.huang
 * [MOLY00095623] [eRRC] Gemini virtual mode
 * Virtual mode interface.
 *
 * 02 12 2015 cooper.lin
 * [MOLY00090532] [MT6291] Change Feature Check-in
 * MDT check-in
 *
 * 02 05 2015 cooper.lin
 * [MOLY00090532] [MT6291] Change Feature Check-in
 * Code sync from MOLY (W15.06)
 *
 * 01 16 2015 david.niu
 * [MOLY00087934] [MT6291][LPP OTDOA Development] Inter-freq RSTD measurement indication
 * .
 *
 * 12 19 2014 birui.li
 * [MOLY00087677] [U3G][TDD][UAS RRCE] modifications for U3G
 * merge from peng-an CBr.
 *
 * 12 16 2014 claud.li
 * [MOLY00087795] [MEME] universal bin check in
 * [Universal bin][FDD][MEME/EAS/GAS] interface
 *
 * 12 12 2014 yuhhwang.yu
 * [MOLY00087211] [CISE] add CSG fingerprint compile option and bug fix
 * . CISE codes
 *
 * 11 12 2014 cooper.lin
 * [MOLY00068710] [MT6291_DEV] Sync MOLY to MT6291_DEV
 * Merge MT6291_DEV code to UMOLY trunk.
 *
 * 11 12 2014 chi-chung.lin
 * [MOLY00068710] [MT6291_DEV] Sync MOLY to MT6291_DEV
 * [CHM] code sync from MT6291_DEV to UMOLY
 *
 * 11 12 2014 yingwei.huang
 * [MOLY00073932] [MT6291_DEV] EDDA implementation -- interface part.	.
 *
 * 11 12 2014 henry.lai
 * [MOLY00079071] [MT6291][U4G] Low Power Modification for CEL Paging
 * .
 *
 * 07 21 2014 william.chang
 * [MOLY00072876] [WW FT][K95 V1.2][4G Gemini][FT][Hangzhou]Externel (EE),0,0,99,/data/core/,1,modem,md0:[ASSERT] file:rsvas_fsm.c line:3776
 * .
 *
 * 05 28 2014 william.chang
 * [MOLY00067209] [LTE Gemini] Add interface for EMM to occupy CS semaphore for Attach procedure
 * .
 *
 * 05 28 2014 william.chang
 * [MOLY00067209] [LTE Gemini] Add interface for EMM to occupy CS semaphore for Attach procedure
 * .
 *
 * 04 30 2014 william.chang
 * [MOLY00064308] Modify EVAL ERRC msg name for VOLTE gemini
 * .
 *
 * 04 02 2014 cookie.chen
 * [MOLY00060012] AT+ECBMR to remove modem CB records
 * .
 *
 * 03 28 2014 william.chang
 * [MOLY00061184] [4G Gemini] Notify AS when IRCCO stage2 cause is updated by NASu1rwduu`wvpghlqg|rliildh+fmdkb
 *
 * 03 28 2014 jasper.chen
 * [MOLY00060988] [LPP CP] LPP code check-in for A-GNSS and eCID feature
 * 	Check in ECID ERRC modifications (OA domain)
 *
 * 03 06 2014 aaron.liu
 * [MOLY00056483] [MT6582LTE][SGLTE][CMCC FT][GZ]
 * Add PLMN SEARCH Abort Interface:
 * 1.MSG_ID_EVAL_ERRC_PLMN_SEARCH_ABORT_REQ
 * 2.MSG_ID_NWSEL_EVAL_PLMN_SEARCH_ABORT_REQ
 *
 * 03 03 2014 peter.chien
 * [MOLY00058082] [CEL][CONN] Change IDLE_CNF to CH_STATUS_CNF
 * Merging
 *  	
 * 	//MOLY_CBr/cookie.chen/MOLY_W14.09.LTE.p1/mcu/interface/sap/md/errc_msgid.h
 *  	
 * 	to //MOLY/TRUNK/MOLY/mcu/interface/sap/md/errc_msgid.h
 *
 * 01 22 2014 jeremy.chen
 * [MOLY00054589] [MT6290E2] add RLF indication from ERLC-DL
 * reaname ERRC_ERLCUL_STATUS_IND to ERRC_ERLC_RLF_IND
 *
 * 01 22 2014 william.chang
 * [MOLY00054324] [4G Gemini][Merge] MOLY.MM.GEMINI.DEV Merge back to MOLY
 * . Check-in Interface part of LTE GEMINI
 *
 * 01 13 2014 aaron.liu
 * [MOLY00053379] [MT6290][VOLTE][ERRC]New feature : IMS emergency
 * Add ERRC Interface.
 *
 * 12 30 2013 menghau.wu
 * [MOLY00051454] [ERRC][CEL] write PLMN list stored cell into NVRAM
 * Add Stored cell info related NVRAM context
 *
 * 11 29 2013 menghau.wu
 * [MOLY00048344] [MT6290][ERRC] Add learned mcc info context to NVRAM/RCM
 * 	add nvram file for learned mcc info
 *
 * 11 13 2013 jed.lee
 * [MOLY00046027] [MT6290E1][MMDS_DC] MMDC feature patch back to MOLY trunk
 * B3&B39 conn part.
 *
 * 11 13 2013 adeline.chang
 * [MOLY00046027] [MT6290E1][MMDS_DC] MMDC feature patch back to MOLY trunk
 * .
 *
 * 10 21 2013 hong-yuan.yang
 * [MOLY00040050] [MultiMode] Dynamic band selection
 * .
 *
 * 10 02 2013 maruco.tu
 * [MOLY00039031] [ERRC][CEL]Inject implement
 * remove leave_4g.
 *
 * 09 25 2013 maruco.tu
 * [MOLY00039031] [ERRC][CEL]Inject implement
 * inject message(new message:MSG_ID_ERRC_CEL_INJECT_LEAVE_LTE_IND)
 *
 * 09 24 2013 peter.chien
 * [MOLY00038599] ERRC MOB CONN inject message feature
 * .Add interface
 *
 * 08 06 2013 adeline.chang
 * [MOLY00031695] Modify CHM/RCM code for UT enhancement .
 * .
 *
 * 08 01 2013 dennis.weng
 * [MOLY00032020] [ERRC][CEL] new carrier search flow check-in
 * .
 *
 * 07 24 2013 dennis.weng
 * [MOLY00031020] [MMDS_DC] Merge MMDC interface to MOLY
 * merge GAS_EAS_EARFCN_LIST_UPDATE_REQ
 *
 * 07 22 2013 stanleyhy.chen
 * [MOLY00029602] [New Feature] NBR_CELL_INFO and TA_INFO related interfaces
 * Add ERRC_EMAC_TA_INFO_INVALID_IND
 *
 * 07 12 2013 stanleyhy.chen
 * [MOLY00029602] [New Feature] NBR_CELL_INFO and TA_INFO related interfaces
 * TA_INFO and NBR_CELL_INFO interfaces for LPP feature
 *
 * 05 27 2013 jed.lee
 * [MOLY00023911] TDS MoDIS MM IT code merge
 * .
 *
 * 05 13 2013 shih-chieh.liao
 * [MOLY00022028] LTE MM.IT errc merge to MOLY
 * merge mrs
 *
 * 04 01 2013 shih-chieh.liao
 * [MOLY00011934] LTE MM IT CBr merge to MOLY
 * .asn1 replacement
 *
 * 01 24 2013 william.chang
 * [MOLY00009163] LTE Multimode merge back to MOLY
 * .Merge from MM preIT CBr
 *
 * 01 23 2013 hong-yuan.yang
 * [MOLY00009163] LTE Multimode merge back to MOLY
 * LTE multimode merge back to moly
 ****************************************************************************/
#include "module_msg_range.h"

#ifndef _ERRC_MSGID_H
#define _ERRC_MSGID_H


MODULE_MSG_BEGIN( MSG_ID_ERRC_CODE_BEGIN )


MSG_ID_EXEVT_RCV_BEGIN = MSG_ID_ERRC_CODE_BEGIN,
MSG_ID_EMM_ERRC_ACTIVATION_REQ,
MSG_ID_EMM_ERRC_RAT_BAND_REQ,
MSG_ID_EMM_ERRC_ESTABLISH_REQ,
MSG_ID_EMM_ERRC_RELEASE_REQ,
MSG_ID_EMM_ERRC_RELEASE_RSP,
MSG_ID_EMM_ERRC_DATA_REQ,
MSG_ID_EMM_ERRC_KEY_UPDATE_REQ,
MSG_ID_EMM_ERRC_TEST_REQ,
MSG_ID_EMM_ERRC_CELLSELECT_REQ,
MSG_ID_EMM_ERRC_PLMNLIST_REQ,
MSG_ID_EMM_ERRC_PLMN_LIST_STATUS_UPDATE_REQ,
MSG_ID_EMM_ERRC_RESUME_REQ,
MSG_ID_EMM_ERRC_NWSEL_STATUS_UPDATE_REQ,
MSG_ID_EMM_ERRC_REG_STATUS_UPDATE_REQ,
MSG_ID_EMM_ERRC_RAT_CHANGE_REQ,
MSG_ID_EMM_ERRC_RAT_CHANGE_RSP,
MSG_ID_EMM_ERRC_STANDBY_REQ,
MSG_ID_EMM_ERRC_PARAM_UPDATE_REQ,
MSG_ID_EMM_ERRC_QOS_UPDATE_REQ,
MSG_ID_EMM_ERRC_CSG_LIST_REQ,
MSG_ID_EMM_ERRC_CSG_LIST_STOP_REQ,
MSG_ID_EMM_ERRC_NULL_SECURITY_ACCEPT_REQ,
MSG_ID_EMM_ERRC_CSG_WHITE_LIST_UPDT_REQ,
MSG_ID_EMM_ERRC_SIM_FILE_UPDATE_REQ,
MSG_ID_EMM_ERRC_CSFB_NTF,
MSG_ID_EMM_ERRC_CSFB_STATUS_REQ,
MSG_ID_EMM_ERRC_CHECK_SERVING_SUITABILITY_REQ,
MSG_ID_EMM_ERRC_SEARCH_PREFERENCE_UPDATE_REQ,
MSG_ID_EMM_ERRC_RAT_CHANGE_CAUSE_UPDATE_REQ,
MSG_ID_EMM_ERRC_GEMINI_LR_REQ,
MSG_ID_EMM_ERRC_GEMINI_SERVICE_REQ,
MSG_ID_EMM_ERRC_MBMS_PACKET_COUNTER_REQ,
MSG_ID_EMM_ERRC_DUPLEX_MODE_CHANGE_REQ,
MSG_ID_EMM_ERRC_UPDATE_UE_LOCATION_INFORMATION_REQ,
MSG_ID_EMM_ERRC_RAT_DISABLE_CONFIG_REQ,
MSG_ID_EMM_ERRC_DATA_ALLOW_REQ,
MSG_ID_EMM_ERRC_PROTECT_TAU_SERVICE_REQ,
MSG_ID_ERRC_LBS_GNSS_POS_IND,
MSG_ID_LBS_ERRC_READ_TIME_SIB_REQ,
MSG_ID_EMM_ERRC_C2K_IRAT_COMPLETE_REQ,
MSG_ID_EMM_ERRC_PROC_RESULT_UPDATE_REQ,
MSG_ID_EMM_ERRC_SET_PGCHECK_REQ,
MSG_ID_EMM_ERRC_HPLMN_INFO_UPDATE_REQ,
MSG_ID_EVAL_ERRC_ADJUST_MEAS_REQ,
MSG_ID_EVAL_ERRC_ETWS_SETTING_REQ,
MSG_ID_EVAL_ERRC_CBCH_REQ,
MSG_ID_EVAL_ERRC_CB_UPDATE_REQ,
MSG_ID_EVAL_ERRC_MMDC_MODE_UPDATE_REQ,
MSG_ID_EVAL_ERRC_LTE_NEIGHBOR_CELL_INFO_REQ,
MSG_ID_EVAL_ERRC_C2K_NORMAL_SERVICE_REQ,
MSG_ID_EVAL_ERRC_NBR_CELL_INFO_START_REQ,
MSG_ID_EVAL_ERRC_NBR_CELL_INFO_STOP_REQ,
MSG_ID_EVAL_ERRC_GET_SSAC_PARAM_REQ,
MSG_ID_EVAL_ERRC_VDM_VOICE_STATUS_REQ,
MSG_ID_EVAL_ERRC_IMS_STATUS_UPDATE_REQ,
MSG_ID_EVAL_ERRC_PLMN_SEARCH_ABORT_REQ,
MSG_ID_EVAL_ERRC_CB_MSG_REMOVAL_REQ,
MSG_ID_EVAL_ERRC_MRU_UPDATE_REQ,
MSG_ID_EVAL_ERRC_CSG_AUTO_SEARCH_MODE_REQ,
MSG_ID_MBMSAL_ERRC_MBMS_CONFIG_REQ,
MSG_ID_EVAL_ERRC_PLMNLIST_ABORT_REQ,
MSG_ID_EVAL_ERRC_ERLM_CONTROL_REQ,
MSG_ID_EVAL_ERRC_CALL_STATUS_IND,
MSG_ID_EVAL_ERRC_ARAL_UPDATE_REQ,
MSG_ID_EVAL_ERRC_NW_BAND_INFO_START_REQ,
MSG_ID_EVAL_ERRC_NW_BAND_INFO_STOP_REQ,
MSG_ID_EVAL_ERRC_SMS_STATUS_REQ,
MSG_ID_EVAL_ERRC_SEMAPHORE_SERVICE_STATUS_REQ,
MSG_ID_EVTH_ERRC_SEMAPHORE_SERVICE_STATUS_REQ,
MSG_ID_EMM_ERRC_SEMAPHORE_SERVICE_STATUS_REQ,
MSG_ID_EVTH_ERRC_IMSM_SEMAPHORE_SERVICE_STATUS_REQ,
MSG_ID_IMS_ERRC_EARLY_CONN_REL_IND,
MSG_ID_EMM_ERRC_SYNC_CONNECTION_STATUS_NTF,
MSG_ID_EMM_ERRC_EPS_BEARER_INFO_REQ,
MSG_ID_EMM_ERRC_IMS_SCM_INFO_REQ,
MSG_ID_EMM_ERRC_MT_SMS_OVER_IMS_STATUS_REQ,
MSG_ID_EVTH_ERRC_FEATURE_CONFIG_REQ,
MSG_ID_EVTH_ERRC_FEATURE_QUERY_REQ,
MSG_ID_ERRC_SIM_PROTECT_REQ,
MSG_ID_SAT_EAS_NMR_REQ,
MSG_ID_ERRC_EL1_SET_RAT_CNF,
MSG_ID_ERRC_EL1_AFC_FWS_ABNORMAL_IND,
MSG_ID_ERRC_EL1MPC_CARRIER_SEARCH_CNF,
MSG_ID_ERRC_EL1MPC_CARRIER_SEARCH_IND,
MSG_ID_ERRC_EL1MPC_CARRIER_SEARCH_STATUS_IND,
MSG_ID_ERRC_EL1MPC_SPECIFIC_MEASURE_CNF,
MSG_ID_ERRC_EL1MPC_SPECIFIC_MEASURE_IND,
MSG_ID_ERRC_EL1MPC_RADIO_MEASURE_CNF,
MSG_ID_ERRC_EL1MPC_RADIO_MEASURE_IND,
MSG_ID_ERRC_EL1MPC_OTDOA_MEAS_CNF,
MSG_ID_ERRC_EL1MPC_OTDOA_CTRL_CNF,
MSG_ID_ERRC_EL1MPC_PRS_GAP_IND,
MSG_ID_ERRC_EL1MPC_NBRCELL_EM_INFO,
MSG_ID_ERRC_EL1MPC_MBSFN_MEASURE_CNF,
MSG_ID_ERRC_EL1MPC_MBSFN_MEASURE_IND,
MSG_ID_LMOB_MOB_POWER_LEVEL_IND,
MSG_ID_LMOB_MOB_RADIO_MEASURE_IND,
MSG_ID_LMOB_MOB_NBRCELL_EM_INFO,
MSG_ID_LMOB_MOB_CEL_RESEL_IND,
MSG_ID_LMOB_MOB_CEL_OOS_IND,
MSG_ID_LMOB_MOB_CEL_NEED_IR_CHANGE_STATUS_IND,
MSG_ID_LMOB_MOB_SCSI_INFO_IND,
MSG_ID_LMOB_MOB_REJ_INFO_IND,
MSG_ID_LMOB_MOB_RADIO_MEASURE_CNF,
MSG_ID_LMOB_MOB_OOS_SCSI_INFO_REQ,
MSG_ID_LMOB_MOB_NBR_CELL_INFO_IND,
MSG_ID_LMOB_MOB_CONFIG_UCELL_MEAS_REQ,
MSG_ID_LMOB_MOB_CONFIG_UCELL_PRIO_MEAS_REQ,
MSG_ID_LMOB_MOB_UCELL_MEAS_IND,
MSG_ID_LMOB_MOB_CONFIG_GCELL_MEAS_REQ,
MSG_ID_LMOB_MOB_CONFIG_GCELL_PRIO_MEAS_REQ,
MSG_ID_LMOB_MOB_GCELL_MEAS_IND,
MSG_ID_LMOB_MOB_GCELL_BSIC_IND,
MSG_ID_LMOB_MOB_CONFIG_CCELL_MEAS_REQ,
MSG_ID_LMOB_MOB_CONFIG_CCELL_PRIO_MEAS_REQ,
MSG_ID_LMOB_MOB_CCELL_MEAS_IND,
MSG_ID_LMOB_MOB_UAS_LTE_MEASUREMENT_CNF,
MSG_ID_LMOB_MOB_GAS_LTE_MEASUREMENT_CNF,
MSG_ID_LMOB_MOB_CAS_LTE_MEASUREMENT_CNF,
MSG_ID_LMOB_MOB_MEAS_INTRARAT_INFO_IND,
MSG_ID_LMOB_MOB_MEAS_INTERRAT_UTRAN_INFO_IND,
MSG_ID_LMOB_MOB_MEAS_INTERRAT_GERAN_INFO_IND,
MSG_ID_LMOB_MOB_MEAS_INTERRAT_C2K_INFO_IND,
MSG_ID_LMOB_MOB_SYNCH_STATUS_CNF,
MSG_ID_LMOB_MOB_CONN_FAKE_IRCCO_GCELL_IND,
MSG_ID_LMOB_MOB_PRS_GAP_IND,
MSG_ID_LMOB_MOB_GCELL_BSIC_ENH_IND,
MSG_ID_MOB_LMOB_MEAS_LOGGING_IND,
MSG_ID_MOB_LMOB_ESTFAIL_REPORT_CNF,
MSG_ID_ERRC_EL1_PAGING_IND,
MSG_ID_ERRC_EL1_BUFFER_CHECK_IND,
MSG_ID_ERRC_EL1_CPHY_CFG_CNF,
MSG_ID_ERRC_EL1_RL_MONITOR_CNF,
MSG_ID_ERRC_EL1_RLF_IND,
MSG_ID_ERRC_EL1_BCCH_IND,
MSG_ID_ERRC_EL1_BCCH_SYS_INFO_IND,
MSG_ID_ERRC_EL1MPC_NBR_BCCH_MEAS_IND,
MSG_ID_ERRC_EL1_SPECIFIC_CELL_SEARCH_CNF,
MSG_ID_ERRC_CEL_SPECIFIC_CELL_SRCH_CNF,
MSG_ID_ERRC_CONN_SPECIFIC_CELL_SRCH_CNF,
MSG_ID_ERRC_EL1_SPECIFIC_CELL_SEARCH_IND,
MSG_ID_ERRC_CEL_SPECIFIC_CELL_SRCH_IND,
MSG_ID_ERRC_CONN_SPECIFIC_CELL_SRCH_IND,
MSG_ID_ERRC_EL1MPC_RSSI_SNIFFER_CNF,
MSG_ID_ERRC_EL1MPC_RSSI_SNIFFER_IND,
MSG_ID_ERRC_EL1_SIB_FRAME_SYNC_IND,
MSG_ID_ERRC_EL1_PCH_CRCNG_IND, /* Need to remove for TK6291 U4G */
MSG_ID_ERRC_EL1_AUTO_GAP_ON_CNF,
MSG_ID_ERRC_EL1_AUTO_GAP_OFF_CNF,
MSG_ID_ERRC_EL1_ACTIVE_AFC_IND,
MSG_ID_ERRC_EL1_HST_IND,
MSG_ID_ERRC_EL1_IDC_IND,
MSG_ID_ERRC_EL1_SCELL_FOUND_IND,
MSG_ID_ERRC_EL1_ABORT_HO_CNF,
MSG_ID_ERRC_EL1_VIRTUAL_MODE_CNF,
MSG_ID_ERRC_EL1_GAP_STATUS_IND, /* VzW MMO C2K GAP */
MSG_ID_ERRC_EMAC_CONTENTION_IND,
MSG_ID_ERRC_EMAC_RA_ERROR_IND,
MSG_ID_ERRC_EMAC_ESTFAIL_REPORT_CNF,
MSG_ID_ERRC_CONN_RRC_TRIGER_RAERR,
MSG_ID_ERRC_EVTH_CHM_NON_RRC_TRIGER_RAERR,
MSG_ID_ERRC_EMAC_CONFIG_CNF,
MSG_ID_ERRC_EMACMCH_SYNCAREA_CFG_CNF,
MSG_ID_ERRC_EMACMCH_AREA_CFG_CNF,
MSG_ID_ERRC_EMACMCH_MXCH_CFG_CNF,
MSG_ID_ERRC_EMACMCH_MCCH_RCV_MODE_CHANGE_CNF,
MSG_ID_ERRC_EMACMCH_MTCH_SUSPEND_IND,
MSG_ID_ERRC_EMAC_L1_UL_REL_IND,
MSG_ID_ERRC_EMAC_RA_INFO_IND,
MSG_ID_ERRC_EMAC_SI_IND,
MSG_ID_ERRC_EMAC_TA_INFO_CNF,
MSG_ID_ERRC_EMAC_TA_INFO_IND,
MSG_ID_ERRC_EMAC_TA_INFO_INVALID_IND,
MSG_ID_LPP_ERRC_ECID_MEAS_REQ,
MSG_ID_LPP_ERRC_ECID_MEAS_ABORT_REQ,
MSG_ID_LPP_ERRC_OTDOA_MEAS_REQ,
MSG_ID_LPP_ERRC_OTDOA_MEAS_ABORT_REQ,
MSG_ID_LPP_ERRC_SRB_STATUS_REQ,
MSG_ID_ERRC_EVTH_SYS_SI,
MSG_ID_ERRC_EVTH_SYS_SIB1,
MSG_ID_ERRC_EVTH_SYS_BCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_SYS_BCCH_UNDEFINE,
MSG_ID_ERRC_EMAC_CCCH_DATA_IND,
MSG_ID_ERRC_EMAC_CA_ACTIVATE_IND,
MSG_ID_ERRC_EVTH_CONN_CONN_REEST,
MSG_ID_ERRC_EVTH_CONN_CONN_REEST_REJ,
MSG_ID_ERRC_EVTH_CONN_CONN_REJ,
MSG_ID_ERRC_EVTH_CONN_CONN_SETUP,
MSG_ID_ERRC_EVTH_CONN_CCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_CONN_CCCH_UNDEFINE,
MSG_ID_ERRC_EPDCP_MCCH_DATA_IND,
MSG_ID_ERRC_EVTH_CONN_MBSFN_AREA_CFG,
MSG_ID_ERRC_EVTH_CONN_MBMS_CNT_REQ,
MSG_ID_ERRC_ERLCUL_CONFIG_CNF,
MSG_ID_ERRC_ERLCDL_CONFIG_CNF,
MSG_ID_ERRC_ERLC_RLF_IND,
MSG_ID_ERRC_ERLCUL_SRB1_ACK_CNF,
MSG_ID_ERRC_ERLC_VIP_DATA_STATUS_IND,
MSG_ID_ERRC_EPDCP_CONFIG_CNF,
MSG_ID_ERRC_EPDCP_DCCH_DATA_CNF,
MSG_ID_ERRC_EPDCP_RLC_INFOTRANS_ACK_IND,
MSG_ID_ERRC_EPDCP_RLC_UEINFO_ACK_IND,
MSG_ID_ERRC_EPDCP_RLC_MOB_ACK_IND,
MSG_ID_ERRC_EPDCP_DCCH_DATA_IND,
MSG_ID_ERRC_EVTH_CONN_DL_INFO_TRANS,
MSG_ID_ERRC_EVTH_CONN_MOB_FROM_EUTRA_CMD,
MSG_ID_ERRC_EVTH_CONN_CONN_RECONF,
MSG_ID_ERRC_EVTH_CONN_RECONF_PRECHK,
MSG_ID_ERRC_EVTH_CONN_CONN_REL,
MSG_ID_ERRC_EVTH_CONN_SECURITY_MODE_CMD,
MSG_ID_ERRC_EVTH_RCM_UE_CAPA_ENQ,
MSG_ID_EL1_ERRC_FACTORY_CAPABILITY_IND,
MSG_ID_ERRC_EVTH_CONN_COUNTER_CHECK,
MSG_ID_ERRC_EVTH_CONN_UE_INFO_REQ,
MSG_ID_ERRC_EVTH_CONN_DCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_CONN_IRAT_DCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_CONN_DCCH_INTG_CHK_ERR,
MSG_ID_ERRC_EVTH_CONN_DCCH_UNDEFINE,
MSG_ID_ERRC_EVTH_MOB_LOGGED_MEAS_CFG,
MSG_ID_ERRC_EPDCP_TEST_CNF,
MSG_ID_ERRC_ERLCDL_TEST_CNF,
MSG_ID_ERRC_EPDCP_CNTINFO_CNF,
MSG_ID_ERRC_EPDCP_DETECTION_TIMER_TIMEOUT_IND,
MSG_ID_ERRC_EPDCP_PS_DATA_INACTIVE_TIME_IND,
MSG_ID_ERRC_EPDCP_MTCH_PC_CNF,
MSG_ID_ERRC_ERLCDL_MTCH_PC_CNF,
MSG_ID_ERRC_TIMER_TRIG_TIMEOUT_REQ,
MSG_ID_ERRC_EVTH_RCM_CSG_WHITE_LIST_UPDATE_IND,
MSG_ID_ERRC_EVTH_RCM_NVRAM_READ_CNF,
MSG_ID_ERRC_EVTH_RCM_NVRAM_WRITE_CNF,
MSG_ID_ERRC_EVTH_RCM_BAND_UPDATE_IND,
MSG_ID_ERRC_EVTH_RCM_SBP_RECONFIG_REQ,
MSG_ID_ERRC_EVTH_RCM_SIM_SWITCH_REQ,
MSG_ID_ERRC_EVTH_CEL_LOWER_LAYER_AVAILABILITY_UPDATE_IND,
MSG_ID_ERRC_EVTH_RCM_DISABLE_B39_IND,
MSG_ID_ERRC_EVTH_RCM_ENABLE_B39_IND,
MSG_ID_ERRC_EVTH_RCM_BAND_CTRL_IND,
MSG_ID_CLC_EAS_EARFCN_LIST_UPDATE_REQ,
MSG_ID_UAS_EAS_HANDOVER_ECELL_REQ,
MSG_ID_ERRC_EVTH_CONN_IRAT_RECONF,
MSG_ID_UAS_EAS_ABORT_HO_ECELL_REQ,
MSG_ID_MRS_EAS_UMTS_HO_INFO_IND,
MSG_ID_MRS_EAS_CLEAR_BLACK_CELL_IND,
MSG_ID_EAS_UAS_HANDOVER_UCELL_CNF,
MSG_ID_EAS_GAS_HANDOVER_GCELL_CNF,
MSG_ID_EAS_UAS_HO_ACTIVATE_UCELL_CNF,
MSG_ID_EAS_GAS_HO_ACTIVATE_GCELL_CNF,
MSG_ID_GAS_EAS_EVALUATE_ECELL_REQ,
MSG_ID_UAS_EAS_EVALUATE_ECELL_REQ,
MSG_ID_CAS_EAS_EVALUATE_ECELL_REQ,
MSG_ID_GAS_EAS_EVALUATE_ECELL_STOP_REQ,
MSG_ID_UAS_EAS_EVALUATE_ECELL_STOP_REQ,
MSG_ID_CAS_EAS_EVALUATE_ECELL_STOP_REQ,
MSG_ID_EAS_GAS_EVALUATE_GCELL_CNF,
MSG_ID_EAS_UAS_EVALUATE_UCELL_CNF,
MSG_ID_EAS_GAS_EVALUATE_GCELL_STOP_CNF,
MSG_ID_EAS_UAS_EVALUATE_UCELL_STOP_CNF,
MSG_ID_EAS_GAS_ACTIVATE_GCELL_CNF,
MSG_ID_EAS_UAS_ACTIVATE_UCELL_CNF,
MSG_ID_EAS_CAS_ACTIVATE_CCELL_CNF,
MSG_ID_GAS_EAS_READY_TIMER_STATUS_IND,
MSG_ID_GAS_EAS_EVALUATE_CSG_ECELL_REQ,
MSG_ID_UAS_EAS_EVALUATE_CSG_ECELL_REQ,
MSG_ID_GAS_EAS_SEARCH_CSG_ECELL_REQ,
MSG_ID_UAS_EAS_SEARCH_CSG_ECELL_REQ,
MSG_ID_EAS_UAS_EVALUATE_CSG_UCELL_CNF,
MSG_ID_EAS_UAS_SEARCH_CSG_UCELL_CNF,
MSG_ID_UAS_EAS_LTE_MEASUREMENT_REQ,
MSG_ID_GAS_EAS_LTE_MEASUREMENT_REQ,
MSG_ID_CAS_EAS_LTE_MEASUREMENT_REQ,
MSG_ID_EAS_CAS_CCELL_MEAS_IND,
MSG_ID_UAS_EAS_LTE_HPS_QUALIFY_CELL_IND,
MSG_ID_GAS_EAS_LTE_HPS_QUALIFY_CELL_IND,
MSG_ID_CAS_EAS_LTE_HPS_QUALIFY_CELL_IND,
MSG_ID_EAS_FDD_UAS_CONFIG_UCELL_MEAS_CNF,
MSG_ID_EAS_TDD_UAS_CONFIG_UCELL_MEAS_CNF,
MSG_ID_EAS_GAS_CONFIG_GCELL_MEAS_CNF,
MSG_ID_EAS_CAS_CONFIG_CCELL_MEAS_CNF,
MSG_ID_EAS_FDD_UAS_CONFIG_UCELL_PRIO_MEAS_CNF,
MSG_ID_EAS_TDD_UAS_CONFIG_UCELL_PRIO_MEAS_CNF,
MSG_ID_EAS_GAS_CONFIG_GCELL_PRIO_MEAS_CNF,
MSG_ID_EAS_FDD_UAS_UCELL_MEAS_IND,
MSG_ID_EAS_TDD_UAS_UCELL_MEAS_IND,
MSG_ID_EAS_GAS_GCELL_MEAS_IND,
MSG_ID_EAS_GAS_GCELL_BSIC_IND,
MSG_ID_EAS_UAS_REPORT_CGI_CNF,
MSG_ID_EAS_GAS_REPORT_CGI_CNF,
MSG_ID_EAS_CAS_REPORT_CGI_CNF,
MSG_ID_UAS_EAS_BACKGROUND_SEARCH_START_REQ,
MSG_ID_UAS_EAS_BACKGROUND_SEARCH_STOP_REQ,
MSG_ID_GAS_EAS_BACKGROUND_SEARCH_START_REQ,
MSG_ID_GAS_EAS_BACKGROUND_SEARCH_STOP_REQ,
MSG_ID_UAS_EAS_BUILD_FINGERPRINT_REQ,
MSG_ID_UAS_EAS_ABORT_FINGERPRINT_IND,
MSG_ID_EAS_UAS_BUILD_FINGERPRINT_CNF,
MSG_ID_EAS_GAS_BUILD_FINGERPRINT_CNF,
MSG_ID_GAS_EAS_EARFCN_LIST_UPDATE_REQ,
MSG_ID_RSVAS_EAS_SERVICE_RES_OCCUPY_IND,
MSG_ID_RSVAS_EAS_SUSPEND_SERVICE_REQ,
MSG_ID_RSVAS_EAS_RESUME_SERVICE_REQ,
MSG_ID_RSVAS_EAS_ABORT_SERVICE_REQ,
MSG_ID_RSVAS_EAS_ABORT_SERVICE_COMPLETE_IND,
MSG_ID_RSVAS_EAS_VIRTUAL_SUSPEND_SERVICE_REQ,
MSG_ID_RSVAS_EAS_VIRTUAL_SUSPEND_SERVICE_COMPLETE_IND,
MSG_ID_RSVAS_EAS_VIRTUAL_RESUME_SERVICE_REQ,
MSG_ID_RSVAS_EAS_VIRTUAL_SUSPEND_STATUS_IND,
MSG_ID_CAS_EAS_C2K_POWER_ON_IND,
MSG_ID_CAS_EAS_C2K_POWER_OFF_IND,
MSG_ID_RSVAE_EAS_FREQUENCY_SCAN_ACCEPT_IND,
MSG_ID_RSVAE_EAS_FREQUENCY_SCAN_PREEMPT_IND,
MSG_ID_LTECSR_ERRC_VOLTE_STATUS_NTF,
MSG_ID_EVAL_ERRC_IMS_CALL_STATUS_REQ,
MSG_ID_LTECSR_ERRC_VOLTE_CALL_SILENCE_NTF,
MSG_ID_EVAL_ERRC_EDDA_REQ,
MSG_ID_EVAL_ERRC_LTECA_MODE_SETTING_REQ,
MSG_ID_EVAL_ERRC_OMADM_UPDATE_REQ,
MSG_ID_EVAL_ERRC_LTE_TM9_FDD_TDD_SETTING_REQ,
MSG_ID_EVAL_ERRC_CA_BAND_COMB_LIST_REQ,
MSG_ID_ML1S_ERRC_TEST_MODE_ENABLE_REQ,
MSG_ID_L4C_CELL_POWER_THRESHOLD_CONFIG_REQ,
MSG_ID_IWLAN_ERRC_WLAN_CAPABILITY_REQ,
MSG_ID_IWLAN_ERRC_WLAN_LWA_CONNECT_RSP,
MSG_ID_IWLAN_ERRC_WLAN_LWA_LOST_REQ,
MSG_ID_IWLAN_ERRC_WLAN_LWA_DISCONNECT_RSP,
MSG_ID_IWLAN_ERRC_WLAN_MEASUREMENT_REQ,
MSG_ID_IWLAN_ERRC_LWI_STEER_STATUS_REQ,
MSG_ID_CLC_ERRC_EVDO_PS_CONNECTION_STATUS_IND,
MSG_ID_PSW_ERRC_1XRTT_PS_CONNECTION_STATUS_IND,
MSG_ID_EAS_GAS_BSIC_ENH_IND,
MSG_ID_EVAL_ERRC_HQ_SERVICE_STATUS_REQ,
MSG_ID_ERRC_ERLCUL_SWITCH_VIRTUAL_CONNECTED_CNF,
MSG_ID_ERRC_ERLCDL_SWITCH_VIRTUAL_CONNECTED_CNF,
MSG_ID_ERRC_EPDCP_SWITCH_VIRTUAL_CONNECTED_CNF,
MSG_ID_RSVAS_EAS_VIRTUAL_CONNECTED_SUSPEND_REQ,
MSG_ID_RSVAS_EAS_VIRTUAL_CONNECTED_RESUME_REQ,
MSG_ID_EMM_ERRC_NAS_FAIL_HANDLE_REQ,
MSG_ID_EXEVT_RCV_END,
MSG_ID_INEVT_BEGIN,
MSG_ID_ERRC_SPV_RCM_INIT_REQ,
MSG_ID_ERRC_SPV_RCM_INIT_CNF,
MSG_ID_ERRC_SPV_RCM_RAT_BAND_REQ,
MSG_ID_ERRC_SPV_RCM_RAT_BAND_CNF,
MSG_ID_ERRC_SPV_RCM_USIM_REQ,
MSG_ID_ERRC_SPV_RCM_USIM_CNF,
MSG_ID_ERRC_ANY_RCM_CONTEXT_WRITE_IND,
MSG_ID_ERRC_ANY_SPV_CHANGE_STATE_REQ,
MSG_ID_ERRC_ANY_SPV_CHANGE_STATE_CNF,
MSG_ID_ERRC_SPV_RCM_PARAM_REQ,
MSG_ID_ERRC_SPV_RCM_PARAM_CNF,
MSG_ID_ERRC_SPV_CEL_PARAM_REQ,
MSG_ID_ERRC_SPV_CEL_PARAM_CNF,
MSG_ID_ERRC_SPV_CONN_KEY_UPDT_REQ,
MSG_ID_ERRC_SPV_CONN_KEY_UPDT_CNF,
MSG_ID_ERRC_SPV_CONN_MBMS_SERVSESS_REQ,
MSG_ID_ERRC_SPV_CONN_MBMS_SERVSESS_CNF,
MSG_ID_ERRC_SPV_CONN_TEST_REQ,
MSG_ID_ERRC_SPV_CONN_TEST_CNF,
MSG_ID_ERRC_SPV_ANY_MBMS_EVENT_IND,
MSG_ID_ERRC_ANY_SPV_MBMS_EVENT_IND,
MSG_ID_ERRC_SPV_CONN_STATUS_UPDATE_REQ,
MSG_ID_ERRC_SPV_ANY_STBY_REQ,
MSG_ID_ERRC_SPV_ANY_STBY_CNF,
MSG_ID_ERRC_SPV_ANY_STANDBY_CMPL_IND,
MSG_ID_ERRC_SPV_ANY_RAT_CHANGE_REQ,
MSG_ID_ERRC_SPV_ANY_RAT_CHANGE_CNF,
MSG_ID_ERRC_ANY_SPV_RAT_CHANGE_IND,
MSG_ID_ERRC_ANY_SPV_RAT_CHANGE_RES,
MSG_ID_ERRC_SPV_ANY_FLIGHT_MODE_REQ,
MSG_ID_ERRC_SPV_ANY_FLIGHT_MODE_CNF,
MSG_ID_ERRC_SPV_ANY_IRTOLTE_SUCCESS_IND,
MSG_ID_ERRC_SPV_CONN_SERVICE_RES_OCCUPY_IND,
MSG_ID_ERRC_SPV_ANY_GEMINI_SUSPEND_REQ,
MSG_ID_ERRC_SPV_ANY_GEMINI_SUSPEND_CNF,
MSG_ID_ERRC_SPV_ANY_GEMINI_RESUME_REQ,
MSG_ID_ERRC_SPV_ANY_GEMINI_RESUME_CNF,
MSG_ID_ERRC_SPV_ANY_GEMINI_RESUME_COMPLETE_IND,
MSG_ID_ERRC_SPV_ANY_GEMINI_VIRTUAL_SUSPEND_REQ,
MSG_ID_ERRC_SPV_ANY_GEMINI_VIRTUAL_SUSPEND_CNF,
MSG_ID_ERRC_SPV_ANY_GEMINI_VIRTUAL_SUSPEND_COMPLETE_IND,
MSG_ID_ERRC_SPV_ANY_GEMINI_VIRTUAL_RESUME_REQ,
MSG_ID_ERRC_SPV_ANY_GEMINI_ABORT_REQ,
MSG_ID_ERRC_SPV_ANY_GEMINI_ABORT_CNF,
MSG_ID_ERRC_SPV_ANY_GEMINI_ABORT_COMPLETE_IND,
MSG_ID_ERRC_SPV_RCM_DUPLEX_MODE_CHANGE_REQ,
MSG_ID_ERRC_SPV_RCM_DUPLEX_MODE_CHANGE_CNF,
MSG_ID_ERRC_CEL_SYS_BCCH_ACT_REQ,
MSG_ID_ERRC_CEL_SYS_BCCH_ACT_CNF,
MSG_ID_ERRC_CEL_SYS_BCCH_DEACT_IND,
MSG_ID_ERRC_SYS_CEL_BCCH_RCVD_IND,
MSG_ID_ERRC_CEL_SYS_DB_UPDT_IND,
MSG_ID_ERRC_CEL_SYS_SOFT_IDX_CHG_IND,
MSG_ID_ERRC_CEL_SYS_PWS_ACT_IND,
MSG_ID_ERRC_CEL_SYS_PWS_DEACT_IND,
MSG_ID_ERRC_SYS_CEL_PWS_RCVD_IND,
MSG_ID_ERRC_SYS_CEL_BCCH_EXPR_IND,
MSG_ID_ERRC_CEL_SYS_CLEAR_DEDICATED_SIB,
MSG_ID_ERRC_CEL_CONN_IDLE_IND,
MSG_ID_ERRC_CONN_CEL_RRC_CONNECTED_REQ,
MSG_ID_ERRC_CONN_CEL_RRC_CONNECTED_CNF,
MSG_ID_ERRC_CONN_CEL_IDLE_REQ,
MSG_ID_ERRC_CEL_CONN_CH_STATUS_IND,
MSG_ID_ERRC_CONN_CEL_REEST_REQ,
MSG_ID_ERRC_CONN_CEL_REEST_CNF,
MSG_ID_ERRC_CONN_CEL_HO_UPDATE_CELL_IND,
MSG_ID_ERRC_CONN_CEL_HO_SUCCESS_IND,
MSG_ID_ERRC_CEL_CONN_UPDT_MIB_IND,
MSG_ID_ERRC_CEL_CONN_UPDT_SIB_IND,
MSG_ID_ERRC_CONN_CEL_CNCT_NG_IND,
MSG_ID_ERRC_CEL_CONN_CELL_NO_SUITABLE_IND,
MSG_ID_ERRC_CONN_CEL_REEST_CMPL_REQ,
MSG_ID_ERRC_CONN_CEL_REEST_CMPL_CNF,
MSG_ID_ERRC_CONN_CEL_EST_JDG_REQ,
MSG_ID_ERRC_CONN_CEL_EST_JDG_CNF,
MSG_ID_ERRC_CONN_CEL_CCO_RESULT_IND,
MSG_ID_ERRC_CONN_CEL_MBMS_SCELL_REQ,
MSG_ID_ERRC_CONN_CEL_MBMS_SCELL_CNF,
MSG_ID_ERRC_CONN_MOB_ESTFAIL_REPORT_REQ,
MSG_ID_ERRC_CONN_MOB_ESTFAIL_REPORT_CNF,
MSG_ID_ERRC_CONN_MOB_WLAN_LOST_IND,
MSG_ID_ERRC_CEL_CONN_IRCCO_ABORT_EST_IND,
MSG_ID_ERRC_CEL_CONN_STATE_UNSYNC_IND,
MSG_ID_ERRC_CEL_MOB_KCELLS_REQ,
MSG_ID_ERRC_CEL_MOB_KCELLS_CNF,
MSG_ID_ERRC_MOB_CEL_RESEL_IND,
MSG_ID_ERRC_MOB_CEL_OOS_IND,
MSG_ID_ERRC_CEL_MOB_CELL_REJ_IND,
MSG_ID_ERRC_CEL_MOB_CELL_RJCT_CLR_IND,
MSG_ID_ERRC_MOB_CEL_REST_LIST_IND,
MSG_ID_ERRC_MOB_CEL_NEED_IR_CHANGE_STATUS_IND,
MSG_ID_ERRC_CEL_MOB_UPDATE_CAUSE_IND,
MSG_ID_ERRC_RCM_MOB_USIM_IND,
MSG_ID_ERRC_MOB_CEL_SI_MEAS_IND,
MSG_ID_ERRC_ANY_MOB_MEAS_PRE_CTRL_REQ,
MSG_ID_ERRC_ANY_MOB_MEAS_PRE_CTRL_CNF,
MSG_ID_ERRC_ANY_MOB_MEAS_POST_CTRL_REQ,
MSG_ID_ERRC_ANY_MOB_MEAS_POST_CTRL_CNF,
MSG_ID_ERRC_ANY_MOB_OTDOA_PRE_CTRL_REQ,
MSG_ID_ERRC_ANY_MOB_OTDOA_PRE_CTRL_CNF,
MSG_ID_ERRC_ANY_MOB_OTDOA_POST_CTRL_REQ,
MSG_ID_ERRC_ANY_MOB_OTDOA_POST_CTRL_CNF,
MSG_ID_ERRC_MOB_CONN_GAP_INTERNAL_CHG_IND,
MSG_ID_ERRC_CEL_MOB_MEAS_REQ,
MSG_ID_ERRC_CEL_MOB_MEAS_CNF,
MSG_ID_ERRC_MOB_CEL_RPT_CGI_REQ,
MSG_ID_ERRC_MOB_CEL_RPT_CGI_CNF,
MSG_ID_ERRC_CEL_MOB_CSG_STATUS_IND,
MSG_ID_ERRC_CEL_MOB_EMERGENCY_STATUS_IND,
MSG_ID_ERRC_ANY_MOB_IR_MEAS_CTRL_REQ,
MSG_ID_ERRC_CEL_MOB_IR_REDIRECT_TO_LTE_IND,
MSG_ID_ERRC_CEL_MOB_MBMS_SCELL_SEARCH_REQ,
MSG_ID_ERRC_CEL_MOB_MBMS_SCELL_SEARCH_CNF,
MSG_ID_ERRC_CEL_MOB_MBMS_SCELL_SEARCH_IND,
MSG_ID_ERRC_CHM_MOB_LWA_CFG_IND,
MSG_ID_ERRC_LCEL_CEL_PAGING_IND,
MSG_ID_ERRC_ANY_CHM_CH_CTRL_REQ,
MSG_ID_ERRC_ANY_CHM_CH_CTRL_CNF,
MSG_ID_ERRC_CHM_CONN_L1_CTRLING_IND,
MSG_ID_ERRC_CHM_CONN_RLF_IND,
MSG_ID_ERRC_CHM_SYS_BCCH_DL_SYNC_FAIL_IND,
MSG_ID_ERRC_CONN_CHM_LPBK_REQ,
MSG_ID_ERRC_CONN_CHM_LPBK_CNF,
MSG_ID_ERRC_CONN_ANY_SUS_REQ,
MSG_ID_ERRC_CONN_ANY_SUS_CNF,
MSG_ID_ERRC_CONN_ANY_RSM_REQ,
MSG_ID_ERRC_CONN_ANY_RSM_CNF,
MSG_ID_ERRC_ANY_CONN_REEST_IND,
MSG_ID_ERRC_TIMER_EXPR_IND,
MSG_ID_ERRC_TIMER_START_IND,
MSG_ID_ERRC_TIMER_STOP_IND,
MSG_ID_ERRC_RCM_CONN_PWS_CAPA_UPDT_IND,
MSG_ID_ERRC_RCM_ANY_CSG_WHITELIST_UPDATE_IND,
MSG_ID_ERRC_RCM_ANY_ACC_UPDATE_IND,
MSG_ID_ERRC_RCM_ANY_DISABLE_B39_IND,
MSG_ID_ERRC_RCM_ANY_ENABLE_B39_IND,
MSG_ID_ERRC_RCM_CEL_START_HSR_SNIFFER,
MSG_ID_ERRC_RCM_CEL_STOP_HSR_SNIFFER,
MSG_ID_ERRC_RCM_LCEL_USIM_REQ,
MSG_ID_ERRC_RCM_LCEL_STMSI_UPDATE_REQ,
MSG_ID_ERRC_MOD_GLOBAL_VAR,
MSG_ID_ERRC_GET_VAR_ADDR,
MSG_ID_ERRC_RETURN_VAR_ADDR,
MSG_ID_ERRC_CHK_DL_DCCH_MSG_IE_IND,
MSG_ID_ERRC_CHK_DL_CCCH_MSG_IE_IND,
MSG_ID_ERRC_CHK_MCCH_MSG_IE_IND,
MSG_ID_ERRC_BCCH_SIB_PTR,
MSG_ID_ERRC_LSYS_NOPDCCH_DATA,
MSG_ID_ERRC_LSYS_SYS_BCCH_IND,
MSG_ID_ERRC_LSYS_SYS_SI_IND,
MSG_ID_ERRC_LSYS_SYS_BCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_LSYS_SYS_BCCH_UNDEFINE,
MSG_ID_ERRC_LSYS_SYS_NOPDCCH_IND,
MSG_ID_ERRC_MIB_DATA,
MSG_ID_ERRC_SIB1_DATA,
MSG_ID_ERRC_SIB2_DATA,
MSG_ID_ERRC_SIB3_DATA,
MSG_ID_ERRC_SIB4_DATA,
MSG_ID_ERRC_SIB4_CSG_DATA,
MSG_ID_ERRC_SIB5_DATA,
MSG_ID_ERRC_SIB6_DATA,
MSG_ID_ERRC_SIB7_DATA,
MSG_ID_ERRC_SIB8_DATA,
MSG_ID_ERRC_SIB9_DATA,
MSG_ID_ERRC_SIB10_DATA,
MSG_ID_ERRC_SIB11_DATA,
MSG_ID_ERRC_SIB12_DATA,
MSG_ID_ERRC_SIB13_DATA,
MSG_ID_ERRC_SIB14_DATA,
MSG_ID_ERRC_SIB15_DATA,
MSG_ID_ERRC_SIB16_DATA,
MSG_ID_ERRC_SIB17_DATA,
MSG_ID_ERRC_SYS_STS_TBL,
MSG_ID_ERRC_SYS_BCCH_TBL_CTRL_INF,
MSG_ID_ERRC_SYS_PWS_RECEPTION_TBL,
MSG_ID_ERRC_SYS_STORED_INF,
MSG_ID_ERRC_SYS_DLIST_HEAD_INF,
MSG_ID_ERRC_NVM_TBL,
MSG_ID_ERRC_SIM_INFO,
MSG_ID_ERRC_UE_CAPA_MNG_TBL,
MSG_ID_ERRC_PWS_SETTING_TBL,
MSG_ID_ERRC_SPV_TBL,
MSG_ID_ERRC_CHM_CTRL_TBL,
MSG_ID_ERRC_CHM_L1_TABLE,
MSG_ID_ERRC_CHM_L2_TABLE,
MSG_ID_ERRC_MBMS_CONFIG,
MSG_ID_ERRC_FINGERPRINT_RECORD,
MSG_ID_ERRC_LEARNED_MCC_RECORD,
MSG_ID_ERRC_STORED_CELL_INF,
MSG_ID_ERRC_STORED_CARR_DATA,
MSG_ID_ERRC_RCM_TEST,
MSG_ID_ERRC_MRS_API_RESULT,
MSG_ID_ERRC_CHM_API_RESULT,
MSG_ID_ERRC_SPV_API_RESULT,
MSG_ID_ERRC_COMMON_API_RESULT,
MSG_ID_ERRC_CONN_LEAVE_CONNECTED_MODE_IND,
MSG_ID_ERRC_MOB_CONN_FAKE_IRCCO_GCELL_IND,
MSG_ID_ERRC_MRU_TABLE,
MSG_ID_ERRC_MBMS_TBL,
MSG_ID_ERRC_SPV_ANY_C2K_POWER_ON_IND,
MSG_ID_ERRC_SPV_ANY_C2K_POWER_OFF_IND,
MSG_ID_ERRC_RCM_UE_EUTRA_CAP_INFO,
MSG_ID_ERRC_SYS_CEL_DEDICATED_SIB1_IND,
MSG_ID_ERRC_SPV_CEL_RSIM_RESUME_CMPL_IND,
MSG_ID_ERRC_CHM_LWA_CONFIGURATION,
MSG_ID_ERRC_ANY_CARRS_UPDATE_IND,
MSG_ID_ERRC_SPV_CONN_VIRTUAL_CONNECTED_SUSPEND_REQ,
MSG_ID_ERRC_SPV_CONN_VIRTUAL_CONNECTED_SUSPEND_CNF,
MSG_ID_ERRC_SPV_CONN_VIRTUAL_CONNECTED_RESUME_REQ,
MSG_ID_ERRC_SPV_CONN_VIRTUAL_CONNECTED_RESUME_CNF,
MSG_ID_INEVT_END,

MODULE_MSG_END( MSG_ID_ERRC_CODE_TAIL )

#endif /* _ERRC_MSGID_H */
