/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************

  FILE NAME:  hsc_msgid.h

  DESCRIPTION:

    This file contains the defenitions of all the HSC msg id's.
    
  HISTORY     :    
    1.File Create by atlas.xu, 2016,2,4

*****************************************************************************/

#ifndef _HSC_MSG_ID_H
#define _HSC_MSG_ID_H


/*----------------------------------------------------------------------------
     Command Message IDs, for FCP task, for HSC_CMD_MAILBOX, EXE_MAILBOX_1_ID
     The message IDs for components shall also be put in here.
     Satya: Add all the PKT_SIM related messages into the area that is defined
     between #ifdef/#endif..Contact me, if you need any clarifications!.
----------------------------------------------------------------------------*/
#include "module_msg_range.h"



MODULE_MSG_BEGIN( MSG_ID_HSC_CODE_BEGIN )
    MSG_ID_HSC_MPA_MSGID_START =  MSG_ID_HSC_CODE_BEGIN,  
    MSG_ID_MPA_RF_ANTENNA_REQUEST_MSG,
    MSG_ID_MPA_RF_RELEASE_IND_MSG,
    MSG_ID_MPA_RF_SHUTOFF_RSP_MSG,
    MSG_ID_MPA_RF_ANTENNA_RELEASE_REQ_MSG,
    MSG_ID_MPA_RF_ANTENNA_ASSIGN_MSG,
    MSG_ID_MPA_RF_ANTENNA_REQUEST_CANCEL_MSG,
    MSG_ID_HSC_MPA_MSGID_LAST,    

    MSG_ID_HSC_SPDO_MSGID_START,
    MSG_ID_HSC_IDP_HANDOFF_CMD_MSG,
    MSG_ID_HSC_IDP_WAKE_CMD_MSG,
    MSG_ID_HSC_IDP_SLEEP_CMD_MSG,
    MSG_ID_HSC_IDP_SRCH_DONE_MSG,
    MSG_ID_HSC_SLEEP_ACK_MSG,
    MSG_ID_HSC_RMC_MINIACQ_RESULT_MSG,
    MSG_ID_HSC_IDP_DISABLE_DO_SLOTTED_MSG,
    MSG_ID_HSC_IDP_ENABLE_DO_SLOTTED_MSG,
    MSG_ID_HSC_CLK_CAL_START_MSG,
    MSG_ID_HSC_IDP_THAW_REQ_MSG,
    MSG_ID_HSC_TIME_PROFILE_MSG,

    MSG_ID_HSC_SPDO_INIT_WARM_MSG,
    MSG_ID_HSC_RESYNC_IND_MSG,
    MSG_ID_HSC_DO_RESYNC_DENIED_MSG,
    MSG_ID_HSC_WAKE_IND_MSG,
    MSG_ID_HSC_FREEZE_MSG,
    MSG_ID_HSC_THAW_MSG,
    MSG_ID_HSC_FM_RESULT_UPDATE_MSG,
    MSG_ID_HSC_SP_RESYNC_RECORD_MSG,
    MSG_ID_HSC_SPDO_MSGID_LAST,
 
    MSG_ID_HSC_SP1X_MSGID_START,
    MSG_ID_L1D_SLEEP_RDY_MSG,
    MSG_ID_HSC_1X_PRIORITY_BOOST_MSG,
    MSG_ID_HSC_DO_PRIORITY_BOOST_MSG,
    MSG_ID_HSC_SP1X_MSGID_LAST,
 
    MSG_ID_HSC_CMD_MSGID_START,
    MSG_ID_L1D_OOSA_REQ_MSG,
    MSG_ID_L1D_OOSA_CONT_MSG,
    MSG_ID_L1D_OOSA_WAKEUP_MSG,
    MSG_ID_HSC_CLC_OOSA_SLEEP_CMD_MSG,
    MSG_ID_HSC_CLC_OOSA_CONT_CMD_MSG,
    MSG_ID_HSC_CLC_OOSA_WAKE_CMD_MSG,
    MSG_ID_HSC_RMC_OOSA_RDY_MSG,
    MSG_ID_HSC_L1D_OOSA_RDY_MSG,
    MSG_ID_HSC_ALTERNATE_AFC_MSG,
    MSG_ID_HSC_SET_SHDR_SVDO_OP_MODE_MSG,
    MSG_ID_HSC_SLEEPOVER_INT_COMP_MSG, 

    /* IRAT */
    MSG_ID_HSC_INSP_SUSPEND_SLEEP_CMD_MSG,
    MSG_ID_LL1A_RMC_RAT_STATUS_IND_MSG,
    MSG_ID_LL1A_RMC_MODE_STATUS_IND_MSG,
    MSG_ID_LL1A_RMC_ACTIVE_MEASURE_INFO_IND_MSG,
    MSG_ID_LL1A_EVSTANDBY_MEASURE_REQ_MSG,
    MSG_ID_LL1A_EVSTANDBY_MEAS_DONE_IND_MSG,
    MSG_ID_LL1A_EVSTANDBY_GAP_STOP_CNF_MSG,
    MSG_ID_LL1A_EVSTANDBY_AUTO_GAP_END_REQ_MSG,
    MSG_ID_LL1A_EVSTANDBY_AUTO_GAP_STOP_RES_MSG,
    MSG_ID_LL1A_EVSTANDBY_AUTO_GAP_REQ_MSG,
    MSG_ID_LL1A_EVSTANDBY_AUTO_GAP_REQ_CANCEL_MSG,
    MSG_ID_HSC_LL1A_MSGID_LAST,
    MSG_ID_HSC_CSS_SUSPEND_RESUME_CMD_MSG,
    MSG_ID_HSC_C2K_SIM_INDEX_INFO_MSG,
    MSG_ID_HSC_C2K_MMO_GAP_INFO_MSG,
    MSG_ID_HSC_C2K_RTBA_CHANNEL_STATUS_INFO_MSG,
    MSG_ID_HSC_C2K_HSC_MPA_STATUS_INFO_MSG,
    MSG_ID_LL1A_EVSTANDBY_SPECIFIC_GAP_REQ_MSG,

    MSG_ID_HSC_CLC_SIB8_INFO_CFG_MSG,
    MSG_ID_HSC_SIB8_TIMING_SYNC_REQ,
    MSG_ID_HSC_SIB8_TIMING_SYNC_CNF,
    MSG_ID_HSC_SIB8_TIMING_STATE_TIMER_EXPIRY,
    MSG_ID_HSC_RECOVER_TIMING_CNF,
    MSG_ID_LL1A_L1D_MODE_STATUS_IND,
    MSG_ID_LL1A_CLC_LTE_SCAN_C2K_ACTIVE_PARAMS_IND,
    MSG_ID_LL1A_IDP_SIGNAL_PROTECT_STATUS_IND,
    MSG_ID_LL1A_PSW_SIGNAL_PROTECT_STATUS_IND,
    MSG_ID_HSC_INFINITE_SLEEP_REQ_MSG,    
    MSG_ID_C2K_SLEEP_CTRL_MSG,
    MSG_ID_HSC_FRC_SYNC_INFO_REPT_MSG,
    MSG_ID_HSC_CSS_PSEUDO_SET_RAT_IND,
    MSG_ID_HSC_CMD_MSGID_LAST,

    MSG_ID_IRQ_TO_HISR_SYSTIME,
MODULE_MSG_END( MSG_ID_HSC_CODE_TAIL )

#endif

