/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
 /*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of MediaTek Inc. (C) 2001
 *
 *******************************************************************************/

 /*******************************************************************************
 * Filename:
 * ---------
 *   l4.sap
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   l4 related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 ****************************************************************************/

/********************************************************************************
*  Copyright Statement:
*  --------------------
*
*  This product has been developed using a protocol stack
*  developed by Sasken Communication Technologies Limited.
*
********************************************************************************/
#include "module_msg_range.h"

#ifndef _L4_MSGID_H
#define _L4_MSGID_H


/*---------------L4_MSG_CODE_BEGIN---------------------------*/
    /*--------------- L4C_INTERNAL_CODE_BEGIN------------------------*/
    /* for msg from L4 task to L4C */
MODULE_MSG_BEGIN( MSG_ID_L4C_INTERNAL_CODE_BEGIN )
    MSG_TAG_L4C_FIRST_CNF_MSG = MSG_ID_L4C_INTERNAL_CODE_BEGIN,
    #define L4C_REQ(MSG, HDLR)
    #define L4C_CNF(MSG, HDLR)  MSG,
    #define L4C_IND(MSG, HDLR)
        #include "l4c_msg_hdlr_defs.h"
    #undef L4C_REQ
    #undef L4C_CNF
    #undef L4C_IND
    MSG_TAG_L4C_LAST_CNF_MSG,

    MSG_TAG_L4C_FIRST_IND_MSG,
    #define L4C_REQ(MSG, HDLR)
    #define L4C_CNF(MSG, HDLR)
    #define L4C_IND(MSG, HDLR)  MSG,
        #include "l4c_msg_hdlr_defs.h"
    #undef L4C_REQ
    #undef L4C_CNF
    #undef L4C_IND
    MSG_TAG_L4C_LAST_IND_MSG,

    MSG_TAG_L4C_FIRST_REQ_MSG,
    #define L4C_REQ(MSG, HDLR)  MSG,
    #define L4C_CNF(MSG, HDLR)
    #define L4C_IND(MSG, HDLR)
        #include "l4c_msg_hdlr_defs.h"
    #undef L4C_REQ
    #undef L4C_CNF
    #undef L4C_IND
    MSG_TAG_L4C_LAST_REQ_MSG,

    MSG_ID_L4C_CODE_END = MSG_TAG_L4C_LAST_REQ_MSG,
MODULE_MSG_END( MSG_ID_L4C_INTERNAL_CODE_TAIL )
    /*--------------- L4C_INTERNAL_CODE_END--------------------------*/
    
    /*--------------- L4C_EXTERNAL_CODE_BEGIN------------------------*/
    /* for msg from non-L4 task to L4C */
MODULE_MSG_BEGIN( MSG_ID_L4C_EXTERNAL_CODE_BEGIN )

    // IMC -> L4C
    MSG_ID_L4C_IMC_MSG_BEGIN = MSG_ID_L4C_EXTERNAL_CODE_BEGIN,
        MSG_ID_L4C_IMC_ECBM_START_RSP,
        MSG_ID_L4C_IMC_ECBM_END_RSP,
        MSG_ID_L4C_IMC_CS_SERVICE_NOTIFICATION_RSP,
    MSG_ID_L4C_IMC_MSG_END,

    // ATP -> L4C
    MSG_ID_ATP_L4C_CSFB_PAGE_REQ,
    
MODULE_MSG_END( MSG_ID_L4C_EXTERNAL_CODE_TAIL ) 
    /*--------------- L4C_EXTERNAL_CODE_END--------------------------*/

    /*-----------------L4BPDN_CODE_BEGIN-----------------------*/
MODULE_MSG_BEGIN( MSG_ID_L4BPDN_CODE_BEGIN )

    MSG_ID_DDM_L4BPDN_MSG_BEGIN, 
        MSG_ID_DDM_L4BPDN_MSG_FROM_DDM_BEGIN,
            MSG_ID_DDM_L4BPDN_CGDCONT_REQ,
            MSG_ID_DDM_L4BPDN_CGDSCONT_REQ,
            MSG_ID_DDM_L4BPDN_CGTFT_REQ,
            MSG_ID_DDM_L4BPDN_CGQREQ_REQ,
            MSG_ID_DDM_L4BPDN_CGQMIN_REQ,
            MSG_ID_DDM_L4BPDN_CGEQREQ_REQ,
            MSG_ID_DDM_L4BPDN_CGEQMIN_REQ,
            MSG_ID_DDM_L4BPDN_CGEQNEG_REQ,
            MSG_ID_DDM_L4BPDN_CGACT_REQ,
            MSG_ID_DDM_L4BPDN_CGCMOD_REQ,
            MSG_ID_DDM_L4BPDN_CGPADDR_REQ,
            MSG_ID_DDM_L4BPDN_CGAUTO_REQ,
            MSG_ID_DDM_L4BPDN_CGANS_REQ,
            MSG_ID_DDM_L4BPDN_CGEREP_REQ,
            MSG_ID_DDM_L4BPDN_CGCONTRDP_REQ,
            MSG_ID_DDM_L4BPDN_CGSCONTRDP_REQ,
            MSG_ID_DDM_L4BPDN_CGTFTRDP_REQ,
            MSG_ID_DDM_L4BPDN_CGEQOS_REQ,
            MSG_ID_DDM_L4BPDN_CGEQOSRDP_REQ,
            MSG_ID_DDM_L4BPDN_CGDEL_REQ,
            MSG_ID_DDM_L4BPDN_CGAUTH_REQ,
            MSG_ID_DDM_L4BPDN_ECNCFG_REQ,
            MSG_ID_DDM_L4BPDN_EGDCONT_REQ,
            MSG_ID_DDM_L4BPDN_VZWAPNETMR_REQ,
            MSG_ID_DDM_L4BPDN_VZWAPNE_REQ,
            MSG_ID_DDM_L4BPDN_EGPAU_REQ,
            MSG_ID_DDM_L4BPDN_EGACT_REQ,
            MSG_ID_DDM_L4BPDN_CGSDATA_REQ,            
            MSG_ID_DDM_L4BPDN_ACTTEST_REQ,
            MSG_ID_DDM_L4BPDN_PSBEARER_REQ,
            MSG_ID_DDM_L4BPDN_EGFB_REQ,
            MSG_ID_DDM_L4BPDN_EGDELPF_REQ,
            MSG_ID_DDM_L4BPDN_EGLNKPF_REQ,
            MSG_ID_DDM_L4BPDN_EGPCORDP_REQ,
            MSG_ID_DDM_L4BPDN_EGPCO_REQ,
            MSG_ID_DDM_L4BPDN_CGDATA_REQ,
            MSG_ID_DDM_L4BPDN_EGLD_REQ,
            MSG_ID_DDM_L4BPDN_EDALLOW_REQ, 
            MSG_ID_DDM_L4BPDN_LTE_ATTACH_PDN_DEFINE_NEEDED_RSP,
            MSG_ID_DDM_L4BPDN_SET_EIMSROAM_CONFIG_VALUE_REQ,
            MSG_ID_DDM_L4BPDN_CMD_NOT_YET_SUPPORT_REQ, /* Only for UT */
            MSG_ID_DDM_L4BPDN_EAPNSYNC_REQ,
            MSG_ID_DDM_L4BPDN_EVZWAPFCIA_REQ,
            MSG_ID_DDM_L4BPDN_EGGRNTRSPT_REQ,
            MSG_ID_DDM_L4BPDN_EGPCAP_REQ,
            MSG_ID_DDM_L4BPDN_PS_SERVICE_TYPE_REQ,
            MSG_ID_DDM_L4BPDN_SET_DEFAULT_SIM_IND,
        MSG_ID_DDM_L4BPDN_MSG_FROM_DDM_END,

        MSG_ID_DDM_L4BPDN_MSG_FROM_L4BPDN_BEGIN,
            MSG_ID_DDM_L4BPDN_CMD_CNF,
            MSG_ID_DDM_L4BPDN_CGEV_IND,
            MSG_ID_DDM_L4BPDN_CGDCONT_IND,
            MSG_ID_DDM_L4BPDN_CGDSCONT_IND,
            MSG_ID_DDM_L4BPDN_CGTFT_IND,
            MSG_ID_DDM_L4BPDN_CGQREQ_IND,
            MSG_ID_DDM_L4BPDN_CGQMIN_IND,
            MSG_ID_DDM_L4BPDN_CGEQREQ_IND,
            MSG_ID_DDM_L4BPDN_CGEQMIN_IND,
            MSG_ID_DDM_L4BPDN_CGEQNEG_IND,
            MSG_ID_DDM_L4BPDN_CGACT_IND,
            MSG_ID_DDM_L4BPDN_CGPADDR_IND,
            MSG_ID_DDM_L4BPDN_CGAUTO_IND,
            MSG_ID_DDM_L4BPDN_CGEREP_IND,
            MSG_ID_DDM_L4BPDN_CGCONTRDP_IND,
            MSG_ID_DDM_L4BPDN_CGSCONTRDP_IND,
            MSG_ID_DDM_L4BPDN_CGTFTRDP_IND,
            MSG_ID_DDM_L4BPDN_CGEQOS_IND,
            MSG_ID_DDM_L4BPDN_CGEQOSRDP_IND,
            MSG_ID_DDM_L4BPDN_CGDEL_IND,
            MSG_ID_DDM_L4BPDN_CGAUTH_IND,
            MSG_ID_DDM_L4BPDN_PSBEARER_IND,
            MSG_ID_DDM_L4BPDN_EGFB_IND,
            MSG_ID_DDM_L4BPDN_EGDELPF_IND,
            MSG_ID_DDM_L4BPDN_EGLNKPF_IND,
            MSG_ID_DDM_L4BPDN_EGPCORDP_IND,
            MSG_ID_DDM_L4BPDN_EGPCO_IND,
            MSG_ID_DDM_L4BPDN_CGDATA_CNF,
            MSG_ID_DDM_L4BPDN_EGLD_CNF,
            MSG_ID_DDM_L4BPDN_EGEV_IND,
            MSG_ID_DDM_L4BPDN_LTE_ATTACH_NEEDED_IND,
            MSG_ID_DDM_L4BPDN_LTE_ATTACH_PDN_DEFINE_NEEDED_IND,
            MSG_ID_DDM_L4BPDN_LTE_ATTACH_PDN_ACTIVATE_SUCCESS_IND,
            MSG_ID_DDM_L4BPDN_LTE_ATTACH_PDN_ACTIVATE_FAILURE_IND,
            MSG_ID_DDM_L4BPDN_VZWAPNE_IND,
            MSG_ID_DDM_L4BPDN_VZWAPNETMR_IND,
            MSG_ID_DDM_L4BPDN_PDN_MODIFY_IND,
            MSG_ID_DDM_L4BPDN_EAPNSYNC_IND,
            MSG_ID_DDM_L4BPDN_EVZWAPFCIA_IND,
            MSG_ID_DDM_L4BPDN_EGGRNTRSPT_IND,
            MSG_ID_DDM_L4BPDN_EGPCAP_TEST_MODE_IND,
            MSG_ID_DDM_L4BPDN_BACKOFF_TIMER_STATUS_IND,
        MSG_ID_DDM_L4BPDN_MSG_FROM_L4BPDN_END,
    MSG_ID_DDM_L4BPDN_MSG_END, 

    MSG_ID_DDM_L4BNW_MSG_BEGIN,
        MSG_ID_DDM_L4BNW_ATTACHED_RAT_IND,
        MSG_ID_DDM_L4BNW_RESTART_CLEAR_CODE_33_PROC_IND,
        MSG_ID_DDM_L4BNW_PS_TYPE_CONFIG_REQ,
        MSG_ID_DDM_L4BNW_PS_TYPE_CONFIG_CNF,
        MSG_ID_DDM_L4BNW_PS_REATTACH_CONFIG_REQ,
    MSG_ID_DDM_L4BNW_MSG_END,

    MSG_ID_DDM_EVAL_MSG_BEGIN,
        MSG_ID_DDM_EVAL_PS_SERVICE_NOTIFY_REQ,
    MSG_ID_DDM_EVAL_MSG_END,

    MSG_ID_WO_L4BNW_MSG_BEGIN,
        MSG_ID_WO_L4BNW_ATTACHED_RAT_IND,
    MSG_ID_WO_L4BNW_MSG_END,    

    MSG_ID_IMSM_L4BNW_MSG_BEGIN,
        MSG_ID_IMSM_L4BNW_ATTACHED_RAT_IND,
    MSG_ID_IMSM_L4BNW_MSG_END,

    MSG_ID_IWLAN_L4BNW_MSG_BEGIN,
        MSG_ID_IWLAN_L4BNW_ATTACHED_RAT_IND,
    MSG_ID_IWLAN_L4BNW_MSG_END,

    MSG_ID_L4BPDN_L4B_MSG_BEGIN,
        MSG_ID_L4BPDN_L4BNW_ATTACHED_RAT_IND,
    MSG_ID_L4BPDN_L4B_MSG_END,

    MSG_ID_L4BNW_L4C_MSG_BEGIN,
        MSG_ID_L4BNW_L4C_ACTIVE_RAT_IND,
        MSG_ID_L4BNW_L4C_SUSPEND_EGREG_UPDATE_IND,
        MSG_ID_L4BNW_L4C_RESTART_CLEAR_CODE_33_PROC_IND,
        MSG_ID_L4BNW_L4C_SIM_LOCK_REQ,
        MSG_ID_L4BNW_L4C_SIM_LOCK_CNF,
        MSG_ID_L4BNW_L4C_PS_TYPE_CONFIG_CNF,
        MSG_ID_L4BNW_L4C_ILLEGAL_ME_IND,
        MSG_ID_L4BNW_L4C_REG_STATE_IND,
    MSG_ID_L4BNW_L4C_MSG_END,
    
    MSG_ID_L4BPWR_L4C_MSG_BEGIN,
        MSG_ID_L4BPWR_L4C_OP01_LOCK_CNF,
    MSG_ID_L4BPWR_L4C_MSG_END,

    MSG_ID_L4BPDN_L4C_MSG_FROM_L4BPDN_BEGIN,
    /* L4BPDN to L4C AT command Primitive */
    #define L4C_PS_REQ(MSG, HDLR1, HDLR2, HDLR3, HDLR4)  MSG,
        #include "l4c_ps_msg_hdlr_defs.h" 
    #undef  L4C_PS_REQ

    /* L4BPDN to L4C Non-AT command Primitive */
    MSG_ID_L4BPDN_L4C_PDN_REVIVE_REQ,
    MSG_ID_L4BPDN_L4C_LTE_ATTACH_PDN_DEFINE_NEEDED_RSP,
    MSG_ID_L4BPDN_L4C_SET_EIMSROAM_CONFIG_VALUE_REQ,
    MSG_ID_L4BPDN_L4C_SET_DEFAULT_SIM_IND,

    MSG_ID_L4BPDN_L4C_MSG_FROM_L4BPDN_END,
     
    MSG_ID_L4BPDN_L4C_MSG_FROM_L4C_BEGIN,
        MSG_ID_L4BPDN_L4C_CMD_CNF,
        MSG_ID_L4BPDN_L4C_CGEV_IND,
        MSG_ID_L4BPDN_L4C_CGDCONT_IND,
        MSG_ID_L4BPDN_L4C_CGDSCONT_IND,
        MSG_ID_L4BPDN_L4C_CGTFT_IND,
        MSG_ID_L4BPDN_L4C_CGQREQ_IND,
        MSG_ID_L4BPDN_L4C_CGQMIN_IND,
        MSG_ID_L4BPDN_L4C_CGEQREQ_IND,
        MSG_ID_L4BPDN_L4C_CGEQMIN_IND,
        MSG_ID_L4BPDN_L4C_CGEQNEG_IND,
        MSG_ID_L4BPDN_L4C_CGACT_IND,
        MSG_ID_L4BPDN_L4C_CGPADDR_IND,
        MSG_ID_L4BPDN_L4C_CGAUTO_IND,
        MSG_ID_L4BPDN_L4C_CGEREP_IND,
        MSG_ID_L4BPDN_L4C_CGCONTRDP_IND,
        MSG_ID_L4BPDN_L4C_CGSCONTRDP_IND,
        MSG_ID_L4BPDN_L4C_CGTFTRDP_IND,
        MSG_ID_L4BPDN_L4C_CGEQOS_IND,
        MSG_ID_L4BPDN_L4C_CGEQOSRDP_IND,
        MSG_ID_L4BPDN_L4C_CGDEL_IND,
        MSG_ID_L4BPDN_L4C_CGAUTH_IND,
        MSG_ID_L4BPDN_L4C_PSBEARER_IND,
        MSG_ID_L4BPDN_L4C_EGFB_IND,
        MSG_ID_L4BPDN_L4C_EGDELPF_IND,
        MSG_ID_L4BPDN_L4C_EGLNKPF_IND,
        MSG_ID_L4BPDN_L4C_EGPCORDP_IND,
        MSG_ID_L4BPDN_L4C_EGPCO_IND,
        MSG_ID_L4BPDN_L4C_RAT_SELECT_IND,
        MSG_ID_L4BPDN_L4C_GMSS_STOP_SEARCH_IND,
        MSG_ID_L4BPDN_L4C_PDN_REVIVE_CNF, 
        MSG_ID_L4BPDN_L4C_PDN_REVIVE_ABORT_CNF,
        MSG_ID_L4BPDN_L4C_LTE_ATTACH_NEEDED_IND,
        MSG_ID_L4BPDN_L4C_LTE_ATTACH_PDN_DEFINE_NEEDED_IND,
        MSG_ID_L4BPDN_L4C_VZWAPNE_IND,
        MSG_ID_L4BPDN_L4C_VZWAPNETMR_IND,
        MSG_ID_L4BPDN_L4C_LTE_ATTACH_PDN_ACTIVATE_SUCCESS_IND,
        MSG_ID_L4BPDN_L4C_LTE_ATTACH_PDN_ACTIVATE_FAILURE_IND,
        MSG_ID_L4BPDN_L4C_EAPNSYNC_IND,
        MSG_ID_L4BPDN_L4C_EVZWAPFCIA_IND,
        MSG_ID_L4BPDN_L4C_EGGRNTRSPT_IND,        
        MSG_ID_L4BPDN_L4C_CMD_NOT_YET_SUPPORT_IND, /* Only for UT */
    MSG_ID_L4BPDN_L4C_MSG_FROM_L4C_END,

    MSG_ID_L4BPDN_TCM_MSG_BEGIN,
        MSG_ID_L4BPDN_TCM_BEARER_ACT_IND,
        MSG_ID_L4BPDN_TCM_BEARER_DEACT_IND, 
        MSG_ID_L4BPDN_TCM_PF_UPDATE_IND,
        MSG_ID_L4BPDN_TCM_PCO_RDP_UPDATE_IND,
    MSG_ID_L4BPDN_TCM_MSG_END,

    /* Note: MSG_ID with MD3 are listed in md3_msgid.h */

    /* For logging */
    MSG_ID_L4BPDN_LOG_CID, 
    MSG_ID_L4BPDN_LOG_LEISIM, 

#ifdef __SMB_SIMME_LOCK__
        MSG_ID_L4BPWR_L4C_SERVICE_MODE_CNF,
        MSG_ID_L4BPWR_L4C_SERVICE_MODE_IND,
#endif /* __SMB_SIMME_LOCK__ */

    MSG_ID_L4BPDN_MSG_DUMMY,
    MSG_ID_L4BPDN_CODE_END = MSG_ID_L4BPDN_MSG_DUMMY,
    /*-----------------L4BPDN_CODE_TAIL-------------------------*/
MODULE_MSG_END( MSG_ID_L4BPDN_CODE_TAIL )
    
	/*-----------------RAT_TCM_CODE_BEGIN-----------------------*/
MODULE_MSG_BEGIN( MSG_ID_RAT_TCM_CODE_BEGIN )
       MSG_ID_L4CTCM_RAT_CHANGE_START_REQ = MSG_ID_RAT_TCM_CODE_BEGIN,
       MSG_ID_L4CTCM_RAT_CHANGE_FINISH_REQ,
       MSG_ID_TCM_RAT_CHANGE_COMPLETE_IND,

       MSG_ID_TCM_RAT_TCM_INIT_DEACTIVATE_CONTEXT_IND,
       MSG_ID_RAT_TCM_PRINT_EMBEDDED_SEC_ACTIVATE_IND_MSG,
       MSG_ID_RAT_TCM_PRINT_EMBEDDED_DEACTIVATE_IND_MSG,
       MSG_ID_RAT_TCM_PRINT_EMBEDDED_MODIFY_IND_MSG,
       MSG_ID_RAT_TCM_CODE_END,
	/*-----------------RAT_TCM_CODE_TAIL-------------------------*/
MODULE_MSG_END( MSG_ID_RAT_TCM_CODE_TAIL )

    /*--------------- TCM_MSG_CODE_BEGIN------------------------*/
MODULE_MSG_BEGIN( MSG_ID_TCM_CODE_BEGIN )

    /* Processed by tcm_at_handler.c. */
    MSG_ID_TCM_AT_MSG_BEGIN, 
        /* Bootup. */
        MSG_ID_L4CTCM_START_REQ,
        MSG_ID_TCM_PAM_START_CNF, 
        /* Set items for PDP and QOS. */
        MSG_ID_L4CTCM_UNDEFINE_PDP_INFO_REQ,
        MSG_ID_L4CTCM_SET_PRI_PDP_INFO_REQ,
        MSG_ID_L4CTCM_SET_SEC_PDP_INFO_REQ,
        MSG_ID_L4CTCM_SET_QOS_INFO_REQ,
        MSG_ID_L4CTCM_SET_EQOS_INFO_REQ,
        MSG_ID_L4CTCM_SET_EPS_QOS_INFO_REQ, /* __LTE_RAT__ */
        /* Set items for others. */
        MSG_ID_L4CTCM_SET_TFT_INFO_REQ,
        MSG_ID_L4CTCM_SET_PPP_AUTH_INFO_REQ,
        MSG_ID_L4CTCM_SET_CGAUTH_INFO_REQ,
        MSG_ID_L4CTCM_ENTER_DATA_MODE_REQ,
        MSG_ID_L4CTCM_LEAVE_DATA_MODE_REQ,
        MSG_ID_L4CTCM_SET_MULTIPLE_PDN_INFO_REQ,
        MSG_ID_L4CTCM_SET_SPECIFIC_CONTEXT_REQ,
        MSG_ID_L4CTCM_SET_EXTENDED_PDP_INFO_REQ,
        MSG_ID_L4CTCM_SYNC_APN_INFO_REQ,
        MSG_ID_L4CTCM_CELLULAR_NETWORK_CONFIG_REQ,
        MSG_ID_L4CTCM_SET_THIS_IS_AN_INVALID_APN_NOTIFY_REQ,
        MSG_ID_L4CTCM_SET_EGPCO_REQ,

        /* __MEDIATEK_SMART_QOS__ */
        MSG_ID_L4CTCM_SET_MSQ_MODE_REQ,     
        MSG_ID_L4CTCM_SET_MSQ_ENTRY_REQ,
        MSG_ID_L4CTCM_DATA_ALLOW_REQ,
        MSG_ID_L4CTCM_SET_EIMSROAM_CONFIG_VALUE_REQ,
    MSG_ID_TCM_AT_MSG_END, 

    /* Processed by BOTH UGTCM and ETCM */
    MSG_ID_TCM_COMMON_FSM_MSG_BEGIN,
        /* From L4C. */
        MSG_ID_TCM_PDP_ACTIVATE_REQ, 
        MSG_ID_TCM_PDP_DEACTIVATE_REQ,
        MSG_ID_TCM_PDP_MODIFY_REQ,
        /* From PPP. */
        MSG_ID_TAF_EXT_PDP_ACTIVATE_IND,
        MSG_ID_TAF_EXT_PDP_DEACTIVATE_IND,
        MSG_ID_TAF_LINK_FREE_IND,   
    MSG_ID_TCM_COMMON_FSM_MSG_END,
    
    /* For PAM message handled by COMMON TCM */
    MSG_ID_TCM_FROM_PAM_MSG_BEGIN,
        /* PAM -> TCM */    
        MSG_ID_TCM_USM_CONTEXT_UPDATE_IND,
        MSG_ID_PAM_BACKOFF_TIMER_REPORT_IND,
    MSG_ID_TCM_FROM_PAM_MSG_END,
        
    /* Processed by UGTCM. */
    MSG_ID_TCM_UGTCM_MSG_BEGIN,
        /* ACT. */
        MSG_ID_SMREG_PDP_ACTIVATE_CNF,
        MSG_ID_SMREG_PDP_ACTIVATE_REJ,
        MSG_ID_SMREG_PDP_ACTIVATE_SEC_CNF,
        MSG_ID_SMREG_PDP_ACTIVATE_SEC_REJ,
        /* MT ACT. */
        MSG_ID_SMREG_PDP_ACTIVATE_IND,
        MSG_ID_SMREG_PDP_ACTIVATE_SEC_IND,
        MSG_ID_TCM_PDP_ACTIVATE_REJ_RSP,
        MSG_ID_TCM_TIMER_EXPIRY,
        /* DEACT. */
        MSG_ID_SMREG_PDP_DEACTIVATE_IND,
        MSG_ID_SMREG_PDP_DEACTIVATE_CNF,
        /* MODIFY. */
        MSG_ID_SMREG_PDP_MODIFY_IND,
        MSG_ID_SMREG_PDP_MODIFY_CNF,
        MSG_ID_SMREG_PDP_MODIFY_REJ,
        /* __LTE_RAT__ */
        MSG_ID_SMREG_RAT_CHANGE_COMPLETE_IND,
        MSG_ID_SMREG_PS_CHANGE_COMPLETE_IND,
        /* __HSDPA_SUPPORT__ */
        MSG_ID_TCM_RATDM_PS_BEARER_CAPABILITY_IND,
        /* 3G PDP preservation. */
        MSG_ID_SMREG_PDP_PRESERVE_IND,
        MSG_ID_SMREG_PDP_REESTABLISH_IND,
        /* 2G CS suspend PS (-> MOD_PPP) */
        MSG_ID_SMREG_PS_SUSPEND_IND,
        MSG_ID_SMREG_PS_RESUME_IND,
    MSG_ID_TCM_UGTCM_MSG_END,

    MSG_ID_TCM_ETCM_MSG_BEGIN,
        /****************************************************************************
         *                          Destination: ESM to ETCM
         ****************************************************************************/
        MSG_ID_ESMREG_PDN_CONN_EST_REJ,
        MSG_ID_EVAL_ESM_PDN_CONN_EST_REJ = MSG_ID_ESMREG_PDN_CONN_EST_REJ,
        MSG_ID_ESMREG_BEARER_RSC_ALLOC_REJ,
        MSG_ID_EVAL_ESM_BEARER_RSC_ALLOC_REJ = MSG_ID_ESMREG_BEARER_RSC_ALLOC_REJ,
        MSG_ID_ESMREG_BEARER_RSC_MOD_REJ,
        MSG_ID_EVAL_ESM_BEARER_RSC_MOD_REJ = MSG_ID_ESMREG_BEARER_RSC_MOD_REJ,
        MSG_ID_ESMREG_EPSB_DEACT_REJ,
        MSG_ID_EVAL_ESM_EPSB_DEACT_REJ = MSG_ID_ESMREG_EPSB_DEACT_REJ,
        MSG_ID_ESMREG_PDN_CONN_EST_IND,
        MSG_ID_EVAL_ESM_PDN_CONN_EST_IND = MSG_ID_ESMREG_PDN_CONN_EST_IND,
        MSG_ID_ESMREG_PDN_CONN_UPDATE_IND,
        MSG_ID_EVAL_ESM_PDN_CONN_UPDATE_IND = MSG_ID_ESMREG_PDN_CONN_UPDATE_IND,
        MSG_ID_ESMREG_EPSB_DEACT_IND,
        MSG_ID_EVAL_ESM_EPSB_DEACT_IND = MSG_ID_ESMREG_EPSB_DEACT_IND,
        MSG_ID_ESMREG_RAT_CHANGE_COMPLETE_IND,
        MSG_ID_EVAL_ESM_RAT_CHANGE_COMPLETE_IND = MSG_ID_ESMREG_RAT_CHANGE_COMPLETE_IND,
        
        MSG_ID_TAF_EXT_ENTER_DATA_MODE_REQ, /* PPP Dial-up */
        MSG_ID_ETCM_EM_DUMP_PDP_CONTEXT_IND, /* ETCM EM msg */

        MSG_ID_ESMREG_PS_INIT_BEARER_DEACT_IND,
        MSG_ID_EVAL_ESM_PS_INIT_BEARER_DEACT_IND = MSG_ID_ESMREG_PS_INIT_BEARER_DEACT_IND,

    MSG_ID_TCM_ETCM_MSG_END,

    /* PAM -> TCM */
    /*
    MSG_ID_TCM_PAM_MSG_BEGIN,        
        MSG_ID_TCM_PAM_SET_VZW_APN_TABLE_CNF,
        MSG_ID_TCM_PAM_GET_VZW_APN_TABLE_CNF,
        MSG_ID_TCM_PAM_SET_VZW_PARAMS_CNF,
        MSG_ID_TCM_PAM_GET_VZW_PARAMS_CNF,
        MSG_ID_TCM_PAM_GET_APN_BLOCKING_TIMER_LENGTH_CNF,
    MSG_ID_TCM_PAM_MSG_END, 
    */

    /* __ACL_SUPPORT__ */
    MSG_ID_TCM_ACL_MSG_BEGIN,
        MSG_ID_L4CTCM_SET_ACL_MODE_REQ,
        MSG_ID_L4CTCM_GET_ACL_ENTRIES_REQ,
        MSG_ID_L4CTCM_SET_ACL_ENTRY_REQ,
        MSG_ID_L4CTCM_ADD_ACL_ENTRY_REQ,
        MSG_ID_L4CTCM_DEL_ACL_ENTRY_REQ,
        MSG_ID_L4CTCM_LEAVE_ACL_MENU_REQ,
    MSG_ID_TCM_ACL_MSG_END, 

    /* __TCM_UT__ */
    MSG_ID_TCM_UT_MSG_BEGIN,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_PRI_PDP_INFO,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_QUERY_NEG_QOS_INFO,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_SEC_PDP_INFO,
        MSG_ID_TCM_UT_CHECK_CALLBACK_TCM_WRITE_TFT,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_SET_TFT_INFO,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_TFT_INFO,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_QOS_INFO,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_CONFIG_OPTION_INFO,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_EQOS_INFO,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_ENCODE_SDU_SIZE,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_DECODE_SDU_SIZE,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_ENCODE_BIT_RATE,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_DECODE_BIT_RATE,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_ENCODE_TRANSFER_DELAY,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_DECODE_TRANSFER_DELAY,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_PDP_ADDR,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_CONTEXT_STATE,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_EMPTY_GPRS_PROF,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_PPP_AUTH,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_CMUX_PORT_TO_CID,
        MSG_ID_TCM_UT_CHECK_CALLBACK_L4CTCM_GET_BEARER_CAPABILITY,
        MSG_ID_TCM_UT_CHECK_CALLBACK_CHECK_PDP_CONTEXT_EXIST_OR_DURING_ACTIVATING_FUNC,
        MSG_ID_TCM_UT_RESULT_OK,
        MSG_ID_TCM_UT_L4CTCM_GET_PRI_PDP_RDP_INFO,
        MSG_ID_TCM_UT_L4CTCM_GET_SEC_PDP_RDP_INFO,
        MSG_ID_TCM_UT_L4CTCM_GET_PRI_PDP_INFO,
        MSG_ID_TCM_UT_L4CTCM_GET_SEC_PDP_INFO,      
        MSG_ID_TCM_UT_L4CTCM_GET_NW_APPLIED_PDP_INFO,
        MSG_ID_TCM_UT_L4CTCM_GET_SIB_INFO,
    MSG_ID_TCM_UT_MSG_END,

    /* __DSBP_MSG __ */
    MSG_ID_TCM_DSBP_MSG_BEGIN,
        MSG_ID_TCM_DSBP_RECONFIGURE_IND,
    MSG_ID_TCM_DSBP_MSG_END,

    /* Obsoleted. */    
    /* Max Yin 2010-05-17: new call log interface */
    MSG_ID_L4C_PS_QUERY_EXT_PDP_STATISTICS_REQ,
    MSG_ID_L4C_PS_QUERY_EXT_PDP_STATISTICS_RSP,
    MSG_ID_L4C_PS_RESET_EXT_PDP_STATISTICS_REQ,
    MSG_ID_L4C_PS_RESET_EXT_PDP_STATISTICS_RSP,
    MSG_ID_L4C_PS_EXT_PDP_STATISTICS_IND,
    MSG_ID_L4C_RATDM_PACKETS_FLUSH_IND,

    /*  RAT_TCM -> TCM on  GRT expiry   */
    MSG_ID_TCM_PDP_DEACTIVATE_NTF, 
MODULE_MSG_END( MSG_ID_TCM_CODE_TAIL )          
    /*--------------- TCM_MSG_CODE_END--------------------------*/

	/*-----------------CSM_MSG_CODE_BEGIN-----------------------*/
	MODULE_MSG_BEGIN( MSG_ID_CSM_CODE_BEGIN )
	MSG_ID_MNCC_SETUP_IND = MSG_ID_CSM_CODE_BEGIN,
	MSG_ID_MNCC_SETUP_CNF,
	MSG_ID_MNCC_SETUP_COMPL_IND,
	MSG_ID_MNCC_REJ_IND,
	MSG_ID_MNCC_CALL_PROC_IND,
	MSG_ID_MNCC_PROGRESS_IND,
	MSG_ID_MNCC_ALERT_IND,
	MSG_ID_MNCC_NOTIFY_IND,
	MSG_ID_MNCC_DISC_IND,
	MSG_ID_MNCC_REL_IND,
	MSG_ID_MNCC_REL_CNF,
	MSG_ID_MNCC_FACILITY_IND,
	MSG_ID_MNCC_START_DTMF_CNF,
	MSG_ID_MNCC_STOP_DTMF_CNF,
	MSG_ID_MNCC_MODIFY_IND,
	MSG_ID_MNCC_MODIFY_CNF,
	MSG_ID_MNCC_SYNC_IND,
	MSG_ID_MNCC_RAT_IND,	
	MSG_ID_MNCC_HOLD_CNF,
	MSG_ID_MNCC_RETRIEVE_CNF,
	MSG_ID_MNCC_USER_INFO_IND,
	MSG_ID_MNCC_CONGESTION_CTRL_IND,
	MSG_ID_MNCC_CCBS_EST_IND,
	MSG_ID_MNCC_CCBS_RECALL_IND,
	MSG_ID_MNCC_AOC_IND,
	MSG_ID_MNCC_SIG_CON_REEST_IND,
	MSG_ID_MNCC_SIG_CON_REEST_CNF,
	MSG_ID_MNCC_SRVCC_TRANSFER_CNF,
	MSG_ID_MNCC_STOP_CALL_RETRY_IND,
	MSG_ID_MNCC_NO_CC_DATA_DETECT_IND,

   	MSG_ID_L4CCSM_CC_STARTUP_REQ,
   	MSG_ID_L4CCSM_CC_ACM_RESET_REQ,
	MSG_ID_L4CCSM_CC_ACMMAX_SET_REQ,
	MSG_ID_L4CCSM_CC_LAST_CCM_RESET_REQ,
	MSG_ID_L4CCSM_CC_CALL_DEFLECTION_REQ,
	MSG_ID_L4CCSM_CC_CRSS_REQ,
	MSG_ID_L4CCSM_CC_CALL_ACCEPT_REQ,
	MSG_ID_L4CCSM_CC_CALL_DISC_REQ,
	MSG_ID_L4CCSM_CC_CALL_MODIFY_REQ,
	MSG_ID_L4CCSM_CC_CALL_SETUP_REQ,
	MSG_ID_L4CCSM_CC_AUTO_DTMF_START_REQ,
	MSG_ID_L4CCSM_CC_EMERGENCY_CALL_SETUP_REQ,
	MSG_ID_L4CCSM_CC_START_DTMF_REQ,
	MSG_ID_L4CCSM_CC_STOP_DTMF_REQ,
	MSG_ID_L4CCSM_CC_SAT_SETUP_REQ,
	MSG_ID_L4CCSM_CC_SAT_SEND_DTMF_REQ,
	MSG_ID_L4CCSM_CC_SAT_ABORT_DTMF_REQ,
	MSG_ID_L4CCSM_CC_SET_CSD_PROF_REQ,
	MSG_ID_L4CCSM_CC_UPDATE_ALS_REQ,
	MSG_ID_L4CCSM_CC_UART_TRANSFER_REQ,
	MSG_ID_L4CCSM_CC_CALL_PRESENT_RSP, /* __AUTO_CALL_REJECTION__ */
	MSG_ID_L4CCSM_CC_ABORT_CALL_REQ,
	MSG_ID_L4CCSM_CC_REL_COMP_REQ,
	MSG_ID_L4CCSM_CC_SRVCC_TRANSFER_REQ,
	MSG_ID_L4CCSM_CC_NO_CC_DATA_DETECT_IND,

	MSG_ID_SAT_CALL_CTRL_BY_SIM_CNF,

	MSG_ID_CSM_TDT_ACTIVATE_CNF,
	MSG_ID_CSM_TDT_DEACTIVATE_CNF,
	MSG_ID_CSM_TDT_ESC_ON_IND,
	MSG_ID_CSM_TDT_DISC_IND,
	MSG_ID_CSM_L2R_ACTIVATE_CNF,
	MSG_ID_CSM_L2R_DEACTIVATE_CNF,
	MSG_ID_CSM_L2R_XID_IND,
	MSG_ID_CSM_L2R_DISC_IND,
	MSG_ID_CSM_L2R_ESC_ON_IND,

   MSG_ID_CSM_T30_ACTIVATE_CNF,
   MSG_ID_CSM_T30_DEACTIVATE_CNF,
   MSG_ID_CSM_T30_FAX_RATE_CNF,
   MSG_ID_CSM_T30_DISC_IND,

   MSG_ID_L4CCSM_CISS_STARTUP_REQ,
   MSG_ID_L4CCSM_CISS_SS_PARSE_REQ,
   MSG_ID_L4CCSM_CISS_CF_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CW_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CB_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_EMLPP_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CLI_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CCBS_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_PUSSR_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CB_FAC_RES,
   MSG_ID_L4CCSM_CISS_USSR_FAC_RES,
   MSG_ID_L4CCSM_CISS_USSN_FAC_RES,
   MSG_ID_L4CCSM_CISS_END_RES,
   MSG_ID_MNSS_BEGIN_IND,
   MSG_ID_MNSS_FAC_IND,
   MSG_ID_MNSS_END_IND,
   MSG_ID_SAT_SS_CTRL_BY_SIM_CNF,
//SSAGPS
    MSG_ID_L4CCSM_CISS_MTLR_END_RSP,
    MSG_ID_L4CCSM_CISS_AERQ_END_RSP,
    MSG_ID_L4CCSM_CISS_AERP_REQ,
    MSG_ID_L4CCSM_CISS_AERP_FAC_RES,
    MSG_ID_L4CCSM_CISS_AERP_END_REQ,
    MSG_ID_L4CCSM_CISS_AECL_END_RSP,
    MSG_ID_L4CCSM_CISS_MOLR_REQ,
    MSG_ID_L4CCSM_CISS_MOLR_FAC_RES,
    MSG_ID_L4CCSM_CISS_MOLR_END_REQ,


    MSG_ID_L4CCSM_IMS_CALL_PROGRESS_REQ,
    MSG_ID_L4CCSM_IMS_CALL_STATUS_IND,

   MSG_ID_CSM_TIMER_EXPIRY,
   MSG_ID_CSM_CODE_END,
	/*-----------------CSM_MSG_CODE_END-------------------------*/
	MODULE_MSG_END( MSG_ID_CSM_CODE_TAIL )

	/*--------------- SMSAL_MSG_CODE_BEGIN----------------------*/
	MODULE_MSG_BEGIN( MSG_ID_SMSAL_CODE_BEGIN )
	MSG_ID_L4CSMSAL_INIT_REQ = MSG_ID_SMSAL_CODE_BEGIN,
	MSG_ID_L4CSMSAL_DE_INIT_REQ,
	MSG_ID_L4CSMSAL_DELETE_REQ,
	MSG_ID_L4CSMSAL_DE_PERSONALIZATION_ACK,
	MSG_ID_L4CSMSAL_READ_REQ,
	MSG_ID_L4CSMSAL_WRITE_REQ,
	MSG_ID_L4CSMSAL_SEND_REQ,
	MSG_ID_L4CSMSAL_SEND_SMMA_REQ,    // triger by MMI
	MSG_ID_L4CSMSAL_SEND_FROM_STORAGE_REQ,
	MSG_ID_L4CSMSAL_SEND_DELIVER_REPORT_REQ, 
	MSG_ID_L4CSMSAL_SEND_ABORT,
	MSG_ID_L4CSMSAL_SET_PARAMETER_REQ,
	MSG_ID_L4CSMSAL_SET_COMMON_PARA_REQ,
	MSG_ID_L4CSMSAL_SET_PROFILE_PARA_REQ,
    MSG_ID_L4CSMSAL_SAT_SEND_REQ, /* SAT MO SMS */
    MSG_ID_L4CSMSAL_STARTUP_READ_NEXT_REQ,
    MSG_ID_L4CSMSAL_FDN_CHECK_RSP,
    MSG_ID_L4CSMSAL_SMS_DEPERSONALIZATION_RSP,
    MSG_ID_L4CSMSAL_COPY_MSG_REQ,
    MSG_ID_L4CSMSAL_SET_STATUS_REQ,
    MSG_ID_L4CSMSAL_GET_MAILBOX_NUM_REQ,
	MSG_ID_L4CSMSAL_INIT_ME_SMS_REQ,       
	MSG_ID_L4CSMSAL_SET_MSG_WAITING_REQ,
    MSG_ID_L4CSMSAL_SYNC_MSG_STORAGE_REQ,
	MSG_ID_L4CSMSAL_READ_RAW_DATA_REQ,
	MSG_ID_L4CSMSAL_WRITE_RAW_DATA_REQ,

    /* __IMS_SUPPORT__ */
    MSG_ID_L4CSMSAL_IMS_SEND_REQ,
    MSG_ID_L4CSMSAL_IMS_SEND_SMMA_REQ,
    MSG_ID_L4CSMSAL_IMS_SEND_SMMA_RESULT_REQ,
    MSG_ID_L4CSMSAL_IMS_SMS_DELIVER_REQ,
    MSG_ID_L4CSMSAL_IMS_SMS_STATUS_REQ,
	MSG_ID_L4CSMSAL_IMS_SEND_FROM_STORAGE_REQ,
    MSG_ID_L4CSMSAL_IMS_UPDATE_MSGBOX_REQ,

	/* MSGS FROM SMS */
	MSG_ID_SMS_DELIVER,
	MSG_ID_SMS_SUBMIT_REPORT_ACK,
	MSG_ID_SMS_SUBMIT_REPORT_NACK,
	MSG_ID_SMS_STATUS_REPORT,
	MSG_ID_SMS_SUBMIT_ABORT_CNF,
	MSG_ID_SMS_MEM_AVL_NOTIF_CNF,
	MSG_ID_SMS_MORE_MSG_SEND_IND,
    MSG_ID_SMS_MT_FINAL_ACK_IND,
	MSG_ID_SMSAL_TST_DELIVER,
	MSG_ID_SMSAL_TST_IMS_DELIVER,

	/* MSGS FROM SIM -- for SAT */
	MSG_ID_SAT_SMS_DL_CNF,
	MSG_ID_SAT_CB_DL_CNF,
    MSG_ID_SAT_SEND_SMS_CTRL_BY_SIM_CNF,

	MSG_ID_L4CSMSAL_CBCH_REQ,
	MSG_ID_L4CSMSAL_CB_UPDATE_REQ,
    MSG_ID_L4CSMSAL_HZ_CB_ACT_REQ,
    MSG_ID_L4CSMSAL_CB_SERVICE_BY_PLMN_REQ,
        
    MSG_ID_SMSAL_AS_CB_PAGE_IND,
    MSG_ID_SMSAL_AS_CB_GS_CHANGE_IND,

    MSG_ID_SMSAL_RATCM_CB_DATA_IND,
    MSG_ID_SMSAL_RATCM_CB_RECONFIG_IND,
    MSG_ID_SMSAL_RATCM_CB_GS_CHANGE_IND,
    
    /* MSGS FROM L4C -- for interRAT*/
    MSG_ID_L4CSMSAL_RAT_CHANGE_START_REQ,
    MSG_ID_L4CSMSAL_RAT_CHANGE_FINISH_REQ,

    /*MSGS FROM EVAL -- for SMSAL*/
    MSG_ID_SMSAL_EVAL_CB_DATA_IND,
    MSG_ID_SMSAL_EVAL_CB_RECONFIG_IND,
    MSG_ID_SMSAL_EVAL_CB_GS_CHANGE_IND,


    /* MSGS FROM PHB */
    MSG_ID_PHBSMSAL_GET_EXT1_NUM_REQ,
    MSG_ID_PHBSMSAL_GET_EXT1_NUM_CNF,
        
	/* MSGS FROM SOC */
	MSG_ID_SMSAL_SOC_REG_PORT_REQ,

    MSG_ID_SMSAL_TR2_EXPIRE_IND,
 //   MSG_ID_L4CSMSAL_UPDATE_SMS_OVER_SGS_CFG_REQ,

    MSG_ID_L4CSMSAL_CB_MSG_REMOVAL_REQ,
    MSG_ID_L4CSMSAL_UPDATE_SMS_OVER_SGS_CFG_REQ,
    MSG_ID_L4CSMSAL_CONFIG_CB_FOR_DUPLEX_MODE_REQ,
    MSG_ID_SMSAL_CODE_END,
	/*------------------ SMSAL_MSG_CODE_END --------------------*/
MODULE_MSG_END( MSG_ID_SMSAL_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_SMU_CODE_BEGIN )
    /*------------------------SMU_MSG_CODE_BEGIN ---------------*/
    MSG_ID_L4CSMU_START_REQ = MSG_ID_SMU_CODE_BEGIN,	
    MSG_ID_L4CSMU_APP_START_REQ,
    MSG_ID_L4CSMU_SECURITY_REQ,
    MSG_ID_L4CSMU_APP_SECURITY_REQ,
    MSG_ID_L4CSMU_SET_PERSONALIZATION_REQ, /* SML */
    MSG_ID_L4CSMU_GET_SHARED_KEY_REQ,
    MSG_ID_L4CSMU_UPDATE_SLB_REQ,
    MSG_ID_L4CSMU_RESET_SLB_REQ,
    MSG_ID_L4CSMU_GET_SLB_VERSION_REQ,
    MSG_ID_L4CSMU_GET_SIM_LOCK_STATUS_REQ,
    MSG_ID_L4CSMU_UPDATE_NW_TIME_REQ,
    MSG_ID_L4CSMU_SML_STATUS_REQ, /* SML */
    MSG_ID_L4CSMU_PLMN_SEL_WRITE_REQ,
    MSG_ID_L4CSMU_SIM_ACCESS_REQ,
    MSG_ID_L4CSMU_PUCT_WRITE_REQ,
    MSG_ID_L4CSMU_PUCT_READ_REQ,
    MSG_ID_L4CSMU_CSP_READ_REQ,
    MSG_ID_L4CSMU_SMS_DEPERSONALIZATION_REQ,
    MSG_ID_L4CSMU_DIAL_MODE_REQ,
    MSG_ID_L4CSMU_SAT_OPEN_CHANNEL_REQ,
    MSG_ID_L4CSMU_SAT_SEND_DATA_REQ,
    MSG_ID_L4CSMU_SAT_RECV_DATA_REQ,
    MSG_ID_L4CSMU_SAT_BEARER_PARA_REQ, // update csd or gprs bearer parameter for SIM
    MSG_ID_L4CSMU_SAT_SET_CSD_PROF_RES,
    MSG_ID_L4CSMU_SAT_SET_GPRS_PROF_RES,
    MSG_ID_UIM_SIM_PIN_SYNC_IND,
    MSG_ID_SMU_DUMP_SML_CONTEXT_IND,
#if defined(__SUBSIDY_LOCK__) || defined(__SMB_SIMME_LOCK__)
	MSG_ID_L4CSMU_SL_UPDATE_BLOB_REQ,
	MSG_ID_L4CSMU_SL_UPDATE_BLOB_CNF,
	MSG_ID_L4CSMU_SL_GET_SIM_LOCK_STATUS_REQ,
	MSG_ID_L4CSMU_SL_GET_SIM_LOCK_STATUS_CNF,
#endif
    MSG_ID_L4CSMU_UT_SET_NONCE_REQ,
    MSG_ID_L4CSMU_UT_SIG_VERIFY_REQ,
#ifdef __SMB_SIMME_LOCK__
    MSG_ID_L4CSMU_UPDATE_GBLOB_LOCK_RULE_REQ,
    MSG_ID_L4CSMU_UPDATE_GBLOB_LOCK_RULE_CNF,
    MSG_ID_L4CSMU_UPDATE_GBLOB_DATA_REQ,
    MSG_ID_L4CSMU_UPDATE_GBLOB_DATA_CNF,
    MSG_ID_L4CSMU_GBLOB_DEV_LOCK_VERIFY_REQ,
    MSG_ID_L4CSMU_GBLOB_DEV_LOCK_VERIFY_CNF,
    MSG_ID_L4CSMU_UPDATE_GBLOB_DEV_LOCK_ALGO_REQ,
    MSG_ID_L4CSMU_UPDATE_GBLOB_DEV_LOCK_ALGO_CNF,
    MSG_ID_L4CSMU_UPDATE_GBLOB_IMEI_REQ,
    MSG_ID_L4CSMU_UPDATE_GBLOB_IMEI_CNF,
    MSG_ID_L4CSMU_GET_GBLOB_DEV_LOCK_STATUS_REQ,
    MSG_ID_L4CSMU_GET_GBLOB_DEV_LOCK_STATUS_CNF,
    MSG_ID_L4CSMU_SML_LOCK_STATUS_UPDATE_IND,
#endif
    MSG_ID_L4CSMU_SML_GET_LOCK_CODES_REQ,
    MSG_ID_L4CSMU_SML_GET_LOCK_CODES_CNF,
    MSG_ID_L4CSMU_SET_CUSTOM_PERSONALIZATION_REQ,
    MSG_ID_L4CSMU_SET_CUSTOM_PERSONALIZATION_CNF,
    MSG_ID_SMU_UT_DYNAMIC_SIMMELOCK_REQ,
    MSG_ID_SMU_UT_DYNAMIC_SIMMELOCK_CNF,
#ifdef __CARRIER_RESTRICTION__
    MSG_ID_L4CSMU_SET_CARRIER_RESTRICTION_REQ,
    MSG_ID_L4CSMU_CARRIER_RESTRICTION_STATUS_REQ,
    MSG_ID_L4CSMU_SET_CRRST_SECURE_DATA_REQ,
    MSG_ID_L4CSMU_SET_CARRIER_RESTRICTION_CNF,
    MSG_ID_L4CSMU_CARRIER_RESTRICTION_STATUS_CNF,
	MSG_ID_L4CSMU_SET_CRRST_SECURE_DATA_CNF,
#endif /* __CARRIER_RESTRICTION__ */
#ifdef __VZW_RSU_SUPPORT__
    MSG_ID_L4CSMU_VZW_RSU_INITIATE_REQ,
    MSG_ID_L4CSMU_VZW_RSU_RESPONSE_REQ,
    MSG_ID_L4CSMU_VZW_RSU_DELAY_TIMER_REQ,
    MSG_ID_L4CSMU_VZW_RSU_DATA_RESET_REQ,
#endif
    MSG_ID_L4CSMU_ICCID_READY_IND,
#ifdef __SBP_OP129_SIMME_LOCK__
    MSG_ID_L4CSMU_OP129_UPDATE_SIMLOCK_SETTING_REQ,
    MSG_ID_L4CSMU_OP129_UPDATE_SIMLOCK_SETTING_CNF,
    MSG_ID_L4CSMU_OP129_GET_SIMLOCK_DATA_REQ,
    MSG_ID_L4CSMU_OP129_GET_SIMLOCK_DATA_CNF,
#endif
    MSG_ID_L4CSMU_GET_MODEM_CONFIG_REQ,
    MSG_ID_L4CSMU_GET_MODEM_CONFIG_CNF,
    MSG_ID_L4CSMU_GET_API_VERSION_REQ,
    MSG_ID_L4CSMU_GET_API_VERSION_CNF,

    MSG_ID_SMU_CODE_END,
    /*------------------------SMU_MSG_CODE_END -----------------*/
MODULE_MSG_END( MSG_ID_SMU_CODE_TAIL )	

MODULE_MSG_BEGIN( MSG_ID_UEM_CODE_BEGIN )
	/*------------------------UEM_MSG_CODE_BEGIN ---------------*/
	MSG_ID_DRVUEM_AUDIO_PLAY_FINISH_IND = MSG_ID_UEM_CODE_BEGIN,
	MSG_ID_DRVUEM_KEYPAD_IND,
	MSG_ID_DRVUEM_POWER_ON_IND,
	MSG_ID_DRVUEM_PMIC_IND,
	MSG_ID_DRVUEM_GPIO_DETECT_IND,
	MSG_ID_DRVUEM_RTC_PERIOD_IND,
//#ifdef __USB_ENABLE__
    MSG_ID_DRVUEM_USBDETECT_IND,
//#endif /* __USB_ENABLE__ */
        MSG_ID_DRVUEM_CCCI_EM_REQ_IND,
	MSG_ID_L4CUEM_AUDIO_PLAY_BY_NAME_REQ,
	MSG_ID_L4CUEM_AUDIO_STOP_BY_NAME_REQ,
	MSG_ID_L4CUEM_AUDIO_PLAY_BY_STRING_REQ,
	MSG_ID_L4CUEM_AUDIO_STOP_BY_STRING_REQ,
	MSG_ID_L4CUEM_STARTUP_REQ,
	MSG_ID_L4CUEM_SET_AUDIO_PROFILE_REQ,
	MSG_ID_L4CUEM_SET_AUDIO_PARAM_REQ,
	MSG_ID_L4CUEM_SET_HW_LEVEL_REQ,
    MSG_ID_UEM_CODE_END = MSG_ID_L4CUEM_SET_HW_LEVEL_REQ,


MODULE_MSG_END( MSG_ID_UEM_CODE_TAIL )
	/*------------------------UEM_MSG_CODE_END -----------------*/

MODULE_MSG_BEGIN( MSG_ID_RAC_CODE_BEGIN )
	/*------------------------RAC_MSG_CODE_BEGIN----------------*/
   MSG_ID_L4CRAC_ACT_REQ = MSG_ID_RAC_CODE_BEGIN,
   MSG_ID_L4CRAC_REG_REQ,
   MSG_ID_L4CRAC_PS_REG_REQ,
   MSG_ID_L4CRAC_DEREG_REQ,
   MSG_ID_L4CRAC_PLMN_LIST_REQ,
   MSG_ID_L4CRAC_CLASS_CHANGE_REQ,
   MSG_ID_L4CRAC_ABORT_LIST_REQ,
   MSG_ID_L4CRAC_RFOFF_REQ, /* Ripple */
   MSG_ID_L4CRAC_SIM_STATUS_UPDATE_REQ, //__GEMINI__
   MSG_ID_L4CRAC_SET_ROAMING_MODE_REQ,   
   MSG_ID_L4CRAC_PLMN_SEARCH_REQ ,
   MSG_ID_L4CRAC_SET_RAT_MODE_REQ,
   MSG_ID_L4CRAC_PLMN_LIST_STOP_REQ,
   MSG_ID_L4CRAC_SET_PREFER_RAT_REQ,
   MSG_ID_L4CRAC_END_PS_DATA_SESSION_REQ , //mtk02475: for Fast Dormancy
   MSG_ID_L4CRAC_CSG_LIST_REQ, //mtk02475: for Rel8 CSG feature
   MSG_ID_L4CRAC_CSG_LIST_STOP_REQ, //mtk02475: for Rel8 CSG feature
   MSG_ID_L4CRAC_SUSP_RESU_UPDATE_REQ, //mtk03643: for CT network selection requirement
   MSG_ID_L4CRAC_ABORT_EMERGENCY_PLMN_SEARCH_REQ,
   MSG_ID_L4CRAC_CUSTOM_PLMN_LIST_UPDATE_REQ,
   MSG_ID_L4CRAC_GET_CUSTOM_PLMN_LIST_REQ,
   //Add for LTE multimode
   MSG_ID_L4CRAC_RAT_CHANGE_START_REQ,
   MSG_ID_L4CRAC_RAT_CHANGE_FINISH_REQ,
   MSG_ID_L4CRAC_CSFB_PAGE_CONFIG_REQ,
   MSG_ID_GMMREG_CSFB_PAGE_IND,
   MSG_ID_L4CRAC_CSFB_PAGE_RSP,
   //End of LTE multimode

   /* LTE multimode for UE mode */
   MSG_ID_L4CRAC_SET_SMS_PREFERENCE_REQ,
   MSG_ID_L4CRAC_SET_VOICE_DOMAIN_PREFERENCE_REQ,
   MSG_ID_L4CRAC_SET_UE_USAGE_SETTING_REQ,
   MSG_ID_L4CRAC_SET_UE_MODE_REQ,
   MSG_ID_L4CRAC_SET_IMS_VOICE_AVAILABILITY_REQ,
   MSG_ID_L4CRAC_SET_IMS_SMS_AVAILABILITY_REQ,
   MSG_ID_L4CRAC_IMS_REG_STATUS_UPDATE_REQ,
   MSG_ID_L4CRAC_IMS_CONFIG_REQ,
   MSG_ID_L4CRAC_IMS_REG_START_REQ,
   MSG_ID_L4CRAC_SIM_READY_IND,
   MSG_ID_L4CRAC_SIM_ERROR_IND,
   MSG_ID_L4CRAC_SET_MM_IMS_VOICE_TERMINATION_REQ,
   MSG_ID_L4CRAC_SET_SMS_OVER_SGS_REQ,
   /* end of LTE multimode for UE mode */
   
   MSG_ID_L4CRAC_SET_RECOVERY_SEARCH_TIMER_REQ,
   MSG_ID_L4CRAC_GET_RECOVERY_SEARCH_TIMER_REQ,
   MSG_ID_L4CRAC_DUPLEX_MODE_REQUIRED_REQ,

   MSG_ID_RAC_GMSS_SET_RECOVERY_SEARCH_TIMER_CNF,
   MSG_ID_RAC_GMSS_GET_RECOVERY_SEARCH_TIMER_CNF,
   MSG_ID_RAC_GMSS_DUPLEX_MODE_REQUIRED_CNF,

   MSG_ID_L4CRAC_EPS_ATTACH_NEEDED_REJ_RSP,
   /* add for 6291 MTC */
   MSG_ID_L4CRAC_IMS_CALL_INFO_REQ,
   /* add for 6291 MTC */

   MSG_ID_L4CRAC_IMS_SCM_REQ,
   MSG_ID_L4CRAC_GET_LAST_RAT_SELECT_IND_REQ,
   MSG_ID_L4CRAC_SET_PGCHECK_REQ,
   MSG_ID_L4CRAC_VOLTE_STATUS_UPDATE_REQ,

   MSG_ID_L4CRAC_MMDC_RECOVERY_SEARCH_REQ,

   MSG_ID_L4CRAC_ACTIVE_SIM_REQ,
   MSG_ID_L4CRAC_SET_CT_MODE_REQ,
   MSG_ID_L4CRAC_CLEAR_MRU_REQ,
   MSG_ID_L4CRAC_SET_MRU_REQ,
   MSG_ID_L4CRAC_SET_AUX_PLMN_REQ,

   // for SONY requirement, not re-enable E-UTRAN after CGATT=0
   MSG_ID_L4CRAC_DISABLE_EUTRAN_REQ,
   MSG_ID_L4CRAC_SET_ROAMING_DATA_CONFIG_REQ,
   MSG_ID_L4CRAC_SET_HVOLTE_MODE_REQ,
   MSG_ID_L4CRAC_EMC_SESSION_START_REQ,
   MSG_ID_L4CRAC_EMC_SESSION_STOP_REQ,
   MSG_ID_L4CRAC_ECBM_MODE_START_REQ,
   MSG_ID_L4CRAC_ECBM_MODE_STOP_REQ,
   MSG_ID_L4CRAC_EMC_SERVICE_SCAN_REQ,
   MSG_ID_L4CRAC_EMC_BAR_NETWORK_REQ,
   MSG_ID_L4CRAC_OMADM_UPDATE_REQ,
   MSG_ID_L4CRAC_PTMSI_CLEAR_REQ,
   MSG_ID_L4CRAC_DATA_ALLOW_REQ,
   MSG_ID_L4CRAC_VZW_ADMIN_APN_SETTING_NOTIFY_REQ,
 #ifdef __REMOTE_SIM__
   MSG_ID_L4CRAC_RSIM_AUTH_ABORT_REQ, 
 #endif
   MSG_ID_L4C_RAC_FREQ_SCAN_START_REQ,
   MSG_ID_L4C_RAC_FREQ_SCAN_END_REQ,

   MSG_ID_GMMREG_ATTACH_CNF,
   MSG_ID_GMMREG_ATTACH_REJ,
   MSG_ID_GMMREG_DETACH_CNF,
   MSG_ID_GMMREG_DETACH_IND,
   MSG_ID_GMMREG_PLMN_LIST_IND, //not used
   MSG_ID_GMMREG_NW_INFO_IND,
   MSG_ID_GMMREG_STATUS_IND,
   MSG_ID_GMMREG_CELL_INFO_UPDATE_IND,
   MSG_ID_GMMREG_PS_SERVICE_INFO_IND, /* For GPRS MMI information. */
   MSG_ID_GMMREG_CIPHER_IND, 
   MSG_ID_GMMREG_RFOFF_CNF, /* Ripple */
 #ifdef __REMOTE_SIM__
   MSG_ID_GMMREG_RSIM_AUTH_ABORT_CNF,
   MSG_ID_GMMREG_AUTH_FINISH_IND,
   MSG_ID_GMMREG_VIRTUAL_MODE_IND,
 #endif
   MSG_ID_GMMREG_DEDICATED_MODE_IND, /* CH_Liang 2005/05/31 Homezone feature */
   MSG_ID_GMMREG_SEARCH_NORMAL_FINISH_IND, //__GEMINI__ not used
#if defined(__GEMINI__)   /* for RAC2 GEMINI */ 
   MSG_ID_GMMREG_POWERON_SEARCH_FINISH_IND, //__GEMINI__ (MONZA)
#endif   
   MSG_ID_GMMREG_RR_SERVICE_STATUS_IND,  //__GEMINI__ ,20080217
   MSG_ID_GMMREG_SUSPEND_STATUS_IND,  //__GEMINI__ ,20080217   
   /* 3G */   
   MSG_ID_GMMREG_SET_ROAMING_MODE_CNF,
   MSG_ID_GMMREG_SUSP_RESU_UPDATE_CNF,
   MSG_ID_GMMREG_SET_PREFER_RAT_CNF,
   MSG_ID_GMMREG_SET_RAT_MODE_CNF, /* for MONZA */
   MSG_ID_GMMREG_PLMN_SEARCH_CNF, /* for MONZA */
   MSG_ID_GMMREG_PLMN_LIST_CNF, /* for MONZA */
   MSG_ID_GMMREG_PLMN_LIST_STOP_CNF, /* for MONZA */
   MSG_ID_GMMREG_CSG_LIST_CNF,
   MSG_ID_GMMREG_CSG_LIST_STOP_CNF,
   MSG_ID_GMMREG_BAND_SEL_CNF,
   MSG_ID_GMMREG_END_PS_DATA_SESSION_CNF, //mtk02475: for Fast Dormancy
   MSG_ID_GMMREG_NW_ECC_IND,  /* __REL5__ */
   MSG_ID_GMMREG_NW_REJECT_IND,
   MSG_ID_GMMREG_NW_FEATURE_IND,

   MSG_ID_MMIAS_CELL_POWER_LEVEL_IND,
   MSG_ID_MMIAS_PKT_TRANSFER_MODE_IND, /*Byron: 2005/06/07/: send the pkt transfer mode indication to RAC*/
   MSG_ID_GMMREG_END_PS_DATA_SESSION_IND, //mtk80370: for FOP request Fast Dormancy
#ifdef __LTE_RAT__
    MSG_ID_EMMREG_SET_RAT_MODE_CNF,
    MSG_ID_EMMREG_ATTACH_CNF,
    MSG_ID_EMMREG_DETACH_IND,
    MSG_ID_EMMREG_DISABLE_NW_LOSS_OPTIMIZE_IND,
    MSG_ID_EMMREG_RFOFF_CNF,
    MSG_ID_EMMREG_CELL_INFO_UPDATE_IND,
    MSG_ID_EMMREG_NW_INFO_IND,
    MSG_ID_EMMREG_EPS_ATTACH_NEEDED_IND,
    MSG_ID_EMMREG_NW_ECC_IND,
    MSG_ID_EMMREG_PEER_REJECT_IND,
    MSG_ID_EMMREG_EMC_ATTACH_IND,
    MSG_ID_EMMREG_EMC_ATTACH_CNF,
    MSG_ID_EMMREG_EMC_DETACH_IND,
    MSG_ID_EMMREG_NW_FEATURE_IND,
    MSG_ID_EMMREG_NW_REJECT_IND,
    MSG_ID_EMMREG_CS_DOMAIN_NOT_AVAILABLE_IND,
	MSG_ID_EMMREG_IMS_SCM_INFO_CNF,
#ifdef __REMOTE_SIM__
    MSG_ID_EMMREG_RSIM_AUTH_FINISH_IND,
	MSG_ID_EMMREG_RSIM_AUTH_ABORT_CNF,
#endif /* __REMOTE_SIM__ */
#endif /* __LTE_RAT__ */

   MSG_ID_RAC_GMSS_RFOFF_CNF,
   MSG_ID_RAC_GMSS_SET_ROAMING_MODE_CNF, /* 3G */
   MSG_ID_RAC_GMSS_SET_PREFER_RAT_CNF,
   MSG_ID_RAC_GMSS_SET_RAT_MODE_CNF,
   MSG_ID_RAC_GMSS_PLMN_SEARCH_CNF,
   MSG_ID_RAC_GMSS_PLMN_LIST_CNF,
   MSG_ID_RAC_GMSS_PLMN_LIST_STOP_CNF,
   MSG_ID_RAC_GMSS_CSG_LIST_CNF,
   MSG_ID_RAC_GMSS_CSG_LIST_STOP_CNF,
   MSG_ID_RAC_GMSS_PLMN_STATUS_IND,
   MSG_ID_RAC_GMSS_SUSPEND_STATUS_IND,
   MSG_ID_RAC_GMSS_PLMN_LIST_IND,
   MSG_ID_RAC_GMSS_SUSP_RESU_UPDATE_CNF,
   MSG_ID_RAC_GMSS_GET_CUSTOM_PLMN_LIST_CNF,

   MSG_ID_RAC_GMSS_IMS_SERVICE_IND,
   MSG_ID_RAC_GMSS_RESTART_CLEAR_CODE_33_PROC_IND,
   MSG_ID_RAC_GMSS_CS_DOMAIN_AVAILABILITY_IND,
   MSG_ID_RAC_GMSS_REPORTED_RAT_CHANGE_IND,
   MSG_ID_L4CRAC_MD_SIM_CONFIG_REQ,
   MSG_ID_RAC_GMSS_RAT_SELECT_IND,
   MSG_ID_L4CRAC_RAT_CHANGE_SUCCESS_NOTIFY_REQ,
   MSG_ID_RAC_GMSS_ATTACH_RESULT_IND,
   MSG_ID_RAC_GMSS_DUPLEX_MODE_CHANGE_IND,
   MSG_ID_L4CRAC_DUPLEX_MODE_CHANGE_REQ,
   MSG_ID_RAC_GMSS_DUPLEX_MODE_CHANGE_CNF,
   MSG_ID_EMMREG_DUPLEX_MODE_CHANGE_CNF,
   MSG_ID_GMMREG_DUPLEX_MODE_CHANGE_CNF,
#ifdef __KOR_CUSTOMIZATION__
   MSG_ID_RAC_GMSS_RPLMN_IND,    /* Get RPLMN */
#endif
   MSG_ID_RAC_GMSS_SET_CT_MODE_CNF,
   MSG_ID_RAC_GMSS_ACTIVE_SIM_INFO_CNF,   
   MSG_ID_RAC_GMSS_C2K_DETACH_IND,
   MSG_ID_RAC_GMSS_SET_WM_POLICY_CNF,
   MSG_ID_L4CRAC_SET_WM_POLICY_REQ,
   MSG_ID_RAC_GMSS_SET_AUX_PLMN_CNF,
   MSG_ID_RAC_GMSS_SET_MRU_CNF,
   MSG_ID_RAC_GMSS_CLEAR_MRU_CNF,
   MSG_ID_RAC_GMSS_EMC_SERVICE_IND,
   MSG_ID_RAC_GMSS_STOP_SEARCH_IND,
   MSG_ID_RAC_GMSS_C2K_SERVICE_IND,
   MSG_ID_RAC_GMSS_1X_CONN_STATUS_IND,
   MSG_ID_RAC_GMSS_SET_HVOLTE_MODE_CNF,
   MSG_ID_L4CRAC_VZWMRU_UPDATE_REQ,
   MSG_ID_RAC_GMSS_VZWMRU_UPDATE_CNF,
   MSG_ID_RAC_GMSS_1XRTT_CELL_LIST_CNF,

   MSG_ID_L4CRAC_GMSS_SET_TW_MODE_REQ,
   MSG_ID_RAC_GMSS_C2K_SILENT_REDIAL_IND,

//#ifdef __LTE_R11__
   MSG_ID_EVAL_RAC_CA_INFO_IND,
   MSG_ID_EVAL_RAC_MT_PAGE_IND,
   MSG_ID_EVAL_RAC_SEND_ESR_IND,
//#endif
   MSG_ID_L4CRAC_CALL_STATUS_REQ,
   MSG_ID_L4CRAC_CSG_AUTO_SEARCH_MODE_REQ,
   MSG_ID_L4CRAC_SET_FIRST_CAMP_ON_PREFER_RAT_REQ,
   MSG_ID_L4CRAC_DUPLEX_MODE_CHANGE_FINISH_REQ,
   MSG_ID_L4CRAC_NW_REG_STATUS_IND,
   MSG_ID_RAC_GMSS_REG_STATUS_IND,
   MSG_ID_RAC_GMSS_OMADM_UPDATE_CNF,
   MSG_ID_RAC_GMSS_C2K_CELL_INFO_IND,
   MSG_ID_RAC_GMSS_ACTIVE_RAT_IND,
   MSG_ID_L4CRAC_ARAL_UPDATE_REQ,
   MSG_ID_L4CRAC_SCREEN_ON_REQ,
   MSG_ID_GMMREG_PACKET_PAGING_IND,
   MSG_ID_L4CRAC_PACKET_PAGING_IND, 
//#if defined(__FAST_ROAMING_SEARCH__)
   MSG_ID_RAC_GMSS_PLMN_FOUND_IND,
//#endif
   MSG_ID_L4CRAC_CS_VOICE_CALL_PROTECTION_REQ,
   MSG_ID_L4CRAC_CAMPED_CELL_INFO_IND,
   MSG_ID_L4CRAC_RRC_CONN_REL_IND,
   MSG_ID_GMMREG_RRC_CONN_REL_CAUSE_IND,

   MSG_ID_L4CRAC_IMS_DEREG_START_REQ,   
   MSG_ID_RAC_GMSS_C2K_CSFB_START_IND,
   MSG_ID_RAC_GMSS_C2K_CSFB_STOP_IND,
   MSG_ID_RAC_GMSS_HVOLTE_MODE_CHANGE_IND,
   MSG_ID_L4CRAC_DATA_SERVICE_STATUS_UPDATE_REQ,
   MSG_ID_RAC_GMSS_INVALID_SIM_RECOVER_IND,

   /* add for CT3G global mode attach */
   MSG_ID_L4CRAC_CT3G_INSERTED_IND,
   MSG_ID_L4CRAC_CA_INFO_IND,
   MSG_ID_L4CRAC_RESET_OTA_CTXT_REQ,
   MSG_ID_RAC_GMSS_SUSPEND_EGREG_UPDATE_IND,
   MSG_ID_RAC_GMSS_MANUAL_SEARCH_NOT_ALLOW_IND,
   /*mtk13782: [MOLY00267639] porting from LR11 to UMOLYA*/
   MSG_ID_RAC_GMSS_WAIT_FOR_IMS_REG_STATUS_IND,
   MSG_ID_RAC_GMSS_GET_LAST_RAT_SELECT_IND_CNF,
   //CDMA less porting
   MSG_ID_L4CRAC_IMS_TIMER_STATUS_UPDATE_REQ,
   MSG_ID_RAC_GMSS_IMS_CALL_END_STATUS_IND,
   MSG_ID_L4CRAC_ABORT_ENWSEL_SEARCH_REQ,
   MSG_ID_L4CRAC_IMS_EVENT_UPDATE_REQ,
   MSG_ID_L4CRAC_SET_IMS_ROAMING_CONFIG_REQ,
   MSG_ID_L4CRAC_GMSS_SET_PLMN_BARRING_TIMER_REQ,
   MSG_ID_L4CRAC_GMSS_GET_PLMN_BARRING_TIMER_REQ, 
   MSG_ID_RAC_GMSS_SET_PLMN_BARRING_TIMER_CNF,
   MSG_ID_RAC_GMSS_GET_PLMN_BARRING_TIMER_CNF,
#ifdef __REMOTE_SIM__
   MSG_ID_L4CRAC_RSIM_SET_PS_ONLY_REQ,
   MSG_ID_L4CRAC_RSIM_AKA_STATUS_REQ,
   MSG_ID_L4CRAC_RSIM_AKA_RSIM_ACCESS_FOR_AUTH_DOWNLOAD_REQ,
   MSG_ID_L4C_RATDM_RSIM_AKA_RSIM_ACCESS_FOR_AUTH_DOWNLOAD_REQ,
   MSG_ID_L4C_RATDM_RSIM_AUTH_ABORT_REQ,
#endif
   /*TMO disable 2G*/
   MSG_ID_L4CRAC_RAT_DISABLE_CONFIG_REQ,
   MSG_ID_L4CRAC_SET_MS_SV_REQ,

   MSG_ID_L4CRAC_FPLMN_ACTION_REQ,
   // Reporting NW abnormal reject causes
   MSG_ID_RAC_GMSS_NW_REG_REJ_IND,
   
   MSG_ID_L4CRAC_CELLULAR_NETWORK_CONFIG_REQ,
   MSG_ID_RAC_GMSS_ILLEGAL_ME_IND,
   MSG_ID_L4CRAC_1XRTT_CELL_LIST_REQ,

   MSG_ID_L4CRAC_1XRTT_CELL_LIST_CNF,
   MSG_ID_L4CRAC_USER_SELECTED_MAIN_PS_REQ,
   MSG_ID_GMMREG_CSFB_RESULT_IND,
   MSG_ID_L4CRAC_PEER_SIM_MANUAL_LIST_START_REQ,
   MSG_ID_L4CRAC_PEER_SIM_MANUAL_LIST_FINISH_REQ,

   MSG_ID_L4CRAC_NW_REJECT_IND,

   MSG_ID_RAC_CODE_MAX,//not used, only for MSG_ID_RAC_CODE_END reference
   MSG_ID_RAC_CODE_END = MSG_ID_RAC_CODE_MAX-1,
MODULE_MSG_END( MSG_ID_RAC_CODE_TAIL )   

	/*------------------------RAC_MSG_CODE_END -----------------*/
	/*------------------------USAT_MSG_CODE_BEGIN --------------*/
	/*------------------------USAT_MSG_CODE_END ----------------*/
	/*------------------------PHB_MSG_CODE_BEGIN ---------------*/
MODULE_MSG_BEGIN( MSG_ID_PHB_CODE_BEGIN )	
	MSG_ID_L4CPHB_STARTUP_REQ = MSG_ID_PHB_CODE_BEGIN,
	MSG_ID_L4CPHB_INIT_LN_REQ,
	MSG_ID_L4CPHB_READ_REQ,
	MSG_ID_L4CPHB_ADD_REQ,
	MSG_ID_L4CPHB_UPDATE_REQ,
	MSG_ID_L4CPHB_DELETE_REQ,
	MSG_ID_L4CPHB_SEARCH_REQ,
	MSG_ID_L4CPHB_APPROVE_REQ,
	MSG_ID_L4CPHB_READ_LN_REQ,
	MSG_ID_L4CPHB_WRITE_LN_REQ,
	MSG_ID_L4CPHB_DELETE_LN_REQ,
	MSG_ID_L4CPHB_SYNC_REQ,
	MSG_ID_L4CPHB_STARTUP_READ_NEXT_REQ,
	MSG_ID_L4CPHB_WRITE_REQ,
	MSG_ID_L4CPHB_UPDATE_NW_ECC_REQ, //mtk01616_070905: for R5 ECC category
	MSG_ID_L4CPHB_INIT_ME_LN_REQ,	
	MSG_ID_L4CPHB_INIT_ME_PHB_REQ,	
        MSG_ID_L4CPHB_WRITE_USIM_REQ,
        MSG_ID_L4CPHB_READ_USIM_REQ,
        MSG_ID_L4CPHB_DELETE_USIM_REQ,
        MSG_ID_L4CPHB_CHECK_WRITE_USIM_ENTRY_REQ,
      MSG_ID_L4CPHB_FDN_GET_NAME_REQ, 
        MSG_ID_L4CPHB_READ_SIM_LN_REQ, 
        MSG_ID_L4CPHB_WRITE_SIM_LN_REQ, 
        MSG_ID_L4CPHB_DELETE_SIM_LN_REQ, 

    MSG_ID_PHB_CODE_END,
	/*------------------------PHB_MSG_CODE_END -----------------*/
MODULE_MSG_END( MSG_ID_PHB_CODE_TAIL )		
	/*------------------------ATCI_MSG_CODE_BEGIN ---------------*/
    //RMMI_UT ---
MODULE_MSG_BEGIN( MSG_ID_ATCI_CODE_BEGIN )
	MSG_ID_ATCI_UT_RMMI_INPUT_STRING = MSG_ID_ATCI_CODE_BEGIN,
	MSG_ID_ATCI_UT_RMMI_OUTPUT_STRING,
    MSG_ID_ATCI_UT_RMMI_INPUT_EXPANDED_AT_STRING,
    MSG_ID_ATCI_UT_CHECK_L4C_CONTEXT_INFO,
    //--- RMMI_UT
    MSG_ID_ATCIDT_UART_TRANSFER_REQ,
    MSG_ID_ATCIDT_UART_TRANSFER_CNF,
    MSG_ID_ATCIDT_UART_TRANSFER_IND,
    MSG_ID_ATCI_THERMAL_EVENT_REPORT_IND, //for thermal_protection
    MSG_ID_ATCI_UT_UART_INPUT_IND,
    MSG_ID_ATCI_MD3_PWROFF_DONE_IND,
    MSG_ID_L4B_ATCI_TARGET_RESET_IND,    
    MSG_ID_L4B_ATCI_AT_CMD_REQ,
    MSG_ID_L4BPWR_ATCI_EPOF_REQ,

    MSG_ID_L4BPWR_ATCI_CFUN_0_REQ,      // temp solution for cfun 0
    MSG_ID_L4BPWR_ATCI_CFUN_0_CNF,      // temp solution for cfun 0

    MSG_ID_ATCI_CODE_END,
MODULE_MSG_END( MSG_ID_ATCI_CODE_TAIL )	    	
	/*------------------------ATCI_MSG_CODE_END -----------------*/
	/*------------------------ENG_MSG_CODE_BEGIN ---------------*/
	/*------------------------ENG_MSG_CODE_END -----------------*/

MODULE_MSG_BEGIN(MSG_ID_MBCI_CODE_BEGIN)
    /*------------------------MBCI_MSG_CODE_BEGIN ---------------*/
    MSG_ID_UPS_MBCI_COMMAND_REQ = MSG_ID_MBCI_CODE_BEGIN,
    MSG_ID_UPS_MBCI_COMMAND_RSP,
    MSG_ID_UPS_MBCI_STATUS_IND,
    MSG_ID_UPS_MBCI_LOOPBACK_START_IND,
    MSG_ID_UPS_MBCI_LOOPBACK_STOP_IND,
    MSG_ID_MBCI_CODE_END,
    /*------------------------MBCI_MSG_CODE_END ---------------*/
MODULE_MSG_END( MSG_ID_MBCI_CODE_TAIL )	


MODULE_MSG_BEGIN( MSG_ID_PS_CODE_BEGIN )	    
   /*----------AS_MSG_CODE_BEGIN ---------------*/ 
   MSG_ID_L4CPS_NBR_CELL_INFO_START_REQ = MSG_ID_PS_CODE_BEGIN,
   MSG_ID_L4CPS_NBR_CELL_INFO_STOP_REQ,

   #if defined(__AT_RRC_TRACE_SUPPORT__)
   MSG_ID_L4CAS_SET_RRC_PEER_TRACE_REQ,
   MSG_ID_L4CAS_RRC_PEER_TRACE_IND,
   #endif

   #if defined(__ETWS_SUPPORT__)
   MSG_ID_L4CAS_ETWS_SETTING_REQ,
   MSG_ID_L4CAS_ETWS_INFORMATION_IND,
   #endif
   
   MSG_ID_L4C_EVAL_ETWS_INFORMATION_IND,
   
   MSG_ID_L4C_EVAL_ADJUST_MEAS_REQ,
   MSG_ID_L4C_EVAL_ADJUST_MEAS_CNF,

   MSG_ID_L4C_EVAL_EDDA_CNF,

   // re-usage 4G LPP CP message to reset LCS pos info during SUPL testing
   MSG_ID_L4C_EVAL_NW_RESET_UE_STORED_POS_INFO_IND,

   // To notify the ERRC state
   MSG_ID_L4C_EVAL_ERRC_STATE_IND,

   // C2K 1XCSFB
   MSG_ID_L4C_EVAL_C2K_CSFB_REQ,
   MSG_ID_L4C_EVAL_C2K_CSFB_CNF,
   MSG_ID_L4C_EVAL_C2K_CSFB_STOP_REQ,
   MSG_ID_L4C_EVAL_C2K_CSFB_STOP_CNF,
   
   MSG_ID_L4CAS_SET_PLMN_LIST_PREFERENCE_REQ,

   MSG_ID_L4CAS_SET_HSPA_PREFERENCE_REQ, //mtk02285, hspa_mmi

   MSG_ID_L4CAS_SET_PREFER_RAT_REQ,
    MSG_ID_L4CAS_CSG_AUTO_SEARCH_REQ,

   MSG_ID_L4CAS_BAR_CELL_CONTROL_REQ,

   MSG_ID_L4CAS_BAR_CELL_CONTROL_CNF,
       
   MSG_ID_L4CAS_IMS_CONFIG_IND,
   MSG_ID_L4CAS_IMS_CALL_INFO_IND,
   
   //agps_up_cp_conflict   
   MSG_ID_L4C_LCSP_AGPS_CP_START_IND,
   MSG_ID_L4C_LCSP_AGPS_CP_END_IND,
   MSG_ID_L4C_LCSP_AGPS_CP_ABORT_REQ,
   
   MSG_ID_L4C_RATCM_AGPS_RESET_POSITIONING_IND,
   MSG_ID_L4CPS_MEAS_INFO_REQ,
   MSG_ID_L4CPS_MEAS_INFO_CNF,
   MSG_ID_L4CPS_RF_INFO_IND,
   MSG_ID_L4C_RRCE_RRC_STATE_IND,
   MSG_ID_L4C_RRCE_PCH_TXRX_IND,
   MSG_ID_L4C_ME_RECONFIGURE_REQ,
   MSG_ID_L4C_ME_RECONFIGURE_CNF,
   MSG_ID_L4C_RRM_RRMS_STATE_IND,
   MSG_ID_L4C_EVAL_DRX_UPDATE_CNF,
   MSG_ID_L4C_EVAL_DRX_UPDATE_IND,
   MSG_ID_L4C_EVAL_SR_FAILURE_IND,
   MSG_ID_L4C_EVAL_SR_REJECT_IND,
   MSG_ID_L4C_EVAL_RACH_REJECT_IND,
   MSG_ID_L4C_CELL_POWER_THRESHOLD_CONFIG_CNF,
   MSG_ID_L4C_ME_VOLTE_RECONFIGURE_REQ,
   MSG_ID_L4C_ME_VOLTE_RECONFIGURE_CNF,
   MSG_ID_L4CAS_CC_ERROR_IND,
   MSG_ID_L4C_ERRC_WLAN_LWA_CONNECT_REQ,
   MSG_ID_L4C_ERRC_WLAN_LWA_DISCONNECT_REQ,
   MSG_ID_L4C_ERRC_WLAN_MEASUREMENT_REQ,
   MSG_ID_L4C_ERRC_WLAN_MEASUREMENT_STOP_REQ,
   MSG_ID_L4C_EVAL_PCELL_INFO_IND,
   
   // To notify the RRC Connection Establishment failure cause
   MSG_ID_L4C_EVAL_ESTABLISHMENT_IND,

   MSG_ID_L4C_ME_IMS_RECONFIGURE_REQ,
   MSG_ID_L4C_ME_IMS_RECONFIGURE_CNF,      
   MSG_ID_L4CPS_NW_BAND_INFO_START_REQ,
   MSG_ID_L4CPS_NW_BAND_INFO_STOP_REQ,
   MSG_ID_L4CPS_NW_BAND_INFO_IND,
   MSG_ID_L4CAS_SIB19_INFO_IND,
   MSG_ID_L4CAS_RR_APC_CTRL_INFO_REQ,
   MSG_ID_L4CAS_RR_APC_CTRL_INFO_CNF,
   MSG_ID_L4C_RRM_PSEUDO_BS_DETECT_IND,
   MSG_ID_L4CAS_RR_PSEUDO_BS_QUERY_REQ,
   MSG_ID_L4CAS_RR_PSEUDO_BS_QUERY_CNF,
   MSG_ID_L4C_ME_DSBP_RECONFIGURE_REQ,
   MSG_ID_L4C_ME_DSBP_RECONFIGURE_CNF,   
   MSG_ID_L4C_SBP_DSBP_RECONFIGURE_REQ,
   MSG_ID_L4C_SBP_DSBP_RECONFIGURE_CNF,   

   MSG_ID_L4C_CC_DSBP_RECONFIGURE_IND,

   // Notify IPCore PLMN LIST current action in order to suspend/resume Tx traffic in data plane
   MSG_ID_L4C_IPCORE_PLMN_LIST_IND,

   MSG_ID_L4C_PHB_UT_REQ,

   MSG_ID_L4CAS_CELL_POWER_THRESHOLD_CONFIG_REQ,

#ifdef __TC7__CS__SUPPORT__
   MSG_ID_L4CUAS_CS_STATUS_REQ,
#endif

#ifdef __REMOTE_SIM__
   MSG_ID_L4C_AKA_RESOURCE_RELEASE_REQ,
#endif
    MSG_ID_DDM_EVAL_CABTSRI_IND,
    MSG_ID_L4C_SMS_DSBP_RECONFIGURE_IND,
    MSG_ID_L4C_SMSAL_DSBP_RECONFIGURE_IND,
    MSG_ID_L4C_IMCSMS_DSBP_RECONFIGURE_IND,

    MSG_ID_L4C_EVAL_CS_SERVICE_NOTIFICATION_IND,
    MSG_ID_L4C_RRM_CHANNEL_PARAM_IND,
    MSG_ID_L4C_RRC_CUR_FREQ_IND,
    
    MSG_ID_L4C_IMS_STK_USSD_REQ,
    MSG_ID_L4C_IMS_STK_USSD_CNF,
    MSG_ID_L4C_DSBP_SETTING_INFO_IND,
    MSG_ID_L4C_EPDCP_DATA_USAGE_NTF,
    MSG_ID_L4C_ATCI_DSBP_RECONFIGURE_IND,
    MSG_ID_L4C_HVOLTE_MODE_SWITCH_IND,
  MSG_ID_PS_CODE_END,

  /*----------AS_MSG_CODE_END -----------------*/
MODULE_MSG_END( MSG_ID_PS_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_VMMI_CODE_BEGIN )
   /*----------VMMI_MSG_CODE_BEGIN -----------------*/
   MSG_ID_L4VMMI_AT_RESPONSE_IND = MSG_ID_VMMI_CODE_BEGIN,
   MSG_ID_L4VMMI_ETS_RESPONSE_IND,
   MSG_ID_VMMI_CODE_END,
   /*----------VMMI_MSG_CODE_END -----------------*/
MODULE_MSG_END( MSG_ID_VMMI_CODE_TAIL )	    
   
#if 0 //move to ATP
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif

MODULE_MSG_BEGIN( MSG_ID_MBMSAL_CODE_BEGIN )
  MSG_ID_MBMSAL_ERRC_MBMS_SERVICE_STATUS_IND = MSG_ID_MBMSAL_CODE_BEGIN,
  MSG_ID_MBMSAL_ERRC_MBMS_SIB15_IND,
  MSG_ID_MBMSAL_ERRC_MBMS_SIB16_IND,
  MSG_ID_MBMSAL_ERRC_MBMS_CONFIG_INFO_IND,
  MSG_ID_MBMSAL_ERRC_MBMS_SERVSESS_STATUS_IND,
  MSG_ID_MBMSAL_INTERNAL_IND,
MODULE_MSG_END( MSG_ID_MBMSAL_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_L4C2K_CODE_BEGIN )
    MSG_ID_C2K_L4C_MDSTATUS_UPDATE_IND = MSG_ID_L4C2K_CODE_BEGIN,
    MSG_ID_L4C_C2K_PWROFF_START_IND,
MODULE_MSG_END( MSG_ID_L4C2K_CODE_TAIL )

   /*---------------L4_MSG_CODE_END---------------------*/

#endif  //_L4_MSGIDID.H
