/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2015
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#ifndef _PSW_MSG_ID_H
#define _PSW_MSG_ID_H

/*****************************************************************************
*
* FILE NAME   :psw_msgid.h
*
* DESCRIPTION :
*
*
*
* HISTORY     :
*     See Log at end of file
*
*****************************************************************************/
/*----------------------------------------------------------------------------
 Include Files
----------------------------------------------------------------------------*/
#include "module_msg_range.h"


MODULE_MSG_BEGIN( MSG_ID_CPSW_CODE_BEGIN )
       /* from multiple sources */
       MSG_ID_PSW_CMD_STATUS_MSG = MSG_ID_CPSW_CODE_BEGIN + 0,

       /* from L1D */
       MSG_ID_PSW_PMRM_REQ_MSG,
       MSG_ID_PSW_CAND_FREQ_TIMES_MSG,
       MSG_ID_PSW_CAND_FREQ_MEASUREMENTS_MSG,
       MSG_ID_PSW_SCAN_MEASUREMENTS_MSG,
       MSG_ID_PSW_IDLE_HANDOFF_MSG,
       MSG_ID_PSW_START_CF_MEASURE_MSG,
       MSG_ID_PSW_END_CF_MEASURE_MSG,
       MSG_ID_PSW_INITIAL_ACQ_REPORT_MSG,

       MSG_ID_PSW_SET_IDLE_HO_PARAMETERS_MSG,

       MSG_ID_PSW_OUTER_LOOP_REPORT_REQ_MSG,
       MSG_ID_PSW_GET_PS_INFO_MSG,
       MSG_ID_PSW_L1D_ACCESS_PREAMBLE_COMPLETE_MSG,
       MSG_ID_PSW_L1D_ACCESS_COMPLETE_MSG,
       MSG_ID_PSW_L1D_ACCESS_PROBE_COMPLETE_MSG,
       MSG_ID_PSW_OOSA_WAKEUP_IND_MSG,
       MSG_ID_PSW_L1D_RSSI_RPT_MSG,
       MSG_ID_PSW_STATUS_REQUEST_RSSI_RSP_MSG,
       MSG_ID_PSW_L1D_DEACTIVE_CNF_MSG,
       MSG_ID_PSW_L1D_OOSA_CNF_MSG,
       MSG_ID_PSW_L1D_RAKE_DDL_CNF_MSG,
	   MSG_ID_PSW_L1D_ACCESS_PREAMBLE_DELAY_MSG,

       /* from LMD */
       MSG_ID_PSW_FORWARD_SYNC_CHAN_FRAME_MSG,
       MSG_ID_PSW_FORWARD_PAGE_CHAN_FRAME_MSG,
       MSG_ID_PSW_FORWARD_BCCH_FRAME_MSG,
       MSG_ID_PSW_FORWARD_FCCCH_FRAME_MSG,
       MSG_ID_PSW_DSCH_CHAN_FRAME_MSG,
       MSG_ID_PSW_REVERSE_STATISTICS_PARMS_MSG,
       MSG_ID_PSW_SERVICE_OPTION_CONTROL_RESP_MSG,
       MSG_ID_PSW_RSCH_REL_IND_MSG,
       MSG_ID_PSW_STAT_CNT_MSG,
       MSG_ID_PSW_FORWARD_PAGE_CHAN_MSG,
       MSG_ID_PSW_FORWARD_FCCCH_MSG,
       MSG_ID_PSW_FORWARD_BCCH_MSG,
       MSG_ID_PSW_FORWARD_SYNC_CHAN_MSG,
       MSG_ID_PSW_DSCH_CHAN_MSG,

       /* from MMI */
       MSG_ID_PSW_POWER_MSG,
       MSG_ID_PSW_CALL_INITIATE_MSG,
       MSG_ID_PSW_CALL_INITIATE_WITH_INFO_REC_MSG,
       MSG_ID_PSW_GET_PRL_INFO_MSG,
       MSG_ID_PSW_E911_MODE_MSG,
       MSG_ID_PSW_CALL_ANSWER_MSG,
       MSG_ID_PSW_CALL_HANGUP_MSG,
       MSG_ID_PSW_SEND_CONT_DTMF_ON_MSG,
       MSG_ID_PSW_SEND_CONT_DTMF_OFF_MSG,
       MSG_ID_PSW_SEND_BURST_DTMF_MSG,
       MSG_ID_PSW_HOOKFLASH_MSG,
       MSG_ID_PSW_SET_PRIVACY_MODE_MSG,

       MSG_ID_PSW_SET_RETRIEVABLE_PARAMETER,
       MSG_ID_PSW_GET_RETRIEVABLE_PARAMETER,
       MSG_ID_PSW_INJECT_HANDOFF_MSG,

       MSG_ID_PSW_GET_FULL_SYS_TIME_MSG,
       MSG_ID_PSW_SET_SILENT_RETRY_MSG,
       MSG_ID_PSW_GET_SILENT_RETRY_STATUS_MSG,
       MSG_ID_PSW_SET_MOB_PREV_MSG,
       MSG_ID_PSW_SET_CUSTOM_FEATURE_MSG,
       MSG_ID_PSW_SET_PRL_ENABLE_MSG,

       /* from VAL - SMS related */
       MSG_ID_PSW_SMS_UNKNOWN_CONNECT_MSG,
       MSG_ID_PSW_SMS_UNKNOWN_DISCONNECT_MSG,
       MSG_ID_PSW_SMS_UNKNOWN_PARMS_MSG,
       MSG_ID_PSW_SMS_PREF_SRV_OPT_MSG,
       MSG_ID_PSW_SMS_CONNECT_MSG,
       MSG_ID_PSW_SMS_DISCONNECT_MSG,
       MSG_ID_PSW_SMS_BCAST_CONNECT_MSG,
       MSG_ID_PSW_SMS_BCAST_DISCONNECT_MSG,
       MSG_ID_PSW_SMS_BCAST_PARMS_MSG,
       MSG_ID_PSW_SMS_SUBMIT_PARMS_MSG,
       MSG_ID_PSW_SMS_SUBMIT_DATA_MSG,
       MSG_ID_PSW_SMS_CANCEL_MSG,
       MSG_ID_PSW_SMS_ACK_PARMS_MSG,
       MSG_ID_PSW_SMS_ACK_DATA_MSG,
       MSG_ID_PSW_SMS_TERMINAL_STATUS_MSG,
       MSG_ID_PSW_SMS_TIMER_EXPIRED_MSG,
       MSG_ID_PSW_SMS_CAUSE_CODE_STATUS_MSG,
       MSG_ID_PSW_SMS_RETX_AMOUNT_MSG,
       MSG_ID_PSW_SMS_CAUSE_CODE_SET_MSG,
       MSG_ID_PSW_SMS_REPLY_TL_ACK_MSG,
       MSG_ID_PSW_TIMER_EXPIRED_MSG,
       MSG_ID_PSW_SMS_PREF_REQ_MSG,
       MSG_ID_PSW_SMS_REL_REQ_MSG,
       MSG_ID_PSW_SMS_TX_REQ_MSG,
       MSG_ID_PSW_SMS_RESEND_TIMER_EXPIRED_MSG,
       MSG_ID_PSW_SMS_MMS_TIMER_EXPIRED_MSG,
       MSG_ID_PSW_SMS_MOREL_TIMER_EXPIRED_MSG,
       MSG_ID_PSW_SMS_TLACK_REQ_MSG,
       MSG_ID_PSW_SMS_RETRY_PERIOD_TIMER_EXPIRED_MSG,

       MSG_ID_PSW_IMS_SMS_READY_MSG,
       MSG_ID_PSW_IMS_SMS_RSP_MSG,
       MSG_ID_PSW_IMS_SMS_NOTIFY_MSG,
       MSG_ID_PSW_SET_MULTI_SMS_MODE_MSG,
       MSG_ID_PSW_SMS_BROADCAST_EXPECTED_MSG,
       MSG_ID_PSW_SMS_MT_DATA_BURST_MSG,
       MSG_ID_PSW_VAL_PREF_VOICE_SERVICEOPTION_SET_MSG,
       MSG_ID_PSW_VAL_REG_RESUME,
       MSG_ID_PSW_SMS_CBS_INFO_CFG,
       MSG_ID_PSW_VAL_SET_SO_SUPPORT_MSG,

#ifdef MTK_CBP_ENCRYPT_VOICE
       MSG_ID_PSW_VAL_ENCRYPT_VOICE_REQ_MSG,
       MSG_ID_PSW_VAL_SET_KS_KEY_REQ_MSG,
       MSG_ID_PSW_VAL_CLEAR_TEMP_KEY_REQ_MSG,
       MSG_ID_PSW_VAL_CANCEL_CIPHER_SMS_SEND_REQ_MSG,
#endif

       /* from DBM */
       MSG_ID_PSW_DBM_DATA_NAM_MSG,
       MSG_ID_PSW_DBM_DATA_NAM_WRITE_ACK_MSG,
       MSG_ID_PSW_DBM_DATA_MSG,
       MSG_ID_PSW_DBM_DATA_WRITE_ACK_MSG,
       MSG_ID_PSW_DBM_FLUSH_ACK_MSG,
       MSG_ID_PSW_DBM_DATA_PRL_MSG,
       MSG_ID_PSW_DBM_DATA_PRL_WRITE_MSG,
       MSG_ID_PSW_DBM_DATA_MS_CAP_DB_MSG,
       MSG_ID_PSW_DBM_DATA_MS_CAP_DB_WRITE_ACK_MSG,
       MSG_ID_PSW_DBM_DATA_MISC_MSG,
       MSG_ID_PSW_NVM_CHANGED_BY_ETS_MSG,
       MSG_ID_PSW_NAM_UNLOCK_ACK_MSG,
       MSG_ID_PSW_DBM_DATA_MISC_WRITE_ACK_MSG,
       MSG_ID_PSW_DBM_SECURE_DATA_WRITE_ACK_MSG,
       MSG_ID_PSW_DBM_SECURE_DATA_MSG,
       MSG_ID_PSW_GET_NAM_MSG,
       MSG_ID_PSW_NAM_CHANGED_MSG,
       MSG_ID_PSW_DBM_INIT_MSG,

       /* from R-UIM */
       MSG_ID_PSW_UIM_GET_NAM_DATA_MSG,
       MSG_ID_PSW_UIM_GET_UIM_MEID_FEATURE_MSG,
       MSG_ID_PSW_UIM_UPDATE_NAM_DATA_MSG,
       MSG_ID_PSW_UIM_STORE_ESN_MSG,
       MSG_ID_PSW_UIM_DATA_PRL_MSG,
       MSG_ID_PSW_UIM_BS_CHALLENGE_ACK_MSG,
       MSG_ID_PSW_UIM_CONFIRM_SSD_ACK_MSG,
       MSG_ID_PSW_UIM_RUN_CAVE_ACK_MSG,
       MSG_ID_PSW_UIM_GENERATE_KEY_VPM_ACK_MSG,
       MSG_ID_PSW_UIM_STATUS_NOTIFY_MSG,
       MSG_ID_PSW_UIM_DATA_OTAFEATURE_MSG,
       MSG_ID_PSW_UIM_MS_KEY_REQUEST_ACK_MSG,
       MSG_ID_PSW_UIM_KEY_GENERATION_REQUEST_ACK_MSG,
       MSG_ID_PSW_UIM_COMMIT_ACK_MSG,
       MSG_ID_PSW_UIM_VALIDATE_ACK_MSG,
       MSG_ID_PSW_UIM_CONFIGURATION_REQUEST_ACK_MSG,
       MSG_ID_PSW_UIM_DOWNLOAD_REQUEST_ACK_MSG,
       MSG_ID_PSW_UIM_SSPR_CONFIGURATION_REQUEST_ACK_MSG,
       MSG_ID_PSW_UIM_SSPR_DOWNLOAD_REQUEST_ACK_MSG,
       MSG_ID_PSW_UIM_OTAPA_REQUEST_ACK_MSG,
       MSG_ID_PSW_UIM_UPDATE_BINARY_ACK_MSG,
       MSG_ID_PSW_UIM_OTA_RUN_CAVE_ACK_MSG,
       MSG_ID_PSW_UIM_STORE_MECONFIG_MSG,
       MSG_ID_PSW_UIM_SMS_CAP_MSG,
       /* from RLP */
       MSG_ID_PSW_DATA_BUFFER_STATUS_MSG,

       /* from ets or generic PS interfaces */
       MSG_ID_PSW_ACCESS_SIGNAL_ETS_MSG,
       MSG_ID_PSW_TEST_MODE_TIMERS_USED_MSG,
       MSG_ID_PSW_UNIT_TEST_REVERSE_SIG_MSG,
       MSG_ID_PSW_SET_IRAT_PARAM_MSG,

       MSG_ID_PSW_ENGINE_TEST_MODE_MSG,
       MSG_ID_PSW_STATUS_REQUEST_MSG,
       MSG_ID_PSW_PHONE_STATE_MSG,
       MSG_ID_PSW_INIT_NAM_NOT_PROVISIONED_MSG,
       MSG_ID_PSW_INIT_NAM_ALREADY_PROVISIONED_MSG,

       MSG_ID_PSW_INIT_MS_CAP_DB_MSG,
       MSG_ID_PSW_HSPD_ACTIVE_CONTROL_HOLD_MSG,
       MSG_ID_PSW_RSCH_REQUEST_MSG,
       MSG_ID_PSW_GET_P_REV_IN_USE_MSG,
       MSG_ID_PSW_CLEAR_MRU_MSG,
       MSG_ID_PSW_GET_ACTIVE_NAM_MSG,
       MSG_ID_PSW_SELECT_ACTIVE_NAM_MSG,
       MSG_ID_PSW_FORCE_ANALOG_MODE_MSG,
       MSG_ID_PSW_ENTER_AKEY_MSG,
       MSG_ID_PSW_SET_ACCESS_HO_PARAMETERS_MSG,
       MSG_ID_PSW_DEBUG_SCREEN_INFO_REQUEST,
       MSG_ID_PSW_DEBUG_PILOT_STRENGTH_INFO_REQUEST,
       MSG_ID_PSW_DEBUG_SCRN_LMD_RSP_MSG,
       MSG_ID_PSW_DEBUG_SCRN_L1D_RSP_MSG,
       MSG_ID_PSW_EXIT_EMERGENCY_MODE_MSG,
       MSG_ID_PSW_GET_GPS_DEBUG_INFO_MSG,
       MSG_ID_PSW_SET_MOBILE_ID_MSG,
       MSG_ID_PSW_GET_MOBILE_ID_MSG,
       MSG_ID_PSW_CL1TST_SET_MOBILE_ID_MSG,
       MSG_ID_PSW_CL1TST_GET_MOBILE_ID_MSG,

       MSG_ID_PSW_OTTS_TIMER_SIMULATION,
       MSG_ID_PSW_HLW_MIP_KEYS_UPDATE_MSG,
       MSG_ID_PSW_READ_RAW_IMSI_MSG,
       MSG_ID_PSW_WRITE_RAW_IMSI_MSG,
       MSG_ID_PSW_SLOTTED_VETO_MSG,
       MSG_ID_PSW_SET_MIP_PASSWORD_MSG,
       MSG_ID_PSW_GET_MIP_KEYS_MSG,
       MSG_ID_PSW_SET_SIP_PASSWORD_MSG,
       MSG_ID_PSW_GET_SIP_PASSWORD_MSG,
       MSG_ID_PSW_SET_SPC_MSG,
       MSG_ID_PSW_GET_SPC_MSG,
       MSG_ID_PSW_GET_SSD_MSG,
       MSG_ID_PSW_INIT_SECURE_DB_MSG,
       MSG_ID_PSW_GET_CP_BC_TO_CDMA_BC_MSG,
       MSG_ID_PSW_BAND_SUPPORTED_QUERY_RSP_MSG,
       MSG_ID_PSW_SET_FLY_MODE_ENABLE_MSG,
       MSG_ID_PSW_ENABLE_PRL_MSG,
       MSG_ID_PSW_SET_PARM_MSG,
       MSG_ID_PSW_GET_PARM_MSG,
       MSG_ID_PSW_WRITE_RAW_MDN_MSG,
       MSG_ID_PSW_TA_TIMER_EXPIRED_MSG,
       MSG_ID_PSW_DATA_CALL_ANSWER_MSG,
       MSG_ID_PSW_UICC_FACTORY_MODE_MSG,
       MSG_ID_PSW_VAL_PILOT_PWR_ACK_MSG,

       MSG_ID_PSW_DS_CALL_REL_MSG,
       MSG_ID_PSW_PS_CALL_REL_MSG,
       MSG_ID_PSW_LS_CALL_REL_MSG,
       MSG_ID_PSW_DS_ENABLE_MSG,
       MSG_ID_PSW_PS_DORMANT_REQ_MSG,
       MSG_ID_PSW_DATA_PREF_REQ_MSG,
       MSG_ID_PSW_VS_PREF_REQ_MSG,
       MSG_ID_PSW_LS_PREF_REQ_MSG,
       MSG_ID_PSW_VS_SWITCH_SO_MSG,
       MSG_ID_PSW_VS_DS_PREARANG_MSG,
       MSG_ID_PSW_SET_SERVICE_CONFIG_MSG,
       MSG_ID_PSW_SET_PKZID_HYSTER_TMR_MSG,
       MSG_ID_PSW_INIT_PSW_MISC_DB_MSG,
       MSG_ID_PSW_CUSTOM_LOCK_FEATURE_REG,
       MSG_ID_PSW_CUSTOM_LOCK_TRIGGER,
       MSG_ID_PSW_PS_SUSPEND_REQ_MSG,
       MSG_ID_PSW_PS_RESUME_REQ_MSG,

       /* System Selection Messages */
       MSG_ID_PSW_CSS_SELECT_RSP_MSG,
       MSG_ID_PSW_CSS_VALIDATE_RSP_MSG,
       MSG_ID_PSW_CSS_SYS_ACQ_REQ_MSG,
       MSG_ID_PSW_CSS_ACQ_ABORT_REQ_MSG,
       MSG_ID_PSW_CSS_OOSA_SLEEP_REQ_MSG,
       MSG_ID_PSW_CSS_OOSA_CONT_SLEEP_REQ_MSG,/*used for continuous sleep cmd after OOSA timer expired*/
       MSG_ID_PSW_CSS_OOSA_WAKEUP_REQ_MSG,
       MSG_ID_PSW_CSS_CONN_START_CNF_MSG,
       MSG_ID_PSW_CSS_OTASP_SCAN_FINISHED_MSG,
       MSG_ID_PSW_CSS_INDICATE_IN_SERVICE_MSG,
       MSG_ID_PSW_CSS_SET_EMERGENCY_CALLBACK_MODE_MSG,
       MSG_ID_PSW_NOTIFY_SRV_STATUS_TO_UPPER_LAYER_MSG,
       MSG_ID_PSW_CSS_END_E911_CALL_REQ_MSG,

       MSG_ID_PSW_CSS_VAL_SYNC_RSP_MSG,
       MSG_ID_PSW_SET_LOST_SCAN_PING_FREQUENCY_MSG,
       MSG_ID_PSW_IRAT_MCC_REQ,
       MSG_ID_PSW_IRAT_CUR_SYS_MEAS_REQ,
       MSG_ID_PSW_IRAT_RAT_SIG_MON_REQ,
       MSG_ID_PSW_IRAT_1X_REG_REQ,

       /* OTASP IS683 */
       MSG_ID_PSW_OTASP_RCVD_MSG,
       MSG_ID_PSW_OTASP_REL_MSG,
       MSG_ID_PSW_OTASP_TX_REQ_MSG,
       MSG_ID_PSW_OTASP_SO_PREF_MSG,
       MSG_ID_PSW_EXP_MOD_MS_RESULT_MSG,
       MSG_ID_PSW_EXP_MOD_BS_RESULT_MSG,
       MSG_ID_PSW_FILL_SSPR_RSP_MSG,
       MSG_ID_PSW_IOTA_IS683_MSG,
       MSG_ID_PSW_IOTA_PRL_MSG,
       MSG_ID_PSW_OTA_SPL_UNLOCK_FAIL_MSG,
       MSG_ID_PSW_OTA_SET_POWER_UP_MODE_MSG,
       MSG_ID_PSW_VERIFY_SPC_MSG,

       /* IS801 Location Services */
       MSG_ID_PSW_POS_AFLT_PPM_REQ_MSG,
       MSG_ID_PSW_POS_AFLT_MEASUREMENTS_MSG,
       MSG_ID_PSW_POS_AFLT_ACK_ABORT_MSG,
       MSG_ID_PSW_POS_AFLT_ABORT_REQ_MSG,
       MSG_ID_PSW_IS801_TCPB_REV_DATA_RESP_INFO_MSG,
       MSG_ID_PSW_IS801_TCPB_FWD_DATA_RESP_INFO_MSG,
       MSG_ID_PSW_IS801_SESSION_START_MSG ,
       MSG_ID_PSW_IS801_TCP_CONN_STATUS_MSG,
       MSG_ID_PSW_IS801_RESET_ASSIST_MSG,
       MSG_ID_PSW_LOC_START_MODE_SET_MSG,
       MSG_ID_PSW_LOC_FIX_MODE_GET_MSG,

       MSG_ID_PSW_IS801_MS_CANCEL_REQ_MSG,
       MSG_ID_PSW_POS_REJECT_MSG,
       MSG_ID_PSW_IS801_EPH_ALM_TIME_MSG,
       MSG_ID_PSW_IS801_MSS_DONE_MSG,
       MSG_ID_PSW_IS801_AFLT_INFO_GET_MSG,
       MSG_ID_PSW_LOC_PREF_REQ_MSG,
       MSG_ID_PSW_PDE_SESSION_ABORT_REQ_MSG,
       MSG_ID_PSW_PDE_PSEUDORANGE_MSMT_RSP_MSG,
       MSG_ID_PSW_PDE_SESSION_END_RSP_MSG,
       MSG_ID_PSW_PDE_GPS_INOP_MSG,
       MSG_ID_PSW_GPS_ENABLE_REPORTS_MSG,
       MSG_ID_PSW_TEST_LOC_PDDM_MSG,
       MSG_ID_PSW_TEST_POWER_CONTROL_MSG,
       MSG_ID_PSW_L1D_ALTERNATE_PILOTS_MSG,
       MSG_ID_PSW_LOCATION_SVC_CFG_MSG,
       MSG_ID_PSW_IS801_RESTART_FIX_MSG,
       /*MS-Based*/
       MSG_ID_PSW_ASSIST_REQ_MSG,
       MSG_ID_PSW_GPS_NMEA_STREAM_MSG,
       MSG_ID_PSW_IS801_NMEA_SETTING_MSG,
       MSG_ID_PSW_IS801_MPC_CONN_MSG,
       MSG_ID_PSW_IS801_GET_SECTOR_INFO_MSG,
       MSG_ID_PSW_LOC_STATE_CHANGE_ETS_TEST_CMD,
       MSG_ID_PSW_IS801_PPM_TIMER_EXP_MSG,
       MSG_ID_PSW_IS801_SESS_TIMER_EXP_MSG,
       MSG_ID_PSW_IS801_PRM_TIMER_EXP_MSG,
       MSG_ID_PSW_IS801_PREF_RESP_QUAL_TIMER_EXP_MSG,
       MSG_ID_PSW_IS801_OUT_REQ_TIMER_EXP_MSG,
       /****MS-Based*********/
       /*From LEC*/
       MSG_ID_PSW_LEC_LOC_RSP_MSG,
       MSG_ID_PSW_GPS_READY_REQ_MSG,
       MSG_ID_PSW_GPS_READY_MSG,
       MSG_ID_PSW_GPS_SIXTY_TIMER_MSG,
       MSG_ID_PSW_GET_TRANSMIT_INFO_MSG,
       MSG_ID_PSW_SET_TRANSMIT_INFO_MSG,
       MSG_ID_PSW_SYSTEM_READY_REQ_MSG,
       MSG_ID_PSW_IS801_CUSTOMER_SETTING_MSG,
       MSG_ID_PSW_LEC_SESSION_END_RSP_MSG,

       /* AMPS related message ID's */
       MSG_ID_PSW_AMPS_BB_IND_TX_STAT_MSG,
       MSG_ID_PSW_AMPS_BB_IND_CHAN_FORMAT_MSG,
       MSG_ID_PSW_AMPS_BB_IND_SAT_CC_MSG,
       MSG_ID_PSW_AMPS_BB_IND_FOCC_DATA_MSG,
       MSG_ID_PSW_AMPS_BB_IND_FVC_DATA_MSG,
       MSG_ID_PSW_AMPS_RELAY_RADIO_TUNE_STAT_MSG,
       MSG_ID_PSW_AMPS_RELAY_RADIO_FSU_LOCK_MSG,
       MSG_ID_PSW_AMPS_RELAY_RADIO_RSSI_VAL_MSG,
       MSG_ID_PSW_AMPS_RELAY_RADIO_CARRIER_STAT_MSG,
       MSG_ID_PSW_AMPS_RELAY_RADIO_POWER_LVL_MSG,
       MSG_ID_PSW_AMPS_RELAY_RADIO_AFC_COMPLETE_MSG,
       MSG_ID_PSW_AMPS_CP_RQ_ENABLE_MSG,
       MSG_ID_PSW_AMPS_CP_RQ_POWER_DOWN_MSG,
       MSG_ID_PSW_AMPS_CP_RQ_CALL_INITIATE_MSG,
       MSG_ID_PSW_AMPS_CP_RQ_CALL_ANSWER_MSG,
       MSG_ID_PSW_AMPS_CP_RQ_CALL_HANGUP_MSG,
       MSG_ID_PSW_AMPS_AUDIO_VOICE_MSG,
       MSG_ID_PSW_AMPS_READ_DATA_ACK_MSG,
       MSG_ID_PSW_AMPS_POWER_MSG,
       MSG_ID_PSW_AMPS_WBIOS_INIT_COMPLETE_MSG,
       MSG_ID_PSW_AMPS_SET_RSSI_TH_MSG,
       MSG_ID_PSW_AMPS_WORD_SYNC_RSP_MSG,

       MSG_ID_PSW_GPS_FRAME_SYNC_DONE_MSG,
       MSG_ID_PSE_LEC_CDMA_SYSTEM_REQ_MSG,
       MSG_ID_PSW_USERMODE_MSG,
       MSG_ID_PSW_TESTMODE_MSG,
       MSG_ID_PSW_LTE_MSG,
       MSG_ID_PSW_NST_POWERUP_MSG,
       MSG_ID_PSW_NST_TCH_FER_CFG_MSG,
       MSG_ID_PSW_NST_TX_PWR_MEAS_CFG_MSG,
       MSG_ID_PSW_NST_RX_PWR_MEAS_CFG_MSG,
       MSG_ID_PSW_NST_TRANSMIT_TCH_MSG,
       MSG_ID_PSW_NST_EXIT_TEST_MODE_MSG,
       MSG_ID_PSW_NST_LIST_SET_MSG,

       MSG_ID_PSW_NST_RX_PWR_REQ_MSG,
       MSG_ID_L1D_NST_RX_PWR_CNF_MSG,
       MSG_ID_PSW_NST_TX_PWR_LEVEL_SET_MSG,

       MSG_ID_PSW_SET_EMERGENCY_CARD_INIT_MSG,
       MSG_ID_PSW_MANUAL_AVOID_NETWORK_MSG,
       MSG_ID_PSW_CSFB_CDMA2000PARM_MSG,
       MSG_ID_PSW_CSFB_SIB8_PARM_MSG,
       MSG_ID_PSW_CSFB_GCSNA_DL_MSG,
       MSG_ID_PSW_CSFB_MEAS_REQ_MSG,
       MSG_ID_PSW_CSFB_REDIRECT_MSG,
       MSG_ID_PSW_CSFB_HO_EUTRA_PREP_MSG,
       MSG_ID_PSW_CSFB_MOBFROM_EUTRA_MSG,
       MSG_ID_PSW_CSFB_SERVICE_REJECT_MSG,
       MSG_ID_PSW_ANTENNA_CFG_MSG,
       MSG_ID_PSW_CSFB_GET_STATUS_MSG,

       MSG_ID_PSW_HLP_DORMANT_CNF_MSG,
       MSG_ID_PSW_HLP_DRS_UPDATE_IND_MSG,

       MSG_ID_PSW_CSS_RSVAS_SUSPEND_CNF_MSG,
       MSG_ID_PSW_CSS_RSVAS_DO_VRTL_SUSP_CNF_MSG,
       MSG_ID_PSW_RSVAS_VIRTUAL_SUSPEND_REQ_MSG,
       MSG_ID_PSW_RSVAS_RESUME_REQ_MSG,
       MSG_ID_PSW_RSVAS_OCCUPY_IND_MSG,

       MSG_ID_RSVAS_CAS_SERVICE_RES_OCCUPY_IND,
       MSG_ID_RSVAS_CAS_SUSPEND_SERVICE_REQ,
       MSG_ID_RSVAS_CAS_RESUME_SERVICE_REQ,
       MSG_ID_RSVAS_CAS_ABORT_SERVICE_REQ,
       MSG_ID_RSVAS_CAS_ABORT_SERVICE_COMPLETE_IND,
       MSG_ID_RSVAS_CAS_VIRTUAL_SUSPEND_SERVICE_REQ,
       MSG_ID_RSVAS_CAS_VIRTUAL_SUSPEND_SERVICE_COMPLETE_IND,
       MSG_ID_RSVAS_CAS_VIRTUAL_RESUME_SERVICE_REQ,
       MSG_ID_C2K_LTE_CSFB_CNF,
       MSG_ID_C2K_LTE_CSFB_STOP_CNF,

       MSG_ID_PSW_IDP_RSVAS_SERVICE_OCCUPY_REQ_MSG,
       MSG_ID_PSW_IDP_RSVAS_SERVICE_RELEASE_REQ_MSG,
       MSG_ID_PSW_C2K_RSVAS_OCCUPY_IND_MSG,
       MSG_ID_PSW_C2K_SIM_INDEX_MSG,

       MSG_ID_PSW_SEND_SMS_CONFIRM_MSG,
       MSG_ID_PSW_SEND_SBP_CONFIG_MSG,
       MSG_ID_PSW_SMS_WAIT_L3ACK_TIMER_EXPIRED_MSG,
       MSG_ID_PSW_SMS_WAIT_RSP_TIMER_EXPIRED_MSG,
       MSG_ID_PSW_STARTUP_SIGNAL,
       MSG_ID_PSW_STARTUP_SIGNAL2,
       MSG_ID_PSW_UIM_RSP_TIMEOUT_MSG,
       MSG_ID_PSW_UIM_OTA_RSP_TIMEOUT_MSG,
       /* PSW UT */
       MSG_ID_RSVAS_CAS_OCCUPY_SERVICE_REQ,
       MSG_ID_RSVAS_CAS_RELEASE_SERVICE_REQ,
       MSG_ID_RSVAS_CAS_TRANSFER_SERVICE_REQ,

       /* SLT msg */
       MSG_ID_PSW_L1D_SLT_TX_VERIFY_IND_MSG,
       MSG_ID_PSW_1X_SLT_VERIFY_RESULT_MSG,
       MSG_ID_PSW_DO_SLT_VERIFY_RESULT_MSG,

#if !defined(__GEMINI__)
       /* Fix build error when GMINI disabled, as in L1S load */
       MSG_ID_RSVAS_CAS_ABORT_SERVICE_CNF,
       MSG_ID_RSVAS_CAS_SUSPEND_SERVICE_CNF,
       MSG_ID_RSVAS_CAS_VIRTUAL_SUSPEND_SERVICE_CNF,
       MSG_ID_RSVAS_CAS_PROTECT_CS_SERVICE_REQ,
       MSG_ID_CSS_RSVAC_FREQUENCY_SCAN_START_REQ,
       MSG_ID_CSS_RSVAC_FREQUENCY_SCAN_MODIFY_REQ,
       MSG_ID_CSS_RSVAC_FREQUENCY_SCAN_STOP_REQ,
#endif

	   /* OTA UT */
	   MSG_ID_PSW_OTASPPA_CONN_IND_MSG,
	   MSG_ID_PSW_OTASPPA_ORIG_IND_MSG,
	   MSG_ID_PSW_OTASPPA_DISCONN_IND_MSG,
	   MSG_ID_PSW_OTASPPA_MSG_CONFIRM_IND_MSG,
	   MSG_ID_PSW_OTASPPA_RECV_MSG_IND_MSG,
	   MSG_ID_PSW_OTASPPA_SEND_MSG_REQ_MSG,

       /* new message id in 93*/
       MSG_ID_PSW_L1D_INIT_CNF_MSG,
       MSG_ID_PSW_STOP_PSC_DORMANT_TIMER_MSG,
       MSG_ID_PSW_HLP_RSVAS_ABORT_CNF_MSG,
       MSG_ID_PSW_VAL_SET_DDTM_MSG,

#ifdef MTK_PLT_ON_PC_UT
	   MSG_ID_PSW_SCC_IND_MSG,
	   MSG_ID_PSW_SCC_REQ_MSG,
	   MSG_ID_SCC_UT_DUMMY_REQ,
	   MSG_ID_SCC_UT_DUMMY_CNF,
#endif
       MSG_ID_PSW_VAL_FLIGHT_MODE_MSG,
       MSG_ID_PSW_CSS_FORCE_POWER_DOWN_MSG,
       MSG_ID_PSW_CSS_DEAC_IND,
	   MSG_ID_PSW_SET_GPS_FLOW_MSG,
       MSG_ID_PSW_TST_INJECT_STRING,
       MSG_ID_PSW_VAL_REPORT_MODE_LWG_MSG,
       MSG_ID_PSW_NUM_MSG_IDS,

MODULE_MSG_END( MSG_ID_CPSW_CODE_TAIL )


#endif
