#ifndef L1TRC_DHL_L1_DEF_H
#define L1TRC_DHL_L1_DEF_H

/******************************/
/* String category definition */
/******************************/


/****************************/
/* Message macro definition */
/****************************/
#include "L1Trc.h"
#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define UMTS_3G_GEMINI_TIME(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0000,0x0000);\
			TRC_OUTPUT_8_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define UMTS_3G_GEMINI_TIME_HW_COND(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v5,v5);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0000,0x0000);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v5,v5);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define UMTS_3G_GEMINI_TIME(v1, v2, v3, v4, v5)
	#define UMTS_3G_GEMINI_TIME_HW_COND(v1, v2, v3, v4, v5)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define UMTS_3G_TIME(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0100,0x0100);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define UMTS_3G_TIME_HW_COND(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0100,0x0100);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define UMTS_3G_TIME(v1, v2, v3, v4)
	#define UMTS_3G_TIME_HW_COND(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define UMTS_2G_GEMINI_TIME(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0200,0x0200);\
			TRC_OUTPUT_8_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_24_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define UMTS_2G_GEMINI_TIME_HW_COND(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0200,0x0200);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_24_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define UMTS_2G_GEMINI_TIME(v1, v2, v3, v4)
	#define UMTS_2G_GEMINI_TIME_HW_COND(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define UMTS_2G_TIME(v1, v2, v3) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0300,0x0300);\
			TRC_OUTPUT_24_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define UMTS_2G_TIME_HW_COND(v1, v2, v3) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0300,0x0300);\
			TRC_OUTPUT_24_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define UMTS_2G_TIME(v1, v2, v3)
	#define UMTS_2G_TIME_HW_COND(v1, v2, v3)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define UMTS_2G_HANDOVER_TIME(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0400,0x0400);\
			TRC_OUTPUT_24_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define UMTS_2G_HANDOVER_TIME_HW_COND(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0400,0x0400);\
			TRC_OUTPUT_24_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define UMTS_2G_HANDOVER_TIME(v1, v2)
	#define UMTS_2G_HANDOVER_TIME_HW_COND(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define UMTS_3G_HANDOVER_TIME(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0500,0x0500);\
			TRC_OUTPUT_24_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define UMTS_3G_HANDOVER_TIME_HW_COND(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0500,0x0500);\
			TRC_OUTPUT_24_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define UMTS_3G_HANDOVER_TIME(v1, v2)
	#define UMTS_3G_HANDOVER_TIME_HW_COND(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define LTE_4G_TIME(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0600,0x0600);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_16_LAST_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define LTE_4G_TIME_HW_COND(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0600,0x0600);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_16_LAST_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define LTE_4G_TIME(v1, v2, v3, v4)
	#define LTE_4G_TIME_HW_COND(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define LTE_4G_TIME_2(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0700,0x0700);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define LTE_4G_TIME_2_HW_COND(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v5,v5);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0700,0x0700);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v5,v5);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define LTE_4G_TIME_2(v1, v2, v3, v4, v5)
	#define LTE_4G_TIME_2_HW_COND(v1, v2, v3, v4, v5)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define LTE_4G_L2_TIME(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x0800,0x0800);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define LTE_4G_L2_TIME(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_TRC_REDUMP() do {\
		{\
			TRC_START_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x02);\
			TRC_START_FILL_L1_EX_FORCE_L1();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_EX_FORCE_L1(0x0900,0x0900);\
			TRC_END_FILL_L1_EX_FORCE_L1();\
			TRC_END_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x02);\
		}\
	} while(0)
#else
	#define L1_TRC_REDUMP()
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define LTE_4G_TIME_GFRC(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0A00,0x0A00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_16_LAST_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define LTE_4G_TIME_GFRC_HW_COND(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0A00,0x0A00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_16_LAST_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define LTE_4G_TIME_GFRC(v1, v2, v3, v4)
	#define LTE_4G_TIME_GFRC_HW_COND(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define LTE_4G_TIME_MET_RTOS(v1, v2, v3) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x04);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0B00,0x0B00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x04);\
		}\
	} while(0)
	#define LTE_4G_TIME_MET_RTOS_HW_COND(v1, v2, v3) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x04);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0B00,0x0B00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x04);\
		}\
	} while(0)
#else
	#define LTE_4G_TIME_MET_RTOS(v1, v2, v3)
	#define LTE_4G_TIME_MET_RTOS_HW_COND(v1, v2, v3)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DHL_HIGH_RESOLUTION_TIME(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0C00,0x0C00);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define DHL_HIGH_RESOLUTION_TIME_HW_COND(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0C00,0x0C00);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define DHL_HIGH_RESOLUTION_TIME(v1, v2)
	#define DHL_HIGH_RESOLUTION_TIME_HW_COND(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DHL_LOW_RESOLUTION_TIME(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0D00,0x0D00);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define DHL_LOW_RESOLUTION_TIME_HW_COND(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0D00,0x0D00);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define DHL_LOW_RESOLUTION_TIME(v1)
	#define DHL_LOW_RESOLUTION_TIME_HW_COND(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DHL_PERIODIC_TIME(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0E00,0x0E00);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define DHL_PERIODIC_TIME_HW_COND(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0E00,0x0E00);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define DHL_PERIODIC_TIME(v1)
	#define DHL_PERIODIC_TIME_HW_COND(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DHL_INCREMENTAL_TIME(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0F00,0x0F00);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define DHL_INCREMENTAL_TIME_HW_COND(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x0F00,0x0F00);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define DHL_INCREMENTAL_TIME(v1)
	#define DHL_INCREMENTAL_TIME_HW_COND(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define LTE_4G_TIME_MET_WCLK(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x04);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1000,0x1000);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x04);\
		}\
	} while(0)
	#define LTE_4G_TIME_MET_WCLK_HW_COND(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x04);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x1000,0x1000);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x04);\
		}\
	} while(0)
#else
	#define LTE_4G_TIME_MET_WCLK(v1, v2, v3, v4)
	#define LTE_4G_TIME_MET_WCLK_HW_COND(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define C2K_1X_TIME(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1100,0x1100);\
			TRC_OUTPUT_8_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_8_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define C2K_1X_TIME_HW_COND(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v5,v5);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x1100,0x1100);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v5,v5);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define C2K_1X_TIME(v1, v2, v3, v4, v5)
	#define C2K_1X_TIME_HW_COND(v1, v2, v3, v4, v5)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define C2K_DO_TIME(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1200,0x1200);\
			TRC_OUTPUT_8_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_8_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define C2K_DO_TIME_HW_COND(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v5,v5);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x1200,0x1200);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v5,v5);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define C2K_DO_TIME(v1, v2, v3, v4, v5)
	#define C2K_DO_TIME_HW_COND(v1, v2, v3, v4, v5)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define LTE_4G_TIME_GFRC_2(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1300,0x1300);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
	#define LTE_4G_TIME_GFRC_2_HW_COND(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_HW_COND(cgen_local_v5,v5);\
			TRC_START_FILL_L1_HW_COND();\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_HW_COND(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_HW_COND(0x1300,0x1300);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v2,v2);\
			TRC_OUTPUT_16_MID_WRAPPER_L1_HW_COND(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_HW_COND(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_HW_COND(cgen_local_v5,v5);\
			TRC_END_FILL_L1_HW_COND();\
			TRC_END_FILTER_CHECK_L1_HW_COND(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define LTE_4G_TIME_GFRC_2(v1, v2, v3, v4, v5)
	#define LTE_4G_TIME_GFRC_2_HW_COND(v1, v2, v3, v4, v5)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_TRC_REDUMP() do {\
		{\
			TRC_START_FILTER_CHECK_L1_EX_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x02);\
			TRC_START_FILL_L1_EX_FORCE_L2();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_EX_FORCE_L2(0x1400,0x1400);\
			TRC_END_FILL_L1_EX_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_EX_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x02);\
		}\
	} while(0)
#else
	#define L2_TRC_REDUMP()
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_DHL_DEBUG_TRC1(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1500,0x1500);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_DHL_DEBUG_TRC1(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_DHL_DEBUG_TRC2(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1600,0x1600);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_DHL_DEBUG_TRC2(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_DHL_DEBUG_TRC3(v1, v2, v3) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1700,0x1700);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_DHL_DEBUG_TRC3(v1, v2, v3)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_DHL_DEBUG_TRC4(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1800,0x1800);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_DHL_DEBUG_TRC4(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_DHL_DEBUG_TRC5(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1900,0x1900);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_DHL_DEBUG_TRC5(v1, v2, v3, v4, v5)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_DHL_DEBUG_TRC6(v1, v2, v3, v4, v5, v6) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v6,v6);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v6,v6);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1A00,0x1A00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v6,v6);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_DHL_DEBUG_TRC6(v1, v2, v3, v4, v5, v6)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_DHL_DEBUG_TRC7(v1, v2, v3, v4, v5, v6, v7) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v7,v7);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v7,v7);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1B00,0x1B00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v6,v6);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v7,v7);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_DHL_DEBUG_TRC7(v1, v2, v3, v4, v5, v6, v7)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_DHL_DEBUG_TRC8(v1, v2, v3, v4, v5, v6, v7, v8) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v7,v7);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v8,v8);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v7,v7);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v8,v8);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x1C00,0x1C00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v5,v5);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v6,v6);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v7,v7);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v8,v8);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_DHL_DEBUG_TRC8(v1, v2, v3, v4, v5, v6, v7, v8)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_DHL_DEBUG_TRC1(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x1D00,0x1D00);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_DHL_DEBUG_TRC1(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_DHL_DEBUG_TRC2(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x1E00,0x1E00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_DHL_DEBUG_TRC2(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_DHL_DEBUG_TRC3(v1, v2, v3) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x1F00,0x1F00);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_DHL_DEBUG_TRC3(v1, v2, v3)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_DHL_DEBUG_TRC4(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x2000,0x2000);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_DHL_DEBUG_TRC4(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_DHL_DEBUG_TRC5(v1, v2, v3, v4, v5) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x2100,0x2100);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_DHL_DEBUG_TRC5(v1, v2, v3, v4, v5)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_DHL_DEBUG_TRC6(v1, v2, v3, v4, v5, v6) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x2200,0x2200);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_DHL_DEBUG_TRC6(v1, v2, v3, v4, v5, v6)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_DHL_DEBUG_TRC7(v1, v2, v3, v4, v5, v6, v7) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v7,v7);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v7,v7);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x2300,0x2300);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v7,v7);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_DHL_DEBUG_TRC7(v1, v2, v3, v4, v5, v6, v7)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_DHL_DEBUG_TRC8(v1, v2, v3, v4, v5, v6, v7, v8) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v7,v7);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v8,v8);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v7,v7);\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v8,v8);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x2400,0x2400);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v3,v3);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v4,v4);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v5,v5);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v6,v6);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_FORCE_L2(cgen_local_v7,v7);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v8,v8);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_DHL_DEBUG_TRC8(v1, v2, v3, v4, v5, v6, v7, v8)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DHL_DEBUGL1_L1_WAKE_INFO(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x08);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x2500,0x2500);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x08);\
		}\
	} while(0)
#else
	#define DHL_DEBUGL1_L1_WAKE_INFO(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DHL_DEBUGL1_L2_WAKE_INFO(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x08);\
			TRC_PREPROCESS_DATA_SECTION1_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_START_FILL_L1_FORCE_L2();\
			TRC_PREPROCESS_DATA_SECTION2_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_FORCE_L2(0x2600,0x2600);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_FORCE_L2(cgen_local_v1,v1);\
			TRC_END_FILL_L1_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x08);\
		}\
	} while(0)
#else
	#define DHL_DEBUGL1_L2_WAKE_INFO(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_TRC_STOP_BEFORE_EE() do {\
		{\
			TRC_START_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_START_FILL_L1_EX_FORCE_L1();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_EX_FORCE_L1(0x2700,0x2700);\
			TRC_END_FILL_L1_EX_FORCE_L1();\
			TRC_END_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L1_TRC_STOP_BEFORE_EE()
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_TRC_STOP_BEFORE_EE() do {\
		{\
			TRC_START_FILTER_CHECK_L1_EX_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
			TRC_START_FILL_L1_EX_FORCE_L2();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_EX_FORCE_L2(0x2800,0x2800);\
			TRC_END_FILL_L1_EX_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_EX_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define L2_TRC_STOP_BEFORE_EE()
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DUMP_COND_L1_TRC_START() do {\
		{\
			TRC_START_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x02);\
			TRC_START_FILL_L1_EX_FORCE_L1();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_EX_FORCE_L1(0x2900,0x2900);\
			TRC_END_FILL_L1_EX_FORCE_L1();\
			TRC_END_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x02);\
		}\
	} while(0)
#else
	#define DUMP_COND_L1_TRC_START()
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DUMP_COND_L1_TRC_END() do {\
		{\
			TRC_START_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x02);\
			TRC_START_FILL_L1_EX_FORCE_L1();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_EX_FORCE_L1(0x2A00,0x2A00);\
			TRC_END_FILL_L1_EX_FORCE_L1();\
			TRC_END_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x02);\
		}\
	} while(0)
#else
	#define DUMP_COND_L1_TRC_END()
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L1_TRC_REDUMP_END() do {\
		{\
			TRC_START_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x02);\
			TRC_START_FILL_L1_EX_FORCE_L1();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_EX_FORCE_L1(0x2B00,0x2B00);\
			TRC_END_FILL_L1_EX_FORCE_L1();\
			TRC_END_FILTER_CHECK_L1_EX_FORCE_L1(DHL_L1_Trace_Filter, 1, 0x02);\
		}\
	} while(0)
#else
	#define L1_TRC_REDUMP_END()
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define L2_TRC_REDUMP_END() do {\
		{\
			TRC_START_FILTER_CHECK_L1_EX_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x02);\
			TRC_START_FILL_L1_EX_FORCE_L2();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_EX_FORCE_L2(0x2C00,0x2C00);\
			TRC_END_FILL_L1_EX_FORCE_L2();\
			TRC_END_FILTER_CHECK_L1_EX_FORCE_L2(DHL_L1_Trace_Filter, 1, 0x02);\
		}\
	} while(0)
#else
	#define L2_TRC_REDUMP_END()
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DHL_DEBUG_ULSP_DSP_LOCK(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x08);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x2D00,0x2D00);\
			TRC_OUTPUT_8_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x08);\
		}\
	} while(0)
#else
	#define DHL_DEBUG_ULSP_DSP_LOCK(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define DHL_DEBUG_ULSP_DSP_UNLOCK(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x08);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x2E00,0x2E00);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(DHL_L1_Trace_Filter, 1, 0x08);\
		}\
	} while(0)
#else
	#define DHL_DEBUG_ULSP_DSP_UNLOCK(v1)
#endif



/*******************************/
/* declaration of filter array */
/*******************************/
EXTERN_TMD_FILTER(unsigned char, DHL_L1_Trace_Filter, 5);
/*************************/
/* Function declarations */
/*************************/
#ifdef L1_CATCHER

void Set_DHL_L1_Filter(unsigned char *setting);

#endif

/************************************/
/* Filter checking API declarations */
/************************************/

#define ChkL1ModFltr_DHL_L1()	(FILTER_CHECK(DHL_L1_Trace_Filter, 0, 1))
#define ChkL1ClsFltr_DHL_L1_L1_Time_Info()	(ChkL1ModFltr_DHL_L1()&&(FILTER_CHECK(DHL_L1_Trace_Filter, 1, 0x01)))
#define ChkL1ClsFltr_DHL_L1_L1_Info()	(ChkL1ModFltr_DHL_L1()&&(FILTER_CHECK(DHL_L1_Trace_Filter, 1, 0x02)))
#define ChkL1ClsFltr_DHL_L1_RTOS_Time_Info()	(ChkL1ModFltr_DHL_L1()&&(FILTER_CHECK(DHL_L1_Trace_Filter, 1, 0x04)))
#define ChkL1ClsFltr_DHL_L1_L1_ULSP_DEBUG()	(ChkL1ModFltr_DHL_L1()&&(FILTER_CHECK(DHL_L1_Trace_Filter, 1, 0x08)))
#define ChkL1MsgFltr_UMTS_3G_GEMINI_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_UMTS_3G_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_UMTS_2G_GEMINI_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_UMTS_2G_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_UMTS_2G_HANDOVER_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_UMTS_3G_HANDOVER_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_LTE_4G_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_LTE_4G_TIME_2()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_LTE_4G_L2_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L1_TRC_REDUMP()	ChkL1ClsFltr_DHL_L1_L1_Info()
#define ChkL1MsgFltr_LTE_4G_TIME_GFRC()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_LTE_4G_TIME_MET_RTOS()	ChkL1ClsFltr_DHL_L1_RTOS_Time_Info()
#define ChkL1MsgFltr_DHL_HIGH_RESOLUTION_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_DHL_LOW_RESOLUTION_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_DHL_PERIODIC_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_DHL_INCREMENTAL_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_LTE_4G_TIME_MET_WCLK()	ChkL1ClsFltr_DHL_L1_RTOS_Time_Info()
#define ChkL1MsgFltr_C2K_1X_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_C2K_DO_TIME()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_LTE_4G_TIME_GFRC_2()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_TRC_REDUMP()	ChkL1ClsFltr_DHL_L1_L1_Info()
#define ChkL1MsgFltr_L1_DHL_DEBUG_TRC1()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L1_DHL_DEBUG_TRC2()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L1_DHL_DEBUG_TRC3()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L1_DHL_DEBUG_TRC4()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L1_DHL_DEBUG_TRC5()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L1_DHL_DEBUG_TRC6()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L1_DHL_DEBUG_TRC7()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L1_DHL_DEBUG_TRC8()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_DHL_DEBUG_TRC1()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_DHL_DEBUG_TRC2()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_DHL_DEBUG_TRC3()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_DHL_DEBUG_TRC4()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_DHL_DEBUG_TRC5()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_DHL_DEBUG_TRC6()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_DHL_DEBUG_TRC7()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_DHL_DEBUG_TRC8()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_DHL_DEBUGL1_L1_WAKE_INFO()	ChkL1ClsFltr_DHL_L1_L1_ULSP_DEBUG()
#define ChkL1MsgFltr_DHL_DEBUGL1_L2_WAKE_INFO()	ChkL1ClsFltr_DHL_L1_L1_ULSP_DEBUG()
#define ChkL1MsgFltr_L1_TRC_STOP_BEFORE_EE()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_L2_TRC_STOP_BEFORE_EE()	ChkL1ClsFltr_DHL_L1_L1_Time_Info()
#define ChkL1MsgFltr_DUMP_COND_L1_TRC_START()	ChkL1ClsFltr_DHL_L1_L1_Info()
#define ChkL1MsgFltr_DUMP_COND_L1_TRC_END()	ChkL1ClsFltr_DHL_L1_L1_Info()
#define ChkL1MsgFltr_L1_TRC_REDUMP_END()	ChkL1ClsFltr_DHL_L1_L1_Info()
#define ChkL1MsgFltr_L2_TRC_REDUMP_END()	ChkL1ClsFltr_DHL_L1_L1_Info()
#define ChkL1MsgFltr_DHL_DEBUG_ULSP_DSP_LOCK()	ChkL1ClsFltr_DHL_L1_L1_ULSP_DEBUG()
#define ChkL1MsgFltr_DHL_DEBUG_ULSP_DSP_UNLOCK()	ChkL1ClsFltr_DHL_L1_L1_ULSP_DEBUG()


#endif
