#ifndef __RXAFC_CMIF_H__
#define __RXAFC_CMIF_H__

#include "reg_access.h"
#include "base_addr_cmif.h"

#define CMIF_RXAFC_REG_BASE                                           (CMIF_RAKE_AFC_OFFSET)
#define CMIF_RXAFC_CON                                                (CMIF_RXAFC_REG_BASE + 0x00000000)
#define CMIF_RXAFC_DCXO_RATIO                                         (CMIF_RXAFC_REG_BASE + 0x00000004)
#define CMIF_RXAFC_FB_RX(i)                                           (CMIF_RXAFC_REG_BASE + 0x00000008 + ((i) * 0x4))
#define CMIF_RXAFC_FB_TX(i)                                           (CMIF_RXAFC_REG_BASE + 0x00000014 + ((i) * 0x4))
#define CMIF_RXAFC_INI_DAC                                            (CMIF_RXAFC_REG_BASE + 0x0000001C)
#define CMIF_RXAFC_INI_PPB_RX(i)                                      (CMIF_RXAFC_REG_BASE + 0x00000020 + ((i) * 0x4))
#define CMIF_RXAFC_INI_PPB_TX(i)                                      (CMIF_RXAFC_REG_BASE + 0x0000002C + ((i) * 0x4))
#define CMIF_RXAFC_DAC_MNT                                            (CMIF_RXAFC_REG_BASE + 0x00000034)
#define CMIF_RXAFC_RXPPB_MNT(i)                                       (CMIF_RXAFC_REG_BASE + 0x00000038 + ((i) * 0x4))
#define CMIF_RXAFC_TXPPB_MNT(i)                                       (CMIF_RXAFC_REG_BASE + 0x00000044 + ((i) * 0x4))
#define CMIF_RXAFC_RXHZ_MNT(i)                                        (CMIF_RXAFC_REG_BASE + 0x0000004C + ((i) * 0x4))
#define CMIF_RXAFC_TXHZ_MNT(i)                                        (CMIF_RXAFC_REG_BASE + 0x00000058 + ((i) * 0x4))
#define CMIF_RXAFC_SW_RST                                             (CMIF_RXAFC_REG_BASE + 0x00000060)
#define CMIF_RXAFC_SIM2_CON                                           (CMIF_RXAFC_REG_BASE + 0x00000064)
#define CMIF_RXAFC_SIM2_FB_RX                                         (CMIF_RXAFC_REG_BASE + 0x00000068)
#define CMIF_RXAFC_SIM2_FB_TX                                         (CMIF_RXAFC_REG_BASE + 0x0000006C)
#define CMIF_RXAFC_SIM2_INI_DAC                                       (CMIF_RXAFC_REG_BASE + 0x00000070)
#define CMIF_RXAFC_SIM2_INI_PPB_RX                                    (CMIF_RXAFC_REG_BASE + 0x00000074)
#define CMIF_RXAFC_SIM2_INI_PPB_TX                                    (CMIF_RXAFC_REG_BASE + 0x00000078)
#define CMIF_RXAFC_SIM2_DAC_MNT                                       (CMIF_RXAFC_REG_BASE + 0x0000007C)
#define CMIF_RXAFC_SIM2_RXPPB_MNT                                     (CMIF_RXAFC_REG_BASE + 0x00000080)
#define CMIF_RXAFC_SIM2_TXPPB_MNT                                     (CMIF_RXAFC_REG_BASE + 0x00000084)
#define CMIF_RXAFC_SIM2_RXHZ_MNT                                      (CMIF_RXAFC_REG_BASE + 0x00000088)
#define CMIF_RXAFC_SIM2_TXHZ_MNT                                      (CMIF_RXAFC_REG_BASE + 0x0000008C)

#define M_CMIF_RXAFC_CON_RD()                                         REG_READ(CMIF_RXAFC_CON)
#define M_CMIF_RXAFC_DCXO_RATIO_RD()                                  REG_READ(CMIF_RXAFC_DCXO_RATIO)
#define M_CMIF_RXAFC_FB_RX_RD(i)                                      REG_READ(CMIF_RXAFC_FB_RX(i))
#define M_CMIF_RXAFC_FB_TX_RD(i)                                      REG_READ(CMIF_RXAFC_FB_TX(i))
#define M_CMIF_RXAFC_INI_DAC_RD()                                     REG_READ(CMIF_RXAFC_INI_DAC)
#define M_CMIF_RXAFC_INI_PPB_RX_RD(i)                                 REG_READ(CMIF_RXAFC_INI_PPB_RX(i))
#define M_CMIF_RXAFC_INI_PPB_TX_RD(i)                                 REG_READ(CMIF_RXAFC_INI_PPB_TX(i))
#define M_CMIF_RXAFC_DAC_MNT_RD()                                     REG_READ(CMIF_RXAFC_DAC_MNT)
#define M_CMIF_RXAFC_RXPPB_MNT_RD(i)                                  REG_READ(CMIF_RXAFC_RXPPB_MNT(i))
#define M_CMIF_RXAFC_TXPPB_MNT_RD(i)                                  REG_READ(CMIF_RXAFC_TXPPB_MNT(i))
#define M_CMIF_RXAFC_RXHZ_MNT_RD(i)                                   REG_READ(CMIF_RXAFC_RXHZ_MNT(i))
#define M_CMIF_RXAFC_TXHZ_MNT_RD(i)                                   REG_READ(CMIF_RXAFC_TXHZ_MNT(i))
#define M_CMIF_RXAFC_SW_RST_RD()                                      REG_READ(CMIF_RXAFC_SW_RST)
#define M_CMIF_RXAFC_SIM2_CON_RD()                                    REG_READ(CMIF_RXAFC_SIM2_CON)
#define M_CMIF_RXAFC_SIM2_FB_RX_RD()                                  REG_READ(CMIF_RXAFC_SIM2_FB_RX)
#define M_CMIF_RXAFC_SIM2_FB_TX_RD()                                  REG_READ(CMIF_RXAFC_SIM2_FB_TX)
#define M_CMIF_RXAFC_SIM2_INI_DAC_RD()                                REG_READ(CMIF_RXAFC_SIM2_INI_DAC)
#define M_CMIF_RXAFC_SIM2_INI_PPB_RX_RD()                             REG_READ(CMIF_RXAFC_SIM2_INI_PPB_RX)
#define M_CMIF_RXAFC_SIM2_INI_PPB_TX_RD()                             REG_READ(CMIF_RXAFC_SIM2_INI_PPB_TX)
#define M_CMIF_RXAFC_SIM2_DAC_MNT_RD()                                REG_READ(CMIF_RXAFC_SIM2_DAC_MNT)
#define M_CMIF_RXAFC_SIM2_RXPPB_MNT_RD()                              REG_READ(CMIF_RXAFC_SIM2_RXPPB_MNT)
#define M_CMIF_RXAFC_SIM2_TXPPB_MNT_RD()                              REG_READ(CMIF_RXAFC_SIM2_TXPPB_MNT)
#define M_CMIF_RXAFC_SIM2_RXHZ_MNT_RD()                               REG_READ(CMIF_RXAFC_SIM2_RXHZ_MNT)
#define M_CMIF_RXAFC_SIM2_TXHZ_MNT_RD()                               REG_READ(CMIF_RXAFC_SIM2_TXHZ_MNT)

#define M_CMIF_RXAFC_CON_WR(reg)                                      REG_WRITE(CMIF_RXAFC_CON, reg)
#define M_CMIF_RXAFC_DCXO_RATIO_WR(reg)                               REG_WRITE(CMIF_RXAFC_DCXO_RATIO, reg)
#define M_CMIF_RXAFC_FB_RX_WR(i, reg)                                 REG_WRITE(CMIF_RXAFC_FB_RX(i), reg)
#define M_CMIF_RXAFC_FB_TX_WR(i, reg)                                 REG_WRITE(CMIF_RXAFC_FB_TX(i), reg)
#define M_CMIF_RXAFC_INI_DAC_WR(reg)                                  REG_WRITE(CMIF_RXAFC_INI_DAC, reg)
#define M_CMIF_RXAFC_INI_PPB_RX_WR(i, reg)                            REG_WRITE(CMIF_RXAFC_INI_PPB_RX(i), reg)
#define M_CMIF_RXAFC_INI_PPB_TX_WR(i, reg)                            REG_WRITE(CMIF_RXAFC_INI_PPB_TX(i), reg)
#define M_CMIF_RXAFC_DAC_MNT_WR(reg)                                  REG_WRITE(CMIF_RXAFC_DAC_MNT, reg)
#define M_CMIF_RXAFC_RXPPB_MNT_WR(i, reg)                             REG_WRITE(CMIF_RXAFC_RXPPB_MNT(i), reg)
#define M_CMIF_RXAFC_TXPPB_MNT_WR(i, reg)                             REG_WRITE(CMIF_RXAFC_TXPPB_MNT(i), reg)
#define M_CMIF_RXAFC_RXHZ_MNT_WR(i, reg)                              REG_WRITE(CMIF_RXAFC_RXHZ_MNT(i), reg)
#define M_CMIF_RXAFC_TXHZ_MNT_WR(i, reg)                              REG_WRITE(CMIF_RXAFC_TXHZ_MNT(i), reg)
#define M_CMIF_RXAFC_SW_RST_WR(reg)                                   REG_WRITE(CMIF_RXAFC_SW_RST, reg)
#define M_CMIF_RXAFC_SIM2_CON_WR(reg)                                 REG_WRITE(CMIF_RXAFC_SIM2_CON, reg)
#define M_CMIF_RXAFC_SIM2_FB_RX_WR(reg)                               REG_WRITE(CMIF_RXAFC_SIM2_FB_RX, reg)
#define M_CMIF_RXAFC_SIM2_FB_TX_WR(reg)                               REG_WRITE(CMIF_RXAFC_SIM2_FB_TX, reg)
#define M_CMIF_RXAFC_SIM2_INI_DAC_WR(reg)                             REG_WRITE(CMIF_RXAFC_SIM2_INI_DAC, reg)
#define M_CMIF_RXAFC_SIM2_INI_PPB_RX_WR(reg)                          REG_WRITE(CMIF_RXAFC_SIM2_INI_PPB_RX, reg)
#define M_CMIF_RXAFC_SIM2_INI_PPB_TX_WR(reg)                          REG_WRITE(CMIF_RXAFC_SIM2_INI_PPB_TX, reg)
#define M_CMIF_RXAFC_SIM2_DAC_MNT_WR(reg)                             REG_WRITE(CMIF_RXAFC_SIM2_DAC_MNT, reg)
#define M_CMIF_RXAFC_SIM2_RXPPB_MNT_WR(reg)                           REG_WRITE(CMIF_RXAFC_SIM2_RXPPB_MNT, reg)
#define M_CMIF_RXAFC_SIM2_TXPPB_MNT_WR(reg)                           REG_WRITE(CMIF_RXAFC_SIM2_TXPPB_MNT, reg)
#define M_CMIF_RXAFC_SIM2_RXHZ_MNT_WR(reg)                            REG_WRITE(CMIF_RXAFC_SIM2_RXHZ_MNT, reg)
#define M_CMIF_RXAFC_SIM2_TXHZ_MNT_WR(reg)                            REG_WRITE(CMIF_RXAFC_SIM2_TXHZ_MNT, reg)

#define CMIF_RXAFC_CON_AFC_MODE_BIT_LSB                               (16)
#define CMIF_RXAFC_CON_AFC_MODE_BIT_WIDTH                             (3)
#define CMIF_RXAFC_CON_AFC_MODE_BIT_MASK                              ((UINT32) (((1<<CMIF_RXAFC_CON_AFC_MODE_BIT_WIDTH)-1) << CMIF_RXAFC_CON_AFC_MODE_BIT_LSB) )
#define CMIF_RXAFC_CON_AFC_MODE_FLD_WR(reg, val)                      (reg |= (val) << CMIF_RXAFC_CON_AFC_MODE_BIT_LSB)
#define CMIF_RXAFC_CON_AFC_MODE_FLD_RD()                              ((M_CMIF_RXAFC_CON_RD() & CMIF_RXAFC_CON_AFC_MODE_BIT_MASK) >> CMIF_RXAFC_CON_AFC_MODE_BIT_LSB)

#define CMIF_RXAFC_CON_DL_EN_TX_BIT_LSB                               (8)
#define CMIF_RXAFC_CON_DL_EN_TX_BIT_WIDTH                             (1)
#define CMIF_RXAFC_CON_DL_EN_TX_BIT_MASK                              ((UINT32) (((1<<CMIF_RXAFC_CON_DL_EN_TX_BIT_WIDTH)-1) << CMIF_RXAFC_CON_DL_EN_TX_BIT_LSB) )
#define CMIF_RXAFC_CON_DL_EN_TX_FLD_WR(reg, val)                      (reg |= (val) << CMIF_RXAFC_CON_DL_EN_TX_BIT_LSB)
#define CMIF_RXAFC_CON_DL_EN_TX_FLD_RD()                              ((M_CMIF_RXAFC_CON_RD() & CMIF_RXAFC_CON_DL_EN_TX_BIT_MASK) >> CMIF_RXAFC_CON_DL_EN_TX_BIT_LSB)

#define CMIF_RXAFC_CON_GPS_ON_BIT_LSB                                 (0)
#define CMIF_RXAFC_CON_GPS_ON_BIT_WIDTH                               (1)
#define CMIF_RXAFC_CON_GPS_ON_BIT_MASK                                ((UINT32) (((1<<CMIF_RXAFC_CON_GPS_ON_BIT_WIDTH)-1) << CMIF_RXAFC_CON_GPS_ON_BIT_LSB) )
#define CMIF_RXAFC_CON_GPS_ON_FLD_WR(reg, val)                        (reg |= (val) << CMIF_RXAFC_CON_GPS_ON_BIT_LSB)
#define CMIF_RXAFC_CON_GPS_ON_FLD_RD()                                ((M_CMIF_RXAFC_CON_RD() & CMIF_RXAFC_CON_GPS_ON_BIT_MASK) >> CMIF_RXAFC_CON_GPS_ON_BIT_LSB)

#define CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_BIT_LSB                   (0)
#define CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_BIT_WIDTH                 (16)
#define CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_BIT_MASK                  ((UINT32) (((1<<CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_BIT_WIDTH)-1) << CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_BIT_LSB) )
#define CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_FLD_WR(reg, val)          (reg |= (val) << CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_BIT_LSB)
#define CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_FLD_RD()                  ((M_CMIF_RXAFC_DCXO_RATIO_RD() & CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_BIT_MASK) >> CMIF_RXAFC_DCXO_RATIO_RATIO_PPB2DAC_BIT_LSB)

#define CMIF_RXAFC_FB_RX_UPD_EN_BIT_LSB                               (31)
#define CMIF_RXAFC_FB_RX_UPD_EN_BIT_WIDTH                             (1)
#define CMIF_RXAFC_FB_RX_UPD_EN_BIT_MASK                              ((UINT32) (((1<<CMIF_RXAFC_FB_RX_UPD_EN_BIT_WIDTH)-1) << CMIF_RXAFC_FB_RX_UPD_EN_BIT_LSB) )
#define CMIF_RXAFC_FB_RX_UPD_EN_FLD_WR(reg, val)                      (reg |= (val) << CMIF_RXAFC_FB_RX_UPD_EN_BIT_LSB)
#define CMIF_RXAFC_FB_RX_UPD_EN_FLD_RD(i)                             ((M_CMIF_RXAFC_FB_RX_RD(i) & CMIF_RXAFC_FB_RX_UPD_EN_BIT_MASK) >> CMIF_RXAFC_FB_RX_UPD_EN_BIT_LSB)

#define CMIF_RXAFC_FB_RX_FREQ_BAND_RX_BIT_LSB                         (0)
#define CMIF_RXAFC_FB_RX_FREQ_BAND_RX_BIT_WIDTH                       (16)
#define CMIF_RXAFC_FB_RX_FREQ_BAND_RX_BIT_MASK                        ((UINT32) (((1<<CMIF_RXAFC_FB_RX_FREQ_BAND_RX_BIT_WIDTH)-1) << CMIF_RXAFC_FB_RX_FREQ_BAND_RX_BIT_LSB) )
#define CMIF_RXAFC_FB_RX_FREQ_BAND_RX_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXAFC_FB_RX_FREQ_BAND_RX_BIT_LSB)
#define CMIF_RXAFC_FB_RX_FREQ_BAND_RX_FLD_RD(i)                       ((M_CMIF_RXAFC_FB_RX_RD(i) & CMIF_RXAFC_FB_RX_FREQ_BAND_RX_BIT_MASK) >> CMIF_RXAFC_FB_RX_FREQ_BAND_RX_BIT_LSB)

#define CMIF_RXAFC_FB_TX_UPD_EN_BIT_LSB                               (31)
#define CMIF_RXAFC_FB_TX_UPD_EN_BIT_WIDTH                             (1)
#define CMIF_RXAFC_FB_TX_UPD_EN_BIT_MASK                              ((UINT32) (((1<<CMIF_RXAFC_FB_TX_UPD_EN_BIT_WIDTH)-1) << CMIF_RXAFC_FB_TX_UPD_EN_BIT_LSB) )
#define CMIF_RXAFC_FB_TX_UPD_EN_FLD_WR(reg, val)                      (reg |= (val) << CMIF_RXAFC_FB_TX_UPD_EN_BIT_LSB)
#define CMIF_RXAFC_FB_TX_UPD_EN_FLD_RD(i)                             ((M_CMIF_RXAFC_FB_TX_RD(i) & CMIF_RXAFC_FB_TX_UPD_EN_BIT_MASK) >> CMIF_RXAFC_FB_TX_UPD_EN_BIT_LSB)

#define CMIF_RXAFC_FB_TX_FREQ_BAND_TX_BIT_LSB                         (0)
#define CMIF_RXAFC_FB_TX_FREQ_BAND_TX_BIT_WIDTH                       (16)
#define CMIF_RXAFC_FB_TX_FREQ_BAND_TX_BIT_MASK                        ((UINT32) (((1<<CMIF_RXAFC_FB_TX_FREQ_BAND_TX_BIT_WIDTH)-1) << CMIF_RXAFC_FB_TX_FREQ_BAND_TX_BIT_LSB) )
#define CMIF_RXAFC_FB_TX_FREQ_BAND_TX_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXAFC_FB_TX_FREQ_BAND_TX_BIT_LSB)
#define CMIF_RXAFC_FB_TX_FREQ_BAND_TX_FLD_RD(i)                       ((M_CMIF_RXAFC_FB_TX_RD(i) & CMIF_RXAFC_FB_TX_FREQ_BAND_TX_BIT_MASK) >> CMIF_RXAFC_FB_TX_FREQ_BAND_TX_BIT_LSB)

#define CMIF_RXAFC_INI_DAC_INI_EN_BIT_LSB                             (31)
#define CMIF_RXAFC_INI_DAC_INI_EN_BIT_WIDTH                           (1)
#define CMIF_RXAFC_INI_DAC_INI_EN_BIT_MASK                            ((UINT32) (((1<<CMIF_RXAFC_INI_DAC_INI_EN_BIT_WIDTH)-1) << CMIF_RXAFC_INI_DAC_INI_EN_BIT_LSB) )
#define CMIF_RXAFC_INI_DAC_INI_EN_FLD_WR(reg, val)                    (reg |= (val) << CMIF_RXAFC_INI_DAC_INI_EN_BIT_LSB)
#define CMIF_RXAFC_INI_DAC_INI_EN_FLD_RD()                            ((M_CMIF_RXAFC_INI_DAC_RD() & CMIF_RXAFC_INI_DAC_INI_EN_BIT_MASK) >> CMIF_RXAFC_INI_DAC_INI_EN_BIT_LSB)

#define CMIF_RXAFC_INI_DAC_INI_DAC_BIT_LSB                            (0)
#define CMIF_RXAFC_INI_DAC_INI_DAC_BIT_WIDTH                          (16)
#define CMIF_RXAFC_INI_DAC_INI_DAC_BIT_MASK                           ((UINT32) (((1<<CMIF_RXAFC_INI_DAC_INI_DAC_BIT_WIDTH)-1) << CMIF_RXAFC_INI_DAC_INI_DAC_BIT_LSB) )
#define CMIF_RXAFC_INI_DAC_INI_DAC_FLD_WR(reg, val)                   (reg |= (val) << CMIF_RXAFC_INI_DAC_INI_DAC_BIT_LSB)
#define CMIF_RXAFC_INI_DAC_INI_DAC_FLD_RD()                           ((M_CMIF_RXAFC_INI_DAC_RD() & CMIF_RXAFC_INI_DAC_INI_DAC_BIT_MASK) >> CMIF_RXAFC_INI_DAC_INI_DAC_BIT_LSB)

#define CMIF_RXAFC_INI_PPB_RX_INI_EN_BIT_LSB                          (31)
#define CMIF_RXAFC_INI_PPB_RX_INI_EN_BIT_WIDTH                        (1)
#define CMIF_RXAFC_INI_PPB_RX_INI_EN_BIT_MASK                         ((UINT32) (((1<<CMIF_RXAFC_INI_PPB_RX_INI_EN_BIT_WIDTH)-1) << CMIF_RXAFC_INI_PPB_RX_INI_EN_BIT_LSB) )
#define CMIF_RXAFC_INI_PPB_RX_INI_EN_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXAFC_INI_PPB_RX_INI_EN_BIT_LSB)
#define CMIF_RXAFC_INI_PPB_RX_INI_EN_FLD_RD(i)                        ((M_CMIF_RXAFC_INI_PPB_RX_RD(i) & CMIF_RXAFC_INI_PPB_RX_INI_EN_BIT_MASK) >> CMIF_RXAFC_INI_PPB_RX_INI_EN_BIT_LSB)

#define CMIF_RXAFC_INI_PPB_RX_INI_PPB_BIT_LSB                         (0)
#define CMIF_RXAFC_INI_PPB_RX_INI_PPB_BIT_WIDTH                       (17)
#define CMIF_RXAFC_INI_PPB_RX_INI_PPB_BIT_MASK                        ((UINT32) (((1<<CMIF_RXAFC_INI_PPB_RX_INI_PPB_BIT_WIDTH)-1) << CMIF_RXAFC_INI_PPB_RX_INI_PPB_BIT_LSB) )
#define CMIF_RXAFC_INI_PPB_RX_INI_PPB_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXAFC_INI_PPB_RX_INI_PPB_BIT_LSB)
#define CMIF_RXAFC_INI_PPB_RX_INI_PPB_FLD_RD(i)                       ((M_CMIF_RXAFC_INI_PPB_RX_RD(i) & CMIF_RXAFC_INI_PPB_RX_INI_PPB_BIT_MASK) >> CMIF_RXAFC_INI_PPB_RX_INI_PPB_BIT_LSB)

#define CMIF_RXAFC_INI_PPB_TX_INI_EN_BIT_LSB                          (31)
#define CMIF_RXAFC_INI_PPB_TX_INI_EN_BIT_WIDTH                        (1)
#define CMIF_RXAFC_INI_PPB_TX_INI_EN_BIT_MASK                         ((UINT32) (((1<<CMIF_RXAFC_INI_PPB_TX_INI_EN_BIT_WIDTH)-1) << CMIF_RXAFC_INI_PPB_TX_INI_EN_BIT_LSB) )
#define CMIF_RXAFC_INI_PPB_TX_INI_EN_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXAFC_INI_PPB_TX_INI_EN_BIT_LSB)
#define CMIF_RXAFC_INI_PPB_TX_INI_EN_FLD_RD(i)                        ((M_CMIF_RXAFC_INI_PPB_TX_RD(i) & CMIF_RXAFC_INI_PPB_TX_INI_EN_BIT_MASK) >> CMIF_RXAFC_INI_PPB_TX_INI_EN_BIT_LSB)

#define CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_BIT_LSB                      (0)
#define CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_BIT_WIDTH                    (17)
#define CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_BIT_MASK                     ((UINT32) (((1<<CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_BIT_WIDTH)-1) << CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_BIT_LSB) )
#define CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_BIT_LSB)
#define CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_FLD_RD(i)                    ((M_CMIF_RXAFC_INI_PPB_TX_RD(i) & CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_BIT_MASK) >> CMIF_RXAFC_INI_PPB_TX_INI_PPB_TX_BIT_LSB)

#define CMIF_RXAFC_DAC_MNT_FREQ_DAC_BIT_LSB                           (0)
#define CMIF_RXAFC_DAC_MNT_FREQ_DAC_BIT_WIDTH                         (16)
#define CMIF_RXAFC_DAC_MNT_FREQ_DAC_BIT_MASK                          ((UINT32) (((1<<CMIF_RXAFC_DAC_MNT_FREQ_DAC_BIT_WIDTH)-1) << CMIF_RXAFC_DAC_MNT_FREQ_DAC_BIT_LSB) )
#define CMIF_RXAFC_DAC_MNT_FREQ_DAC_FLD_WR(reg, val)                  (reg |= (val) << CMIF_RXAFC_DAC_MNT_FREQ_DAC_BIT_LSB)
#define CMIF_RXAFC_DAC_MNT_FREQ_DAC_FLD_RD()                          ((M_CMIF_RXAFC_DAC_MNT_RD() & CMIF_RXAFC_DAC_MNT_FREQ_DAC_BIT_MASK) >> CMIF_RXAFC_DAC_MNT_FREQ_DAC_BIT_LSB)

#define CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_BIT_LSB                      (0)
#define CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_BIT_WIDTH                    (32)
#define CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_BIT_MASK                     ((UINT32) (((1<<CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_BIT_WIDTH)-1) << CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_BIT_LSB) )
#define CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_BIT_LSB)
#define CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_FLD_RD(i)                    ((M_CMIF_RXAFC_RXPPB_MNT_RD(i) & CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_BIT_MASK) >> CMIF_RXAFC_RXPPB_MNT_DIG_ADJ_PPB_BIT_LSB)

#define CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_BIT_LSB                      (0)
#define CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_BIT_WIDTH                    (32)
#define CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_BIT_MASK                     ((UINT32) (((1<<CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_BIT_WIDTH)-1) << CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_BIT_LSB) )
#define CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_BIT_LSB)
#define CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_FLD_RD(i)                    ((M_CMIF_RXAFC_TXPPB_MNT_RD(i) & CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_BIT_MASK) >> CMIF_RXAFC_TXPPB_MNT_DIG_ADJ_PPB_BIT_LSB)

#define CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_LSB                     (0)
#define CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_WIDTH                   (32)
#define CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_MASK                    ((UINT32) (((1<<CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_WIDTH)-1) << CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_LSB) )
#define CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_FLD_WR(reg, val)            (reg |= (val) << CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_LSB)
#define CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_FLD_RD(i)                   ((M_CMIF_RXAFC_RXHZ_MNT_RD(i) & CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_MASK) >> CMIF_RXAFC_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_LSB)

#define CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_LSB                     (0)
#define CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_WIDTH                   (32)
#define CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_MASK                    ((UINT32) (((1<<CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_WIDTH)-1) << CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_LSB) )
#define CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_FLD_WR(reg, val)            (reg |= (val) << CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_LSB)
#define CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_FLD_RD(i)                   ((M_CMIF_RXAFC_TXHZ_MNT_RD(i) & CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_MASK) >> CMIF_RXAFC_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_LSB)

#define CMIF_RXAFC_SW_RST_SW_RST_BIT_LSB                              (31)
#define CMIF_RXAFC_SW_RST_SW_RST_BIT_WIDTH                            (1)
#define CMIF_RXAFC_SW_RST_SW_RST_BIT_MASK                             ((UINT32) (((1<<CMIF_RXAFC_SW_RST_SW_RST_BIT_WIDTH)-1) << CMIF_RXAFC_SW_RST_SW_RST_BIT_LSB) )
#define CMIF_RXAFC_SW_RST_SW_RST_FLD_WR(reg, val)                     (reg |= (val) << CMIF_RXAFC_SW_RST_SW_RST_BIT_LSB)
#define CMIF_RXAFC_SW_RST_SW_RST_FLD_RD()                             ((M_CMIF_RXAFC_SW_RST_RD() & CMIF_RXAFC_SW_RST_SW_RST_BIT_MASK) >> CMIF_RXAFC_SW_RST_SW_RST_BIT_LSB)

#define CMIF_RXAFC_SIM2_CON_AFC_MODE_BIT_LSB                          (16)
#define CMIF_RXAFC_SIM2_CON_AFC_MODE_BIT_WIDTH                        (3)
#define CMIF_RXAFC_SIM2_CON_AFC_MODE_BIT_MASK                         ((UINT32) (((1<<CMIF_RXAFC_SIM2_CON_AFC_MODE_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_CON_AFC_MODE_BIT_LSB) )
#define CMIF_RXAFC_SIM2_CON_AFC_MODE_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXAFC_SIM2_CON_AFC_MODE_BIT_LSB)
#define CMIF_RXAFC_SIM2_CON_AFC_MODE_FLD_RD()                         ((M_CMIF_RXAFC_SIM2_CON_RD() & CMIF_RXAFC_SIM2_CON_AFC_MODE_BIT_MASK) >> CMIF_RXAFC_SIM2_CON_AFC_MODE_BIT_LSB)

#define CMIF_RXAFC_SIM2_CON_DL_EN_TX_BIT_LSB                          (8)
#define CMIF_RXAFC_SIM2_CON_DL_EN_TX_BIT_WIDTH                        (1)
#define CMIF_RXAFC_SIM2_CON_DL_EN_TX_BIT_MASK                         ((UINT32) (((1<<CMIF_RXAFC_SIM2_CON_DL_EN_TX_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_CON_DL_EN_TX_BIT_LSB) )
#define CMIF_RXAFC_SIM2_CON_DL_EN_TX_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXAFC_SIM2_CON_DL_EN_TX_BIT_LSB)
#define CMIF_RXAFC_SIM2_CON_DL_EN_TX_FLD_RD()                         ((M_CMIF_RXAFC_SIM2_CON_RD() & CMIF_RXAFC_SIM2_CON_DL_EN_TX_BIT_MASK) >> CMIF_RXAFC_SIM2_CON_DL_EN_TX_BIT_LSB)

#define CMIF_RXAFC_SIM2_CON_GPS_ON_BIT_LSB                            (0)
#define CMIF_RXAFC_SIM2_CON_GPS_ON_BIT_WIDTH                          (1)
#define CMIF_RXAFC_SIM2_CON_GPS_ON_BIT_MASK                           ((UINT32) (((1<<CMIF_RXAFC_SIM2_CON_GPS_ON_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_CON_GPS_ON_BIT_LSB) )
#define CMIF_RXAFC_SIM2_CON_GPS_ON_FLD_WR(reg, val)                   (reg |= (val) << CMIF_RXAFC_SIM2_CON_GPS_ON_BIT_LSB)
#define CMIF_RXAFC_SIM2_CON_GPS_ON_FLD_RD()                           ((M_CMIF_RXAFC_SIM2_CON_RD() & CMIF_RXAFC_SIM2_CON_GPS_ON_BIT_MASK) >> CMIF_RXAFC_SIM2_CON_GPS_ON_BIT_LSB)

#define CMIF_RXAFC_SIM2_FB_RX_UPD_EN_BIT_LSB                          (31)
#define CMIF_RXAFC_SIM2_FB_RX_UPD_EN_BIT_WIDTH                        (1)
#define CMIF_RXAFC_SIM2_FB_RX_UPD_EN_BIT_MASK                         ((UINT32) (((1<<CMIF_RXAFC_SIM2_FB_RX_UPD_EN_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_FB_RX_UPD_EN_BIT_LSB) )
#define CMIF_RXAFC_SIM2_FB_RX_UPD_EN_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXAFC_SIM2_FB_RX_UPD_EN_BIT_LSB)
#define CMIF_RXAFC_SIM2_FB_RX_UPD_EN_FLD_RD()                         ((M_CMIF_RXAFC_SIM2_FB_RX_RD() & CMIF_RXAFC_SIM2_FB_RX_UPD_EN_BIT_MASK) >> CMIF_RXAFC_SIM2_FB_RX_UPD_EN_BIT_LSB)

#define CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_BIT_LSB                    (0)
#define CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_BIT_WIDTH                  (16)
#define CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_BIT_MASK                   ((UINT32) (((1<<CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_BIT_LSB) )
#define CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_FLD_WR(reg, val)           (reg |= (val) << CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_BIT_LSB)
#define CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_FLD_RD()                   ((M_CMIF_RXAFC_SIM2_FB_RX_RD() & CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_BIT_MASK) >> CMIF_RXAFC_SIM2_FB_RX_FREQ_BAND_RX_BIT_LSB)

#define CMIF_RXAFC_SIM2_FB_TX_UPD_EN_BIT_LSB                          (31)
#define CMIF_RXAFC_SIM2_FB_TX_UPD_EN_BIT_WIDTH                        (1)
#define CMIF_RXAFC_SIM2_FB_TX_UPD_EN_BIT_MASK                         ((UINT32) (((1<<CMIF_RXAFC_SIM2_FB_TX_UPD_EN_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_FB_TX_UPD_EN_BIT_LSB) )
#define CMIF_RXAFC_SIM2_FB_TX_UPD_EN_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXAFC_SIM2_FB_TX_UPD_EN_BIT_LSB)
#define CMIF_RXAFC_SIM2_FB_TX_UPD_EN_FLD_RD()                         ((M_CMIF_RXAFC_SIM2_FB_TX_RD() & CMIF_RXAFC_SIM2_FB_TX_UPD_EN_BIT_MASK) >> CMIF_RXAFC_SIM2_FB_TX_UPD_EN_BIT_LSB)

#define CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_BIT_LSB                    (0)
#define CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_BIT_WIDTH                  (16)
#define CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_BIT_MASK                   ((UINT32) (((1<<CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_BIT_LSB) )
#define CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_FLD_WR(reg, val)           (reg |= (val) << CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_BIT_LSB)
#define CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_FLD_RD()                   ((M_CMIF_RXAFC_SIM2_FB_TX_RD() & CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_BIT_MASK) >> CMIF_RXAFC_SIM2_FB_TX_FREQ_BAND_TX_BIT_LSB)

#define CMIF_RXAFC_SIM2_INI_DAC_INI_EN_BIT_LSB                        (31)
#define CMIF_RXAFC_SIM2_INI_DAC_INI_EN_BIT_WIDTH                      (1)
#define CMIF_RXAFC_SIM2_INI_DAC_INI_EN_BIT_MASK                       ((UINT32) (((1<<CMIF_RXAFC_SIM2_INI_DAC_INI_EN_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_INI_DAC_INI_EN_BIT_LSB) )
#define CMIF_RXAFC_SIM2_INI_DAC_INI_EN_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXAFC_SIM2_INI_DAC_INI_EN_BIT_LSB)
#define CMIF_RXAFC_SIM2_INI_DAC_INI_EN_FLD_RD()                       ((M_CMIF_RXAFC_SIM2_INI_DAC_RD() & CMIF_RXAFC_SIM2_INI_DAC_INI_EN_BIT_MASK) >> CMIF_RXAFC_SIM2_INI_DAC_INI_EN_BIT_LSB)

#define CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_BIT_LSB                       (0)
#define CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_BIT_WIDTH                     (16)
#define CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_BIT_MASK                      ((UINT32) (((1<<CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_BIT_LSB) )
#define CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_BIT_LSB)
#define CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_FLD_RD()                      ((M_CMIF_RXAFC_SIM2_INI_DAC_RD() & CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_BIT_MASK) >> CMIF_RXAFC_SIM2_INI_DAC_INI_DAC_BIT_LSB)

#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_BIT_LSB                     (31)
#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_BIT_WIDTH                   (1)
#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_BIT_MASK                    ((UINT32) (((1<<CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_BIT_LSB) )
#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_FLD_WR(reg, val)            (reg |= (val) << CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_BIT_LSB)
#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_FLD_RD()                    ((M_CMIF_RXAFC_SIM2_INI_PPB_RX_RD() & CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_BIT_MASK) >> CMIF_RXAFC_SIM2_INI_PPB_RX_INI_EN_BIT_LSB)

#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_BIT_LSB                    (0)
#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_BIT_WIDTH                  (17)
#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_BIT_MASK                   ((UINT32) (((1<<CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_BIT_LSB) )
#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_FLD_WR(reg, val)           (reg |= (val) << CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_BIT_LSB)
#define CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_FLD_RD()                   ((M_CMIF_RXAFC_SIM2_INI_PPB_RX_RD() & CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_BIT_MASK) >> CMIF_RXAFC_SIM2_INI_PPB_RX_INI_PPB_BIT_LSB)

#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_BIT_LSB                     (31)
#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_BIT_WIDTH                   (1)
#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_BIT_MASK                    ((UINT32) (((1<<CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_BIT_LSB) )
#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_FLD_WR(reg, val)            (reg |= (val) << CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_BIT_LSB)
#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_FLD_RD()                    ((M_CMIF_RXAFC_SIM2_INI_PPB_TX_RD() & CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_BIT_MASK) >> CMIF_RXAFC_SIM2_INI_PPB_TX_INI_EN_BIT_LSB)

#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_BIT_LSB                 (0)
#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_BIT_WIDTH               (17)
#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_BIT_MASK                ((UINT32) (((1<<CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_BIT_LSB) )
#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_FLD_WR(reg, val)        (reg |= (val) << CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_BIT_LSB)
#define CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_FLD_RD()                ((M_CMIF_RXAFC_SIM2_INI_PPB_TX_RD() & CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_BIT_MASK) >> CMIF_RXAFC_SIM2_INI_PPB_TX_INI_PPB_TX_BIT_LSB)

#define CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_BIT_LSB                      (0)
#define CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_BIT_WIDTH                    (16)
#define CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_BIT_MASK                     ((UINT32) (((1<<CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_BIT_LSB) )
#define CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_BIT_LSB)
#define CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_FLD_RD()                     ((M_CMIF_RXAFC_SIM2_DAC_MNT_RD() & CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_BIT_MASK) >> CMIF_RXAFC_SIM2_DAC_MNT_FREQ_DAC_BIT_LSB)

#define CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_BIT_LSB                 (0)
#define CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_BIT_WIDTH               (32)
#define CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_BIT_MASK                ((UINT32) (((1<<CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_BIT_LSB) )
#define CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_FLD_WR(reg, val)        (reg |= (val) << CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_BIT_LSB)
#define CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_FLD_RD()                ((M_CMIF_RXAFC_SIM2_RXPPB_MNT_RD() & CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_BIT_MASK) >> CMIF_RXAFC_SIM2_RXPPB_MNT_DIG_ADJ_PPB_BIT_LSB)

#define CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_BIT_LSB                 (0)
#define CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_BIT_WIDTH               (32)
#define CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_BIT_MASK                ((UINT32) (((1<<CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_BIT_LSB) )
#define CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_FLD_WR(reg, val)        (reg |= (val) << CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_BIT_LSB)
#define CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_FLD_RD()                ((M_CMIF_RXAFC_SIM2_TXPPB_MNT_RD() & CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_BIT_MASK) >> CMIF_RXAFC_SIM2_TXPPB_MNT_DIG_ADJ_PPB_BIT_LSB)

#define CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_LSB                (0)
#define CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_WIDTH              (32)
#define CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_MASK               ((UINT32) (((1<<CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_LSB) )
#define CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_FLD_WR(reg, val)       (reg |= (val) << CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_LSB)
#define CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_FLD_RD()               ((M_CMIF_RXAFC_SIM2_RXHZ_MNT_RD() & CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_MASK) >> CMIF_RXAFC_SIM2_RXHZ_MNT_DIG_ADJ_RX_HZ_BIT_LSB)

#define CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_LSB                (0)
#define CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_WIDTH              (32)
#define CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_MASK               ((UINT32) (((1<<CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_WIDTH)-1) << CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_LSB) )
#define CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_FLD_WR(reg, val)       (reg |= (val) << CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_LSB)
#define CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_FLD_RD()               ((M_CMIF_RXAFC_SIM2_TXHZ_MNT_RD() & CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_MASK) >> CMIF_RXAFC_SIM2_TXHZ_MNT_DIG_ADJ_TX_HZ_BIT_LSB)

#endif /* __RXAFC_CMIF_H__ */
