#ifndef __RAKE_CMIF_CMIF_H__
#define __RAKE_CMIF_CMIF_H__

#include "reg_access.h"
#include "dsp_header_define_cmif.h"

#define CMIF_RAKE_CMIF_REG_BASE                                       (WCDMA_RAKE_CMIF_REG_BASE)
#define CMIF_RAKE_HSCQI_OFFSET                                        (CMIF_RAKE_CMIF_REG_BASE + 0x0000)
#define CMIF_RAKE_INDEC_OFFSET                                        (CMIF_RAKE_CMIF_REG_BASE + 0x0004)
#define CMIF_RAKE_RXSRP_OFFSET                                        (CMIF_RAKE_CMIF_REG_BASE + 0x003C)
#define CMIF_RAKE_HIRG_OFFSET                                         (CMIF_RAKE_CMIF_REG_BASE + 0x0140)
#define CMIF_RAKE_FOE_OFFSET                                          (CMIF_RAKE_CMIF_REG_BASE + 0x02B0)
#define CMIF_RAKE_AFC_OFFSET                                          (CMIF_RAKE_CMIF_REG_BASE + 0x02D4)
#define CMIF_RAKE_SPEST_OFFSET                                        (CMIF_RAKE_CMIF_REG_BASE + 0x0374)
#define CMIF_RAKE_OC_OFFSET                                           (CMIF_RAKE_CMIF_REG_BASE + 0x0390)
#define CMIF_RAKE_TRACKER_OFFSET                                      (CMIF_RAKE_CMIF_REG_BASE + 0x03B4)
#define CMIF_RAKE_GENERAL_CTRL_OFFSET                                 (CMIF_RAKE_CMIF_REG_BASE + 0x04A8)
#define CMIF_RAKE_LOADER_OFFSET                                       (CMIF_RAKE_CMIF_REG_BASE + 0x0568)
#define CMIF_RAKE_RFM_OFFSET                                          (CMIF_RAKE_CMIF_REG_BASE + 0x0584)
#define CMIF_RAKE_CH_CONFIG_OFFSET                                    (CMIF_RAKE_CMIF_REG_BASE + 0x06EC)
#define CMIF_RAKE_CM_OFFSET                                           (CMIF_RAKE_CMIF_REG_BASE + 0x0948)
#define CMIF_RAKE_RSC_OFFSET                                          (CMIF_RAKE_CMIF_REG_BASE + 0x0990)
#define CMIF_RAKE_LO_RX                                               (CMIF_RAKE_CMIF_REG_BASE + 0x0B30)
#define CMIF_RAKE_BRP_REQD                                            (CMIF_RAKE_CMIF_REG_BASE + 0x0B44)
#define CMIF_RAKE_DORMANT_OFFSET                                      (CMIF_RAKE_CMIF_REG_BASE + 0x0BB0)
#define CMIF_RAKE_DEBUG_OFFSET                                        (CMIF_RAKE_CMIF_REG_BASE + 0x0BD4)

#define M_CMIF_RAKE_HSCQI_OFFSET_RD()                                 REG_READ(CMIF_RAKE_HSCQI_OFFSET)
#define M_CMIF_RAKE_INDEC_OFFSET_RD()                                 REG_READ(CMIF_RAKE_INDEC_OFFSET)
#define M_CMIF_RAKE_RXSRP_OFFSET_RD()                                 REG_READ(CMIF_RAKE_RXSRP_OFFSET)
#define M_CMIF_RAKE_HIRG_OFFSET_RD()                                  REG_READ(CMIF_RAKE_HIRG_OFFSET)
#define M_CMIF_RAKE_FOE_OFFSET_RD()                                   REG_READ(CMIF_RAKE_FOE_OFFSET)
#define M_CMIF_RAKE_AFC_OFFSET_RD()                                   REG_READ(CMIF_RAKE_AFC_OFFSET)
#define M_CMIF_RAKE_SPEST_OFFSET_RD()                                 REG_READ(CMIF_RAKE_SPEST_OFFSET)
#define M_CMIF_RAKE_OC_OFFSET_RD()                                    REG_READ(CMIF_RAKE_OC_OFFSET)
#define M_CMIF_RAKE_TRACKER_OFFSET_RD()                               REG_READ(CMIF_RAKE_TRACKER_OFFSET)
#define M_CMIF_RAKE_GENERAL_CTRL_OFFSET_RD()                          REG_READ(CMIF_RAKE_GENERAL_CTRL_OFFSET)
#define M_CMIF_RAKE_LOADER_OFFSET_RD()                                REG_READ(CMIF_RAKE_LOADER_OFFSET)
#define M_CMIF_RAKE_RFM_OFFSET_RD()                                   REG_READ(CMIF_RAKE_RFM_OFFSET)
#define M_CMIF_RAKE_CH_CONFIG_OFFSET_RD()                             REG_READ(CMIF_RAKE_CH_CONFIG_OFFSET)
#define M_CMIF_RAKE_CM_OFFSET_RD()                                    REG_READ(CMIF_RAKE_CM_OFFSET)
#define M_CMIF_RAKE_RSC_OFFSET_RD()                                   REG_READ(CMIF_RAKE_RSC_OFFSET)
#define M_CMIF_RAKE_LO_RX_RD()                                        REG_READ(CMIF_RAKE_LO_RX)
#define M_CMIF_RAKE_BRP_REQD_RD()                                     REG_READ(CMIF_RAKE_BRP_REQD)
#define M_CMIF_RAKE_DORMANT_OFFSET_RD()                               REG_READ(CMIF_RAKE_DORMANT_OFFSET)
#define M_CMIF_RAKE_DEBUG_OFFSET_RD()                                 REG_READ(CMIF_RAKE_DEBUG_OFFSET)

#define M_CMIF_RAKE_HSCQI_OFFSET_WR(reg)                              REG_WRITE(CMIF_RAKE_HSCQI_OFFSET, reg)
#define M_CMIF_RAKE_INDEC_OFFSET_WR(reg)                              REG_WRITE(CMIF_RAKE_INDEC_OFFSET, reg)
#define M_CMIF_RAKE_RXSRP_OFFSET_WR(reg)                              REG_WRITE(CMIF_RAKE_RXSRP_OFFSET, reg)
#define M_CMIF_RAKE_HIRG_OFFSET_WR(reg)                               REG_WRITE(CMIF_RAKE_HIRG_OFFSET, reg)
#define M_CMIF_RAKE_FOE_OFFSET_WR(reg)                                REG_WRITE(CMIF_RAKE_FOE_OFFSET, reg)
#define M_CMIF_RAKE_AFC_OFFSET_WR(reg)                                REG_WRITE(CMIF_RAKE_AFC_OFFSET, reg)
#define M_CMIF_RAKE_SPEST_OFFSET_WR(reg)                              REG_WRITE(CMIF_RAKE_SPEST_OFFSET, reg)
#define M_CMIF_RAKE_OC_OFFSET_WR(reg)                                 REG_WRITE(CMIF_RAKE_OC_OFFSET, reg)
#define M_CMIF_RAKE_TRACKER_OFFSET_WR(reg)                            REG_WRITE(CMIF_RAKE_TRACKER_OFFSET, reg)
#define M_CMIF_RAKE_GENERAL_CTRL_OFFSET_WR(reg)                       REG_WRITE(CMIF_RAKE_GENERAL_CTRL_OFFSET, reg)
#define M_CMIF_RAKE_LOADER_OFFSET_WR(reg)                             REG_WRITE(CMIF_RAKE_LOADER_OFFSET, reg)
#define M_CMIF_RAKE_RFM_OFFSET_WR(reg)                                REG_WRITE(CMIF_RAKE_RFM_OFFSET, reg)
#define M_CMIF_RAKE_CH_CONFIG_OFFSET_WR(reg)                          REG_WRITE(CMIF_RAKE_CH_CONFIG_OFFSET, reg)
#define M_CMIF_RAKE_CM_OFFSET_WR(reg)                                 REG_WRITE(CMIF_RAKE_CM_OFFSET, reg)
#define M_CMIF_RAKE_RSC_OFFSET_WR(reg)                                REG_WRITE(CMIF_RAKE_RSC_OFFSET, reg)
#define M_CMIF_RAKE_LO_RX_WR(reg)                                     REG_WRITE(CMIF_RAKE_LO_RX, reg)
#define M_CMIF_RAKE_BRP_REQD_WR(reg)                                  REG_WRITE(CMIF_RAKE_BRP_REQD, reg)
#define M_CMIF_RAKE_DORMANT_OFFSET_WR(reg)                            REG_WRITE(CMIF_RAKE_DORMANT_OFFSET, reg)
#define M_CMIF_RAKE_DEBUG_OFFSET_WR(reg)                              REG_WRITE(CMIF_RAKE_DEBUG_OFFSET, reg)

#define CMIF_RAKE_HSCQI_OFFSET_BASE_BIT_LSB                           (0)
#define CMIF_RAKE_HSCQI_OFFSET_BASE_BIT_WIDTH                         (32)
#define CMIF_RAKE_HSCQI_OFFSET_BASE_BIT_MASK                          ((UINT32) (((1<<CMIF_RAKE_HSCQI_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_HSCQI_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_HSCQI_OFFSET_BASE_FLD_WR(reg, val)                  (reg |= (val) << CMIF_RAKE_HSCQI_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_HSCQI_OFFSET_BASE_FLD_RD()                          ((M_CMIF_RAKE_HSCQI_OFFSET_RD() & CMIF_RAKE_HSCQI_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_HSCQI_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_INDEC_OFFSET_BASE_BIT_LSB                           (0)
#define CMIF_RAKE_INDEC_OFFSET_BASE_BIT_WIDTH                         (32)
#define CMIF_RAKE_INDEC_OFFSET_BASE_BIT_MASK                          ((UINT32) (((1<<CMIF_RAKE_INDEC_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_INDEC_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_INDEC_OFFSET_BASE_FLD_WR(reg, val)                  (reg |= (val) << CMIF_RAKE_INDEC_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_INDEC_OFFSET_BASE_FLD_RD()                          ((M_CMIF_RAKE_INDEC_OFFSET_RD() & CMIF_RAKE_INDEC_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_INDEC_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_RXSRP_OFFSET_BASE_BIT_LSB                           (0)
#define CMIF_RAKE_RXSRP_OFFSET_BASE_BIT_WIDTH                         (32)
#define CMIF_RAKE_RXSRP_OFFSET_BASE_BIT_MASK                          ((UINT32) (((1<<CMIF_RAKE_RXSRP_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_RXSRP_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_RXSRP_OFFSET_BASE_FLD_WR(reg, val)                  (reg |= (val) << CMIF_RAKE_RXSRP_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_RXSRP_OFFSET_BASE_FLD_RD()                          ((M_CMIF_RAKE_RXSRP_OFFSET_RD() & CMIF_RAKE_RXSRP_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_RXSRP_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_HIRG_OFFSET_BASE_BIT_LSB                            (0)
#define CMIF_RAKE_HIRG_OFFSET_BASE_BIT_WIDTH                          (32)
#define CMIF_RAKE_HIRG_OFFSET_BASE_BIT_MASK                           ((UINT32) (((1<<CMIF_RAKE_HIRG_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_HIRG_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_HIRG_OFFSET_BASE_FLD_WR(reg, val)                   (reg |= (val) << CMIF_RAKE_HIRG_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_HIRG_OFFSET_BASE_FLD_RD()                           ((M_CMIF_RAKE_HIRG_OFFSET_RD() & CMIF_RAKE_HIRG_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_HIRG_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_FOE_OFFSET_BASE_BIT_LSB                             (0)
#define CMIF_RAKE_FOE_OFFSET_BASE_BIT_WIDTH                           (32)
#define CMIF_RAKE_FOE_OFFSET_BASE_BIT_MASK                            ((UINT32) (((1<<CMIF_RAKE_FOE_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_FOE_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_FOE_OFFSET_BASE_FLD_WR(reg, val)                    (reg |= (val) << CMIF_RAKE_FOE_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_FOE_OFFSET_BASE_FLD_RD()                            ((M_CMIF_RAKE_FOE_OFFSET_RD() & CMIF_RAKE_FOE_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_FOE_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_AFC_OFFSET_BASE_BIT_LSB                             (0)
#define CMIF_RAKE_AFC_OFFSET_BASE_BIT_WIDTH                           (32)
#define CMIF_RAKE_AFC_OFFSET_BASE_BIT_MASK                            ((UINT32) (((1<<CMIF_RAKE_AFC_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_AFC_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_AFC_OFFSET_BASE_FLD_WR(reg, val)                    (reg |= (val) << CMIF_RAKE_AFC_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_AFC_OFFSET_BASE_FLD_RD()                            ((M_CMIF_RAKE_AFC_OFFSET_RD() & CMIF_RAKE_AFC_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_AFC_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_SPEST_OFFSET_BASE_BIT_LSB                           (0)
#define CMIF_RAKE_SPEST_OFFSET_BASE_BIT_WIDTH                         (32)
#define CMIF_RAKE_SPEST_OFFSET_BASE_BIT_MASK                          ((UINT32) (((1<<CMIF_RAKE_SPEST_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_SPEST_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_SPEST_OFFSET_BASE_FLD_WR(reg, val)                  (reg |= (val) << CMIF_RAKE_SPEST_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_SPEST_OFFSET_BASE_FLD_RD()                          ((M_CMIF_RAKE_SPEST_OFFSET_RD() & CMIF_RAKE_SPEST_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_SPEST_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_OC_OFFSET_BASE_BIT_LSB                              (0)
#define CMIF_RAKE_OC_OFFSET_BASE_BIT_WIDTH                            (32)
#define CMIF_RAKE_OC_OFFSET_BASE_BIT_MASK                             ((UINT32) (((1<<CMIF_RAKE_OC_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_OC_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_OC_OFFSET_BASE_FLD_WR(reg, val)                     (reg |= (val) << CMIF_RAKE_OC_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_OC_OFFSET_BASE_FLD_RD()                             ((M_CMIF_RAKE_OC_OFFSET_RD() & CMIF_RAKE_OC_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_OC_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_TRACKER_OFFSET_BASE_BIT_LSB                         (0)
#define CMIF_RAKE_TRACKER_OFFSET_BASE_BIT_WIDTH                       (32)
#define CMIF_RAKE_TRACKER_OFFSET_BASE_BIT_MASK                        ((UINT32) (((1<<CMIF_RAKE_TRACKER_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_TRACKER_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_TRACKER_OFFSET_BASE_FLD_WR(reg, val)                (reg |= (val) << CMIF_RAKE_TRACKER_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_TRACKER_OFFSET_BASE_FLD_RD()                        ((M_CMIF_RAKE_TRACKER_OFFSET_RD() & CMIF_RAKE_TRACKER_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_TRACKER_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_BIT_LSB                    (0)
#define CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_BIT_WIDTH                  (32)
#define CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_BIT_MASK                   ((UINT32) (((1<<CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_FLD_WR(reg, val)           (reg |= (val) << CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_FLD_RD()                   ((M_CMIF_RAKE_GENERAL_CTRL_OFFSET_RD() & CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_GENERAL_CTRL_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_LOADER_OFFSET_BASE_BIT_LSB                          (0)
#define CMIF_RAKE_LOADER_OFFSET_BASE_BIT_WIDTH                        (32)
#define CMIF_RAKE_LOADER_OFFSET_BASE_BIT_MASK                         ((UINT32) (((1<<CMIF_RAKE_LOADER_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_LOADER_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_LOADER_OFFSET_BASE_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RAKE_LOADER_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_LOADER_OFFSET_BASE_FLD_RD()                         ((M_CMIF_RAKE_LOADER_OFFSET_RD() & CMIF_RAKE_LOADER_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_LOADER_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_RFM_OFFSET_BASE_BIT_LSB                             (0)
#define CMIF_RAKE_RFM_OFFSET_BASE_BIT_WIDTH                           (32)
#define CMIF_RAKE_RFM_OFFSET_BASE_BIT_MASK                            ((UINT32) (((1<<CMIF_RAKE_RFM_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_RFM_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_RFM_OFFSET_BASE_FLD_WR(reg, val)                    (reg |= (val) << CMIF_RAKE_RFM_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_RFM_OFFSET_BASE_FLD_RD()                            ((M_CMIF_RAKE_RFM_OFFSET_RD() & CMIF_RAKE_RFM_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_RFM_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_CH_CONFIG_OFFSET_BASE_BIT_LSB                       (0)
#define CMIF_RAKE_CH_CONFIG_OFFSET_BASE_BIT_WIDTH                     (32)
#define CMIF_RAKE_CH_CONFIG_OFFSET_BASE_BIT_MASK                      ((UINT32) (((1<<CMIF_RAKE_CH_CONFIG_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_CH_CONFIG_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_CH_CONFIG_OFFSET_BASE_FLD_WR(reg, val)              (reg |= (val) << CMIF_RAKE_CH_CONFIG_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_CH_CONFIG_OFFSET_BASE_FLD_RD()                      ((M_CMIF_RAKE_CH_CONFIG_OFFSET_RD() & CMIF_RAKE_CH_CONFIG_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_CH_CONFIG_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_CM_OFFSET_BASE_BIT_LSB                              (0)
#define CMIF_RAKE_CM_OFFSET_BASE_BIT_WIDTH                            (32)
#define CMIF_RAKE_CM_OFFSET_BASE_BIT_MASK                             ((UINT32) (((1<<CMIF_RAKE_CM_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_CM_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_CM_OFFSET_BASE_FLD_WR(reg, val)                     (reg |= (val) << CMIF_RAKE_CM_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_CM_OFFSET_BASE_FLD_RD()                             ((M_CMIF_RAKE_CM_OFFSET_RD() & CMIF_RAKE_CM_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_CM_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_RSC_OFFSET_BASE_BIT_LSB                             (0)
#define CMIF_RAKE_RSC_OFFSET_BASE_BIT_WIDTH                           (32)
#define CMIF_RAKE_RSC_OFFSET_BASE_BIT_MASK                            ((UINT32) (((1<<CMIF_RAKE_RSC_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_RSC_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_RSC_OFFSET_BASE_FLD_WR(reg, val)                    (reg |= (val) << CMIF_RAKE_RSC_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_RSC_OFFSET_BASE_FLD_RD()                            ((M_CMIF_RAKE_RSC_OFFSET_RD() & CMIF_RAKE_RSC_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_RSC_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_LO_RX_BASE_BIT_LSB                                  (0)
#define CMIF_RAKE_LO_RX_BASE_BIT_WIDTH                                (32)
#define CMIF_RAKE_LO_RX_BASE_BIT_MASK                                 ((UINT32) (((1<<CMIF_RAKE_LO_RX_BASE_BIT_WIDTH)-1) << CMIF_RAKE_LO_RX_BASE_BIT_LSB) )
#define CMIF_RAKE_LO_RX_BASE_FLD_WR(reg, val)                         (reg |= (val) << CMIF_RAKE_LO_RX_BASE_BIT_LSB)
#define CMIF_RAKE_LO_RX_BASE_FLD_RD()                                 ((M_CMIF_RAKE_LO_RX_RD() & CMIF_RAKE_LO_RX_BASE_BIT_MASK) >> CMIF_RAKE_LO_RX_BASE_BIT_LSB)

#define CMIF_RAKE_BRP_REQD_BASE_BIT_LSB                               (0)
#define CMIF_RAKE_BRP_REQD_BASE_BIT_WIDTH                             (32)
#define CMIF_RAKE_BRP_REQD_BASE_BIT_MASK                              ((UINT32) (((1<<CMIF_RAKE_BRP_REQD_BASE_BIT_WIDTH)-1) << CMIF_RAKE_BRP_REQD_BASE_BIT_LSB) )
#define CMIF_RAKE_BRP_REQD_BASE_FLD_WR(reg, val)                      (reg |= (val) << CMIF_RAKE_BRP_REQD_BASE_BIT_LSB)
#define CMIF_RAKE_BRP_REQD_BASE_FLD_RD()                              ((M_CMIF_RAKE_BRP_REQD_RD() & CMIF_RAKE_BRP_REQD_BASE_BIT_MASK) >> CMIF_RAKE_BRP_REQD_BASE_BIT_LSB)

#define CMIF_RAKE_DORMANT_OFFSET_BASE_BIT_LSB                         (0)
#define CMIF_RAKE_DORMANT_OFFSET_BASE_BIT_WIDTH                       (32)
#define CMIF_RAKE_DORMANT_OFFSET_BASE_BIT_MASK                        ((UINT32) (((1<<CMIF_RAKE_DORMANT_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_DORMANT_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_DORMANT_OFFSET_BASE_FLD_WR(reg, val)                (reg |= (val) << CMIF_RAKE_DORMANT_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_DORMANT_OFFSET_BASE_FLD_RD()                        ((M_CMIF_RAKE_DORMANT_OFFSET_RD() & CMIF_RAKE_DORMANT_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_DORMANT_OFFSET_BASE_BIT_LSB)

#define CMIF_RAKE_DEBUG_OFFSET_BASE_BIT_LSB                           (0)
#define CMIF_RAKE_DEBUG_OFFSET_BASE_BIT_WIDTH                         (32)
#define CMIF_RAKE_DEBUG_OFFSET_BASE_BIT_MASK                          ((UINT32) (((1<<CMIF_RAKE_DEBUG_OFFSET_BASE_BIT_WIDTH)-1) << CMIF_RAKE_DEBUG_OFFSET_BASE_BIT_LSB) )
#define CMIF_RAKE_DEBUG_OFFSET_BASE_FLD_WR(reg, val)                  (reg |= (val) << CMIF_RAKE_DEBUG_OFFSET_BASE_BIT_LSB)
#define CMIF_RAKE_DEBUG_OFFSET_BASE_FLD_RD()                          ((M_CMIF_RAKE_DEBUG_OFFSET_RD() & CMIF_RAKE_DEBUG_OFFSET_BASE_BIT_MASK) >> CMIF_RAKE_DEBUG_OFFSET_BASE_BIT_LSB)

#endif /* __RAKE_CMIF_CMIF_H__ */

