#ifndef __C2M_M2C_CTRL_CMIF_H__
#define __C2M_M2C_CTRL_CMIF_H__

#include "reg_access.h"
#include "base_addr_cmif.h"

#define CMIF_C2M_M2C_CTRL_REG_BASE                                    (CMIF_C2M_M2C_CTRL_OFFSET)
#define CMIF_M2C_WFI_IRQ_STA                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0000)
#define CMIF_M2C_WFI_IRQ_MASK                                         (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0004)
#define CMIF_M2CTI_EVENT                                              (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0008)
#define CMIF_C2M_U3G_IRQ_STA                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x000C)
#define CMIF_C2M_U3G_IRQ_CLR                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0010)
#define CMIF_C2M_U4G_IRQ_STA                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0014)
#define CMIF_C2M_U4G_IRQ_CLR                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0018)
#define CMIF_M2C_U3G_IRQ_STA                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x001C)
#define CMIF_M2C_U3G_IRQ_SET                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0020)
#define CMIF_M2C_U4G_IRQ_STA                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0024)
#define CMIF_M2C_U4G_IRQ_SET                                          (CMIF_C2M_M2C_CTRL_REG_BASE + 0x0028)
#define CMIF_RESERVED_OS_LOG(i)                                       (CMIF_C2M_M2C_CTRL_REG_BASE + 0x002C + ((i) * 0x4))

#define M_CMIF_M2C_WFI_IRQ_STA_RD()                                   REG_READ(CMIF_M2C_WFI_IRQ_STA)
#define M_CMIF_M2C_WFI_IRQ_MASK_RD()                                  REG_READ(CMIF_M2C_WFI_IRQ_MASK)
#define M_CMIF_M2CTI_EVENT_RD()                                       REG_READ(CMIF_M2CTI_EVENT)
#define M_CMIF_C2M_U3G_IRQ_STA_RD()                                   REG_READ(CMIF_C2M_U3G_IRQ_STA)
#define M_CMIF_C2M_U3G_IRQ_CLR_RD()                                   REG_READ(CMIF_C2M_U3G_IRQ_CLR)
#define M_CMIF_C2M_U4G_IRQ_STA_RD()                                   REG_READ(CMIF_C2M_U4G_IRQ_STA)
#define M_CMIF_C2M_U4G_IRQ_CLR_RD()                                   REG_READ(CMIF_C2M_U4G_IRQ_CLR)
#define M_CMIF_M2C_U3G_IRQ_STA_RD()                                   REG_READ(CMIF_M2C_U3G_IRQ_STA)
#define M_CMIF_M2C_U3G_IRQ_SET_RD()                                   REG_READ(CMIF_M2C_U3G_IRQ_SET)
#define M_CMIF_M2C_U4G_IRQ_STA_RD()                                   REG_READ(CMIF_M2C_U4G_IRQ_STA)
#define M_CMIF_M2C_U4G_IRQ_SET_RD()                                   REG_READ(CMIF_M2C_U4G_IRQ_SET)
#define M_CMIF_RESERVED_OS_LOG_RD(i)                                  REG_READ(CMIF_RESERVED_OS_LOG(i))

#define M_CMIF_M2C_WFI_IRQ_STA_WR(reg)                                REG_WRITE(CMIF_M2C_WFI_IRQ_STA, reg)
#define M_CMIF_M2C_WFI_IRQ_MASK_WR(reg)                               REG_WRITE(CMIF_M2C_WFI_IRQ_MASK, reg)
#define M_CMIF_M2CTI_EVENT_WR(reg)                                    REG_WRITE(CMIF_M2CTI_EVENT, reg)
#define M_CMIF_C2M_U3G_IRQ_STA_WR(reg)                                REG_WRITE(CMIF_C2M_U3G_IRQ_STA, reg)
#define M_CMIF_C2M_U3G_IRQ_CLR_WR(reg)                                REG_WRITE(CMIF_C2M_U3G_IRQ_CLR, reg)
#define M_CMIF_C2M_U4G_IRQ_STA_WR(reg)                                REG_WRITE(CMIF_C2M_U4G_IRQ_STA, reg)
#define M_CMIF_C2M_U4G_IRQ_CLR_WR(reg)                                REG_WRITE(CMIF_C2M_U4G_IRQ_CLR, reg)
#define M_CMIF_M2C_U3G_IRQ_STA_WR(reg)                                REG_WRITE(CMIF_M2C_U3G_IRQ_STA, reg)
#define M_CMIF_M2C_U3G_IRQ_SET_WR(reg)                                REG_WRITE(CMIF_M2C_U3G_IRQ_SET, reg)
#define M_CMIF_M2C_U4G_IRQ_STA_WR(reg)                                REG_WRITE(CMIF_M2C_U4G_IRQ_STA, reg)
#define M_CMIF_M2C_U4G_IRQ_SET_WR(reg)                                REG_WRITE(CMIF_M2C_U4G_IRQ_SET, reg)
#define M_CMIF_RESERVED_OS_LOG_WR(i, reg)                             REG_WRITE(CMIF_RESERVED_OS_LOG(i), reg)

#define CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_BIT_LSB                  (0)
#define CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_BIT_WIDTH                (1)
#define CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_BIT_MASK                 ((UINT32) (((1<<CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_BIT_WIDTH)-1) << CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_BIT_LSB) )
#define CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_FLD_WR(reg, val)         (reg |= (val) << CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_BIT_LSB)
#define CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_FLD_RD()                 ((M_CMIF_M2C_WFI_IRQ_STA_RD() & CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_BIT_MASK) >> CMIF_M2C_WFI_IRQ_STA_M2C_WFI_IRQ_STA_BIT_LSB)

#define CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_BIT_LSB                (0)
#define CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_BIT_WIDTH              (1)
#define CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_BIT_MASK               ((UINT32) (((1<<CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_BIT_WIDTH)-1) << CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_BIT_LSB) )
#define CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_FLD_WR(reg, val)       (reg |= (val) << CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_BIT_LSB)
#define CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_FLD_RD()               ((M_CMIF_M2C_WFI_IRQ_MASK_RD() & CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_BIT_MASK) >> CMIF_M2C_WFI_IRQ_MASK_M2C_WFI_IRQ_MASK_BIT_LSB)

#define CMIF_M2CTI_EVENT_CTI_EVENT_BIT_LSB                            (0)
#define CMIF_M2CTI_EVENT_CTI_EVENT_BIT_WIDTH                          (1)
#define CMIF_M2CTI_EVENT_CTI_EVENT_BIT_MASK                           ((UINT32) (((1<<CMIF_M2CTI_EVENT_CTI_EVENT_BIT_WIDTH)-1) << CMIF_M2CTI_EVENT_CTI_EVENT_BIT_LSB) )
#define CMIF_M2CTI_EVENT_CTI_EVENT_FLD_WR(reg, val)                   (reg |= (val) << CMIF_M2CTI_EVENT_CTI_EVENT_BIT_LSB)
#define CMIF_M2CTI_EVENT_CTI_EVENT_FLD_RD()                           ((M_CMIF_M2CTI_EVENT_RD() & CMIF_M2CTI_EVENT_CTI_EVENT_BIT_MASK) >> CMIF_M2CTI_EVENT_CTI_EVENT_BIT_LSB)

#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_BIT_LSB             (1)
#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_BIT_WIDTH           (1)
#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_BIT_MASK            ((UINT32) (((1<<CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_BIT_WIDTH)-1) << CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_BIT_LSB) )
#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_FLD_WR(reg, val)    (reg |= (val) << CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_BIT_LSB)
#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_FLD_RD()            ((M_CMIF_C2M_U3G_IRQ_STA_RD() & CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_BIT_MASK) >> CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_POWERDOWN_BIT_LSB)

#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_BIT_LSB               (0)
#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_BIT_WIDTH             (1)
#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_BIT_MASK              ((UINT32) (((1<<CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_BIT_WIDTH)-1) << CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_BIT_LSB) )
#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_FLD_WR(reg, val)      (reg |= (val) << CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_BIT_LSB)
#define CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_FLD_RD()              ((M_CMIF_C2M_U3G_IRQ_STA_RD() & CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_BIT_MASK) >> CMIF_C2M_U3G_IRQ_STA_RAKE_SLEEP_DORMANT_BIT_LSB)

#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_BIT_LSB             (1)
#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_BIT_WIDTH           (1)
#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_BIT_MASK            ((UINT32) (((1<<CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_BIT_WIDTH)-1) << CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_BIT_LSB) )
#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_FLD_WR(reg, val)    (reg |= (val) << CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_BIT_LSB)
#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_FLD_RD()            ((M_CMIF_C2M_U3G_IRQ_CLR_RD() & CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_BIT_MASK) >> CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_POWERDOWN_BIT_LSB)

#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_BIT_LSB               (0)
#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_BIT_WIDTH             (1)
#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_BIT_MASK              ((UINT32) (((1<<CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_BIT_WIDTH)-1) << CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_BIT_LSB) )
#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_FLD_WR(reg, val)      (reg |= (val) << CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_BIT_LSB)
#define CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_FLD_RD()              ((M_CMIF_C2M_U3G_IRQ_CLR_RD() & CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_BIT_MASK) >> CMIF_C2M_U3G_IRQ_CLR_RAKE_SLEEP_DORMANT_BIT_LSB)

#define CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_BIT_LSB                  (0)
#define CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_BIT_WIDTH                (32)
#define CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_BIT_MASK                 ((UINT32) (((1<<CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_BIT_WIDTH)-1) << CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_BIT_LSB) )
#define CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_FLD_WR(reg, val)         (reg |= (val) << CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_BIT_LSB)
#define CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_FLD_RD()                 ((M_CMIF_C2M_U4G_IRQ_STA_RD() & CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_BIT_MASK) >> CMIF_C2M_U4G_IRQ_STA_C2M_U4G_IRQ_STA_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_STA_TFCI_1_BIT_LSB                           (4)
#define CMIF_M2C_U3G_IRQ_STA_TFCI_1_BIT_WIDTH                         (1)
#define CMIF_M2C_U3G_IRQ_STA_TFCI_1_BIT_MASK                          ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_STA_TFCI_1_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_STA_TFCI_1_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_STA_TFCI_1_FLD_WR(reg, val)                  (reg |= (val) << CMIF_M2C_U3G_IRQ_STA_TFCI_1_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_STA_TFCI_1_FLD_RD()                          ((M_CMIF_M2C_U3G_IRQ_STA_RD() & CMIF_M2C_U3G_IRQ_STA_TFCI_1_BIT_MASK) >> CMIF_M2C_U3G_IRQ_STA_TFCI_1_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_STA_TFCI_0_BIT_LSB                           (3)
#define CMIF_M2C_U3G_IRQ_STA_TFCI_0_BIT_WIDTH                         (1)
#define CMIF_M2C_U3G_IRQ_STA_TFCI_0_BIT_MASK                          ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_STA_TFCI_0_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_STA_TFCI_0_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_STA_TFCI_0_FLD_WR(reg, val)                  (reg |= (val) << CMIF_M2C_U3G_IRQ_STA_TFCI_0_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_STA_TFCI_0_FLD_RD()                          ((M_CMIF_M2C_U3G_IRQ_STA_RD() & CMIF_M2C_U3G_IRQ_STA_TFCI_0_BIT_MASK) >> CMIF_M2C_U3G_IRQ_STA_TFCI_0_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_STA_PI_BIT_LSB                               (2)
#define CMIF_M2C_U3G_IRQ_STA_PI_BIT_WIDTH                             (1)
#define CMIF_M2C_U3G_IRQ_STA_PI_BIT_MASK                              ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_STA_PI_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_STA_PI_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_STA_PI_FLD_WR(reg, val)                      (reg |= (val) << CMIF_M2C_U3G_IRQ_STA_PI_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_STA_PI_FLD_RD()                              ((M_CMIF_M2C_U3G_IRQ_STA_RD() & CMIF_M2C_U3G_IRQ_STA_PI_BIT_MASK) >> CMIF_M2C_U3G_IRQ_STA_PI_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_STA_AI_BIT_LSB                               (1)
#define CMIF_M2C_U3G_IRQ_STA_AI_BIT_WIDTH                             (1)
#define CMIF_M2C_U3G_IRQ_STA_AI_BIT_MASK                              ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_STA_AI_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_STA_AI_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_STA_AI_FLD_WR(reg, val)                      (reg |= (val) << CMIF_M2C_U3G_IRQ_STA_AI_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_STA_AI_FLD_RD()                              ((M_CMIF_M2C_U3G_IRQ_STA_RD() & CMIF_M2C_U3G_IRQ_STA_AI_BIT_MASK) >> CMIF_M2C_U3G_IRQ_STA_AI_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_BIT_LSB                    (0)
#define CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_BIT_WIDTH                  (1)
#define CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_BIT_MASK                   ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_FLD_WR(reg, val)           (reg |= (val) << CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_FLD_RD()                   ((M_CMIF_M2C_U3G_IRQ_STA_RD() & CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_BIT_MASK) >> CMIF_M2C_U3G_IRQ_STA_BOOT_UP_READY_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_SET_TFCI_1_BIT_LSB                           (4)
#define CMIF_M2C_U3G_IRQ_SET_TFCI_1_BIT_WIDTH                         (1)
#define CMIF_M2C_U3G_IRQ_SET_TFCI_1_BIT_MASK                          ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_SET_TFCI_1_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_SET_TFCI_1_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_SET_TFCI_1_FLD_WR(reg, val)                  (reg |= (val) << CMIF_M2C_U3G_IRQ_SET_TFCI_1_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_SET_TFCI_1_FLD_RD()                          ((M_CMIF_M2C_U3G_IRQ_SET_RD() & CMIF_M2C_U3G_IRQ_SET_TFCI_1_BIT_MASK) >> CMIF_M2C_U3G_IRQ_SET_TFCI_1_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_SET_TFCI_0_BIT_LSB                           (3)
#define CMIF_M2C_U3G_IRQ_SET_TFCI_0_BIT_WIDTH                         (1)
#define CMIF_M2C_U3G_IRQ_SET_TFCI_0_BIT_MASK                          ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_SET_TFCI_0_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_SET_TFCI_0_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_SET_TFCI_0_FLD_WR(reg, val)                  (reg |= (val) << CMIF_M2C_U3G_IRQ_SET_TFCI_0_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_SET_TFCI_0_FLD_RD()                          ((M_CMIF_M2C_U3G_IRQ_SET_RD() & CMIF_M2C_U3G_IRQ_SET_TFCI_0_BIT_MASK) >> CMIF_M2C_U3G_IRQ_SET_TFCI_0_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_SET_PI_BIT_LSB                               (2)
#define CMIF_M2C_U3G_IRQ_SET_PI_BIT_WIDTH                             (1)
#define CMIF_M2C_U3G_IRQ_SET_PI_BIT_MASK                              ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_SET_PI_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_SET_PI_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_SET_PI_FLD_WR(reg, val)                      (reg |= (val) << CMIF_M2C_U3G_IRQ_SET_PI_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_SET_PI_FLD_RD()                              ((M_CMIF_M2C_U3G_IRQ_SET_RD() & CMIF_M2C_U3G_IRQ_SET_PI_BIT_MASK) >> CMIF_M2C_U3G_IRQ_SET_PI_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_SET_AI_BIT_LSB                               (1)
#define CMIF_M2C_U3G_IRQ_SET_AI_BIT_WIDTH                             (1)
#define CMIF_M2C_U3G_IRQ_SET_AI_BIT_MASK                              ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_SET_AI_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_SET_AI_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_SET_AI_FLD_WR(reg, val)                      (reg |= (val) << CMIF_M2C_U3G_IRQ_SET_AI_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_SET_AI_FLD_RD()                              ((M_CMIF_M2C_U3G_IRQ_SET_RD() & CMIF_M2C_U3G_IRQ_SET_AI_BIT_MASK) >> CMIF_M2C_U3G_IRQ_SET_AI_BIT_LSB)

#define CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_BIT_LSB                    (0)
#define CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_BIT_WIDTH                  (1)
#define CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_BIT_MASK                   ((UINT32) (((1<<CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_BIT_WIDTH)-1) << CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_BIT_LSB) )
#define CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_FLD_WR(reg, val)           (reg |= (val) << CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_BIT_LSB)
#define CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_FLD_RD()                   ((M_CMIF_M2C_U3G_IRQ_SET_RD() & CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_BIT_MASK) >> CMIF_M2C_U3G_IRQ_SET_BOOT_UP_READY_BIT_LSB)

#define CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_BIT_LSB                  (0)
#define CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_BIT_WIDTH                (32)
#define CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_BIT_MASK                 ((UINT32) (((1<<CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_BIT_WIDTH)-1) << CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_BIT_LSB) )
#define CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_FLD_WR(reg, val)         (reg |= (val) << CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_BIT_LSB)
#define CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_FLD_RD()                 ((M_CMIF_M2C_U4G_IRQ_STA_RD() & CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_BIT_MASK) >> CMIF_M2C_U4G_IRQ_STA_M2C_U4G_IRQ_STA_BIT_LSB)

#define CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_BIT_LSB                  (0)
#define CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_BIT_WIDTH                (32)
#define CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_BIT_MASK                 ((UINT32) (((1<<CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_BIT_WIDTH)-1) << CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_BIT_LSB) )
#define CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_FLD_WR(reg, val)         (reg |= (val) << CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_BIT_LSB)
#define CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_FLD_RD(i)                ((M_CMIF_RESERVED_OS_LOG_RD(i) & CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_BIT_MASK) >> CMIF_RESERVED_OS_LOG_RESERVED_OS_LOG_BIT_LSB)

#endif /* __C2M_M2C_CTRL_CMIF_H__ */
