#ifndef __INDEC_CMIF_H__
#define __INDEC_CMIF_H__

#include "reg_access.h"
#include "base_addr_cmif.h"

#define CMIF_INDEC_REG_BASE                                           (CMIF_RAKE_INDEC_OFFSET)
#define CMIF_INDEC_AICH_PAR                                           (CMIF_INDEC_REG_BASE + 0x0000)
#define CMIF_INDEC_AICH_TH                                            (CMIF_INDEC_REG_BASE + 0x0004)
#define CMIF_INDEC_AICH_OUT                                           (CMIF_INDEC_REG_BASE + 0x0008)
#define CMIF_INDEC_PICH_OUT                                           (CMIF_INDEC_REG_BASE + 0x000C)
#define CMIF_INDEC_EAI_EN_PAR                                         (CMIF_INDEC_REG_BASE + 0x0010)
#define CMIF_INDEC_TFCI_CTRL(i)                                       (CMIF_INDEC_REG_BASE + 0x0014 + ((i) * 0x4))
#define CMIF_INDEC_TFCI_OUT(i)                                        (CMIF_INDEC_REG_BASE + 0x001C + ((i) * 0x4))
#define CMIF_INDEC_AICH_ACC                                           (CMIF_INDEC_REG_BASE + 0x0024)
#define CMIF_INDEC_PICH_ACC                                           (CMIF_INDEC_REG_BASE + 0x0028)
#define CMIF_INDEC_TFCI_STS(i)                                        (CMIF_INDEC_REG_BASE + 0x002C + ((i) * 0x4))
#define CMIF_INDEC_EAI_ACC                                            (CMIF_INDEC_REG_BASE + 0x0034)

#define M_CMIF_INDEC_AICH_PAR_RD()                                    REG_READ(CMIF_INDEC_AICH_PAR)
#define M_CMIF_INDEC_AICH_TH_RD()                                     REG_READ(CMIF_INDEC_AICH_TH)
#define M_CMIF_INDEC_AICH_OUT_RD()                                    REG_READ(CMIF_INDEC_AICH_OUT)
#define M_CMIF_INDEC_PICH_OUT_RD()                                    REG_READ(CMIF_INDEC_PICH_OUT)
#define M_CMIF_INDEC_EAI_EN_PAR_RD()                                  REG_READ(CMIF_INDEC_EAI_EN_PAR)
#define M_CMIF_INDEC_TFCI_CTRL_RD(i)                                  REG_READ(CMIF_INDEC_TFCI_CTRL(i))
#define M_CMIF_INDEC_TFCI_OUT_RD(i)                                   REG_READ(CMIF_INDEC_TFCI_OUT(i))
#define M_CMIF_INDEC_AICH_ACC_RD()                                    REG_READ(CMIF_INDEC_AICH_ACC)
#define M_CMIF_INDEC_PICH_ACC_RD()                                    REG_READ(CMIF_INDEC_PICH_ACC)
#define M_CMIF_INDEC_TFCI_STS_RD(i)                                   REG_READ(CMIF_INDEC_TFCI_STS(i))
#define M_CMIF_INDEC_EAI_ACC_RD()                                     REG_READ(CMIF_INDEC_EAI_ACC)

#define M_CMIF_INDEC_AICH_PAR_WR(reg)                                 REG_WRITE(CMIF_INDEC_AICH_PAR, reg)
#define M_CMIF_INDEC_AICH_TH_WR(reg)                                  REG_WRITE(CMIF_INDEC_AICH_TH, reg)
#define M_CMIF_INDEC_AICH_OUT_WR(reg)                                 REG_WRITE(CMIF_INDEC_AICH_OUT, reg)
#define M_CMIF_INDEC_PICH_OUT_WR(reg)                                 REG_WRITE(CMIF_INDEC_PICH_OUT, reg)
#define M_CMIF_INDEC_EAI_EN_PAR_WR(reg)                               REG_WRITE(CMIF_INDEC_EAI_EN_PAR, reg)
#define M_CMIF_INDEC_TFCI_CTRL_WR(i, reg)                             REG_WRITE(CMIF_INDEC_TFCI_CTRL(i), reg)
#define M_CMIF_INDEC_TFCI_OUT_WR(i, reg)                              REG_WRITE(CMIF_INDEC_TFCI_OUT(i), reg)
#define M_CMIF_INDEC_AICH_ACC_WR(reg)                                 REG_WRITE(CMIF_INDEC_AICH_ACC, reg)
#define M_CMIF_INDEC_PICH_ACC_WR(reg)                                 REG_WRITE(CMIF_INDEC_PICH_ACC, reg)
#define M_CMIF_INDEC_TFCI_STS_WR(i, reg)                              REG_WRITE(CMIF_INDEC_TFCI_STS(i), reg)
#define M_CMIF_INDEC_EAI_ACC_WR(reg)                                  REG_WRITE(CMIF_INDEC_EAI_ACC, reg)

#define CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_BIT_LSB             (8)
#define CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_BIT_WIDTH           (8)
#define CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_BIT_MASK            ((UINT32) (((1<<CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_BIT_WIDTH)-1) << CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_BIT_LSB) )
#define CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_FLD_WR(reg, val)    (reg |= (val) << CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_BIT_LSB)
#define CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_FLD_RD()            ((M_CMIF_INDEC_AICH_PAR_RD() & CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_BIT_MASK) >> CMIF_INDEC_AICH_PAR_AMP_OFFSET_AICH_CPICH_BIT_LSB)

#define CMIF_INDEC_AICH_PAR_SIGN_INDEX_BIT_LSB                        (0)
#define CMIF_INDEC_AICH_PAR_SIGN_INDEX_BIT_WIDTH                      (8)
#define CMIF_INDEC_AICH_PAR_SIGN_INDEX_BIT_MASK                       ((UINT32) (((1<<CMIF_INDEC_AICH_PAR_SIGN_INDEX_BIT_WIDTH)-1) << CMIF_INDEC_AICH_PAR_SIGN_INDEX_BIT_LSB) )
#define CMIF_INDEC_AICH_PAR_SIGN_INDEX_FLD_WR(reg, val)               (reg |= (val) << CMIF_INDEC_AICH_PAR_SIGN_INDEX_BIT_LSB)
#define CMIF_INDEC_AICH_PAR_SIGN_INDEX_FLD_RD()                       ((M_CMIF_INDEC_AICH_PAR_RD() & CMIF_INDEC_AICH_PAR_SIGN_INDEX_BIT_MASK) >> CMIF_INDEC_AICH_PAR_SIGN_INDEX_BIT_LSB)

#define CMIF_INDEC_AICH_TH_TH_POW_H_BIT_LSB                           (16)
#define CMIF_INDEC_AICH_TH_TH_POW_H_BIT_WIDTH                         (8)
#define CMIF_INDEC_AICH_TH_TH_POW_H_BIT_MASK                          ((UINT32) (((1<<CMIF_INDEC_AICH_TH_TH_POW_H_BIT_WIDTH)-1) << CMIF_INDEC_AICH_TH_TH_POW_H_BIT_LSB) )
#define CMIF_INDEC_AICH_TH_TH_POW_H_FLD_WR(reg, val)                  (reg |= (val) << CMIF_INDEC_AICH_TH_TH_POW_H_BIT_LSB)
#define CMIF_INDEC_AICH_TH_TH_POW_H_FLD_RD()                          ((M_CMIF_INDEC_AICH_TH_RD() & CMIF_INDEC_AICH_TH_TH_POW_H_BIT_MASK) >> CMIF_INDEC_AICH_TH_TH_POW_H_BIT_LSB)

#define CMIF_INDEC_AICH_TH_TH_LOW_BIT_LSB                             (8)
#define CMIF_INDEC_AICH_TH_TH_LOW_BIT_WIDTH                           (8)
#define CMIF_INDEC_AICH_TH_TH_LOW_BIT_MASK                            ((UINT32) (((1<<CMIF_INDEC_AICH_TH_TH_LOW_BIT_WIDTH)-1) << CMIF_INDEC_AICH_TH_TH_LOW_BIT_LSB) )
#define CMIF_INDEC_AICH_TH_TH_LOW_FLD_WR(reg, val)                    (reg |= (val) << CMIF_INDEC_AICH_TH_TH_LOW_BIT_LSB)
#define CMIF_INDEC_AICH_TH_TH_LOW_FLD_RD()                            ((M_CMIF_INDEC_AICH_TH_RD() & CMIF_INDEC_AICH_TH_TH_LOW_BIT_MASK) >> CMIF_INDEC_AICH_TH_TH_LOW_BIT_LSB)

#define CMIF_INDEC_AICH_TH_TH_HIGH_BIT_LSB                            (0)
#define CMIF_INDEC_AICH_TH_TH_HIGH_BIT_WIDTH                          (8)
#define CMIF_INDEC_AICH_TH_TH_HIGH_BIT_MASK                           ((UINT32) (((1<<CMIF_INDEC_AICH_TH_TH_HIGH_BIT_WIDTH)-1) << CMIF_INDEC_AICH_TH_TH_HIGH_BIT_LSB) )
#define CMIF_INDEC_AICH_TH_TH_HIGH_FLD_WR(reg, val)                   (reg |= (val) << CMIF_INDEC_AICH_TH_TH_HIGH_BIT_LSB)
#define CMIF_INDEC_AICH_TH_TH_HIGH_FLD_RD()                           ((M_CMIF_INDEC_AICH_TH_RD() & CMIF_INDEC_AICH_TH_TH_HIGH_BIT_MASK) >> CMIF_INDEC_AICH_TH_TH_HIGH_BIT_LSB)

#define CMIF_INDEC_AICH_OUT_AICH_RDY_BIT_LSB                          (24)
#define CMIF_INDEC_AICH_OUT_AICH_RDY_BIT_WIDTH                        (8)
#define CMIF_INDEC_AICH_OUT_AICH_RDY_BIT_MASK                         ((UINT32) (((1<<CMIF_INDEC_AICH_OUT_AICH_RDY_BIT_WIDTH)-1) << CMIF_INDEC_AICH_OUT_AICH_RDY_BIT_LSB) )
#define CMIF_INDEC_AICH_OUT_AICH_RDY_FLD_WR(reg, val)                 (reg |= (val) << CMIF_INDEC_AICH_OUT_AICH_RDY_BIT_LSB)
#define CMIF_INDEC_AICH_OUT_AICH_RDY_FLD_RD()                         ((M_CMIF_INDEC_AICH_OUT_RD() & CMIF_INDEC_AICH_OUT_AICH_RDY_BIT_MASK) >> CMIF_INDEC_AICH_OUT_AICH_RDY_BIT_LSB)

#define CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_BIT_LSB                    (16)
#define CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_BIT_WIDTH                  (8)
#define CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_BIT_MASK                   ((UINT32) (((1<<CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_BIT_WIDTH)-1) << CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_BIT_LSB) )
#define CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_FLD_WR(reg, val)           (reg |= (val) << CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_BIT_LSB)
#define CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_FLD_RD()                   ((M_CMIF_INDEC_AICH_OUT_RD() & CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_BIT_MASK) >> CMIF_INDEC_AICH_OUT_EAI_SIGN_INDEX_BIT_LSB)

#define CMIF_INDEC_AICH_OUT_EAI_BIT_LSB                               (8)
#define CMIF_INDEC_AICH_OUT_EAI_BIT_WIDTH                             (8)
#define CMIF_INDEC_AICH_OUT_EAI_BIT_MASK                              ((UINT32) (((1<<CMIF_INDEC_AICH_OUT_EAI_BIT_WIDTH)-1) << CMIF_INDEC_AICH_OUT_EAI_BIT_LSB) )
#define CMIF_INDEC_AICH_OUT_EAI_FLD_WR(reg, val)                      (reg |= (val) << CMIF_INDEC_AICH_OUT_EAI_BIT_LSB)
#define CMIF_INDEC_AICH_OUT_EAI_FLD_RD()                              ((M_CMIF_INDEC_AICH_OUT_RD() & CMIF_INDEC_AICH_OUT_EAI_BIT_MASK) >> CMIF_INDEC_AICH_OUT_EAI_BIT_LSB)

#define CMIF_INDEC_AICH_OUT_AI_BIT_LSB                                (0)
#define CMIF_INDEC_AICH_OUT_AI_BIT_WIDTH                              (8)
#define CMIF_INDEC_AICH_OUT_AI_BIT_MASK                               ((UINT32) (((1<<CMIF_INDEC_AICH_OUT_AI_BIT_WIDTH)-1) << CMIF_INDEC_AICH_OUT_AI_BIT_LSB) )
#define CMIF_INDEC_AICH_OUT_AI_FLD_WR(reg, val)                       (reg |= (val) << CMIF_INDEC_AICH_OUT_AI_BIT_LSB)
#define CMIF_INDEC_AICH_OUT_AI_FLD_RD()                               ((M_CMIF_INDEC_AICH_OUT_RD() & CMIF_INDEC_AICH_OUT_AI_BIT_MASK) >> CMIF_INDEC_AICH_OUT_AI_BIT_LSB)

#define CMIF_INDEC_PICH_OUT_PICH_RDY_BIT_LSB                          (8)
#define CMIF_INDEC_PICH_OUT_PICH_RDY_BIT_WIDTH                        (8)
#define CMIF_INDEC_PICH_OUT_PICH_RDY_BIT_MASK                         ((UINT32) (((1<<CMIF_INDEC_PICH_OUT_PICH_RDY_BIT_WIDTH)-1) << CMIF_INDEC_PICH_OUT_PICH_RDY_BIT_LSB) )
#define CMIF_INDEC_PICH_OUT_PICH_RDY_FLD_WR(reg, val)                 (reg |= (val) << CMIF_INDEC_PICH_OUT_PICH_RDY_BIT_LSB)
#define CMIF_INDEC_PICH_OUT_PICH_RDY_FLD_RD()                         ((M_CMIF_INDEC_PICH_OUT_RD() & CMIF_INDEC_PICH_OUT_PICH_RDY_BIT_MASK) >> CMIF_INDEC_PICH_OUT_PICH_RDY_BIT_LSB)

#define CMIF_INDEC_PICH_OUT_PI_BIT_LSB                                (0)
#define CMIF_INDEC_PICH_OUT_PI_BIT_WIDTH                              (8)
#define CMIF_INDEC_PICH_OUT_PI_BIT_MASK                               ((UINT32) (((1<<CMIF_INDEC_PICH_OUT_PI_BIT_WIDTH)-1) << CMIF_INDEC_PICH_OUT_PI_BIT_LSB) )
#define CMIF_INDEC_PICH_OUT_PI_FLD_WR(reg, val)                       (reg |= (val) << CMIF_INDEC_PICH_OUT_PI_BIT_LSB)
#define CMIF_INDEC_PICH_OUT_PI_FLD_RD()                               ((M_CMIF_INDEC_PICH_OUT_RD() & CMIF_INDEC_PICH_OUT_PI_BIT_MASK) >> CMIF_INDEC_PICH_OUT_PI_BIT_LSB)

#define CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_BIT_LSB                       (16)
#define CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_BIT_WIDTH                     (8)
#define CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_BIT_MASK                      ((UINT32) (((1<<CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_BIT_WIDTH)-1) << CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_BIT_LSB) )
#define CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_FLD_WR(reg, val)              (reg |= (val) << CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_BIT_LSB)
#define CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_FLD_RD()                      ((M_CMIF_INDEC_EAI_EN_PAR_RD() & CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_BIT_MASK) >> CMIF_INDEC_EAI_EN_PAR_EAI_GAMMA_BIT_LSB)

#define CMIF_INDEC_EAI_EN_PAR_TH_POW_H_BIT_LSB                        (8)
#define CMIF_INDEC_EAI_EN_PAR_TH_POW_H_BIT_WIDTH                      (8)
#define CMIF_INDEC_EAI_EN_PAR_TH_POW_H_BIT_MASK                       ((UINT32) (((1<<CMIF_INDEC_EAI_EN_PAR_TH_POW_H_BIT_WIDTH)-1) << CMIF_INDEC_EAI_EN_PAR_TH_POW_H_BIT_LSB) )
#define CMIF_INDEC_EAI_EN_PAR_TH_POW_H_FLD_WR(reg, val)               (reg |= (val) << CMIF_INDEC_EAI_EN_PAR_TH_POW_H_BIT_LSB)
#define CMIF_INDEC_EAI_EN_PAR_TH_POW_H_FLD_RD()                       ((M_CMIF_INDEC_EAI_EN_PAR_RD() & CMIF_INDEC_EAI_EN_PAR_TH_POW_H_BIT_MASK) >> CMIF_INDEC_EAI_EN_PAR_TH_POW_H_BIT_LSB)

#define CMIF_INDEC_EAI_EN_PAR_EAI_EN_BIT_LSB                          (0)
#define CMIF_INDEC_EAI_EN_PAR_EAI_EN_BIT_WIDTH                        (8)
#define CMIF_INDEC_EAI_EN_PAR_EAI_EN_BIT_MASK                         ((UINT32) (((1<<CMIF_INDEC_EAI_EN_PAR_EAI_EN_BIT_WIDTH)-1) << CMIF_INDEC_EAI_EN_PAR_EAI_EN_BIT_LSB) )
#define CMIF_INDEC_EAI_EN_PAR_EAI_EN_FLD_WR(reg, val)                 (reg |= (val) << CMIF_INDEC_EAI_EN_PAR_EAI_EN_BIT_LSB)
#define CMIF_INDEC_EAI_EN_PAR_EAI_EN_FLD_RD()                         ((M_CMIF_INDEC_EAI_EN_PAR_RD() & CMIF_INDEC_EAI_EN_PAR_EAI_EN_BIT_MASK) >> CMIF_INDEC_EAI_EN_PAR_EAI_EN_BIT_LSB)

#define CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_BIT_LSB                        (8)
#define CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_BIT_WIDTH                      (8)
#define CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_BIT_MASK                       ((UINT32) (((1<<CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_BIT_WIDTH)-1) << CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_BIT_LSB) )
#define CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_FLD_WR(reg, val)               (reg |= (val) << CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_BIT_LSB)
#define CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_FLD_RD(i)                      ((M_CMIF_INDEC_TFCI_CTRL_RD(i) & CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_BIT_MASK) >> CMIF_INDEC_TFCI_CTRL_TFCI_EN_0_BIT_LSB)

#define CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_BIT_LSB                     (0)
#define CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_BIT_WIDTH                   (8)
#define CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_BIT_MASK                    ((UINT32) (((1<<CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_BIT_WIDTH)-1) << CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_BIT_LSB) )
#define CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_FLD_WR(reg, val)            (reg |= (val) << CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_BIT_LSB)
#define CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_FLD_RD(i)                   ((M_CMIF_INDEC_TFCI_CTRL_RD(i) & CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_BIT_MASK) >> CMIF_INDEC_TFCI_CTRL_NUM_OF_TFC_0_BIT_LSB)

#define CMIF_INDEC_TFCI_OUT_TFCI_RDY_BIT_LSB                          (16)
#define CMIF_INDEC_TFCI_OUT_TFCI_RDY_BIT_WIDTH                        (8)
#define CMIF_INDEC_TFCI_OUT_TFCI_RDY_BIT_MASK                         ((UINT32) (((1<<CMIF_INDEC_TFCI_OUT_TFCI_RDY_BIT_WIDTH)-1) << CMIF_INDEC_TFCI_OUT_TFCI_RDY_BIT_LSB) )
#define CMIF_INDEC_TFCI_OUT_TFCI_RDY_FLD_WR(reg, val)                 (reg |= (val) << CMIF_INDEC_TFCI_OUT_TFCI_RDY_BIT_LSB)
#define CMIF_INDEC_TFCI_OUT_TFCI_RDY_FLD_RD(i)                        ((M_CMIF_INDEC_TFCI_OUT_RD(i) & CMIF_INDEC_TFCI_OUT_TFCI_RDY_BIT_MASK) >> CMIF_INDEC_TFCI_OUT_TFCI_RDY_BIT_LSB)

#define CMIF_INDEC_TFCI_OUT_TFCI_BIT_LSB                              (0)
#define CMIF_INDEC_TFCI_OUT_TFCI_BIT_WIDTH                            (16)
#define CMIF_INDEC_TFCI_OUT_TFCI_BIT_MASK                             ((UINT32) (((1<<CMIF_INDEC_TFCI_OUT_TFCI_BIT_WIDTH)-1) << CMIF_INDEC_TFCI_OUT_TFCI_BIT_LSB) )
#define CMIF_INDEC_TFCI_OUT_TFCI_FLD_WR(reg, val)                     (reg |= (val) << CMIF_INDEC_TFCI_OUT_TFCI_BIT_LSB)
#define CMIF_INDEC_TFCI_OUT_TFCI_FLD_RD(i)                            ((M_CMIF_INDEC_TFCI_OUT_RD(i) & CMIF_INDEC_TFCI_OUT_TFCI_BIT_MASK) >> CMIF_INDEC_TFCI_OUT_TFCI_BIT_LSB)

#define CMIF_INDEC_AICH_ACC_POW_H_BIT_LSB                             (16)
#define CMIF_INDEC_AICH_ACC_POW_H_BIT_WIDTH                           (16)
#define CMIF_INDEC_AICH_ACC_POW_H_BIT_MASK                            ((UINT32) (((1<<CMIF_INDEC_AICH_ACC_POW_H_BIT_WIDTH)-1) << CMIF_INDEC_AICH_ACC_POW_H_BIT_LSB) )
#define CMIF_INDEC_AICH_ACC_POW_H_FLD_WR(reg, val)                    (reg |= (val) << CMIF_INDEC_AICH_ACC_POW_H_BIT_LSB)
#define CMIF_INDEC_AICH_ACC_POW_H_FLD_RD()                            ((M_CMIF_INDEC_AICH_ACC_RD() & CMIF_INDEC_AICH_ACC_POW_H_BIT_MASK) >> CMIF_INDEC_AICH_ACC_POW_H_BIT_LSB)

#define CMIF_INDEC_AICH_ACC_ACC_BIT_LSB                               (0)
#define CMIF_INDEC_AICH_ACC_ACC_BIT_WIDTH                             (16)
#define CMIF_INDEC_AICH_ACC_ACC_BIT_MASK                              ((UINT32) (((1<<CMIF_INDEC_AICH_ACC_ACC_BIT_WIDTH)-1) << CMIF_INDEC_AICH_ACC_ACC_BIT_LSB) )
#define CMIF_INDEC_AICH_ACC_ACC_FLD_WR(reg, val)                      (reg |= (val) << CMIF_INDEC_AICH_ACC_ACC_BIT_LSB)
#define CMIF_INDEC_AICH_ACC_ACC_FLD_RD()                              ((M_CMIF_INDEC_AICH_ACC_RD() & CMIF_INDEC_AICH_ACC_ACC_BIT_MASK) >> CMIF_INDEC_AICH_ACC_ACC_BIT_LSB)

#define CMIF_INDEC_PICH_ACC_POW_H_BIT_LSB                             (16)
#define CMIF_INDEC_PICH_ACC_POW_H_BIT_WIDTH                           (16)
#define CMIF_INDEC_PICH_ACC_POW_H_BIT_MASK                            ((UINT32) (((1<<CMIF_INDEC_PICH_ACC_POW_H_BIT_WIDTH)-1) << CMIF_INDEC_PICH_ACC_POW_H_BIT_LSB) )
#define CMIF_INDEC_PICH_ACC_POW_H_FLD_WR(reg, val)                    (reg |= (val) << CMIF_INDEC_PICH_ACC_POW_H_BIT_LSB)
#define CMIF_INDEC_PICH_ACC_POW_H_FLD_RD()                            ((M_CMIF_INDEC_PICH_ACC_RD() & CMIF_INDEC_PICH_ACC_POW_H_BIT_MASK) >> CMIF_INDEC_PICH_ACC_POW_H_BIT_LSB)

#define CMIF_INDEC_PICH_ACC_ACC_BIT_LSB                               (0)
#define CMIF_INDEC_PICH_ACC_ACC_BIT_WIDTH                             (16)
#define CMIF_INDEC_PICH_ACC_ACC_BIT_MASK                              ((UINT32) (((1<<CMIF_INDEC_PICH_ACC_ACC_BIT_WIDTH)-1) << CMIF_INDEC_PICH_ACC_ACC_BIT_LSB) )
#define CMIF_INDEC_PICH_ACC_ACC_FLD_WR(reg, val)                      (reg |= (val) << CMIF_INDEC_PICH_ACC_ACC_BIT_LSB)
#define CMIF_INDEC_PICH_ACC_ACC_FLD_RD()                              ((M_CMIF_INDEC_PICH_ACC_RD() & CMIF_INDEC_PICH_ACC_ACC_BIT_MASK) >> CMIF_INDEC_PICH_ACC_ACC_BIT_LSB)

#define CMIF_INDEC_TFCI_STS_MAX_CORR_BIT_LSB                          (0)
#define CMIF_INDEC_TFCI_STS_MAX_CORR_BIT_WIDTH                        (32)
#define CMIF_INDEC_TFCI_STS_MAX_CORR_BIT_MASK                         ((UINT32) (((1<<CMIF_INDEC_TFCI_STS_MAX_CORR_BIT_WIDTH)-1) << CMIF_INDEC_TFCI_STS_MAX_CORR_BIT_LSB) )
#define CMIF_INDEC_TFCI_STS_MAX_CORR_FLD_WR(reg, val)                 (reg |= (val) << CMIF_INDEC_TFCI_STS_MAX_CORR_BIT_LSB)
#define CMIF_INDEC_TFCI_STS_MAX_CORR_FLD_RD(i)                        ((M_CMIF_INDEC_TFCI_STS_RD(i) & CMIF_INDEC_TFCI_STS_MAX_CORR_BIT_MASK) >> CMIF_INDEC_TFCI_STS_MAX_CORR_BIT_LSB)

#define CMIF_INDEC_EAI_ACC_EAI_ACC_BIT_LSB                            (0)
#define CMIF_INDEC_EAI_ACC_EAI_ACC_BIT_WIDTH                          (16)
#define CMIF_INDEC_EAI_ACC_EAI_ACC_BIT_MASK                           ((UINT32) (((1<<CMIF_INDEC_EAI_ACC_EAI_ACC_BIT_WIDTH)-1) << CMIF_INDEC_EAI_ACC_EAI_ACC_BIT_LSB) )
#define CMIF_INDEC_EAI_ACC_EAI_ACC_FLD_WR(reg, val)                   (reg |= (val) << CMIF_INDEC_EAI_ACC_EAI_ACC_BIT_LSB)
#define CMIF_INDEC_EAI_ACC_EAI_ACC_FLD_RD()                           ((M_CMIF_INDEC_EAI_ACC_RD() & CMIF_INDEC_EAI_ACC_EAI_ACC_BIT_MASK) >> CMIF_INDEC_EAI_ACC_EAI_ACC_BIT_LSB)

#endif /* __INDEC_CMIF_H__ */
