#ifndef __RXSRP_CMIF_H__
#define __RXSRP_CMIF_H__

#include "reg_access.h"
#include "base_addr_cmif.h"

#define CMIF_RXSRP_REG_BASE                                           (CMIF_RAKE_RXSRP_OFFSET)
#define CMIF_RXSRP_CTRL                                               (CMIF_RXSRP_REG_BASE + 0x0000)
#define CMIF_RXSRP_RL_RLS_ID_0_C(i)                                   (CMIF_RXSRP_REG_BASE + 0x0004 + ((i) * 0x4))
#define CMIF_RXSRP_RL_RLS_ID_1_C0                                     (CMIF_RXSRP_REG_BASE + 0x000C)
#define CMIF_RXSRP_DLT_SIR_C(i)                                       (CMIF_RXSRP_REG_BASE + 0x0010 + ((i) * 0x4))
#define CMIF_RXSRP_SIG_AMP_0_C(i)                                     (CMIF_RXSRP_REG_BASE + 0x0018 + ((i) * 0x4))
#define CMIF_RXSRP_SIG_AMP_1_C0                                       (CMIF_RXSRP_REG_BASE + 0x0020)
#define CMIF_RXSRP_FDPCH_0_C(i)                                       (CMIF_RXSRP_REG_BASE + 0x0024 + ((i) * 0x4))
#define CMIF_RXSRP_FDPCH_1_C0                                         (CMIF_RXSRP_REG_BASE + 0x002C)
#define CMIF_RXSRP_SVC_ID_C(i)                                        (CMIF_RXSRP_REG_BASE + 0x0034 + ((i) * 0x4))
#define CMIF_RXSRP_SVC_CHANGE_C(i)                                    (CMIF_RXSRP_REG_BASE + 0x003C + ((i) * 0x4))
#define CMIF_RXSRP_DF_TRAN_C0                                         (CMIF_RXSRP_REG_BASE + 0x0044)
#define CMIF_RXSRP_CLTD_RST_C0                                        (CMIF_RXSRP_REG_BASE + 0x0048)
#define CMIF_RXSRP_CER_C(i)                                           (CMIF_RXSRP_REG_BASE + 0x004C + ((i) * 0x4))
#define CMIF_RXSRP_CLTD_CTRL_0_C0                                     (CMIF_RXSRP_REG_BASE + 0x0054)
#define CMIF_RXSRP_CLTD_CTRL_1_C0                                     (CMIF_RXSRP_REG_BASE + 0x0058)
#define CMIF_RXSRP_CLTD_FBI_C0                                        (CMIF_RXSRP_REG_BASE + 0x005C)
#define CMIF_RXSRP_CLTD_INFO0_C0                                      (CMIF_RXSRP_REG_BASE + 0x0060)
#define CMIF_RXSRP_CLTD_INFO1_C0                                      (CMIF_RXSRP_REG_BASE + 0x0064)
#define CMIF_RXSRP_CLTD_INFO2_C0                                      (CMIF_RXSRP_REG_BASE + 0x0068)
#define CMIF_RXSRP_SIR_RST_C(i)                                       (CMIF_RXSRP_REG_BASE + 0x006C + ((i) * 0x4))
#define CMIF_RXSRP_SIR_PO2_0_C0                                       (CMIF_RXSRP_REG_BASE + 0x0074)
#define CMIF_RXSRP_SIR_PO2_1_C0                                       (CMIF_RXSRP_REG_BASE + 0x0078)
#define CMIF_RXSRP_TPC_PCA_C(i)                                       (CMIF_RXSRP_REG_BASE + 0x007C + ((i) * 0x4))
#define CMIF_RXSRP_TPC_RELI_TH_C(i)                                   (CMIF_RXSRP_REG_BASE + 0x0084 + ((i) * 0x4))
#define CMIF_RXSRP_TPC_CTRL_C(i)                                      (CMIF_RXSRP_REG_BASE + 0x008C + ((i) * 0x4))
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C(i)                          (CMIF_RXSRP_REG_BASE + 0x0094 + ((i) * 0x4))
#define CMIF_RXSRP_TPC_FRAME_C(i)                                     (CMIF_RXSRP_REG_BASE + 0x009C + ((i) * 0x4))
#define CMIF_RXSRP_GAP_FRAME_C(i)                                     (CMIF_RXSRP_REG_BASE + 0x00A4 + ((i) * 0x4))
#define CMIF_RXSRP_DPC_CTRL_C(i)                                      (CMIF_RXSRP_REG_BASE + 0x00AC + ((i) * 0x4))
#define CMIF_RXSRP_DPC_TGT_SIR_C(i)                                   (CMIF_RXSRP_REG_BASE + 0x00B4 + ((i) * 0x4))
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C(i)                            (CMIF_RXSRP_REG_BASE + 0x00BC + ((i) * 0x4))
#define CMIF_RXSRP_DPC_FRAME_C(i)                                     (CMIF_RXSRP_REG_BASE + 0x00C4 + ((i) * 0x4))
#define CMIF_RXSRP_DPC_WIND_UP_C(i)                                   (CMIF_RXSRP_REG_BASE + 0x00CC + ((i) * 0x4))
#define CMIF_RXSRP_DPC_WIND_DN_C(i)                                   (CMIF_RXSRP_REG_BASE + 0x00D4 + ((i) * 0x4))
#define CMIF_RXSRP_DPC_SIR_LTA_C(i)                                   (CMIF_RXSRP_REG_BASE + 0x00DC + ((i) * 0x4))
#define CMIF_RXSRP_PO3                                                (CMIF_RXSRP_REG_BASE + 0x00E4)
#define CMIF_RXSRP_WI_FROM_DPCCH                                      (CMIF_RXSRP_REG_BASE + 0x00E8)

#define M_CMIF_RXSRP_CTRL_RD()                                        REG_READ(CMIF_RXSRP_CTRL)
#define M_CMIF_RXSRP_RL_RLS_ID_0_C_RD(i)                              REG_READ(CMIF_RXSRP_RL_RLS_ID_0_C(i))
#define M_CMIF_RXSRP_RL_RLS_ID_1_C0_RD()                              REG_READ(CMIF_RXSRP_RL_RLS_ID_1_C0)
#define M_CMIF_RXSRP_DLT_SIR_C_RD(i)                                  REG_READ(CMIF_RXSRP_DLT_SIR_C(i))
#define M_CMIF_RXSRP_SIG_AMP_0_C_RD(i)                                REG_READ(CMIF_RXSRP_SIG_AMP_0_C(i))
#define M_CMIF_RXSRP_SIG_AMP_1_C0_RD()                                REG_READ(CMIF_RXSRP_SIG_AMP_1_C0)
#define M_CMIF_RXSRP_FDPCH_0_C_RD(i)                                  REG_READ(CMIF_RXSRP_FDPCH_0_C(i))
#define M_CMIF_RXSRP_FDPCH_1_C0_RD()                                  REG_READ(CMIF_RXSRP_FDPCH_1_C0)
#define M_CMIF_RXSRP_SVC_ID_C_RD(i)                                   REG_READ(CMIF_RXSRP_SVC_ID_C(i))
#define M_CMIF_RXSRP_SVC_CHANGE_C_RD(i)                               REG_READ(CMIF_RXSRP_SVC_CHANGE_C(i))
#define M_CMIF_RXSRP_DF_TRAN_C0_RD()                                  REG_READ(CMIF_RXSRP_DF_TRAN_C0)
#define M_CMIF_RXSRP_CLTD_RST_C0_RD()                                 REG_READ(CMIF_RXSRP_CLTD_RST_C0)
#define M_CMIF_RXSRP_CER_C_RD(i)                                      REG_READ(CMIF_RXSRP_CER_C(i))
#define M_CMIF_RXSRP_CLTD_CTRL_0_C0_RD()                              REG_READ(CMIF_RXSRP_CLTD_CTRL_0_C0)
#define M_CMIF_RXSRP_CLTD_CTRL_1_C0_RD()                              REG_READ(CMIF_RXSRP_CLTD_CTRL_1_C0)
#define M_CMIF_RXSRP_CLTD_FBI_C0_RD()                                 REG_READ(CMIF_RXSRP_CLTD_FBI_C0)
#define M_CMIF_RXSRP_CLTD_INFO0_C0_RD()                               REG_READ(CMIF_RXSRP_CLTD_INFO0_C0)
#define M_CMIF_RXSRP_CLTD_INFO1_C0_RD()                               REG_READ(CMIF_RXSRP_CLTD_INFO1_C0)
#define M_CMIF_RXSRP_CLTD_INFO2_C0_RD()                               REG_READ(CMIF_RXSRP_CLTD_INFO2_C0)
#define M_CMIF_RXSRP_SIR_RST_C_RD(i)                                  REG_READ(CMIF_RXSRP_SIR_RST_C(i))
#define M_CMIF_RXSRP_SIR_PO2_0_C0_RD()                                REG_READ(CMIF_RXSRP_SIR_PO2_0_C0)
#define M_CMIF_RXSRP_SIR_PO2_1_C0_RD()                                REG_READ(CMIF_RXSRP_SIR_PO2_1_C0)
#define M_CMIF_RXSRP_TPC_PCA_C_RD(i)                                  REG_READ(CMIF_RXSRP_TPC_PCA_C(i))
#define M_CMIF_RXSRP_TPC_RELI_TH_C_RD(i)                              REG_READ(CMIF_RXSRP_TPC_RELI_TH_C(i))
#define M_CMIF_RXSRP_TPC_CTRL_C_RD(i)                                 REG_READ(CMIF_RXSRP_TPC_CTRL_C(i))
#define M_CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_RD(i)                     REG_READ(CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C(i))
#define M_CMIF_RXSRP_TPC_FRAME_C_RD(i)                                REG_READ(CMIF_RXSRP_TPC_FRAME_C(i))
#define M_CMIF_RXSRP_GAP_FRAME_C_RD(i)                                REG_READ(CMIF_RXSRP_GAP_FRAME_C(i))
#define M_CMIF_RXSRP_DPC_CTRL_C_RD(i)                                 REG_READ(CMIF_RXSRP_DPC_CTRL_C(i))
#define M_CMIF_RXSRP_DPC_TGT_SIR_C_RD(i)                              REG_READ(CMIF_RXSRP_DPC_TGT_SIR_C(i))
#define M_CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_RD(i)                       REG_READ(CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C(i))
#define M_CMIF_RXSRP_DPC_FRAME_C_RD(i)                                REG_READ(CMIF_RXSRP_DPC_FRAME_C(i))
#define M_CMIF_RXSRP_DPC_WIND_UP_C_RD(i)                              REG_READ(CMIF_RXSRP_DPC_WIND_UP_C(i))
#define M_CMIF_RXSRP_DPC_WIND_DN_C_RD(i)                              REG_READ(CMIF_RXSRP_DPC_WIND_DN_C(i))
#define M_CMIF_RXSRP_DPC_SIR_LTA_C_RD(i)                              REG_READ(CMIF_RXSRP_DPC_SIR_LTA_C(i))
#define M_CMIF_RXSRP_PO3_RD()                                         REG_READ(CMIF_RXSRP_PO3)
#define M_CMIF_RXSRP_WI_FROM_DPCCH_RD()                               REG_READ(CMIF_RXSRP_WI_FROM_DPCCH)

#define M_CMIF_RXSRP_CTRL_WR(reg)                                     REG_WRITE(CMIF_RXSRP_CTRL, reg)
#define M_CMIF_RXSRP_RL_RLS_ID_0_C_WR(i, reg)                         REG_WRITE(CMIF_RXSRP_RL_RLS_ID_0_C(i), reg)
#define M_CMIF_RXSRP_RL_RLS_ID_1_C0_WR(reg)                           REG_WRITE(CMIF_RXSRP_RL_RLS_ID_1_C0, reg)
#define M_CMIF_RXSRP_DLT_SIR_C_WR(i, reg)                             REG_WRITE(CMIF_RXSRP_DLT_SIR_C(i), reg)
#define M_CMIF_RXSRP_SIG_AMP_0_C_WR(i, reg)                           REG_WRITE(CMIF_RXSRP_SIG_AMP_0_C(i), reg)
#define M_CMIF_RXSRP_SIG_AMP_1_C0_WR(reg)                             REG_WRITE(CMIF_RXSRP_SIG_AMP_1_C0, reg)
#define M_CMIF_RXSRP_FDPCH_0_C_WR(i, reg)                             REG_WRITE(CMIF_RXSRP_FDPCH_0_C(i), reg)
#define M_CMIF_RXSRP_FDPCH_1_C0_WR(reg)                               REG_WRITE(CMIF_RXSRP_FDPCH_1_C0, reg)
#define M_CMIF_RXSRP_SVC_ID_C_WR(i, reg)                              REG_WRITE(CMIF_RXSRP_SVC_ID_C(i), reg)
#define M_CMIF_RXSRP_SVC_CHANGE_C_WR(i, reg)                          REG_WRITE(CMIF_RXSRP_SVC_CHANGE_C(i), reg)
#define M_CMIF_RXSRP_DF_TRAN_C0_WR(reg)                               REG_WRITE(CMIF_RXSRP_DF_TRAN_C0, reg)
#define M_CMIF_RXSRP_CLTD_RST_C0_WR(reg)                              REG_WRITE(CMIF_RXSRP_CLTD_RST_C0, reg)
#define M_CMIF_RXSRP_CER_C_WR(i, reg)                                 REG_WRITE(CMIF_RXSRP_CER_C(i), reg)
#define M_CMIF_RXSRP_CLTD_CTRL_0_C0_WR(reg)                           REG_WRITE(CMIF_RXSRP_CLTD_CTRL_0_C0, reg)
#define M_CMIF_RXSRP_CLTD_CTRL_1_C0_WR(reg)                           REG_WRITE(CMIF_RXSRP_CLTD_CTRL_1_C0, reg)
#define M_CMIF_RXSRP_CLTD_FBI_C0_WR(reg)                              REG_WRITE(CMIF_RXSRP_CLTD_FBI_C0, reg)
#define M_CMIF_RXSRP_CLTD_INFO0_C0_WR(reg)                            REG_WRITE(CMIF_RXSRP_CLTD_INFO0_C0, reg)
#define M_CMIF_RXSRP_CLTD_INFO1_C0_WR(reg)                            REG_WRITE(CMIF_RXSRP_CLTD_INFO1_C0, reg)
#define M_CMIF_RXSRP_CLTD_INFO2_C0_WR(reg)                            REG_WRITE(CMIF_RXSRP_CLTD_INFO2_C0, reg)
#define M_CMIF_RXSRP_SIR_RST_C_WR(i, reg)                             REG_WRITE(CMIF_RXSRP_SIR_RST_C(i), reg)
#define M_CMIF_RXSRP_SIR_PO2_0_C0_WR(reg)                             REG_WRITE(CMIF_RXSRP_SIR_PO2_0_C0, reg)
#define M_CMIF_RXSRP_SIR_PO2_1_C0_WR(reg)                             REG_WRITE(CMIF_RXSRP_SIR_PO2_1_C0, reg)
#define M_CMIF_RXSRP_TPC_PCA_C_WR(i, reg)                             REG_WRITE(CMIF_RXSRP_TPC_PCA_C(i), reg)
#define M_CMIF_RXSRP_TPC_RELI_TH_C_WR(i, reg)                         REG_WRITE(CMIF_RXSRP_TPC_RELI_TH_C(i), reg)
#define M_CMIF_RXSRP_TPC_CTRL_C_WR(i, reg)                            REG_WRITE(CMIF_RXSRP_TPC_CTRL_C(i), reg)
#define M_CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_WR(i, reg)                REG_WRITE(CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C(i), reg)
#define M_CMIF_RXSRP_TPC_FRAME_C_WR(i, reg)                           REG_WRITE(CMIF_RXSRP_TPC_FRAME_C(i), reg)
#define M_CMIF_RXSRP_GAP_FRAME_C_WR(i, reg)                           REG_WRITE(CMIF_RXSRP_GAP_FRAME_C(i), reg)
#define M_CMIF_RXSRP_DPC_CTRL_C_WR(i, reg)                            REG_WRITE(CMIF_RXSRP_DPC_CTRL_C(i), reg)
#define M_CMIF_RXSRP_DPC_TGT_SIR_C_WR(i, reg)                         REG_WRITE(CMIF_RXSRP_DPC_TGT_SIR_C(i), reg)
#define M_CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_WR(i, reg)                  REG_WRITE(CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C(i), reg)
#define M_CMIF_RXSRP_DPC_FRAME_C_WR(i, reg)                           REG_WRITE(CMIF_RXSRP_DPC_FRAME_C(i), reg)
#define M_CMIF_RXSRP_DPC_WIND_UP_C_WR(i, reg)                         REG_WRITE(CMIF_RXSRP_DPC_WIND_UP_C(i), reg)
#define M_CMIF_RXSRP_DPC_WIND_DN_C_WR(i, reg)                         REG_WRITE(CMIF_RXSRP_DPC_WIND_DN_C(i), reg)
#define M_CMIF_RXSRP_DPC_SIR_LTA_C_WR(i, reg)                         REG_WRITE(CMIF_RXSRP_DPC_SIR_LTA_C(i), reg)
#define M_CMIF_RXSRP_PO3_WR(reg)                                      REG_WRITE(CMIF_RXSRP_PO3, reg)
#define M_CMIF_RXSRP_WI_FROM_DPCCH_WR(reg)                            REG_WRITE(CMIF_RXSRP_WI_FROM_DPCCH, reg)

#define CMIF_RXSRP_CTRL_RST_BIT_LSB                                   (0)
#define CMIF_RXSRP_CTRL_RST_BIT_WIDTH                                 (8)
#define CMIF_RXSRP_CTRL_RST_BIT_MASK                                  ((UINT32) (((1<<CMIF_RXSRP_CTRL_RST_BIT_WIDTH)-1) << CMIF_RXSRP_CTRL_RST_BIT_LSB) )
#define CMIF_RXSRP_CTRL_RST_FLD_WR(reg, val)                          (reg |= (val) << CMIF_RXSRP_CTRL_RST_BIT_LSB)
#define CMIF_RXSRP_CTRL_RST_FLD_RD()                                  ((M_CMIF_RXSRP_CTRL_RD() & CMIF_RXSRP_CTRL_RST_BIT_MASK) >> CMIF_RXSRP_CTRL_RST_BIT_LSB)

#define CMIF_RXSRP_RL_RLS_ID_0_C_RL3_BIT_LSB                          (24)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL3_BIT_WIDTH                        (8)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL3_BIT_MASK                         ((UINT32) (((1<<CMIF_RXSRP_RL_RLS_ID_0_C_RL3_BIT_WIDTH)-1) << CMIF_RXSRP_RL_RLS_ID_0_C_RL3_BIT_LSB) )
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL3_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXSRP_RL_RLS_ID_0_C_RL3_BIT_LSB)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL3_FLD_RD(i)                        ((M_CMIF_RXSRP_RL_RLS_ID_0_C_RD(i) & CMIF_RXSRP_RL_RLS_ID_0_C_RL3_BIT_MASK) >> CMIF_RXSRP_RL_RLS_ID_0_C_RL3_BIT_LSB)

#define CMIF_RXSRP_RL_RLS_ID_0_C_RL2_BIT_LSB                          (16)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL2_BIT_WIDTH                        (8)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL2_BIT_MASK                         ((UINT32) (((1<<CMIF_RXSRP_RL_RLS_ID_0_C_RL2_BIT_WIDTH)-1) << CMIF_RXSRP_RL_RLS_ID_0_C_RL2_BIT_LSB) )
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL2_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXSRP_RL_RLS_ID_0_C_RL2_BIT_LSB)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL2_FLD_RD(i)                        ((M_CMIF_RXSRP_RL_RLS_ID_0_C_RD(i) & CMIF_RXSRP_RL_RLS_ID_0_C_RL2_BIT_MASK) >> CMIF_RXSRP_RL_RLS_ID_0_C_RL2_BIT_LSB)

#define CMIF_RXSRP_RL_RLS_ID_0_C_RL1_BIT_LSB                          (8)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL1_BIT_WIDTH                        (8)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL1_BIT_MASK                         ((UINT32) (((1<<CMIF_RXSRP_RL_RLS_ID_0_C_RL1_BIT_WIDTH)-1) << CMIF_RXSRP_RL_RLS_ID_0_C_RL1_BIT_LSB) )
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL1_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXSRP_RL_RLS_ID_0_C_RL1_BIT_LSB)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL1_FLD_RD(i)                        ((M_CMIF_RXSRP_RL_RLS_ID_0_C_RD(i) & CMIF_RXSRP_RL_RLS_ID_0_C_RL1_BIT_MASK) >> CMIF_RXSRP_RL_RLS_ID_0_C_RL1_BIT_LSB)

#define CMIF_RXSRP_RL_RLS_ID_0_C_RL0_BIT_LSB                          (0)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL0_BIT_WIDTH                        (8)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL0_BIT_MASK                         ((UINT32) (((1<<CMIF_RXSRP_RL_RLS_ID_0_C_RL0_BIT_WIDTH)-1) << CMIF_RXSRP_RL_RLS_ID_0_C_RL0_BIT_LSB) )
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL0_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXSRP_RL_RLS_ID_0_C_RL0_BIT_LSB)
#define CMIF_RXSRP_RL_RLS_ID_0_C_RL0_FLD_RD(i)                        ((M_CMIF_RXSRP_RL_RLS_ID_0_C_RD(i) & CMIF_RXSRP_RL_RLS_ID_0_C_RL0_BIT_MASK) >> CMIF_RXSRP_RL_RLS_ID_0_C_RL0_BIT_LSB)

#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_BIT_LSB                         (8)
#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_BIT_WIDTH                       (8)
#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_BIT_WIDTH)-1) << CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_BIT_LSB) )
#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_BIT_LSB)
#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_FLD_RD()                        ((M_CMIF_RXSRP_RL_RLS_ID_1_C0_RD() & CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_BIT_MASK) >> CMIF_RXSRP_RL_RLS_ID_1_C0_RL5_BIT_LSB)

#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_BIT_LSB                         (0)
#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_BIT_WIDTH                       (8)
#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_BIT_WIDTH)-1) << CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_BIT_LSB) )
#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_BIT_LSB)
#define CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_FLD_RD()                        ((M_CMIF_RXSRP_RL_RLS_ID_1_C0_RD() & CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_BIT_MASK) >> CMIF_RXSRP_RL_RLS_ID_1_C0_RL4_BIT_LSB)

#define CMIF_RXSRP_DLT_SIR_C_DLT_SIR_BIT_LSB                          (0)
#define CMIF_RXSRP_DLT_SIR_C_DLT_SIR_BIT_WIDTH                        (16)
#define CMIF_RXSRP_DLT_SIR_C_DLT_SIR_BIT_MASK                         ((UINT32) (((1<<CMIF_RXSRP_DLT_SIR_C_DLT_SIR_BIT_WIDTH)-1) << CMIF_RXSRP_DLT_SIR_C_DLT_SIR_BIT_LSB) )
#define CMIF_RXSRP_DLT_SIR_C_DLT_SIR_FLD_WR(reg, val)                 (reg |= (val) << CMIF_RXSRP_DLT_SIR_C_DLT_SIR_BIT_LSB)
#define CMIF_RXSRP_DLT_SIR_C_DLT_SIR_FLD_RD(i)                        ((M_CMIF_RXSRP_DLT_SIR_C_RD(i) & CMIF_RXSRP_DLT_SIR_C_DLT_SIR_BIT_MASK) >> CMIF_RXSRP_DLT_SIR_C_DLT_SIR_BIT_LSB)

#define CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_BIT_LSB                        (24)
#define CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_BIT_WIDTH                      (8)
#define CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_BIT_WIDTH)-1) << CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_BIT_LSB) )
#define CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_BIT_LSB)
#define CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_FLD_RD(i)                      ((M_CMIF_RXSRP_SIG_AMP_0_C_RD(i) & CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_BIT_MASK) >> CMIF_RXSRP_SIG_AMP_0_C_MA_FLAG_BIT_LSB)

#define CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_BIT_LSB                         (16)
#define CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_BIT_WIDTH                       (8)
#define CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_BIT_WIDTH)-1) << CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_BIT_LSB) )
#define CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_BIT_LSB)
#define CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_FLD_RD(i)                       ((M_CMIF_RXSRP_SIG_AMP_0_C_RD(i) & CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_BIT_MASK) >> CMIF_RXSRP_SIG_AMP_0_C_SL_NUM_BIT_LSB)

#define CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_BIT_LSB                        (0)
#define CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_BIT_WIDTH                      (16)
#define CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_BIT_WIDTH)-1) << CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_BIT_LSB) )
#define CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_BIT_LSB)
#define CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_FLD_RD(i)                      ((M_CMIF_RXSRP_SIG_AMP_0_C_RD(i) & CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_BIT_MASK) >> CMIF_RXSRP_SIG_AMP_0_C_SIR_FRM_BIT_LSB)

#define CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_BIT_LSB                        (8)
#define CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_BIT_WIDTH                      (8)
#define CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_BIT_WIDTH)-1) << CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_BIT_LSB) )
#define CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_BIT_LSB)
#define CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_FLD_RD()                       ((M_CMIF_RXSRP_SIG_AMP_1_C0_RD() & CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_BIT_MASK) >> CMIF_RXSRP_SIG_AMP_1_C0_LAMBDA_BIT_LSB)

#define CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_BIT_LSB                      (0)
#define CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_BIT_WIDTH                    (8)
#define CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_BIT_MASK                     ((UINT32) (((1<<CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_BIT_WIDTH)-1) << CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_BIT_LSB) )
#define CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_BIT_LSB)
#define CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_FLD_RD()                     ((M_CMIF_RXSRP_SIG_AMP_1_C0_RD() & CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_BIT_MASK) >> CMIF_RXSRP_SIG_AMP_1_C0_PHY_TYPE_BIT_LSB)

#define CMIF_RXSRP_FDPCH_0_C_RL3_BIT_LSB                              (24)
#define CMIF_RXSRP_FDPCH_0_C_RL3_BIT_WIDTH                            (8)
#define CMIF_RXSRP_FDPCH_0_C_RL3_BIT_MASK                             ((UINT32) (((1<<CMIF_RXSRP_FDPCH_0_C_RL3_BIT_WIDTH)-1) << CMIF_RXSRP_FDPCH_0_C_RL3_BIT_LSB) )
#define CMIF_RXSRP_FDPCH_0_C_RL3_FLD_WR(reg, val)                     (reg |= (val) << CMIF_RXSRP_FDPCH_0_C_RL3_BIT_LSB)
#define CMIF_RXSRP_FDPCH_0_C_RL3_FLD_RD(i)                            ((M_CMIF_RXSRP_FDPCH_0_C_RD(i) & CMIF_RXSRP_FDPCH_0_C_RL3_BIT_MASK) >> CMIF_RXSRP_FDPCH_0_C_RL3_BIT_LSB)

#define CMIF_RXSRP_FDPCH_0_C_RL2_BIT_LSB                              (16)
#define CMIF_RXSRP_FDPCH_0_C_RL2_BIT_WIDTH                            (8)
#define CMIF_RXSRP_FDPCH_0_C_RL2_BIT_MASK                             ((UINT32) (((1<<CMIF_RXSRP_FDPCH_0_C_RL2_BIT_WIDTH)-1) << CMIF_RXSRP_FDPCH_0_C_RL2_BIT_LSB) )
#define CMIF_RXSRP_FDPCH_0_C_RL2_FLD_WR(reg, val)                     (reg |= (val) << CMIF_RXSRP_FDPCH_0_C_RL2_BIT_LSB)
#define CMIF_RXSRP_FDPCH_0_C_RL2_FLD_RD(i)                            ((M_CMIF_RXSRP_FDPCH_0_C_RD(i) & CMIF_RXSRP_FDPCH_0_C_RL2_BIT_MASK) >> CMIF_RXSRP_FDPCH_0_C_RL2_BIT_LSB)

#define CMIF_RXSRP_FDPCH_0_C_RL1_BIT_LSB                              (8)
#define CMIF_RXSRP_FDPCH_0_C_RL1_BIT_WIDTH                            (8)
#define CMIF_RXSRP_FDPCH_0_C_RL1_BIT_MASK                             ((UINT32) (((1<<CMIF_RXSRP_FDPCH_0_C_RL1_BIT_WIDTH)-1) << CMIF_RXSRP_FDPCH_0_C_RL1_BIT_LSB) )
#define CMIF_RXSRP_FDPCH_0_C_RL1_FLD_WR(reg, val)                     (reg |= (val) << CMIF_RXSRP_FDPCH_0_C_RL1_BIT_LSB)
#define CMIF_RXSRP_FDPCH_0_C_RL1_FLD_RD(i)                            ((M_CMIF_RXSRP_FDPCH_0_C_RD(i) & CMIF_RXSRP_FDPCH_0_C_RL1_BIT_MASK) >> CMIF_RXSRP_FDPCH_0_C_RL1_BIT_LSB)

#define CMIF_RXSRP_FDPCH_0_C_RL0_BIT_LSB                              (0)
#define CMIF_RXSRP_FDPCH_0_C_RL0_BIT_WIDTH                            (8)
#define CMIF_RXSRP_FDPCH_0_C_RL0_BIT_MASK                             ((UINT32) (((1<<CMIF_RXSRP_FDPCH_0_C_RL0_BIT_WIDTH)-1) << CMIF_RXSRP_FDPCH_0_C_RL0_BIT_LSB) )
#define CMIF_RXSRP_FDPCH_0_C_RL0_FLD_WR(reg, val)                     (reg |= (val) << CMIF_RXSRP_FDPCH_0_C_RL0_BIT_LSB)
#define CMIF_RXSRP_FDPCH_0_C_RL0_FLD_RD(i)                            ((M_CMIF_RXSRP_FDPCH_0_C_RD(i) & CMIF_RXSRP_FDPCH_0_C_RL0_BIT_MASK) >> CMIF_RXSRP_FDPCH_0_C_RL0_BIT_LSB)

#define CMIF_RXSRP_FDPCH_1_C0_RL5_BIT_LSB                             (8)
#define CMIF_RXSRP_FDPCH_1_C0_RL5_BIT_WIDTH                           (8)
#define CMIF_RXSRP_FDPCH_1_C0_RL5_BIT_MASK                            ((UINT32) (((1<<CMIF_RXSRP_FDPCH_1_C0_RL5_BIT_WIDTH)-1) << CMIF_RXSRP_FDPCH_1_C0_RL5_BIT_LSB) )
#define CMIF_RXSRP_FDPCH_1_C0_RL5_FLD_WR(reg, val)                    (reg |= (val) << CMIF_RXSRP_FDPCH_1_C0_RL5_BIT_LSB)
#define CMIF_RXSRP_FDPCH_1_C0_RL5_FLD_RD()                            ((M_CMIF_RXSRP_FDPCH_1_C0_RD() & CMIF_RXSRP_FDPCH_1_C0_RL5_BIT_MASK) >> CMIF_RXSRP_FDPCH_1_C0_RL5_BIT_LSB)

#define CMIF_RXSRP_FDPCH_1_C0_RL4_BIT_LSB                             (0)
#define CMIF_RXSRP_FDPCH_1_C0_RL4_BIT_WIDTH                           (8)
#define CMIF_RXSRP_FDPCH_1_C0_RL4_BIT_MASK                            ((UINT32) (((1<<CMIF_RXSRP_FDPCH_1_C0_RL4_BIT_WIDTH)-1) << CMIF_RXSRP_FDPCH_1_C0_RL4_BIT_LSB) )
#define CMIF_RXSRP_FDPCH_1_C0_RL4_FLD_WR(reg, val)                    (reg |= (val) << CMIF_RXSRP_FDPCH_1_C0_RL4_BIT_LSB)
#define CMIF_RXSRP_FDPCH_1_C0_RL4_FLD_RD()                            ((M_CMIF_RXSRP_FDPCH_1_C0_RD() & CMIF_RXSRP_FDPCH_1_C0_RL4_BIT_MASK) >> CMIF_RXSRP_FDPCH_1_C0_RL4_BIT_LSB)

#define CMIF_RXSRP_SVC_ID_C_SVC_ID_BIT_LSB                            (0)
#define CMIF_RXSRP_SVC_ID_C_SVC_ID_BIT_WIDTH                          (8)
#define CMIF_RXSRP_SVC_ID_C_SVC_ID_BIT_MASK                           ((UINT32) (((1<<CMIF_RXSRP_SVC_ID_C_SVC_ID_BIT_WIDTH)-1) << CMIF_RXSRP_SVC_ID_C_SVC_ID_BIT_LSB) )
#define CMIF_RXSRP_SVC_ID_C_SVC_ID_FLD_WR(reg, val)                   (reg |= (val) << CMIF_RXSRP_SVC_ID_C_SVC_ID_BIT_LSB)
#define CMIF_RXSRP_SVC_ID_C_SVC_ID_FLD_RD(i)                          ((M_CMIF_RXSRP_SVC_ID_C_RD(i) & CMIF_RXSRP_SVC_ID_C_SVC_ID_BIT_MASK) >> CMIF_RXSRP_SVC_ID_C_SVC_ID_BIT_LSB)

#define CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_BIT_LSB                    (0)
#define CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_BIT_WIDTH                  (8)
#define CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_BIT_MASK                   ((UINT32) (((1<<CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_BIT_WIDTH)-1) << CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_BIT_LSB) )
#define CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_FLD_WR(reg, val)           (reg |= (val) << CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_BIT_LSB)
#define CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_FLD_RD(i)                  ((M_CMIF_RXSRP_SVC_CHANGE_C_RD(i) & CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_BIT_MASK) >> CMIF_RXSRP_SVC_CHANGE_C_SVC_CHANGE_BIT_LSB)

#define CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_BIT_LSB                         (0)
#define CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_BIT_WIDTH                       (8)
#define CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_BIT_WIDTH)-1) << CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_BIT_LSB) )
#define CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_BIT_LSB)
#define CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_FLD_RD()                        ((M_CMIF_RXSRP_DF_TRAN_C0_RD() & CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_BIT_MASK) >> CMIF_RXSRP_DF_TRAN_C0_DF_TRAN_BIT_LSB)

#define CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_BIT_LSB                       (0)
#define CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_BIT_WIDTH                     (8)
#define CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_BIT_LSB) )
#define CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_BIT_LSB)
#define CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_FLD_RD()                      ((M_CMIF_RXSRP_CLTD_RST_C0_RD() & CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_BIT_MASK) >> CMIF_RXSRP_CLTD_RST_C0_RL_RECFG_BIT_LSB)

#define CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_BIT_LSB                    (16)
#define CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_BIT_WIDTH                  (16)
#define CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_BIT_MASK                   ((UINT32) (((1<<CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_BIT_WIDTH)-1) << CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_BIT_LSB) )
#define CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_FLD_WR(reg, val)           (reg |= (val) << CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_BIT_LSB)
#define CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_FLD_RD(i)                  ((M_CMIF_RXSRP_CER_C_RD(i) & CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_BIT_MASK) >> CMIF_RXSRP_CER_C_MISMATCH_TPC_SLOT_BIT_LSB)

#define CMIF_RXSRP_CER_C_VALID_TPC_SLOT_BIT_LSB                       (0)
#define CMIF_RXSRP_CER_C_VALID_TPC_SLOT_BIT_WIDTH                     (16)
#define CMIF_RXSRP_CER_C_VALID_TPC_SLOT_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_CER_C_VALID_TPC_SLOT_BIT_WIDTH)-1) << CMIF_RXSRP_CER_C_VALID_TPC_SLOT_BIT_LSB) )
#define CMIF_RXSRP_CER_C_VALID_TPC_SLOT_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_CER_C_VALID_TPC_SLOT_BIT_LSB)
#define CMIF_RXSRP_CER_C_VALID_TPC_SLOT_FLD_RD(i)                     ((M_CMIF_RXSRP_CER_C_RD(i) & CMIF_RXSRP_CER_C_VALID_TPC_SLOT_BIT_MASK) >> CMIF_RXSRP_CER_C_VALID_TPC_SLOT_BIT_LSB)

#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_BIT_LSB                        (24)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_BIT_WIDTH                      (8)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_BIT_LSB) )
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_BIT_LSB)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_FLD_RD()                       ((M_CMIF_RXSRP_CLTD_CTRL_0_C0_RD() & CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_BIT_MASK) >> CMIF_RXSRP_CLTD_CTRL_0_C0_ATM3_BIT_LSB)

#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_BIT_LSB                        (16)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_BIT_WIDTH                      (8)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_BIT_LSB) )
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_BIT_LSB)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_FLD_RD()                       ((M_CMIF_RXSRP_CLTD_CTRL_0_C0_RD() & CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_BIT_MASK) >> CMIF_RXSRP_CLTD_CTRL_0_C0_ATM2_BIT_LSB)

#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_BIT_LSB                        (8)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_BIT_WIDTH                      (8)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_BIT_LSB) )
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_BIT_LSB)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_FLD_RD()                       ((M_CMIF_RXSRP_CLTD_CTRL_0_C0_RD() & CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_BIT_MASK) >> CMIF_RXSRP_CLTD_CTRL_0_C0_ATM1_BIT_LSB)

#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_BIT_LSB                        (0)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_BIT_WIDTH                      (8)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_BIT_LSB) )
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_BIT_LSB)
#define CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_FLD_RD()                       ((M_CMIF_RXSRP_CLTD_CTRL_0_C0_RD() & CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_BIT_MASK) >> CMIF_RXSRP_CLTD_CTRL_0_C0_ATM0_BIT_LSB)

#define CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_BIT_LSB                     (16)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_BIT_WIDTH                   (8)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_BIT_MASK                    ((UINT32) (((1<<CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_BIT_LSB) )
#define CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_FLD_WR(reg, val)            (reg |= (val) << CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_BIT_LSB)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_FLD_RD()                    ((M_CMIF_RXSRP_CLTD_CTRL_1_C0_RD() & CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_BIT_MASK) >> CMIF_RXSRP_CLTD_CTRL_1_C0_CLTD_EN_BIT_LSB)

#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_BIT_LSB                        (8)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_BIT_WIDTH                      (8)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_BIT_LSB) )
#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_BIT_LSB)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_FLD_RD()                       ((M_CMIF_RXSRP_CLTD_CTRL_1_C0_RD() & CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_BIT_MASK) >> CMIF_RXSRP_CLTD_CTRL_1_C0_ATM5_BIT_LSB)

#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_BIT_LSB                        (0)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_BIT_WIDTH                      (8)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_BIT_LSB) )
#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_BIT_LSB)
#define CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_FLD_RD()                       ((M_CMIF_RXSRP_CLTD_CTRL_1_C0_RD() & CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_BIT_MASK) >> CMIF_RXSRP_CLTD_CTRL_1_C0_ATM4_BIT_LSB)

#define CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_BIT_LSB                        (8)
#define CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_BIT_WIDTH                      (8)
#define CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_BIT_LSB) )
#define CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_BIT_LSB)
#define CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_FLD_RD()                       ((M_CMIF_RXSRP_CLTD_FBI_C0_RD() & CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_BIT_MASK) >> CMIF_RXSRP_CLTD_FBI_C0_FBI_RDY_BIT_LSB)

#define CMIF_RXSRP_CLTD_FBI_C0_FBI_BIT_LSB                            (0)
#define CMIF_RXSRP_CLTD_FBI_C0_FBI_BIT_WIDTH                          (8)
#define CMIF_RXSRP_CLTD_FBI_C0_FBI_BIT_MASK                           ((UINT32) (((1<<CMIF_RXSRP_CLTD_FBI_C0_FBI_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_FBI_C0_FBI_BIT_LSB) )
#define CMIF_RXSRP_CLTD_FBI_C0_FBI_FLD_WR(reg, val)                   (reg |= (val) << CMIF_RXSRP_CLTD_FBI_C0_FBI_BIT_LSB)
#define CMIF_RXSRP_CLTD_FBI_C0_FBI_FLD_RD()                           ((M_CMIF_RXSRP_CLTD_FBI_C0_RD() & CMIF_RXSRP_CLTD_FBI_C0_FBI_BIT_MASK) >> CMIF_RXSRP_CLTD_FBI_C0_FBI_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_BIT_LSB                       (24)
#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_BIT_WIDTH                     (8)
#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_FLD_RD()                      ((M_CMIF_RXSRP_CLTD_INFO0_C0_RD() & CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO0_C0_FBER_1_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO0_C0_W2_1_BIT_LSB                         (16)
#define CMIF_RXSRP_CLTD_INFO0_C0_W2_1_BIT_WIDTH                       (8)
#define CMIF_RXSRP_CLTD_INFO0_C0_W2_1_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO0_C0_W2_1_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO0_C0_W2_1_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO0_C0_W2_1_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_CLTD_INFO0_C0_W2_1_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO0_C0_W2_1_FLD_RD()                        ((M_CMIF_RXSRP_CLTD_INFO0_C0_RD() & CMIF_RXSRP_CLTD_INFO0_C0_W2_1_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO0_C0_W2_1_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_BIT_LSB                       (8)
#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_BIT_WIDTH                     (8)
#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_FLD_RD()                      ((M_CMIF_RXSRP_CLTD_INFO0_C0_RD() & CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO0_C0_FBER_0_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO0_C0_W2_0_BIT_LSB                         (0)
#define CMIF_RXSRP_CLTD_INFO0_C0_W2_0_BIT_WIDTH                       (8)
#define CMIF_RXSRP_CLTD_INFO0_C0_W2_0_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO0_C0_W2_0_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO0_C0_W2_0_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO0_C0_W2_0_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_CLTD_INFO0_C0_W2_0_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO0_C0_W2_0_FLD_RD()                        ((M_CMIF_RXSRP_CLTD_INFO0_C0_RD() & CMIF_RXSRP_CLTD_INFO0_C0_W2_0_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO0_C0_W2_0_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_BIT_LSB                       (24)
#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_BIT_WIDTH                     (8)
#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_FLD_RD()                      ((M_CMIF_RXSRP_CLTD_INFO1_C0_RD() & CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO1_C0_FBER_3_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO1_C0_W2_3_BIT_LSB                         (16)
#define CMIF_RXSRP_CLTD_INFO1_C0_W2_3_BIT_WIDTH                       (8)
#define CMIF_RXSRP_CLTD_INFO1_C0_W2_3_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO1_C0_W2_3_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO1_C0_W2_3_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO1_C0_W2_3_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_CLTD_INFO1_C0_W2_3_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO1_C0_W2_3_FLD_RD()                        ((M_CMIF_RXSRP_CLTD_INFO1_C0_RD() & CMIF_RXSRP_CLTD_INFO1_C0_W2_3_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO1_C0_W2_3_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_BIT_LSB                       (8)
#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_BIT_WIDTH                     (8)
#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_FLD_RD()                      ((M_CMIF_RXSRP_CLTD_INFO1_C0_RD() & CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO1_C0_FBER_2_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO1_C0_W2_2_BIT_LSB                         (0)
#define CMIF_RXSRP_CLTD_INFO1_C0_W2_2_BIT_WIDTH                       (8)
#define CMIF_RXSRP_CLTD_INFO1_C0_W2_2_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO1_C0_W2_2_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO1_C0_W2_2_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO1_C0_W2_2_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_CLTD_INFO1_C0_W2_2_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO1_C0_W2_2_FLD_RD()                        ((M_CMIF_RXSRP_CLTD_INFO1_C0_RD() & CMIF_RXSRP_CLTD_INFO1_C0_W2_2_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO1_C0_W2_2_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_BIT_LSB                       (24)
#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_BIT_WIDTH                     (8)
#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_FLD_RD()                      ((M_CMIF_RXSRP_CLTD_INFO2_C0_RD() & CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO2_C0_FBER_5_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO2_C0_W2_5_BIT_LSB                         (16)
#define CMIF_RXSRP_CLTD_INFO2_C0_W2_5_BIT_WIDTH                       (8)
#define CMIF_RXSRP_CLTD_INFO2_C0_W2_5_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO2_C0_W2_5_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO2_C0_W2_5_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO2_C0_W2_5_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_CLTD_INFO2_C0_W2_5_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO2_C0_W2_5_FLD_RD()                        ((M_CMIF_RXSRP_CLTD_INFO2_C0_RD() & CMIF_RXSRP_CLTD_INFO2_C0_W2_5_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO2_C0_W2_5_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_BIT_LSB                       (8)
#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_BIT_WIDTH                     (8)
#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_FLD_RD()                      ((M_CMIF_RXSRP_CLTD_INFO2_C0_RD() & CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO2_C0_FBER_4_BIT_LSB)

#define CMIF_RXSRP_CLTD_INFO2_C0_W2_4_BIT_LSB                         (0)
#define CMIF_RXSRP_CLTD_INFO2_C0_W2_4_BIT_WIDTH                       (8)
#define CMIF_RXSRP_CLTD_INFO2_C0_W2_4_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_CLTD_INFO2_C0_W2_4_BIT_WIDTH)-1) << CMIF_RXSRP_CLTD_INFO2_C0_W2_4_BIT_LSB) )
#define CMIF_RXSRP_CLTD_INFO2_C0_W2_4_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_CLTD_INFO2_C0_W2_4_BIT_LSB)
#define CMIF_RXSRP_CLTD_INFO2_C0_W2_4_FLD_RD()                        ((M_CMIF_RXSRP_CLTD_INFO2_C0_RD() & CMIF_RXSRP_CLTD_INFO2_C0_W2_4_BIT_MASK) >> CMIF_RXSRP_CLTD_INFO2_C0_W2_4_BIT_LSB)

#define CMIF_RXSRP_SIR_RST_C_POW_CHANGE_BIT_LSB                       (0)
#define CMIF_RXSRP_SIR_RST_C_POW_CHANGE_BIT_WIDTH                     (8)
#define CMIF_RXSRP_SIR_RST_C_POW_CHANGE_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_SIR_RST_C_POW_CHANGE_BIT_WIDTH)-1) << CMIF_RXSRP_SIR_RST_C_POW_CHANGE_BIT_LSB) )
#define CMIF_RXSRP_SIR_RST_C_POW_CHANGE_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_SIR_RST_C_POW_CHANGE_BIT_LSB)
#define CMIF_RXSRP_SIR_RST_C_POW_CHANGE_FLD_RD(i)                     ((M_CMIF_RXSRP_SIR_RST_C_RD(i) & CMIF_RXSRP_SIR_RST_C_POW_CHANGE_BIT_MASK) >> CMIF_RXSRP_SIR_RST_C_POW_CHANGE_BIT_LSB)

#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_BIT_LSB                         (24)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_BIT_WIDTH                       (8)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_BIT_WIDTH)-1) << CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_BIT_LSB) )
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_BIT_LSB)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_FLD_RD()                        ((M_CMIF_RXSRP_SIR_PO2_0_C0_RD() & CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_BIT_MASK) >> CMIF_RXSRP_SIR_PO2_0_C0_PO2_3_BIT_LSB)

#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_BIT_LSB                         (16)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_BIT_WIDTH                       (8)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_BIT_WIDTH)-1) << CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_BIT_LSB) )
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_BIT_LSB)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_FLD_RD()                        ((M_CMIF_RXSRP_SIR_PO2_0_C0_RD() & CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_BIT_MASK) >> CMIF_RXSRP_SIR_PO2_0_C0_PO2_2_BIT_LSB)

#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_BIT_LSB                         (8)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_BIT_WIDTH                       (8)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_BIT_WIDTH)-1) << CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_BIT_LSB) )
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_BIT_LSB)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_FLD_RD()                        ((M_CMIF_RXSRP_SIR_PO2_0_C0_RD() & CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_BIT_MASK) >> CMIF_RXSRP_SIR_PO2_0_C0_PO2_1_BIT_LSB)

#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_BIT_LSB                         (0)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_BIT_WIDTH                       (8)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_BIT_WIDTH)-1) << CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_BIT_LSB) )
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_BIT_LSB)
#define CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_FLD_RD()                        ((M_CMIF_RXSRP_SIR_PO2_0_C0_RD() & CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_BIT_MASK) >> CMIF_RXSRP_SIR_PO2_0_C0_PO2_0_BIT_LSB)

#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_BIT_LSB                         (8)
#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_BIT_WIDTH                       (8)
#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_BIT_WIDTH)-1) << CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_BIT_LSB) )
#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_BIT_LSB)
#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_FLD_RD()                        ((M_CMIF_RXSRP_SIR_PO2_1_C0_RD() & CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_BIT_MASK) >> CMIF_RXSRP_SIR_PO2_1_C0_PO2_5_BIT_LSB)

#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_BIT_LSB                         (0)
#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_BIT_WIDTH                       (8)
#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_BIT_WIDTH)-1) << CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_BIT_LSB) )
#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_BIT_LSB)
#define CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_FLD_RD()                        ((M_CMIF_RXSRP_SIR_PO2_1_C0_RD() & CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_BIT_MASK) >> CMIF_RXSRP_SIR_PO2_1_C0_PO2_4_BIT_LSB)

#define CMIF_RXSRP_TPC_PCA_C_PCA_BIT_LSB                              (16)
#define CMIF_RXSRP_TPC_PCA_C_PCA_BIT_WIDTH                            (8)
#define CMIF_RXSRP_TPC_PCA_C_PCA_BIT_MASK                             ((UINT32) (((1<<CMIF_RXSRP_TPC_PCA_C_PCA_BIT_WIDTH)-1) << CMIF_RXSRP_TPC_PCA_C_PCA_BIT_LSB) )
#define CMIF_RXSRP_TPC_PCA_C_PCA_FLD_WR(reg, val)                     (reg |= (val) << CMIF_RXSRP_TPC_PCA_C_PCA_BIT_LSB)
#define CMIF_RXSRP_TPC_PCA_C_PCA_FLD_RD(i)                            ((M_CMIF_RXSRP_TPC_PCA_C_RD(i) & CMIF_RXSRP_TPC_PCA_C_PCA_BIT_MASK) >> CMIF_RXSRP_TPC_PCA_C_PCA_BIT_LSB)

#define CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_BIT_LSB                     (0)
#define CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_BIT_WIDTH                   (16)
#define CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_BIT_MASK                    ((UINT32) (((1<<CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_BIT_WIDTH)-1) << CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_BIT_LSB) )
#define CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_FLD_WR(reg, val)            (reg |= (val) << CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_BIT_LSB)
#define CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_FLD_RD(i)                   ((M_CMIF_RXSRP_TPC_PCA_C_RD(i) & CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_BIT_MASK) >> CMIF_RXSRP_TPC_PCA_C_PCA_PER_SLOT_BIT_LSB)

#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_BIT_LSB                    (8)
#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_BIT_WIDTH                  (8)
#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_BIT_MASK                   ((UINT32) (((1<<CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_BIT_WIDTH)-1) << CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_BIT_LSB) )
#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_FLD_WR(reg, val)           (reg |= (val) << CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_BIT_LSB)
#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_FLD_RD(i)                  ((M_CMIF_RXSRP_TPC_RELI_TH_C_RD(i) & CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_BIT_MASK) >> CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_H_BIT_LSB)

#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_BIT_LSB                    (0)
#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_BIT_WIDTH                  (8)
#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_BIT_MASK                   ((UINT32) (((1<<CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_BIT_WIDTH)-1) << CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_BIT_LSB) )
#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_FLD_WR(reg, val)           (reg |= (val) << CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_BIT_LSB)
#define CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_FLD_RD(i)                  ((M_CMIF_RXSRP_TPC_RELI_TH_C_RD(i) & CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_BIT_MASK) >> CMIF_RXSRP_TPC_RELI_TH_C_PCA1_TH_L_BIT_LSB)

#define CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_BIT_LSB                       (0)
#define CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_BIT_WIDTH                     (8)
#define CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_BIT_MASK                      ((UINT32) (((1<<CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_BIT_WIDTH)-1) << CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_BIT_LSB) )
#define CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_FLD_WR(reg, val)              (reg |= (val) << CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_BIT_LSB)
#define CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_FLD_RD(i)                     ((M_CMIF_RXSRP_TPC_CTRL_C_RD(i) & CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_BIT_MASK) >> CMIF_RXSRP_TPC_CTRL_C_RLS_RECFG_BIT_LSB)

#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_BIT_LSB         (16)
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_BIT_WIDTH       (8)
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_BIT_MASK        ((UINT32) (((1<<CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_BIT_WIDTH)-1) << CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_BIT_LSB) )
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_FLD_WR(reg, val) (reg |= (val) << CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_BIT_LSB)
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_FLD_RD(i)       ((M_CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_RD(i) & CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_BIT_MASK) >> CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_PCA2_TIMING_BIT_LSB)

#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_BIT_LSB     (0)
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_BIT_WIDTH   (16)
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_BIT_MASK    ((UINT32) (((1<<CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_BIT_WIDTH)-1) << CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_BIT_LSB) )
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_FLD_WR(reg, val) (reg |= (val) << CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_BIT_LSB)
#define CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_FLD_RD(i)   ((M_CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_RD(i) & CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_BIT_MASK) >> CMIF_RXSRP_TPC_IGNORE_PCA2_TIME_C_SLOT_TPC_IGNORE_BIT_LSB)

#define CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_BIT_LSB                      (0)
#define CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_BIT_WIDTH                    (32)
#define CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_BIT_MASK                     ((UINT32) (((1<<CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_BIT_WIDTH)-1) << CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_BIT_LSB) )
#define CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_BIT_LSB)
#define CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_FLD_RD(i)                    ((M_CMIF_RXSRP_TPC_FRAME_C_RD(i) & CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_BIT_MASK) >> CMIF_RXSRP_TPC_FRAME_C_TPC_FRAME_BIT_LSB)

#define CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_BIT_LSB                      (0)
#define CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_BIT_WIDTH                    (32)
#define CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_BIT_MASK                     ((UINT32) (((1<<CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_BIT_WIDTH)-1) << CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_BIT_LSB) )
#define CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_BIT_LSB)
#define CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_FLD_RD(i)                    ((M_CMIF_RXSRP_GAP_FRAME_C_RD(i) & CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_BIT_MASK) >> CMIF_RXSRP_GAP_FRAME_C_GAP_FRAME_BIT_LSB)

#define CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_BIT_LSB                    (24)
#define CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_BIT_WIDTH                  (8)
#define CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_BIT_MASK                   ((UINT32) (((1<<CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_BIT_LSB) )
#define CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_FLD_WR(reg, val)           (reg |= (val) << CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_BIT_LSB)
#define CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_FLD_RD(i)                  ((M_CMIF_RXSRP_DPC_CTRL_C_RD(i) & CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_BIT_MASK) >> CMIF_RXSRP_DPC_CTRL_C_SIR_LTA_RATE_BIT_LSB)

#define CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_BIT_LSB                        (16)
#define CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_BIT_WIDTH                      (8)
#define CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_BIT_LSB) )
#define CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_BIT_LSB)
#define CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_FLD_RD(i)                      ((M_CMIF_RXSRP_DPC_CTRL_C_RD(i) & CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_BIT_MASK) >> CMIF_RXSRP_DPC_CTRL_C_TGT_RATE_BIT_LSB)

#define CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_BIT_LSB                         (8)
#define CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_BIT_WIDTH                       (8)
#define CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_BIT_MASK                        ((UINT32) (((1<<CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_BIT_LSB) )
#define CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_FLD_WR(reg, val)                (reg |= (val) << CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_BIT_LSB)
#define CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_FLD_RD(i)                       ((M_CMIF_RXSRP_DPC_CTRL_C_RD(i) & CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_BIT_MASK) >> CMIF_RXSRP_DPC_CTRL_C_TGL_DIS_BIT_LSB)

#define CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_BIT_LSB                        (0)
#define CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_BIT_WIDTH                      (8)
#define CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_BIT_MASK                       ((UINT32) (((1<<CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_BIT_LSB) )
#define CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_FLD_WR(reg, val)               (reg |= (val) << CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_BIT_LSB)
#define CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_FLD_RD(i)                      ((M_CMIF_RXSRP_DPC_CTRL_C_RD(i) & CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_BIT_MASK) >> CMIF_RXSRP_DPC_CTRL_C_DPC_MODE_BIT_LSB)

#define CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_BIT_LSB                      (0)
#define CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_BIT_WIDTH                    (16)
#define CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_BIT_MASK                     ((UINT32) (((1<<CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_BIT_LSB) )
#define CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_BIT_LSB)
#define CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_FLD_RD(i)                    ((M_CMIF_RXSRP_DPC_TGT_SIR_C_RD(i) & CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_BIT_MASK) >> CMIF_RXSRP_DPC_TGT_SIR_C_TGT_SIR_BIT_LSB)

#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_BIT_LSB           (16)
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_BIT_WIDTH         (16)
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_BIT_MASK          ((UINT32) (((1<<CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_BIT_LSB) )
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_FLD_WR(reg, val)  (reg |= (val) << CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_BIT_LSB)
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_FLD_RD(i)         ((M_CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_RD(i) & CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_BIT_MASK) >> CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_DATA_TH_SIR_BIT_LSB)

#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_BIT_LSB                (0)
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_BIT_WIDTH              (16)
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_BIT_MASK               ((UINT32) (((1<<CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_BIT_LSB) )
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_FLD_WR(reg, val)       (reg |= (val) << CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_BIT_LSB)
#define CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_FLD_RD(i)              ((M_CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_RD(i) & CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_BIT_MASK) >> CMIF_RXSRP_DPC_TH_SIR_DATA_TH_C_TH_SIR_BIT_LSB)

#define CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_BIT_LSB                      (0)
#define CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_BIT_WIDTH                    (16)
#define CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_BIT_MASK                     ((UINT32) (((1<<CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_BIT_LSB) )
#define CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_BIT_LSB)
#define CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_FLD_RD(i)                    ((M_CMIF_RXSRP_DPC_FRAME_C_RD(i) & CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_BIT_MASK) >> CMIF_RXSRP_DPC_FRAME_C_DPC_FRAME_BIT_LSB)

#define CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_BIT_LSB                  (0)
#define CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_BIT_WIDTH                (32)
#define CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_BIT_MASK                 ((UINT32) (((1<<CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_BIT_LSB) )
#define CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_FLD_WR(reg, val)         (reg |= (val) << CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_BIT_LSB)
#define CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_FLD_RD(i)                ((M_CMIF_RXSRP_DPC_WIND_UP_C_RD(i) & CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_BIT_MASK) >> CMIF_RXSRP_DPC_WIND_UP_C_WIND_UP_SIR_BIT_LSB)

#define CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_BIT_LSB                  (0)
#define CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_BIT_WIDTH                (32)
#define CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_BIT_MASK                 ((UINT32) (((1<<CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_BIT_LSB) )
#define CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_FLD_WR(reg, val)         (reg |= (val) << CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_BIT_LSB)
#define CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_FLD_RD(i)                ((M_CMIF_RXSRP_DPC_WIND_DN_C_RD(i) & CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_BIT_MASK) >> CMIF_RXSRP_DPC_WIND_DN_C_WIND_DN_SIR_BIT_LSB)

#define CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_BIT_LSB                      (0)
#define CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_BIT_WIDTH                    (16)
#define CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_BIT_MASK                     ((UINT32) (((1<<CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_BIT_WIDTH)-1) << CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_BIT_LSB) )
#define CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_FLD_WR(reg, val)             (reg |= (val) << CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_BIT_LSB)
#define CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_FLD_RD(i)                    ((M_CMIF_RXSRP_DPC_SIR_LTA_C_RD(i) & CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_BIT_MASK) >> CMIF_RXSRP_DPC_SIR_LTA_C_SIR_LTA_BIT_LSB)

#define CMIF_RXSRP_PO3_PO3_BIT_LSB                                    (0)
#define CMIF_RXSRP_PO3_PO3_BIT_WIDTH                                  (8)
#define CMIF_RXSRP_PO3_PO3_BIT_MASK                                   ((UINT32) (((1<<CMIF_RXSRP_PO3_PO3_BIT_WIDTH)-1) << CMIF_RXSRP_PO3_PO3_BIT_LSB) )
#define CMIF_RXSRP_PO3_PO3_FLD_WR(reg, val)                           (reg |= (val) << CMIF_RXSRP_PO3_PO3_BIT_LSB)
#define CMIF_RXSRP_PO3_PO3_FLD_RD()                                   ((M_CMIF_RXSRP_PO3_RD() & CMIF_RXSRP_PO3_PO3_BIT_MASK) >> CMIF_RXSRP_PO3_PO3_BIT_LSB)

#define CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_BIT_LSB                (0)
#define CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_BIT_WIDTH              (8)
#define CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_BIT_MASK               ((UINT32) (((1<<CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_BIT_WIDTH)-1) << CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_BIT_LSB) )
#define CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_FLD_WR(reg, val)       (reg |= (val) << CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_BIT_LSB)
#define CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_FLD_RD()               ((M_CMIF_RXSRP_WI_FROM_DPCCH_RD() & CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_BIT_MASK) >> CMIF_RXSRP_WI_FROM_DPCCH_WI_FROM_DPCCH_BIT_LSB)

#endif /* __RXSRP_CMIF_H__ */
