
#include "dsp_header_define_cuif_inner_brp.h"
#include "dsp_header_define_cuif_inner_brp_macro.h"
#include "dsp_header_define_cuif_fec_wbrp.h"
#include "dsp_header_define_cuif_fec_wbrp_macro.h"

typedef volatile unsigned short* SRAMADDR;       /* SRAM addr is 16 bits */
typedef volatile unsigned short  SRAMDATA;       /* SRAM data is 16 bits */
typedef volatile unsigned short* APBADDR;        /*  APB addr is 16 bits */
typedef volatile unsigned short  APBDATA;        /*  APB data is 16 bits */
typedef volatile unsigned long*  APBADDR32;     /*  APB addr is 32 bits */
typedef volatile unsigned long   APBDATA32;     /*  APB data is 32 bits */
typedef volatile unsigned short* DPRAMADDR;     /* DPRAM addr is 16 bits */
typedef volatile signed   short* DPRAMADDR_S;  /* DPRAM addr is 16 bits */
typedef volatile unsigned short  DPRAMDATA;     /* DPRAM data is 16 bits */


//#ifdef __MT6293M_CUIF_STRUCTURE_BASE_MIGRATE__
#define RXBRP_CCm_TRCH_EN_OR_EBD(x)                                                                 ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_TRCH_EN_OR_EBD[x])))
#define RXBRP_CCm_FRAME_IDX(x)                                                                      ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_FRAME_IDX[x])))
#define RXBRP_CCm_PHCH(x)                                                                           ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_PHCH[x])))
#define RXBRP_CCm_BTFD_DMA_DST_CALC(x)                                                              ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_BTFD_DMA_DST_CALC[x])))
#define RXBRP_CCm_BTFD_PARAMk(x)                                                                    ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_BTFD_PARAMk[x])))
#define RXBRP_CCm_BTFD_STOP_POINTk(x)                                                               ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_BTFD_STOP_POINTk[x])))
#define RXBRP_CCm_BTFD_CRC_POINTk(x)                                                                ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_BTFD_CRC_POINTk[x])))
#define RXBRP_TRCHm_E_PLUS(x)                                                                       ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_E_PLUS[x])))
#define RXBRP_TRCHm_E_MINUS(x)                                                                      ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_E_MINUS[x])))
#define RXBRP_TRCHm_CLEN(x)                                                                         ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_CLEN[x])))
#define RXBRP_TRCHm_BASEP(x)                                                                        ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_BASEP[x])))
#define RXBRP_TRCHm_TRBK(x)                                                                         ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_TRBK[x])))
#define RXBRP_TRCHm_COBK(x)                                                                         ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_COBK[x])))
#define RXBRP_TRCHm_DST_ADDR(x)                                                                     ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_DST_ADDR[x])))
#define RXBRP_TRCHm_DMA_CFG(x)                                                                      ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_DMA_CFG[x])))
#define RXBRP_BCH_DMA_CFG                                                                           ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_BCH_DMA_CFG)))
#define RXBRP_BCH_DST_ADDR                                                                          ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_BCH_DST_ADDR)))
#define RXBRP_CCm_TFk_ENERGY(x)                                                                     ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_TFk_ENERGY[x])))
#define RXBRP_CCm_BTFD_RESULTk(x)                                                                   ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_BTFD_RESULTk[x])))
#define RXBRP_TRCHm_TBCRC_STATUS(x)                                                                 ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_TBCRC_STATUS[x])))
#define RXBRP_TRCHm_ENERGY(x)                                                                       ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_ENERGY[x])))
#define RXBRP_TRCHm_CBkSVALUE(x)                                                                    ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_CBkSVALUE[x])))
#define RXBRP_BCH_SFN                                                                               ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_BCH_SFN)))
#define RXBRP_BCH_SVALUE                                                                            ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_BCH_SVALUE)))
#define RXBRP_CCm_PARAM(x)                                                                          ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_PARAM[x])))
#define RXBRP_TRCHm_CFG(x)                                                                          ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_CFG[x])))
#define RXBRP_BCH_START                                                                             ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_BCH_START)))
#define RXBRP_BCHSFN_STOP                                                                           ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_BCHSFN_STOP)))
#define RXBRP_CCm_TRCH_EN_OR_EBD_IRQ(x)                                                             ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_TRCH_EN_OR_EBD_IRQ[x])))
#define RXBRP_CCm_BTFD_PHASE_ACT(x)                                                                 ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_BTFD_PHASE_ACT[x])))
#define RXBRP_BCH_GNRL_CFG                                                                          ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_BCH_GNRL_CFG)))
#define RXBRP_CCm_3GLORX_EN(x)                                                                      ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_3GLORX_EN[x])))
#define RXBRP_CCm_3GLORX_VALID_DATA_NUM(x)                                                          ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_3GLORX_VALID_DATA_NUM[x])))
#define RXBRP_CCm_3GLORX_SVALUE_THRESHOLD(x)                                                        ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_3GLORX_SVALUE_THRESHOLD[x])))
#define RXBRP_CCm_3GLORX_EBD_COEFF(x)                                                               ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_3GLORX_EBD_COEFF[x])))
#define RXBRP_CCm_3GLORX_DUAL_COEFF(x)                                                              ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_3GLORX_DUAL_COEFF[x])))
#define RXBRP_3GLORX_DFE_PULSE                                                                      ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_3GLORX_DFE_PULSE)))
#define RXBRP_CCm_EBD_DEC_TRCH_MASK(x)                                                              ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_EBD_DEC_TRCH_MASK[x])))
#define RXBRP_CCm_STOP(x)                                                                           ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_STOP[x])))
#define RXBRP_CCm_SYMBOL_NUM(x)                                                                     ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_SYMBOL_NUM[x])))
#define RXBRP_CCm_SYMBOL_SUM(x)                                                                     ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_SYMBOL_SUM[x])))
#define RXBRP_CCm_BUFIDX(x)                                                                         ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_BUFIDX[x])))
#define RXBRP_CCm_SUSPEND_GAP(x)                                                                    ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_SUSPEND_GAP[x])))
#define RXBRP_CCm_WRITE_PHCH_TWICE(x)                                                               ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_WRITE_PHCH_TWICE[x])))
#define RXBRP_CCm_TRCH_DONE(x)                                                                      ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_CCm_TRCH_DONE[x])))
#define RXBRP_TRCHm_TTI_MIN_SCF(x)                                                                  ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_TRCHm_TTI_MIN_SCF[x])))
#define RXBRP_BCHSFN_GUARD_TIME                                                                     ((APBADDR32)(&(FEC_WBRP_WR99_CUIF->RXBRP_BCHSFN_GUARD_TIME)))
/*MT6293m TEMP WORKAROUND*/
#define RXBRP_3G_SLEEP_ACK                                                                          (APBADDR32)(0xD0358530)
#define RXBRP_3G_PM_DM_STATE                                                                        (APBADDR32)(0xD0358534)
#define RXBRP_3G_ALLOW_SLEEP                                                                        (APBADDR32)(0xD0358538)

/*MT6293m TEMP WORKAROUND*/
#define RXBRP_CUIF_REG_BASE                                                                         RXBRP_CCm_TRCH_EN_OR_EBD(0)
#define RXBRP_CUIF_end                                                                              RXBRP_BCHSFN_GUARD_TIME



#define RXBRP_CCm_TRCH_EN_OR_EBD_TRCH_EN_OR_EBD_LSB                                                 P_WR99_CUIF_RXBRP_CCm_TRCH_EN_OR_EBD_TRCH_EN_OR_EBD
#define RXBRP_CCm_TRCH_EN_OR_EBD_TRCH_EN_OR_EBD_WIDTH                                               L_WR99_CUIF_RXBRP_CCm_TRCH_EN_OR_EBD_TRCH_EN_OR_EBD
#define RXBRP_CCm_TRCH_EN_OR_EBD_TRCH_EN_OR_EBD_MASK                                                M_WR99_CUIF_RXBRP_CCm_TRCH_EN_OR_EBD_TRCH_EN_OR_EBD
#define RXBRP_CCm_TRCH_EN_OR_EBD_TRCH_EN_OR_EBD_BIT                                                 M_WR99_CUIF_RXBRP_CCm_TRCH_EN_OR_EBD_TRCH_EN_OR_EBD
#define RXBRP_CCm_FRAME_IDX_FRAME_INDEX_LSB                                                         P_WR99_CUIF_RXBRP_CCm_FRAME_IDX_FRAME_INDEX
#define RXBRP_CCm_FRAME_IDX_FRAME_INDEX_WIDTH                                                       L_WR99_CUIF_RXBRP_CCm_FRAME_IDX_FRAME_INDEX
#define RXBRP_CCm_FRAME_IDX_FRAME_INDEX_MASK                                                        M_WR99_CUIF_RXBRP_CCm_FRAME_IDX_FRAME_INDEX
#define RXBRP_CCm_FRAME_IDX_FRAME_INDEX_BIT                                                         M_WR99_CUIF_RXBRP_CCm_FRAME_IDX_FRAME_INDEX
#define RXBRP_CCm_PHCH_PHCH_NUM_LSB                                                                 P_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_NUM
#define RXBRP_CCm_PHCH_PHCH_NUM_WIDTH                                                               L_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_NUM
#define RXBRP_CCm_PHCH_PHCH_NUM_MASK                                                                M_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_NUM
#define RXBRP_CCm_PHCH_PHCH_NUM_BIT                                                                 M_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_NUM
#define RXBRP_CCm_PHCH_PHCH_ROWS_LSB                                                                P_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_ROWS
#define RXBRP_CCm_PHCH_PHCH_ROWS_WIDTH                                                              L_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_ROWS
#define RXBRP_CCm_PHCH_PHCH_ROWS_MASK                                                               M_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_ROWS
#define RXBRP_CCm_PHCH_PHCH_ROWS_BIT                                                                M_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_ROWS
#define RXBRP_CCm_PHCH_PHCH_LAST_ROW_LSB                                                            P_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_LAST_ROW
#define RXBRP_CCm_PHCH_PHCH_LAST_ROW_WIDTH                                                          L_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_LAST_ROW
#define RXBRP_CCm_PHCH_PHCH_LAST_ROW_MASK                                                           M_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_LAST_ROW
#define RXBRP_CCm_PHCH_PHCH_LAST_ROW_BIT                                                            M_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_LAST_ROW
#define RXBRP_CCm_PHCH_PHCH_LENGTH_LSB                                                              P_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_LENGTH
#define RXBRP_CCm_PHCH_PHCH_LENGTH_WIDTH                                                            L_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_LENGTH
#define RXBRP_CCm_PHCH_PHCH_LENGTH_MASK                                                             M_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_LENGTH
#define RXBRP_CCm_PHCH_PHCH_LENGTH_BIT                                                              M_WR99_CUIF_RXBRP_CCm_PHCH_PHCH_LENGTH
#define RXBRP_CCm_BTFD_DMA_DST_CALC_DMA_DST_CALC_SET_LSB                                            P_WR99_CUIF_RXBRP_CCm_BTFD_DMA_DST_CALC_DMA_DST_CALC_SET
#define RXBRP_CCm_BTFD_DMA_DST_CALC_DMA_DST_CALC_SET_WIDTH                                          L_WR99_CUIF_RXBRP_CCm_BTFD_DMA_DST_CALC_DMA_DST_CALC_SET
#define RXBRP_CCm_BTFD_DMA_DST_CALC_DMA_DST_CALC_SET_MASK                                           M_WR99_CUIF_RXBRP_CCm_BTFD_DMA_DST_CALC_DMA_DST_CALC_SET
#define RXBRP_CCm_BTFD_DMA_DST_CALC_DMA_DST_CALC_SET_BIT                                            M_WR99_CUIF_RXBRP_CCm_BTFD_DMA_DST_CALC_DMA_DST_CALC_SET
#define RXBRP_CCm_BTFD_PARAMk_EXPLICIT_IND_LSB                                                      P_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_EXPLICIT_IND
#define RXBRP_CCm_BTFD_PARAMk_EXPLICIT_IND_WIDTH                                                    L_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_EXPLICIT_IND
#define RXBRP_CCm_BTFD_PARAMk_EXPLICIT_IND_MASK                                                     M_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_EXPLICIT_IND
#define RXBRP_CCm_BTFD_PARAMk_EXPLICIT_IND_BIT                                                      M_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_EXPLICIT_IND
#define RXBRP_CCm_BTFD_PARAMk_TRCH_ID_LSB                                                           P_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_TRCH_ID
#define RXBRP_CCm_BTFD_PARAMk_TRCH_ID_WIDTH                                                         L_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_TRCH_ID
#define RXBRP_CCm_BTFD_PARAMk_TRCH_ID_MASK                                                          M_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_TRCH_ID
#define RXBRP_CCm_BTFD_PARAMk_TRCH_ID_BIT                                                           M_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_TRCH_ID
#define RXBRP_CCm_BTFD_PARAMk_LAST_STOP_POINT_IDX_LSB                                               P_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_LAST_STOP_POINT_IDX
#define RXBRP_CCm_BTFD_PARAMk_LAST_STOP_POINT_IDX_WIDTH                                             L_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_LAST_STOP_POINT_IDX
#define RXBRP_CCm_BTFD_PARAMk_LAST_STOP_POINT_IDX_MASK                                              M_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_LAST_STOP_POINT_IDX
#define RXBRP_CCm_BTFD_PARAMk_LAST_STOP_POINT_IDX_BIT                                               M_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_LAST_STOP_POINT_IDX
#define RXBRP_CCm_BTFD_PARAMk_FIRST_STOP_POINT_IDX_LSB                                              P_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_FIRST_STOP_POINT_IDX
#define RXBRP_CCm_BTFD_PARAMk_FIRST_STOP_POINT_IDX_WIDTH                                            L_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_FIRST_STOP_POINT_IDX
#define RXBRP_CCm_BTFD_PARAMk_FIRST_STOP_POINT_IDX_MASK                                             M_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_FIRST_STOP_POINT_IDX
#define RXBRP_CCm_BTFD_PARAMk_FIRST_STOP_POINT_IDX_BIT                                              M_WR99_CUIF_RXBRP_CCm_BTFD_PARAMk_FIRST_STOP_POINT_IDX
#define RXBRP_CCm_BTFD_STOP_POINTk_TF_GLEN_LSB                                                      P_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_TF_GLEN
#define RXBRP_CCm_BTFD_STOP_POINTk_TF_GLEN_WIDTH                                                    L_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_TF_GLEN
#define RXBRP_CCm_BTFD_STOP_POINTk_TF_GLEN_MASK                                                     M_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_TF_GLEN
#define RXBRP_CCm_BTFD_STOP_POINTk_TF_GLEN_BIT                                                      M_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_TF_GLEN
#define RXBRP_CCm_BTFD_STOP_POINTk_BTFD_MULTI_LSB                                                   P_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_BTFD_MULTI
#define RXBRP_CCm_BTFD_STOP_POINTk_BTFD_MULTI_WIDTH                                                 L_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_BTFD_MULTI
#define RXBRP_CCm_BTFD_STOP_POINTk_BTFD_MULTI_MASK                                                  M_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_BTFD_MULTI
#define RXBRP_CCm_BTFD_STOP_POINTk_BTFD_MULTI_BIT                                                   M_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_BTFD_MULTI
#define RXBRP_CCm_BTFD_STOP_POINTk_BTFD_STOP_POINT_LSB                                              P_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_BTFD_STOP_POINT
#define RXBRP_CCm_BTFD_STOP_POINTk_BTFD_STOP_POINT_WIDTH                                            L_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_BTFD_STOP_POINT
#define RXBRP_CCm_BTFD_STOP_POINTk_BTFD_STOP_POINT_MASK                                             M_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_BTFD_STOP_POINT
#define RXBRP_CCm_BTFD_STOP_POINTk_BTFD_STOP_POINT_BIT                                              M_WR99_CUIF_RXBRP_CCm_BTFD_STOP_POINTk_BTFD_STOP_POINT
#define RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_NUM_LSB                                         P_WR99_CUIF_RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_NUM
#define RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_NUM_WIDTH                                       L_WR99_CUIF_RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_NUM
#define RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_NUM_MASK                                        M_WR99_CUIF_RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_NUM
#define RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_NUM_BIT                                         M_WR99_CUIF_RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_NUM
#define RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_SIZE_LSB                                        P_WR99_CUIF_RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_SIZE
#define RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_SIZE_WIDTH                                      L_WR99_CUIF_RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_SIZE
#define RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_SIZE_MASK                                       M_WR99_CUIF_RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_SIZE
#define RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_SIZE_BIT                                        M_WR99_CUIF_RXBRP_CCm_BTFD_CRC_POINTk_BTFD_CRC_POINT_TB_SIZE
#define RXBRP_TRCHm_E_PLUS_E_PLUS_LSB                                                               P_WR99_CUIF_RXBRP_TRCHm_E_PLUS_E_PLUS
#define RXBRP_TRCHm_E_PLUS_E_PLUS_WIDTH                                                             L_WR99_CUIF_RXBRP_TRCHm_E_PLUS_E_PLUS
#define RXBRP_TRCHm_E_PLUS_E_PLUS_MASK                                                              M_WR99_CUIF_RXBRP_TRCHm_E_PLUS_E_PLUS
#define RXBRP_TRCHm_E_PLUS_E_PLUS_BIT                                                               M_WR99_CUIF_RXBRP_TRCHm_E_PLUS_E_PLUS
#define RXBRP_TRCHm_E_MINUS_E_M_2_FACTOR_LSB                                                        P_WR99_CUIF_RXBRP_TRCHm_E_MINUS_E_M_2_FACTOR
#define RXBRP_TRCHm_E_MINUS_E_M_2_FACTOR_WIDTH                                                      L_WR99_CUIF_RXBRP_TRCHm_E_MINUS_E_M_2_FACTOR
#define RXBRP_TRCHm_E_MINUS_E_M_2_FACTOR_MASK                                                       M_WR99_CUIF_RXBRP_TRCHm_E_MINUS_E_M_2_FACTOR
#define RXBRP_TRCHm_E_MINUS_E_M_2_FACTOR_BIT                                                        M_WR99_CUIF_RXBRP_TRCHm_E_MINUS_E_M_2_FACTOR
#define RXBRP_TRCHm_E_MINUS_E_MINUS_LSB                                                             P_WR99_CUIF_RXBRP_TRCHm_E_MINUS_E_MINUS
#define RXBRP_TRCHm_E_MINUS_E_MINUS_WIDTH                                                           L_WR99_CUIF_RXBRP_TRCHm_E_MINUS_E_MINUS
#define RXBRP_TRCHm_E_MINUS_E_MINUS_MASK                                                            M_WR99_CUIF_RXBRP_TRCHm_E_MINUS_E_MINUS
#define RXBRP_TRCHm_E_MINUS_E_MINUS_BIT                                                             M_WR99_CUIF_RXBRP_TRCHm_E_MINUS_E_MINUS
#define RXBRP_TRCHm_CLEN_CLEN_LSB                                                                   P_WR99_CUIF_RXBRP_TRCHm_CLEN_CLEN
#define RXBRP_TRCHm_CLEN_CLEN_WIDTH                                                                 L_WR99_CUIF_RXBRP_TRCHm_CLEN_CLEN
#define RXBRP_TRCHm_CLEN_CLEN_MASK                                                                  M_WR99_CUIF_RXBRP_TRCHm_CLEN_CLEN
#define RXBRP_TRCHm_CLEN_CLEN_BIT                                                                   M_WR99_CUIF_RXBRP_TRCHm_CLEN_CLEN
#define RXBRP_TRCHm_BASEP_FRAME_RD_BASEP_LSB                                                        P_WR99_CUIF_RXBRP_TRCHm_BASEP_FRAME_RD_BASEP
#define RXBRP_TRCHm_BASEP_FRAME_RD_BASEP_WIDTH                                                      L_WR99_CUIF_RXBRP_TRCHm_BASEP_FRAME_RD_BASEP
#define RXBRP_TRCHm_BASEP_FRAME_RD_BASEP_MASK                                                       M_WR99_CUIF_RXBRP_TRCHm_BASEP_FRAME_RD_BASEP
#define RXBRP_TRCHm_BASEP_FRAME_RD_BASEP_BIT                                                        M_WR99_CUIF_RXBRP_TRCHm_BASEP_FRAME_RD_BASEP
#define RXBRP_TRCHm_BASEP_TTI_BASEP_LSB                                                             P_WR99_CUIF_RXBRP_TRCHm_BASEP_TTI_BASEP
#define RXBRP_TRCHm_BASEP_TTI_BASEP_WIDTH                                                           L_WR99_CUIF_RXBRP_TRCHm_BASEP_TTI_BASEP
#define RXBRP_TRCHm_BASEP_TTI_BASEP_MASK                                                            M_WR99_CUIF_RXBRP_TRCHm_BASEP_TTI_BASEP
#define RXBRP_TRCHm_BASEP_TTI_BASEP_BIT                                                             M_WR99_CUIF_RXBRP_TRCHm_BASEP_TTI_BASEP
#define RXBRP_TRCHm_TRBK_TBSIZE_LSB                                                                 P_WR99_CUIF_RXBRP_TRCHm_TRBK_TBSIZE
#define RXBRP_TRCHm_TRBK_TBSIZE_WIDTH                                                               L_WR99_CUIF_RXBRP_TRCHm_TRBK_TBSIZE
#define RXBRP_TRCHm_TRBK_TBSIZE_MASK                                                                M_WR99_CUIF_RXBRP_TRCHm_TRBK_TBSIZE
#define RXBRP_TRCHm_TRBK_TBSIZE_BIT                                                                 M_WR99_CUIF_RXBRP_TRCHm_TRBK_TBSIZE
#define RXBRP_TRCHm_TRBK_TBNUM_LSB                                                                  P_WR99_CUIF_RXBRP_TRCHm_TRBK_TBNUM
#define RXBRP_TRCHm_TRBK_TBNUM_WIDTH                                                                L_WR99_CUIF_RXBRP_TRCHm_TRBK_TBNUM
#define RXBRP_TRCHm_TRBK_TBNUM_MASK                                                                 M_WR99_CUIF_RXBRP_TRCHm_TRBK_TBNUM
#define RXBRP_TRCHm_TRBK_TBNUM_BIT                                                                  M_WR99_CUIF_RXBRP_TRCHm_TRBK_TBNUM
#define RXBRP_TRCHm_COBK_CBSIZE_LSB                                                                 P_WR99_CUIF_RXBRP_TRCHm_COBK_CBSIZE
#define RXBRP_TRCHm_COBK_CBSIZE_WIDTH                                                               L_WR99_CUIF_RXBRP_TRCHm_COBK_CBSIZE
#define RXBRP_TRCHm_COBK_CBSIZE_MASK                                                                M_WR99_CUIF_RXBRP_TRCHm_COBK_CBSIZE
#define RXBRP_TRCHm_COBK_CBSIZE_BIT                                                                 M_WR99_CUIF_RXBRP_TRCHm_COBK_CBSIZE
#define RXBRP_TRCHm_COBK_CBPAD_LSB                                                                  P_WR99_CUIF_RXBRP_TRCHm_COBK_CBPAD
#define RXBRP_TRCHm_COBK_CBPAD_WIDTH                                                                L_WR99_CUIF_RXBRP_TRCHm_COBK_CBPAD
#define RXBRP_TRCHm_COBK_CBPAD_MASK                                                                 M_WR99_CUIF_RXBRP_TRCHm_COBK_CBPAD
#define RXBRP_TRCHm_COBK_CBPAD_BIT                                                                  M_WR99_CUIF_RXBRP_TRCHm_COBK_CBPAD
#define RXBRP_TRCHm_COBK_CBNUM_LSB                                                                  P_WR99_CUIF_RXBRP_TRCHm_COBK_CBNUM
#define RXBRP_TRCHm_COBK_CBNUM_WIDTH                                                                L_WR99_CUIF_RXBRP_TRCHm_COBK_CBNUM
#define RXBRP_TRCHm_COBK_CBNUM_MASK                                                                 M_WR99_CUIF_RXBRP_TRCHm_COBK_CBNUM
#define RXBRP_TRCHm_COBK_CBNUM_BIT                                                                  M_WR99_CUIF_RXBRP_TRCHm_COBK_CBNUM
#define RXBRP_TRCHm_DST_ADDR_DST_ADDR_LSB                                                           P_WR99_CUIF_RXBRP_TRCHm_DST_ADDR_DST_ADDR
#define RXBRP_TRCHm_DST_ADDR_DST_ADDR_WIDTH                                                         L_WR99_CUIF_RXBRP_TRCHm_DST_ADDR_DST_ADDR
#define RXBRP_TRCHm_DST_ADDR_DST_ADDR_MASK                                                          M_WR99_CUIF_RXBRP_TRCHm_DST_ADDR_DST_ADDR
#define RXBRP_TRCHm_DST_ADDR_DST_ADDR_BIT                                                           M_WR99_CUIF_RXBRP_TRCHm_DST_ADDR_DST_ADDR
#define RXBRP_TRCHm_DMA_CFG_CRC_REMOVE_LSB                                                          P_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_CRC_REMOVE
#define RXBRP_TRCHm_DMA_CFG_CRC_REMOVE_WIDTH                                                        L_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_CRC_REMOVE
#define RXBRP_TRCHm_DMA_CFG_CRC_REMOVE_MASK                                                         M_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_CRC_REMOVE
#define RXBRP_TRCHm_DMA_CFG_CRC_REMOVE_BIT                                                          M_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_CRC_REMOVE
#define RXBRP_TRCHm_DMA_CFG_SWAP_ENDIAN_LSB                                                         P_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_SWAP_ENDIAN
#define RXBRP_TRCHm_DMA_CFG_SWAP_ENDIAN_WIDTH                                                       L_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_SWAP_ENDIAN
#define RXBRP_TRCHm_DMA_CFG_SWAP_ENDIAN_MASK                                                        M_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_SWAP_ENDIAN
#define RXBRP_TRCHm_DMA_CFG_SWAP_ENDIAN_BIT                                                         M_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_SWAP_ENDIAN
#define RXBRP_TRCHm_DMA_CFG_BIT_OFFSET_LSB                                                          P_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_BIT_OFFSET
#define RXBRP_TRCHm_DMA_CFG_BIT_OFFSET_WIDTH                                                        L_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_BIT_OFFSET
#define RXBRP_TRCHm_DMA_CFG_BIT_OFFSET_MASK                                                         M_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_BIT_OFFSET
#define RXBRP_TRCHm_DMA_CFG_BIT_OFFSET_BIT                                                          M_WR99_CUIF_RXBRP_TRCHm_DMA_CFG_BIT_OFFSET
#define RXBRP_BCH_DMA_CFG_DMA_ENAB_LSB                                                              P_WR99_CUIF_RXBRP_BCH_DMA_CFG_DMA_ENAB
#define RXBRP_BCH_DMA_CFG_DMA_ENAB_WIDTH                                                            L_WR99_CUIF_RXBRP_BCH_DMA_CFG_DMA_ENAB
#define RXBRP_BCH_DMA_CFG_DMA_ENAB_MASK                                                             M_WR99_CUIF_RXBRP_BCH_DMA_CFG_DMA_ENAB
#define RXBRP_BCH_DMA_CFG_DMA_ENAB_BIT                                                              M_WR99_CUIF_RXBRP_BCH_DMA_CFG_DMA_ENAB
#define RXBRP_BCH_DMA_CFG_CRC_REMOVE_LSB                                                            P_WR99_CUIF_RXBRP_BCH_DMA_CFG_CRC_REMOVE
#define RXBRP_BCH_DMA_CFG_CRC_REMOVE_WIDTH                                                          L_WR99_CUIF_RXBRP_BCH_DMA_CFG_CRC_REMOVE
#define RXBRP_BCH_DMA_CFG_CRC_REMOVE_MASK                                                           M_WR99_CUIF_RXBRP_BCH_DMA_CFG_CRC_REMOVE
#define RXBRP_BCH_DMA_CFG_CRC_REMOVE_BIT                                                            M_WR99_CUIF_RXBRP_BCH_DMA_CFG_CRC_REMOVE
#define RXBRP_BCH_DMA_CFG_SWAP_ENDIAN_LSB                                                           P_WR99_CUIF_RXBRP_BCH_DMA_CFG_SWAP_ENDIAN
#define RXBRP_BCH_DMA_CFG_SWAP_ENDIAN_WIDTH                                                         L_WR99_CUIF_RXBRP_BCH_DMA_CFG_SWAP_ENDIAN
#define RXBRP_BCH_DMA_CFG_SWAP_ENDIAN_MASK                                                          M_WR99_CUIF_RXBRP_BCH_DMA_CFG_SWAP_ENDIAN
#define RXBRP_BCH_DMA_CFG_SWAP_ENDIAN_BIT                                                           M_WR99_CUIF_RXBRP_BCH_DMA_CFG_SWAP_ENDIAN
#define RXBRP_BCH_DMA_CFG_BIT_OFFSET_LSB                                                            P_WR99_CUIF_RXBRP_BCH_DMA_CFG_BIT_OFFSET
#define RXBRP_BCH_DMA_CFG_BIT_OFFSET_WIDTH                                                          L_WR99_CUIF_RXBRP_BCH_DMA_CFG_BIT_OFFSET
#define RXBRP_BCH_DMA_CFG_BIT_OFFSET_MASK                                                           M_WR99_CUIF_RXBRP_BCH_DMA_CFG_BIT_OFFSET
#define RXBRP_BCH_DMA_CFG_BIT_OFFSET_BIT                                                            M_WR99_CUIF_RXBRP_BCH_DMA_CFG_BIT_OFFSET
#define RXBRP_BCH_DST_ADDR_DST_ADDR_LSB                                                             P_WR99_CUIF_RXBRP_BCH_DST_ADDR_DST_ADDR
#define RXBRP_BCH_DST_ADDR_DST_ADDR_WIDTH                                                           L_WR99_CUIF_RXBRP_BCH_DST_ADDR_DST_ADDR
#define RXBRP_BCH_DST_ADDR_DST_ADDR_MASK                                                            M_WR99_CUIF_RXBRP_BCH_DST_ADDR_DST_ADDR
#define RXBRP_BCH_DST_ADDR_DST_ADDR_BIT                                                             M_WR99_CUIF_RXBRP_BCH_DST_ADDR_DST_ADDR
#define RXBRP_CCm_TFk_ENERGY_CCm_TFk_ENERGY_LSB                                                     P_WR99_CUIF_RXBRP_CCm_TFk_ENERGY_CCm_TFk_ENERGY
#define RXBRP_CCm_TFk_ENERGY_CCm_TFk_ENERGY_WIDTH                                                   L_WR99_CUIF_RXBRP_CCm_TFk_ENERGY_CCm_TFk_ENERGY
#define RXBRP_CCm_TFk_ENERGY_CCm_TFk_ENERGY_MASK                                                    M_WR99_CUIF_RXBRP_CCm_TFk_ENERGY_CCm_TFk_ENERGY
#define RXBRP_CCm_TFk_ENERGY_CCm_TFk_ENERGY_BIT                                                     M_WR99_CUIF_RXBRP_CCm_TFk_ENERGY_CCm_TFk_ENERGY
#define RXBRP_CCm_BTFD_RESULTk_BTFD_PASS_LSB                                                        P_WR99_CUIF_RXBRP_CCm_BTFD_RESULTk_BTFD_PASS
#define RXBRP_CCm_BTFD_RESULTk_BTFD_PASS_WIDTH                                                      L_WR99_CUIF_RXBRP_CCm_BTFD_RESULTk_BTFD_PASS
#define RXBRP_CCm_BTFD_RESULTk_BTFD_PASS_MASK                                                       M_WR99_CUIF_RXBRP_CCm_BTFD_RESULTk_BTFD_PASS
#define RXBRP_CCm_BTFD_RESULTk_BTFD_PASS_BIT                                                        M_WR99_CUIF_RXBRP_CCm_BTFD_RESULTk_BTFD_PASS
#define RXBRP_CCm_BTFD_RESULTk_BTFD_POINT_IDX_LSB                                                   P_WR99_CUIF_RXBRP_CCm_BTFD_RESULTk_BTFD_POINT_IDX
#define RXBRP_CCm_BTFD_RESULTk_BTFD_POINT_IDX_WIDTH                                                 L_WR99_CUIF_RXBRP_CCm_BTFD_RESULTk_BTFD_POINT_IDX
#define RXBRP_CCm_BTFD_RESULTk_BTFD_POINT_IDX_MASK                                                  M_WR99_CUIF_RXBRP_CCm_BTFD_RESULTk_BTFD_POINT_IDX
#define RXBRP_CCm_BTFD_RESULTk_BTFD_POINT_IDX_BIT                                                   M_WR99_CUIF_RXBRP_CCm_BTFD_RESULTk_BTFD_POINT_IDX
#define RXBRP_TRCHm_TBCRC_STATUS_TB0_TB31_LSB                                                       P_WR99_CUIF_RXBRP_TRCHm_TBCRC_STATUS_TB0_TB31
#define RXBRP_TRCHm_TBCRC_STATUS_TB0_TB31_WIDTH                                                     L_WR99_CUIF_RXBRP_TRCHm_TBCRC_STATUS_TB0_TB31
#define RXBRP_TRCHm_TBCRC_STATUS_TB0_TB31_MASK                                                      M_WR99_CUIF_RXBRP_TRCHm_TBCRC_STATUS_TB0_TB31
#define RXBRP_TRCHm_TBCRC_STATUS_TB0_TB31_BIT                                                       M_WR99_CUIF_RXBRP_TRCHm_TBCRC_STATUS_TB0_TB31
#define RXBRP_TRCHm_ENERGY_ENERGY_LSB                                                               P_WR99_CUIF_RXBRP_TRCHm_ENERGY_ENERGY
#define RXBRP_TRCHm_ENERGY_ENERGY_WIDTH                                                             L_WR99_CUIF_RXBRP_TRCHm_ENERGY_ENERGY
#define RXBRP_TRCHm_ENERGY_ENERGY_MASK                                                              M_WR99_CUIF_RXBRP_TRCHm_ENERGY_ENERGY
#define RXBRP_TRCHm_ENERGY_ENERGY_BIT                                                               M_WR99_CUIF_RXBRP_TRCHm_ENERGY_ENERGY
#define RXBRP_TRCHm_CBkSVALUE_CONFIDENCE_VALUE_LSB                                                  P_WR99_CUIF_RXBRP_TRCHm_CBkSVALUE_CONFIDENCE_VALUE
#define RXBRP_TRCHm_CBkSVALUE_CONFIDENCE_VALUE_WIDTH                                                L_WR99_CUIF_RXBRP_TRCHm_CBkSVALUE_CONFIDENCE_VALUE
#define RXBRP_TRCHm_CBkSVALUE_CONFIDENCE_VALUE_MASK                                                 M_WR99_CUIF_RXBRP_TRCHm_CBkSVALUE_CONFIDENCE_VALUE
#define RXBRP_TRCHm_CBkSVALUE_CONFIDENCE_VALUE_BIT                                                  M_WR99_CUIF_RXBRP_TRCHm_CBkSVALUE_CONFIDENCE_VALUE
#define RXBRP_BCH_SFN_CRC_IND_LSB                                                                   P_WR99_CUIF_RXBRP_BCH_SFN_CRC_IND
#define RXBRP_BCH_SFN_CRC_IND_WIDTH                                                                 L_WR99_CUIF_RXBRP_BCH_SFN_CRC_IND
#define RXBRP_BCH_SFN_CRC_IND_MASK                                                                  M_WR99_CUIF_RXBRP_BCH_SFN_CRC_IND
#define RXBRP_BCH_SFN_CRC_IND_BIT                                                                   M_WR99_CUIF_RXBRP_BCH_SFN_CRC_IND
#define RXBRP_BCH_SFN_BCH_SFN_LSB                                                                   P_WR99_CUIF_RXBRP_BCH_SFN_BCH_SFN
#define RXBRP_BCH_SFN_BCH_SFN_WIDTH                                                                 L_WR99_CUIF_RXBRP_BCH_SFN_BCH_SFN
#define RXBRP_BCH_SFN_BCH_SFN_MASK                                                                  M_WR99_CUIF_RXBRP_BCH_SFN_BCH_SFN
#define RXBRP_BCH_SFN_BCH_SFN_BIT                                                                   M_WR99_CUIF_RXBRP_BCH_SFN_BCH_SFN
#define RXBRP_BCH_SVALUE_CONFIDENCE_VALUE_LSB                                                       P_WR99_CUIF_RXBRP_BCH_SVALUE_CONFIDENCE_VALUE
#define RXBRP_BCH_SVALUE_CONFIDENCE_VALUE_WIDTH                                                     L_WR99_CUIF_RXBRP_BCH_SVALUE_CONFIDENCE_VALUE
#define RXBRP_BCH_SVALUE_CONFIDENCE_VALUE_MASK                                                      M_WR99_CUIF_RXBRP_BCH_SVALUE_CONFIDENCE_VALUE
#define RXBRP_BCH_SVALUE_CONFIDENCE_VALUE_BIT                                                       M_WR99_CUIF_RXBRP_BCH_SVALUE_CONFIDENCE_VALUE
#define RXBRP_CCm_PARAM_TRCH_EN_LSB                                                                 P_WR99_CUIF_RXBRP_CCm_PARAM_TRCH_EN
#define RXBRP_CCm_PARAM_TRCH_EN_WIDTH                                                               L_WR99_CUIF_RXBRP_CCm_PARAM_TRCH_EN
#define RXBRP_CCm_PARAM_TRCH_EN_MASK                                                                M_WR99_CUIF_RXBRP_CCm_PARAM_TRCH_EN
#define RXBRP_CCm_PARAM_TRCH_EN_BIT                                                                 M_WR99_CUIF_RXBRP_CCm_PARAM_TRCH_EN
#define RXBRP_CCm_PARAM_MINTTI_LSB                                                                  P_WR99_CUIF_RXBRP_CCm_PARAM_MINTTI
#define RXBRP_CCm_PARAM_MINTTI_WIDTH                                                                L_WR99_CUIF_RXBRP_CCm_PARAM_MINTTI
#define RXBRP_CCm_PARAM_MINTTI_MASK                                                                 M_WR99_CUIF_RXBRP_CCm_PARAM_MINTTI
#define RXBRP_CCm_PARAM_MINTTI_BIT                                                                  M_WR99_CUIF_RXBRP_CCm_PARAM_MINTTI
#define RXBRP_CCm_PARAM_FMO_RESUME_LSB                                                              P_WR99_CUIF_RXBRP_CCm_PARAM_FMO_RESUME
#define RXBRP_CCm_PARAM_FMO_RESUME_WIDTH                                                            L_WR99_CUIF_RXBRP_CCm_PARAM_FMO_RESUME
#define RXBRP_CCm_PARAM_FMO_RESUME_MASK                                                             M_WR99_CUIF_RXBRP_CCm_PARAM_FMO_RESUME
#define RXBRP_CCm_PARAM_FMO_RESUME_BIT                                                              M_WR99_CUIF_RXBRP_CCm_PARAM_FMO_RESUME
#define RXBRP_CCm_PARAM_MAXTTI_LSB                                                                  P_WR99_CUIF_RXBRP_CCm_PARAM_MAXTTI
#define RXBRP_CCm_PARAM_MAXTTI_WIDTH                                                                L_WR99_CUIF_RXBRP_CCm_PARAM_MAXTTI
#define RXBRP_CCm_PARAM_MAXTTI_MASK                                                                 M_WR99_CUIF_RXBRP_CCm_PARAM_MAXTTI
#define RXBRP_CCm_PARAM_MAXTTI_BIT                                                                  M_WR99_CUIF_RXBRP_CCm_PARAM_MAXTTI
#define RXBRP_CCm_PARAM_BTFD_MODE_LSB                                                               P_WR99_CUIF_RXBRP_CCm_PARAM_BTFD_MODE
#define RXBRP_CCm_PARAM_BTFD_MODE_WIDTH                                                             L_WR99_CUIF_RXBRP_CCm_PARAM_BTFD_MODE
#define RXBRP_CCm_PARAM_BTFD_MODE_MASK                                                              M_WR99_CUIF_RXBRP_CCm_PARAM_BTFD_MODE
#define RXBRP_CCm_PARAM_BTFD_MODE_BIT                                                               M_WR99_CUIF_RXBRP_CCm_PARAM_BTFD_MODE
#define RXBRP_TRCHm_CFG_REF_EBD_IDX_LSB                                                             P_WR99_CUIF_RXBRP_TRCHm_CFG_REF_EBD_IDX
#define RXBRP_TRCHm_CFG_REF_EBD_IDX_WIDTH                                                           L_WR99_CUIF_RXBRP_TRCHm_CFG_REF_EBD_IDX
#define RXBRP_TRCHm_CFG_REF_EBD_IDX_MASK                                                            M_WR99_CUIF_RXBRP_TRCHm_CFG_REF_EBD_IDX
#define RXBRP_TRCHm_CFG_REF_EBD_IDX_BIT                                                             M_WR99_CUIF_RXBRP_TRCHm_CFG_REF_EBD_IDX
#define RXBRP_TRCHm_CFG_DUAL_TF_EN_LSB                                                              P_WR99_CUIF_RXBRP_TRCHm_CFG_DUAL_TF_EN
#define RXBRP_TRCHm_CFG_DUAL_TF_EN_WIDTH                                                            L_WR99_CUIF_RXBRP_TRCHm_CFG_DUAL_TF_EN
#define RXBRP_TRCHm_CFG_DUAL_TF_EN_MASK                                                             M_WR99_CUIF_RXBRP_TRCHm_CFG_DUAL_TF_EN
#define RXBRP_TRCHm_CFG_DUAL_TF_EN_BIT                                                              M_WR99_CUIF_RXBRP_TRCHm_CFG_DUAL_TF_EN
#define RXBRP_TRCHm_CFG_RM_TYPE_LSB                                                                 P_WR99_CUIF_RXBRP_TRCHm_CFG_RM_TYPE
#define RXBRP_TRCHm_CFG_RM_TYPE_WIDTH                                                               L_WR99_CUIF_RXBRP_TRCHm_CFG_RM_TYPE
#define RXBRP_TRCHm_CFG_RM_TYPE_MASK                                                                M_WR99_CUIF_RXBRP_TRCHm_CFG_RM_TYPE
#define RXBRP_TRCHm_CFG_RM_TYPE_BIT                                                                 M_WR99_CUIF_RXBRP_TRCHm_CFG_RM_TYPE
#define RXBRP_TRCHm_CFG_CRC_LSB                                                                     P_WR99_CUIF_RXBRP_TRCHm_CFG_CRC
#define RXBRP_TRCHm_CFG_CRC_WIDTH                                                                   L_WR99_CUIF_RXBRP_TRCHm_CFG_CRC
#define RXBRP_TRCHm_CFG_CRC_MASK                                                                    M_WR99_CUIF_RXBRP_TRCHm_CFG_CRC
#define RXBRP_TRCHm_CFG_CRC_BIT                                                                     M_WR99_CUIF_RXBRP_TRCHm_CFG_CRC
#define RXBRP_TRCHm_CFG_RATE_LSB                                                                    P_WR99_CUIF_RXBRP_TRCHm_CFG_RATE
#define RXBRP_TRCHm_CFG_RATE_WIDTH                                                                  L_WR99_CUIF_RXBRP_TRCHm_CFG_RATE
#define RXBRP_TRCHm_CFG_RATE_MASK                                                                   M_WR99_CUIF_RXBRP_TRCHm_CFG_RATE
#define RXBRP_TRCHm_CFG_RATE_BIT                                                                    M_WR99_CUIF_RXBRP_TRCHm_CFG_RATE
#define RXBRP_TRCHm_CFG_ENCODING_LSB                                                                P_WR99_CUIF_RXBRP_TRCHm_CFG_ENCODING
#define RXBRP_TRCHm_CFG_ENCODING_WIDTH                                                              L_WR99_CUIF_RXBRP_TRCHm_CFG_ENCODING
#define RXBRP_TRCHm_CFG_ENCODING_MASK                                                               M_WR99_CUIF_RXBRP_TRCHm_CFG_ENCODING
#define RXBRP_TRCHm_CFG_ENCODING_BIT                                                                M_WR99_CUIF_RXBRP_TRCHm_CFG_ENCODING
#define RXBRP_TRCHm_CFG_TTI_LSB                                                                     P_WR99_CUIF_RXBRP_TRCHm_CFG_TTI
#define RXBRP_TRCHm_CFG_TTI_WIDTH                                                                   L_WR99_CUIF_RXBRP_TRCHm_CFG_TTI
#define RXBRP_TRCHm_CFG_TTI_MASK                                                                    M_WR99_CUIF_RXBRP_TRCHm_CFG_TTI
#define RXBRP_TRCHm_CFG_TTI_BIT                                                                     M_WR99_CUIF_RXBRP_TRCHm_CFG_TTI
#define RXBRP_BCH_START_BCH_EN_LSB                                                                  P_WR99_CUIF_RXBRP_BCH_START_BCH_EN
#define RXBRP_BCH_START_BCH_EN_WIDTH                                                                L_WR99_CUIF_RXBRP_BCH_START_BCH_EN
#define RXBRP_BCH_START_BCH_EN_MASK                                                                 M_WR99_CUIF_RXBRP_BCH_START_BCH_EN
#define RXBRP_BCH_START_BCH_EN_BIT                                                                  M_WR99_CUIF_RXBRP_BCH_START_BCH_EN
#define RXBRP_BCHSFN_STOP_ENABLE_LSB                                                                P_WR99_CUIF_RXBRP_BCHSFN_STOP_ENABLE
#define RXBRP_BCHSFN_STOP_ENABLE_WIDTH                                                              L_WR99_CUIF_RXBRP_BCHSFN_STOP_ENABLE
#define RXBRP_BCHSFN_STOP_ENABLE_MASK                                                               M_WR99_CUIF_RXBRP_BCHSFN_STOP_ENABLE
#define RXBRP_BCHSFN_STOP_ENABLE_BIT                                                                M_WR99_CUIF_RXBRP_BCHSFN_STOP_ENABLE
#define RXBRP_BCHSFN_STOP_STOPPING_LSB                                                              P_WR99_CUIF_RXBRP_BCHSFN_STOP_STOPPING
#define RXBRP_BCHSFN_STOP_STOPPING_WIDTH                                                            L_WR99_CUIF_RXBRP_BCHSFN_STOP_STOPPING
#define RXBRP_BCHSFN_STOP_STOPPING_MASK                                                             M_WR99_CUIF_RXBRP_BCHSFN_STOP_STOPPING
#define RXBRP_BCHSFN_STOP_STOPPING_BIT                                                              M_WR99_CUIF_RXBRP_BCHSFN_STOP_STOPPING
#define RXBRP_CCm_TRCH_EN_OR_EBD_IRQ_TRCH_EN_OR_EBD_IRQ_LSB                                         P_WR99_CUIF_RXBRP_CCm_TRCH_EN_OR_EBD_IRQ_TRCH_EN_OR_EBD_IRQ
#define RXBRP_CCm_TRCH_EN_OR_EBD_IRQ_TRCH_EN_OR_EBD_IRQ_WIDTH                                       L_WR99_CUIF_RXBRP_CCm_TRCH_EN_OR_EBD_IRQ_TRCH_EN_OR_EBD_IRQ
#define RXBRP_CCm_TRCH_EN_OR_EBD_IRQ_TRCH_EN_OR_EBD_IRQ_MASK                                        M_WR99_CUIF_RXBRP_CCm_TRCH_EN_OR_EBD_IRQ_TRCH_EN_OR_EBD_IRQ
#define RXBRP_CCm_TRCH_EN_OR_EBD_IRQ_TRCH_EN_OR_EBD_IRQ_BIT                                         M_WR99_CUIF_RXBRP_CCm_TRCH_EN_OR_EBD_IRQ_TRCH_EN_OR_EBD_IRQ
#define RXBRP_CCm_BTFD_PHASE_ACT_PHASE_ACT_LSB                                                      P_WR99_CUIF_RXBRP_CCm_BTFD_PHASE_ACT_PHASE_ACT
#define RXBRP_CCm_BTFD_PHASE_ACT_PHASE_ACT_WIDTH                                                    L_WR99_CUIF_RXBRP_CCm_BTFD_PHASE_ACT_PHASE_ACT
#define RXBRP_CCm_BTFD_PHASE_ACT_PHASE_ACT_MASK                                                     M_WR99_CUIF_RXBRP_CCm_BTFD_PHASE_ACT_PHASE_ACT
#define RXBRP_CCm_BTFD_PHASE_ACT_PHASE_ACT_BIT                                                      M_WR99_CUIF_RXBRP_CCm_BTFD_PHASE_ACT_PHASE_ACT
#define RXBRP_BCH_GNRL_CFG_SFN_MODE_LSB                                                             P_WR99_CUIF_RXBRP_BCH_GNRL_CFG_SFN_MODE
#define RXBRP_BCH_GNRL_CFG_SFN_MODE_WIDTH                                                           L_WR99_CUIF_RXBRP_BCH_GNRL_CFG_SFN_MODE
#define RXBRP_BCH_GNRL_CFG_SFN_MODE_MASK                                                            M_WR99_CUIF_RXBRP_BCH_GNRL_CFG_SFN_MODE
#define RXBRP_BCH_GNRL_CFG_SFN_MODE_BIT                                                             M_WR99_CUIF_RXBRP_BCH_GNRL_CFG_SFN_MODE
#define RXBRP_CCm_3GLORX_EN_SW_MODE_LSB                                                             P_WR99_CUIF_RXBRP_CCm_3GLORX_EN_SW_MODE
#define RXBRP_CCm_3GLORX_EN_SW_MODE_WIDTH                                                           L_WR99_CUIF_RXBRP_CCm_3GLORX_EN_SW_MODE
#define RXBRP_CCm_3GLORX_EN_SW_MODE_MASK                                                            M_WR99_CUIF_RXBRP_CCm_3GLORX_EN_SW_MODE
#define RXBRP_CCm_3GLORX_EN_SW_MODE_BIT                                                             M_WR99_CUIF_RXBRP_CCm_3GLORX_EN_SW_MODE
#define RXBRP_CCm_3GLORX_EN_FRAME_BOUND_LSB                                                         P_WR99_CUIF_RXBRP_CCm_3GLORX_EN_FRAME_BOUND
#define RXBRP_CCm_3GLORX_EN_FRAME_BOUND_WIDTH                                                       L_WR99_CUIF_RXBRP_CCm_3GLORX_EN_FRAME_BOUND
#define RXBRP_CCm_3GLORX_EN_FRAME_BOUND_MASK                                                        M_WR99_CUIF_RXBRP_CCm_3GLORX_EN_FRAME_BOUND
#define RXBRP_CCm_3GLORX_EN_FRAME_BOUND_BIT                                                         M_WR99_CUIF_RXBRP_CCm_3GLORX_EN_FRAME_BOUND
#define RXBRP_CCm_3GLORX_EN_ENABLE_LSB                                                              P_WR99_CUIF_RXBRP_CCm_3GLORX_EN_ENABLE
#define RXBRP_CCm_3GLORX_EN_ENABLE_WIDTH                                                            L_WR99_CUIF_RXBRP_CCm_3GLORX_EN_ENABLE
#define RXBRP_CCm_3GLORX_EN_ENABLE_MASK                                                             M_WR99_CUIF_RXBRP_CCm_3GLORX_EN_ENABLE
#define RXBRP_CCm_3GLORX_EN_ENABLE_BIT                                                              M_WR99_CUIF_RXBRP_CCm_3GLORX_EN_ENABLE
#define RXBRP_CCm_3GLORX_VALID_DATA_NUM_VALID_NUM_LSB                                               P_WR99_CUIF_RXBRP_CCm_3GLORX_VALID_DATA_NUM_VALID_NUM
#define RXBRP_CCm_3GLORX_VALID_DATA_NUM_VALID_NUM_WIDTH                                             L_WR99_CUIF_RXBRP_CCm_3GLORX_VALID_DATA_NUM_VALID_NUM
#define RXBRP_CCm_3GLORX_VALID_DATA_NUM_VALID_NUM_MASK                                              M_WR99_CUIF_RXBRP_CCm_3GLORX_VALID_DATA_NUM_VALID_NUM
#define RXBRP_CCm_3GLORX_VALID_DATA_NUM_VALID_NUM_BIT                                               M_WR99_CUIF_RXBRP_CCm_3GLORX_VALID_DATA_NUM_VALID_NUM
#define RXBRP_CCm_3GLORX_SVALUE_THRESHOLD_S_THRES_LSB                                               P_WR99_CUIF_RXBRP_CCm_3GLORX_SVALUE_THRESHOLD_S_THRES
#define RXBRP_CCm_3GLORX_SVALUE_THRESHOLD_S_THRES_WIDTH                                             L_WR99_CUIF_RXBRP_CCm_3GLORX_SVALUE_THRESHOLD_S_THRES
#define RXBRP_CCm_3GLORX_SVALUE_THRESHOLD_S_THRES_MASK                                              M_WR99_CUIF_RXBRP_CCm_3GLORX_SVALUE_THRESHOLD_S_THRES
#define RXBRP_CCm_3GLORX_SVALUE_THRESHOLD_S_THRES_BIT                                               M_WR99_CUIF_RXBRP_CCm_3GLORX_SVALUE_THRESHOLD_S_THRES
#define RXBRP_CCm_3GLORX_EBD_COEFF_REF_LSB                                                          P_WR99_CUIF_RXBRP_CCm_3GLORX_EBD_COEFF_REF
#define RXBRP_CCm_3GLORX_EBD_COEFF_REF_WIDTH                                                        L_WR99_CUIF_RXBRP_CCm_3GLORX_EBD_COEFF_REF
#define RXBRP_CCm_3GLORX_EBD_COEFF_REF_MASK                                                         M_WR99_CUIF_RXBRP_CCm_3GLORX_EBD_COEFF_REF
#define RXBRP_CCm_3GLORX_EBD_COEFF_REF_BIT                                                          M_WR99_CUIF_RXBRP_CCm_3GLORX_EBD_COEFF_REF
#define RXBRP_CCm_3GLORX_DUAL_COEFF_DUALTF_LSB                                                      P_WR99_CUIF_RXBRP_CCm_3GLORX_DUAL_COEFF_DUALTF
#define RXBRP_CCm_3GLORX_DUAL_COEFF_DUALTF_WIDTH                                                    L_WR99_CUIF_RXBRP_CCm_3GLORX_DUAL_COEFF_DUALTF
#define RXBRP_CCm_3GLORX_DUAL_COEFF_DUALTF_MASK                                                     M_WR99_CUIF_RXBRP_CCm_3GLORX_DUAL_COEFF_DUALTF
#define RXBRP_CCm_3GLORX_DUAL_COEFF_DUALTF_BIT                                                      M_WR99_CUIF_RXBRP_CCm_3GLORX_DUAL_COEFF_DUALTF
#define RXBRP_3GLORX_DFE_PULSE_WIDTH_LSB                                                            P_WR99_CUIF_RXBRP_3GLORX_DFE_PULSE_WIDTH
#define RXBRP_3GLORX_DFE_PULSE_WIDTH_WIDTH                                                          L_WR99_CUIF_RXBRP_3GLORX_DFE_PULSE_WIDTH
#define RXBRP_3GLORX_DFE_PULSE_WIDTH_MASK                                                           M_WR99_CUIF_RXBRP_3GLORX_DFE_PULSE_WIDTH
#define RXBRP_3GLORX_DFE_PULSE_WIDTH_BIT                                                            M_WR99_CUIF_RXBRP_3GLORX_DFE_PULSE_WIDTH
#define RXBRP_CCm_EBD_DEC_TRCH_MASK_TRCH_EN_LSB                                                     P_WR99_CUIF_RXBRP_CCm_EBD_DEC_TRCH_MASK_TRCH_EN
#define RXBRP_CCm_EBD_DEC_TRCH_MASK_TRCH_EN_WIDTH                                                   L_WR99_CUIF_RXBRP_CCm_EBD_DEC_TRCH_MASK_TRCH_EN
#define RXBRP_CCm_EBD_DEC_TRCH_MASK_TRCH_EN_MASK                                                    M_WR99_CUIF_RXBRP_CCm_EBD_DEC_TRCH_MASK_TRCH_EN
#define RXBRP_CCm_EBD_DEC_TRCH_MASK_TRCH_EN_BIT                                                     M_WR99_CUIF_RXBRP_CCm_EBD_DEC_TRCH_MASK_TRCH_EN
#define RXBRP_CCm_STOP_ENABLE_LSB                                                                   P_WR99_CUIF_RXBRP_CCm_STOP_ENABLE
#define RXBRP_CCm_STOP_ENABLE_WIDTH                                                                 L_WR99_CUIF_RXBRP_CCm_STOP_ENABLE
#define RXBRP_CCm_STOP_ENABLE_MASK                                                                  M_WR99_CUIF_RXBRP_CCm_STOP_ENABLE
#define RXBRP_CCm_STOP_ENABLE_BIT                                                                   M_WR99_CUIF_RXBRP_CCm_STOP_ENABLE
#define RXBRP_CCm_STOP_STOPPING_LSB                                                                 P_WR99_CUIF_RXBRP_CCm_STOP_STOPPING
#define RXBRP_CCm_STOP_STOPPING_WIDTH                                                               L_WR99_CUIF_RXBRP_CCm_STOP_STOPPING
#define RXBRP_CCm_STOP_STOPPING_MASK                                                                M_WR99_CUIF_RXBRP_CCm_STOP_STOPPING
#define RXBRP_CCm_STOP_STOPPING_BIT                                                                 M_WR99_CUIF_RXBRP_CCm_STOP_STOPPING
#define RXBRP_CCm_SYMBOL_NUM_SYM_NUM_LSB                                                            P_WR99_CUIF_RXBRP_CCm_SYMBOL_NUM_SYM_NUM
#define RXBRP_CCm_SYMBOL_NUM_SYM_NUM_WIDTH                                                          L_WR99_CUIF_RXBRP_CCm_SYMBOL_NUM_SYM_NUM
#define RXBRP_CCm_SYMBOL_NUM_SYM_NUM_MASK                                                           M_WR99_CUIF_RXBRP_CCm_SYMBOL_NUM_SYM_NUM
#define RXBRP_CCm_SYMBOL_NUM_SYM_NUM_BIT                                                            M_WR99_CUIF_RXBRP_CCm_SYMBOL_NUM_SYM_NUM
#define RXBRP_CCm_SYMBOL_SUM_SYM_SUM_LSB                                                            P_WR99_CUIF_RXBRP_CCm_SYMBOL_SUM_SYM_SUM
#define RXBRP_CCm_SYMBOL_SUM_SYM_SUM_WIDTH                                                          L_WR99_CUIF_RXBRP_CCm_SYMBOL_SUM_SYM_SUM
#define RXBRP_CCm_SYMBOL_SUM_SYM_SUM_MASK                                                           M_WR99_CUIF_RXBRP_CCm_SYMBOL_SUM_SYM_SUM
#define RXBRP_CCm_SYMBOL_SUM_SYM_SUM_BIT                                                            M_WR99_CUIF_RXBRP_CCm_SYMBOL_SUM_SYM_SUM
#define RXBRP_CCm_BUFIDX_BUFIDX_LSB                                                                 P_WR99_CUIF_RXBRP_CCm_BUFIDX_BUFIDX
#define RXBRP_CCm_BUFIDX_BUFIDX_WIDTH                                                               L_WR99_CUIF_RXBRP_CCm_BUFIDX_BUFIDX
#define RXBRP_CCm_BUFIDX_BUFIDX_MASK                                                                M_WR99_CUIF_RXBRP_CCm_BUFIDX_BUFIDX
#define RXBRP_CCm_BUFIDX_BUFIDX_BIT                                                                 M_WR99_CUIF_RXBRP_CCm_BUFIDX_BUFIDX
#define RXBRP_CCm_SUSPEND_GAP_DVIT_RESET_FOR_GEMINI_RESUME_LSB                                      P_WR99_CUIF_RXBRP_CCm_SUSPEND_GAP_DVIT_RESET_FOR_GEMINI_RESUME
#define RXBRP_CCm_SUSPEND_GAP_DVIT_RESET_FOR_GEMINI_RESUME_WIDTH                                    L_WR99_CUIF_RXBRP_CCm_SUSPEND_GAP_DVIT_RESET_FOR_GEMINI_RESUME
#define RXBRP_CCm_SUSPEND_GAP_DVIT_RESET_FOR_GEMINI_RESUME_MASK                                     M_WR99_CUIF_RXBRP_CCm_SUSPEND_GAP_DVIT_RESET_FOR_GEMINI_RESUME
#define RXBRP_CCm_SUSPEND_GAP_DVIT_RESET_FOR_GEMINI_RESUME_BIT                                      M_WR99_CUIF_RXBRP_CCm_SUSPEND_GAP_DVIT_RESET_FOR_GEMINI_RESUME
#define RXBRP_CCm_SUSPEND_GAP_GAP_LSB                                                               P_WR99_CUIF_RXBRP_CCm_SUSPEND_GAP_GAP
#define RXBRP_CCm_SUSPEND_GAP_GAP_WIDTH                                                             L_WR99_CUIF_RXBRP_CCm_SUSPEND_GAP_GAP
#define RXBRP_CCm_SUSPEND_GAP_GAP_MASK                                                              M_WR99_CUIF_RXBRP_CCm_SUSPEND_GAP_GAP
#define RXBRP_CCm_SUSPEND_GAP_GAP_BIT                                                               M_WR99_CUIF_RXBRP_CCm_SUSPEND_GAP_GAP
#define RXBRP_CCm_WRITE_PHCH_TWICE_LSB                                                              P_WR99_CUIF_RXBRP_CCm_WRITE_PHCH_TWICE
#define RXBRP_CCm_WRITE_PHCH_TWICE_WIDTH                                                            L_WR99_CUIF_RXBRP_CCm_WRITE_PHCH_TWICE
#define RXBRP_CCm_WRITE_PHCH_TWICE_MASK                                                             M_WR99_CUIF_RXBRP_CCm_WRITE_PHCH_TWICE
#define RXBRP_CCm_WRITE_PHCH_TWICE_BIT                                                              M_WR99_CUIF_RXBRP_CCm_WRITE_PHCH_TWICE
#define RXBRP_CCm_TRCH_DONE_RFOFF_STATUS_LSB                                                        P_WR99_CUIF_RXBRP_CCm_TRCH_DONE_RFOFF_STATUS
#define RXBRP_CCm_TRCH_DONE_RFOFF_STATUS_WIDTH                                                      L_WR99_CUIF_RXBRP_CCm_TRCH_DONE_RFOFF_STATUS
#define RXBRP_CCm_TRCH_DONE_RFOFF_STATUS_MASK                                                       M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_RFOFF_STATUS
#define RXBRP_CCm_TRCH_DONE_RFOFF_STATUS_BIT                                                        M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_RFOFF_STATUS
#define RXBRP_CCm_TRCH_DONE_SVALUE_STATUS_LSB                                                       P_WR99_CUIF_RXBRP_CCm_TRCH_DONE_SVALUE_STATUS
#define RXBRP_CCm_TRCH_DONE_SVALUE_STATUS_WIDTH                                                     L_WR99_CUIF_RXBRP_CCm_TRCH_DONE_SVALUE_STATUS
#define RXBRP_CCm_TRCH_DONE_SVALUE_STATUS_MASK                                                      M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_SVALUE_STATUS
#define RXBRP_CCm_TRCH_DONE_SVALUE_STATUS_BIT                                                       M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_SVALUE_STATUS
#define RXBRP_CCm_TRCH_DONE_CRC_STATUS_LSB                                                          P_WR99_CUIF_RXBRP_CCm_TRCH_DONE_CRC_STATUS
#define RXBRP_CCm_TRCH_DONE_CRC_STATUS_WIDTH                                                        L_WR99_CUIF_RXBRP_CCm_TRCH_DONE_CRC_STATUS
#define RXBRP_CCm_TRCH_DONE_CRC_STATUS_MASK                                                         M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_CRC_STATUS
#define RXBRP_CCm_TRCH_DONE_CRC_STATUS_BIT                                                          M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_CRC_STATUS
#define RXBRP_CCm_TRCH_DONE_EBD_STATUS_LSB                                                          P_WR99_CUIF_RXBRP_CCm_TRCH_DONE_EBD_STATUS
#define RXBRP_CCm_TRCH_DONE_EBD_STATUS_WIDTH                                                        L_WR99_CUIF_RXBRP_CCm_TRCH_DONE_EBD_STATUS
#define RXBRP_CCm_TRCH_DONE_EBD_STATUS_MASK                                                         M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_EBD_STATUS
#define RXBRP_CCm_TRCH_DONE_EBD_STATUS_BIT                                                          M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_EBD_STATUS
#define RXBRP_CCm_TRCH_DONE_DUALTF_STATUS_LSB                                                       P_WR99_CUIF_RXBRP_CCm_TRCH_DONE_DUALTF_STATUS
#define RXBRP_CCm_TRCH_DONE_DUALTF_STATUS_WIDTH                                                     L_WR99_CUIF_RXBRP_CCm_TRCH_DONE_DUALTF_STATUS
#define RXBRP_CCm_TRCH_DONE_DUALTF_STATUS_MASK                                                      M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_DUALTF_STATUS
#define RXBRP_CCm_TRCH_DONE_DUALTF_STATUS_BIT                                                       M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_DUALTF_STATUS
#define RXBRP_CCm_TRCH_DONE_DONE_FLAG_LSB                                                           P_WR99_CUIF_RXBRP_CCm_TRCH_DONE_DONE_FLAG
#define RXBRP_CCm_TRCH_DONE_DONE_FLAG_WIDTH                                                         L_WR99_CUIF_RXBRP_CCm_TRCH_DONE_DONE_FLAG
#define RXBRP_CCm_TRCH_DONE_DONE_FLAG_MASK                                                          M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_DONE_FLAG
#define RXBRP_CCm_TRCH_DONE_DONE_FLAG_BIT                                                           M_WR99_CUIF_RXBRP_CCm_TRCH_DONE_DONE_FLAG
#define RXBRP_TRCHm_TTI_MIN_SCF_MINSCF_LSB                                                          P_WR99_CUIF_RXBRP_TRCHm_TTI_MIN_SCF_MINSCF
#define RXBRP_TRCHm_TTI_MIN_SCF_MINSCF_WIDTH                                                        L_WR99_CUIF_RXBRP_TRCHm_TTI_MIN_SCF_MINSCF
#define RXBRP_TRCHm_TTI_MIN_SCF_MINSCF_MASK                                                         M_WR99_CUIF_RXBRP_TRCHm_TTI_MIN_SCF_MINSCF
#define RXBRP_TRCHm_TTI_MIN_SCF_MINSCF_BIT                                                          M_WR99_CUIF_RXBRP_TRCHm_TTI_MIN_SCF_MINSCF
#define RXBRP_BCHSFN_GUARD_TIME_SLOT_MASK_LSB                                                       P_WR99_CUIF_RXBRP_BCHSFN_GUARD_TIME_SLOT_MASK
#define RXBRP_BCHSFN_GUARD_TIME_SLOT_MASK_WIDTH                                                     L_WR99_CUIF_RXBRP_BCHSFN_GUARD_TIME_SLOT_MASK
#define RXBRP_BCHSFN_GUARD_TIME_SLOT_MASK_MASK                                                      M_WR99_CUIF_RXBRP_BCHSFN_GUARD_TIME_SLOT_MASK
#define RXBRP_BCHSFN_GUARD_TIME_SLOT_MASK_BIT                                                       M_WR99_CUIF_RXBRP_BCHSFN_GUARD_TIME_SLOT_MASK
//#endif


