#ifndef __MCD_CMIF_H__
#define __MCD_CMIF_H__

#include "reg_access.h"
#include "c2k_base_addr_cmif.h"

#define CMIF_MCD_REG_BASE                                             (CMIF_RAKE_MCD_OFFSET)
#define CMIF_MCD_CTRL                                                 (CMIF_MCD_REG_BASE + 0x0000)
#define CMIF_MCD_RAB_LEN                                              (CMIF_MCD_REG_BASE + 0x0004)
#define CMIF_MCD_RABOFT                                               (CMIF_MCD_REG_BASE + 0x0008)
#define CMIF_MCD_RAC_GAIN                                             (CMIF_MCD_REG_BASE + 0x000C)
#define CMIF_MCD_PCG                                                  (CMIF_MCD_REG_BASE + 0x0010)
#define CMIF_MCD_SERV                                                 (CMIF_MCD_REG_BASE + 0x0014)
#define CMIF_MCD_DRCL_PERIOD                                          (CMIF_MCD_REG_BASE + 0x0018)
#define CMIF_MCD_DRCL_LEN                                             (CMIF_MCD_REG_BASE + 0x001C)
#define CMIF_MCD_ARQ_MODE                                             (CMIF_MCD_REG_BASE + 0x0020)
#define CMIF_MCD_ARQ_TYPE                                             (CMIF_MCD_REG_BASE + 0x0024)
#define CMIF_MCD_TC_FRAB                                              (CMIF_MCD_REG_BASE + 0x0028)
#define CMIF_MCD_TC_QRAB                                              (CMIF_MCD_REG_BASE + 0x002C)
#define CMIF_MCD_RPC                                                  (CMIF_MCD_REG_BASE + 0x0030)
#define CMIF_MCD_DONE                                                 (CMIF_MCD_REG_BASE + 0x0034)
#define CMIF_MCD_MAXFRAB                                              (CMIF_MCD_REG_BASE + 0x0038)
#define CMIF_MCD_HLARQ_DET                                            (CMIF_MCD_REG_BASE + 0x003C)
#define CMIF_MCD_DRC_LOCK(i)                                          (CMIF_MCD_REG_BASE + 0x0040 + ((i) * 0x4))
#define CMIF_MCD_SLOTQRAB(i)                                          (CMIF_MCD_REG_BASE + 0x0058 + ((i) * 0x4))
#define CMIF_MCD_RAB0                                                 (CMIF_MCD_REG_BASE + 0x0070)
#define CMIF_MCD_HARQMET0                                             (CMIF_MCD_REG_BASE + 0x0074)
#define CMIF_MCD_PARQMET0                                             (CMIF_MCD_REG_BASE + 0x0078)
#define CMIF_MCD_CIMET0                                               (CMIF_MCD_REG_BASE + 0x007C)
#define CMIF_MCD_RAB1                                                 (CMIF_MCD_REG_BASE + 0x0080)
#define CMIF_MCD_HARQMET1                                             (CMIF_MCD_REG_BASE + 0x0084)
#define CMIF_MCD_PARQMET1                                             (CMIF_MCD_REG_BASE + 0x0088)
#define CMIF_MCD_CIMET1                                               (CMIF_MCD_REG_BASE + 0x008C)
#define CMIF_MCD_RAB2                                                 (CMIF_MCD_REG_BASE + 0x0090)
#define CMIF_MCD_HARQMET2                                             (CMIF_MCD_REG_BASE + 0x0094)
#define CMIF_MCD_PARQMET2                                             (CMIF_MCD_REG_BASE + 0x0098)
#define CMIF_MCD_CIMET2                                               (CMIF_MCD_REG_BASE + 0x009C)
#define CMIF_MCD_RAB3                                                 (CMIF_MCD_REG_BASE + 0x00A0)
#define CMIF_MCD_HARQMET3                                             (CMIF_MCD_REG_BASE + 0x00A4)
#define CMIF_MCD_PARQMET3                                             (CMIF_MCD_REG_BASE + 0x00A8)
#define CMIF_MCD_CIMET3                                               (CMIF_MCD_REG_BASE + 0x00AC)
#define CMIF_MCD_RAB4                                                 (CMIF_MCD_REG_BASE + 0x00B0)
#define CMIF_MCD_HARQMET4                                             (CMIF_MCD_REG_BASE + 0x00B4)
#define CMIF_MCD_PARQMET4                                             (CMIF_MCD_REG_BASE + 0x00B8)
#define CMIF_MCD_CIMET4                                               (CMIF_MCD_REG_BASE + 0x00BC)
#define CMIF_MCD_RAB5                                                 (CMIF_MCD_REG_BASE + 0x00C0)
#define CMIF_MCD_HARQMET5                                             (CMIF_MCD_REG_BASE + 0x00C4)
#define CMIF_MCD_PARQMET5                                             (CMIF_MCD_REG_BASE + 0x00C8)
#define CMIF_MCD_CIMET5                                               (CMIF_MCD_REG_BASE + 0x00CC)
#define CMIF_MCD_STAT_REG                                             (CMIF_MCD_REG_BASE + 0x00D0)
#define CMIF_MCD_DRCVAL(i)                                            (CMIF_MCD_REG_BASE + 0x00D4 + ((i) * 0x4))
#define CMIF_MCD_RPC_TC                                               (CMIF_MCD_REG_BASE + 0x00EC)
#define CMIF_MCD_HL_DMET(i)                                           (CMIF_MCD_REG_BASE + 0x00F0 + ((i) * 0x4))
#define CMIF_MCD_HARQ_REL_TH                                          (CMIF_MCD_REG_BASE + 0x0108)
#define CMIF_MCD_ARQ_SEL                                              (CMIF_MCD_REG_BASE + 0x010C)
#define CMIF_MCD_MRC_MODE                                             (CMIF_MCD_REG_BASE + 0x0110)
#define CMIF_MCD_RPC_DEBUG_MODE                                       (CMIF_MCD_REG_BASE + 0x0114)
#define CMIF_MCD_ARQ_DEBUG_MODE                                       (CMIF_MCD_REG_BASE + 0x0118)

#define M_CMIF_MCD_CTRL_RD()                                          REG_READ(CMIF_MCD_CTRL)
#define M_CMIF_MCD_RAB_LEN_RD()                                       REG_READ(CMIF_MCD_RAB_LEN)
#define M_CMIF_MCD_RABOFT_RD()                                        REG_READ(CMIF_MCD_RABOFT)
#define M_CMIF_MCD_RAC_GAIN_RD()                                      REG_READ(CMIF_MCD_RAC_GAIN)
#define M_CMIF_MCD_PCG_RD()                                           REG_READ(CMIF_MCD_PCG)
#define M_CMIF_MCD_SERV_RD()                                          REG_READ(CMIF_MCD_SERV)
#define M_CMIF_MCD_DRCL_PERIOD_RD()                                   REG_READ(CMIF_MCD_DRCL_PERIOD)
#define M_CMIF_MCD_DRCL_LEN_RD()                                      REG_READ(CMIF_MCD_DRCL_LEN)
#define M_CMIF_MCD_ARQ_MODE_RD()                                      REG_READ(CMIF_MCD_ARQ_MODE)
#define M_CMIF_MCD_ARQ_TYPE_RD()                                      REG_READ(CMIF_MCD_ARQ_TYPE)
#define M_CMIF_MCD_TC_FRAB_RD()                                       REG_READ(CMIF_MCD_TC_FRAB)
#define M_CMIF_MCD_TC_QRAB_RD()                                       REG_READ(CMIF_MCD_TC_QRAB)
#define M_CMIF_MCD_RPC_RD()                                           REG_READ(CMIF_MCD_RPC)
#define M_CMIF_MCD_DONE_RD()                                          REG_READ(CMIF_MCD_DONE)
#define M_CMIF_MCD_MAXFRAB_RD()                                       REG_READ(CMIF_MCD_MAXFRAB)
#define M_CMIF_MCD_HLARQ_DET_RD()                                     REG_READ(CMIF_MCD_HLARQ_DET)
#define M_CMIF_MCD_DRC_LOCK_RD(i)                                     REG_READ(CMIF_MCD_DRC_LOCK(i))
#define M_CMIF_MCD_SLOTQRAB_RD(i)                                     REG_READ(CMIF_MCD_SLOTQRAB(i))
#define M_CMIF_MCD_RAB0_RD()                                          REG_READ(CMIF_MCD_RAB0)
#define M_CMIF_MCD_HARQMET0_RD()                                      REG_READ(CMIF_MCD_HARQMET0)
#define M_CMIF_MCD_PARQMET0_RD()                                      REG_READ(CMIF_MCD_PARQMET0)
#define M_CMIF_MCD_CIMET0_RD()                                        REG_READ(CMIF_MCD_CIMET0)
#define M_CMIF_MCD_RAB1_RD()                                          REG_READ(CMIF_MCD_RAB1)
#define M_CMIF_MCD_HARQMET1_RD()                                      REG_READ(CMIF_MCD_HARQMET1)
#define M_CMIF_MCD_PARQMET1_RD()                                      REG_READ(CMIF_MCD_PARQMET1)
#define M_CMIF_MCD_CIMET1_RD()                                        REG_READ(CMIF_MCD_CIMET1)
#define M_CMIF_MCD_RAB2_RD()                                          REG_READ(CMIF_MCD_RAB2)
#define M_CMIF_MCD_HARQMET2_RD()                                      REG_READ(CMIF_MCD_HARQMET2)
#define M_CMIF_MCD_PARQMET2_RD()                                      REG_READ(CMIF_MCD_PARQMET2)
#define M_CMIF_MCD_CIMET2_RD()                                        REG_READ(CMIF_MCD_CIMET2)
#define M_CMIF_MCD_RAB3_RD()                                          REG_READ(CMIF_MCD_RAB3)
#define M_CMIF_MCD_HARQMET3_RD()                                      REG_READ(CMIF_MCD_HARQMET3)
#define M_CMIF_MCD_PARQMET3_RD()                                      REG_READ(CMIF_MCD_PARQMET3)
#define M_CMIF_MCD_CIMET3_RD()                                        REG_READ(CMIF_MCD_CIMET3)
#define M_CMIF_MCD_RAB4_RD()                                          REG_READ(CMIF_MCD_RAB4)
#define M_CMIF_MCD_HARQMET4_RD()                                      REG_READ(CMIF_MCD_HARQMET4)
#define M_CMIF_MCD_PARQMET4_RD()                                      REG_READ(CMIF_MCD_PARQMET4)
#define M_CMIF_MCD_CIMET4_RD()                                        REG_READ(CMIF_MCD_CIMET4)
#define M_CMIF_MCD_RAB5_RD()                                          REG_READ(CMIF_MCD_RAB5)
#define M_CMIF_MCD_HARQMET5_RD()                                      REG_READ(CMIF_MCD_HARQMET5)
#define M_CMIF_MCD_PARQMET5_RD()                                      REG_READ(CMIF_MCD_PARQMET5)
#define M_CMIF_MCD_CIMET5_RD()                                        REG_READ(CMIF_MCD_CIMET5)
#define M_CMIF_MCD_STAT_REG_RD()                                      REG_READ(CMIF_MCD_STAT_REG)
#define M_CMIF_MCD_DRCVAL_RD(i)                                       REG_READ(CMIF_MCD_DRCVAL(i))
#define M_CMIF_MCD_RPC_TC_RD()                                        REG_READ(CMIF_MCD_RPC_TC)
#define M_CMIF_MCD_HL_DMET_RD(i)                                      REG_READ(CMIF_MCD_HL_DMET(i))
#define M_CMIF_MCD_HARQ_REL_TH_RD()                                   REG_READ(CMIF_MCD_HARQ_REL_TH)
#define M_CMIF_MCD_ARQ_SEL_RD()                                       REG_READ(CMIF_MCD_ARQ_SEL)
#define M_CMIF_MCD_MRC_MODE_RD()                                      REG_READ(CMIF_MCD_MRC_MODE)
#define M_CMIF_MCD_RPC_DEBUG_MODE_RD()                                REG_READ(CMIF_MCD_RPC_DEBUG_MODE)
#define M_CMIF_MCD_ARQ_DEBUG_MODE_RD()                                REG_READ(CMIF_MCD_ARQ_DEBUG_MODE)

#define M_CMIF_MCD_CTRL_WR(reg)                                       REG_WRITE(CMIF_MCD_CTRL, reg)
#define M_CMIF_MCD_RAB_LEN_WR(reg)                                    REG_WRITE(CMIF_MCD_RAB_LEN, reg)
#define M_CMIF_MCD_RABOFT_WR(reg)                                     REG_WRITE(CMIF_MCD_RABOFT, reg)
#define M_CMIF_MCD_RAC_GAIN_WR(reg)                                   REG_WRITE(CMIF_MCD_RAC_GAIN, reg)
#define M_CMIF_MCD_PCG_WR(reg)                                        REG_WRITE(CMIF_MCD_PCG, reg)
#define M_CMIF_MCD_SERV_WR(reg)                                       REG_WRITE(CMIF_MCD_SERV, reg)
#define M_CMIF_MCD_DRCL_PERIOD_WR(reg)                                REG_WRITE(CMIF_MCD_DRCL_PERIOD, reg)
#define M_CMIF_MCD_DRCL_LEN_WR(reg)                                   REG_WRITE(CMIF_MCD_DRCL_LEN, reg)
#define M_CMIF_MCD_ARQ_MODE_WR(reg)                                   REG_WRITE(CMIF_MCD_ARQ_MODE, reg)
#define M_CMIF_MCD_ARQ_TYPE_WR(reg)                                   REG_WRITE(CMIF_MCD_ARQ_TYPE, reg)
#define M_CMIF_MCD_TC_FRAB_WR(reg)                                    REG_WRITE(CMIF_MCD_TC_FRAB, reg)
#define M_CMIF_MCD_TC_QRAB_WR(reg)                                    REG_WRITE(CMIF_MCD_TC_QRAB, reg)
#define M_CMIF_MCD_RPC_WR(reg)                                        REG_WRITE(CMIF_MCD_RPC, reg)
#define M_CMIF_MCD_DONE_WR(reg)                                       REG_WRITE(CMIF_MCD_DONE, reg)
#define M_CMIF_MCD_MAXFRAB_WR(reg)                                    REG_WRITE(CMIF_MCD_MAXFRAB, reg)
#define M_CMIF_MCD_HLARQ_DET_WR(reg)                                  REG_WRITE(CMIF_MCD_HLARQ_DET, reg)
#define M_CMIF_MCD_DRC_LOCK_WR(i, reg)                                REG_WRITE(CMIF_MCD_DRC_LOCK(i), reg)
#define M_CMIF_MCD_SLOTQRAB_WR(i, reg)                                REG_WRITE(CMIF_MCD_SLOTQRAB(i), reg)
#define M_CMIF_MCD_RAB0_WR(reg)                                       REG_WRITE(CMIF_MCD_RAB0, reg)
#define M_CMIF_MCD_HARQMET0_WR(reg)                                   REG_WRITE(CMIF_MCD_HARQMET0, reg)
#define M_CMIF_MCD_PARQMET0_WR(reg)                                   REG_WRITE(CMIF_MCD_PARQMET0, reg)
#define M_CMIF_MCD_CIMET0_WR(reg)                                     REG_WRITE(CMIF_MCD_CIMET0, reg)
#define M_CMIF_MCD_RAB1_WR(reg)                                       REG_WRITE(CMIF_MCD_RAB1, reg)
#define M_CMIF_MCD_HARQMET1_WR(reg)                                   REG_WRITE(CMIF_MCD_HARQMET1, reg)
#define M_CMIF_MCD_PARQMET1_WR(reg)                                   REG_WRITE(CMIF_MCD_PARQMET1, reg)
#define M_CMIF_MCD_CIMET1_WR(reg)                                     REG_WRITE(CMIF_MCD_CIMET1, reg)
#define M_CMIF_MCD_RAB2_WR(reg)                                       REG_WRITE(CMIF_MCD_RAB2, reg)
#define M_CMIF_MCD_HARQMET2_WR(reg)                                   REG_WRITE(CMIF_MCD_HARQMET2, reg)
#define M_CMIF_MCD_PARQMET2_WR(reg)                                   REG_WRITE(CMIF_MCD_PARQMET2, reg)
#define M_CMIF_MCD_CIMET2_WR(reg)                                     REG_WRITE(CMIF_MCD_CIMET2, reg)
#define M_CMIF_MCD_RAB3_WR(reg)                                       REG_WRITE(CMIF_MCD_RAB3, reg)
#define M_CMIF_MCD_HARQMET3_WR(reg)                                   REG_WRITE(CMIF_MCD_HARQMET3, reg)
#define M_CMIF_MCD_PARQMET3_WR(reg)                                   REG_WRITE(CMIF_MCD_PARQMET3, reg)
#define M_CMIF_MCD_CIMET3_WR(reg)                                     REG_WRITE(CMIF_MCD_CIMET3, reg)
#define M_CMIF_MCD_RAB4_WR(reg)                                       REG_WRITE(CMIF_MCD_RAB4, reg)
#define M_CMIF_MCD_HARQMET4_WR(reg)                                   REG_WRITE(CMIF_MCD_HARQMET4, reg)
#define M_CMIF_MCD_PARQMET4_WR(reg)                                   REG_WRITE(CMIF_MCD_PARQMET4, reg)
#define M_CMIF_MCD_CIMET4_WR(reg)                                     REG_WRITE(CMIF_MCD_CIMET4, reg)
#define M_CMIF_MCD_RAB5_WR(reg)                                       REG_WRITE(CMIF_MCD_RAB5, reg)
#define M_CMIF_MCD_HARQMET5_WR(reg)                                   REG_WRITE(CMIF_MCD_HARQMET5, reg)
#define M_CMIF_MCD_PARQMET5_WR(reg)                                   REG_WRITE(CMIF_MCD_PARQMET5, reg)
#define M_CMIF_MCD_CIMET5_WR(reg)                                     REG_WRITE(CMIF_MCD_CIMET5, reg)
#define M_CMIF_MCD_STAT_REG_WR(reg)                                   REG_WRITE(CMIF_MCD_STAT_REG, reg)
#define M_CMIF_MCD_DRCVAL_WR(i, reg)                                  REG_WRITE(CMIF_MCD_DRCVAL(i), reg)
#define M_CMIF_MCD_RPC_TC_WR(reg)                                     REG_WRITE(CMIF_MCD_RPC_TC, reg)
#define M_CMIF_MCD_HL_DMET_WR(i, reg)                                 REG_WRITE(CMIF_MCD_HL_DMET(i), reg)
#define M_CMIF_MCD_HARQ_REL_TH_WR(reg)                                REG_WRITE(CMIF_MCD_HARQ_REL_TH, reg)
#define M_CMIF_MCD_ARQ_SEL_WR(reg)                                    REG_WRITE(CMIF_MCD_ARQ_SEL, reg)
#define M_CMIF_MCD_MRC_MODE_WR(reg)                                   REG_WRITE(CMIF_MCD_MRC_MODE, reg)
#define M_CMIF_MCD_RPC_DEBUG_MODE_WR(reg)                             REG_WRITE(CMIF_MCD_RPC_DEBUG_MODE, reg)
#define M_CMIF_MCD_ARQ_DEBUG_MODE_WR(reg)                             REG_WRITE(CMIF_MCD_ARQ_DEBUG_MODE, reg)

#define CMIF_MCD_CTRL_REVA_BIT_LSB                                    (3)
#define CMIF_MCD_CTRL_REVA_BIT_WIDTH                                  (1)
#define CMIF_MCD_CTRL_REVA_BIT_MASK                                   ((UINT32) (((1<<CMIF_MCD_CTRL_REVA_BIT_WIDTH)-1) << CMIF_MCD_CTRL_REVA_BIT_LSB) )
#define CMIF_MCD_CTRL_REVA_FLD_WR(reg, val)                           (reg |= (val) << CMIF_MCD_CTRL_REVA_BIT_LSB)
#define CMIF_MCD_CTRL_REVA_FLD_RD()                                   ((M_CMIF_MCD_CTRL_RD() & CMIF_MCD_CTRL_REVA_BIT_MASK) >> CMIF_MCD_CTRL_REVA_BIT_LSB)

#define CMIF_MCD_CTRL_RESERVED2_BIT_LSB                               (2)
#define CMIF_MCD_CTRL_RESERVED2_BIT_WIDTH                             (1)
#define CMIF_MCD_CTRL_RESERVED2_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_CTRL_RESERVED2_BIT_WIDTH)-1) << CMIF_MCD_CTRL_RESERVED2_BIT_LSB) )
#define CMIF_MCD_CTRL_RESERVED2_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_CTRL_RESERVED2_BIT_LSB)
#define CMIF_MCD_CTRL_RESERVED2_FLD_RD()                              ((M_CMIF_MCD_CTRL_RD() & CMIF_MCD_CTRL_RESERVED2_BIT_MASK) >> CMIF_MCD_CTRL_RESERVED2_BIT_LSB)

#define CMIF_MCD_CTRL_RESERVED1_BIT_LSB                               (1)
#define CMIF_MCD_CTRL_RESERVED1_BIT_WIDTH                             (1)
#define CMIF_MCD_CTRL_RESERVED1_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_CTRL_RESERVED1_BIT_WIDTH)-1) << CMIF_MCD_CTRL_RESERVED1_BIT_LSB) )
#define CMIF_MCD_CTRL_RESERVED1_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_CTRL_RESERVED1_BIT_LSB)
#define CMIF_MCD_CTRL_RESERVED1_FLD_RD()                              ((M_CMIF_MCD_CTRL_RD() & CMIF_MCD_CTRL_RESERVED1_BIT_MASK) >> CMIF_MCD_CTRL_RESERVED1_BIT_LSB)

#define CMIF_MCD_CTRL_RESERVED0_BIT_LSB                               (0)
#define CMIF_MCD_CTRL_RESERVED0_BIT_WIDTH                             (1)
#define CMIF_MCD_CTRL_RESERVED0_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_CTRL_RESERVED0_BIT_WIDTH)-1) << CMIF_MCD_CTRL_RESERVED0_BIT_LSB) )
#define CMIF_MCD_CTRL_RESERVED0_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_CTRL_RESERVED0_BIT_LSB)
#define CMIF_MCD_CTRL_RESERVED0_FLD_RD()                              ((M_CMIF_MCD_CTRL_RD() & CMIF_MCD_CTRL_RESERVED0_BIT_MASK) >> CMIF_MCD_CTRL_RESERVED0_BIT_LSB)

#define CMIF_MCD_RAB_LEN_RABL5_BIT_LSB                                (10)
#define CMIF_MCD_RAB_LEN_RABL5_BIT_WIDTH                              (2)
#define CMIF_MCD_RAB_LEN_RABL5_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB_LEN_RABL5_BIT_WIDTH)-1) << CMIF_MCD_RAB_LEN_RABL5_BIT_LSB) )
#define CMIF_MCD_RAB_LEN_RABL5_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB_LEN_RABL5_BIT_LSB)
#define CMIF_MCD_RAB_LEN_RABL5_FLD_RD()                               ((M_CMIF_MCD_RAB_LEN_RD() & CMIF_MCD_RAB_LEN_RABL5_BIT_MASK) >> CMIF_MCD_RAB_LEN_RABL5_BIT_LSB)

#define CMIF_MCD_RAB_LEN_RABL4_BIT_LSB                                (8)
#define CMIF_MCD_RAB_LEN_RABL4_BIT_WIDTH                              (2)
#define CMIF_MCD_RAB_LEN_RABL4_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB_LEN_RABL4_BIT_WIDTH)-1) << CMIF_MCD_RAB_LEN_RABL4_BIT_LSB) )
#define CMIF_MCD_RAB_LEN_RABL4_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB_LEN_RABL4_BIT_LSB)
#define CMIF_MCD_RAB_LEN_RABL4_FLD_RD()                               ((M_CMIF_MCD_RAB_LEN_RD() & CMIF_MCD_RAB_LEN_RABL4_BIT_MASK) >> CMIF_MCD_RAB_LEN_RABL4_BIT_LSB)

#define CMIF_MCD_RAB_LEN_RABL3_BIT_LSB                                (6)
#define CMIF_MCD_RAB_LEN_RABL3_BIT_WIDTH                              (2)
#define CMIF_MCD_RAB_LEN_RABL3_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB_LEN_RABL3_BIT_WIDTH)-1) << CMIF_MCD_RAB_LEN_RABL3_BIT_LSB) )
#define CMIF_MCD_RAB_LEN_RABL3_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB_LEN_RABL3_BIT_LSB)
#define CMIF_MCD_RAB_LEN_RABL3_FLD_RD()                               ((M_CMIF_MCD_RAB_LEN_RD() & CMIF_MCD_RAB_LEN_RABL3_BIT_MASK) >> CMIF_MCD_RAB_LEN_RABL3_BIT_LSB)

#define CMIF_MCD_RAB_LEN_RABL2_BIT_LSB                                (4)
#define CMIF_MCD_RAB_LEN_RABL2_BIT_WIDTH                              (2)
#define CMIF_MCD_RAB_LEN_RABL2_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB_LEN_RABL2_BIT_WIDTH)-1) << CMIF_MCD_RAB_LEN_RABL2_BIT_LSB) )
#define CMIF_MCD_RAB_LEN_RABL2_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB_LEN_RABL2_BIT_LSB)
#define CMIF_MCD_RAB_LEN_RABL2_FLD_RD()                               ((M_CMIF_MCD_RAB_LEN_RD() & CMIF_MCD_RAB_LEN_RABL2_BIT_MASK) >> CMIF_MCD_RAB_LEN_RABL2_BIT_LSB)

#define CMIF_MCD_RAB_LEN_RABL1_BIT_LSB                                (2)
#define CMIF_MCD_RAB_LEN_RABL1_BIT_WIDTH                              (2)
#define CMIF_MCD_RAB_LEN_RABL1_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB_LEN_RABL1_BIT_WIDTH)-1) << CMIF_MCD_RAB_LEN_RABL1_BIT_LSB) )
#define CMIF_MCD_RAB_LEN_RABL1_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB_LEN_RABL1_BIT_LSB)
#define CMIF_MCD_RAB_LEN_RABL1_FLD_RD()                               ((M_CMIF_MCD_RAB_LEN_RD() & CMIF_MCD_RAB_LEN_RABL1_BIT_MASK) >> CMIF_MCD_RAB_LEN_RABL1_BIT_LSB)

#define CMIF_MCD_RAB_LEN_RABL0_BIT_LSB                                (0)
#define CMIF_MCD_RAB_LEN_RABL0_BIT_WIDTH                              (2)
#define CMIF_MCD_RAB_LEN_RABL0_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB_LEN_RABL0_BIT_WIDTH)-1) << CMIF_MCD_RAB_LEN_RABL0_BIT_LSB) )
#define CMIF_MCD_RAB_LEN_RABL0_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB_LEN_RABL0_BIT_LSB)
#define CMIF_MCD_RAB_LEN_RABL0_FLD_RD()                               ((M_CMIF_MCD_RAB_LEN_RD() & CMIF_MCD_RAB_LEN_RABL0_BIT_MASK) >> CMIF_MCD_RAB_LEN_RABL0_BIT_LSB)

#define CMIF_MCD_RABOFT_RAB_OFT5_BIT_LSB                              (15)
#define CMIF_MCD_RABOFT_RAB_OFT5_BIT_WIDTH                            (3)
#define CMIF_MCD_RABOFT_RAB_OFT5_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_RABOFT_RAB_OFT5_BIT_WIDTH)-1) << CMIF_MCD_RABOFT_RAB_OFT5_BIT_LSB) )
#define CMIF_MCD_RABOFT_RAB_OFT5_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_RABOFT_RAB_OFT5_BIT_LSB)
#define CMIF_MCD_RABOFT_RAB_OFT5_FLD_RD()                             ((M_CMIF_MCD_RABOFT_RD() & CMIF_MCD_RABOFT_RAB_OFT5_BIT_MASK) >> CMIF_MCD_RABOFT_RAB_OFT5_BIT_LSB)

#define CMIF_MCD_RABOFT_RAB_OFT4_BIT_LSB                              (12)
#define CMIF_MCD_RABOFT_RAB_OFT4_BIT_WIDTH                            (3)
#define CMIF_MCD_RABOFT_RAB_OFT4_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_RABOFT_RAB_OFT4_BIT_WIDTH)-1) << CMIF_MCD_RABOFT_RAB_OFT4_BIT_LSB) )
#define CMIF_MCD_RABOFT_RAB_OFT4_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_RABOFT_RAB_OFT4_BIT_LSB)
#define CMIF_MCD_RABOFT_RAB_OFT4_FLD_RD()                             ((M_CMIF_MCD_RABOFT_RD() & CMIF_MCD_RABOFT_RAB_OFT4_BIT_MASK) >> CMIF_MCD_RABOFT_RAB_OFT4_BIT_LSB)

#define CMIF_MCD_RABOFT_RAB_OFT3_BIT_LSB                              (9)
#define CMIF_MCD_RABOFT_RAB_OFT3_BIT_WIDTH                            (3)
#define CMIF_MCD_RABOFT_RAB_OFT3_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_RABOFT_RAB_OFT3_BIT_WIDTH)-1) << CMIF_MCD_RABOFT_RAB_OFT3_BIT_LSB) )
#define CMIF_MCD_RABOFT_RAB_OFT3_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_RABOFT_RAB_OFT3_BIT_LSB)
#define CMIF_MCD_RABOFT_RAB_OFT3_FLD_RD()                             ((M_CMIF_MCD_RABOFT_RD() & CMIF_MCD_RABOFT_RAB_OFT3_BIT_MASK) >> CMIF_MCD_RABOFT_RAB_OFT3_BIT_LSB)

#define CMIF_MCD_RABOFT_RAB_OFT2_BIT_LSB                              (6)
#define CMIF_MCD_RABOFT_RAB_OFT2_BIT_WIDTH                            (3)
#define CMIF_MCD_RABOFT_RAB_OFT2_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_RABOFT_RAB_OFT2_BIT_WIDTH)-1) << CMIF_MCD_RABOFT_RAB_OFT2_BIT_LSB) )
#define CMIF_MCD_RABOFT_RAB_OFT2_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_RABOFT_RAB_OFT2_BIT_LSB)
#define CMIF_MCD_RABOFT_RAB_OFT2_FLD_RD()                             ((M_CMIF_MCD_RABOFT_RD() & CMIF_MCD_RABOFT_RAB_OFT2_BIT_MASK) >> CMIF_MCD_RABOFT_RAB_OFT2_BIT_LSB)

#define CMIF_MCD_RABOFT_RAB_OFT1_BIT_LSB                              (3)
#define CMIF_MCD_RABOFT_RAB_OFT1_BIT_WIDTH                            (3)
#define CMIF_MCD_RABOFT_RAB_OFT1_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_RABOFT_RAB_OFT1_BIT_WIDTH)-1) << CMIF_MCD_RABOFT_RAB_OFT1_BIT_LSB) )
#define CMIF_MCD_RABOFT_RAB_OFT1_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_RABOFT_RAB_OFT1_BIT_LSB)
#define CMIF_MCD_RABOFT_RAB_OFT1_FLD_RD()                             ((M_CMIF_MCD_RABOFT_RD() & CMIF_MCD_RABOFT_RAB_OFT1_BIT_MASK) >> CMIF_MCD_RABOFT_RAB_OFT1_BIT_LSB)

#define CMIF_MCD_RABOFT_RAB_OFT0_BIT_LSB                              (0)
#define CMIF_MCD_RABOFT_RAB_OFT0_BIT_WIDTH                            (3)
#define CMIF_MCD_RABOFT_RAB_OFT0_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_RABOFT_RAB_OFT0_BIT_WIDTH)-1) << CMIF_MCD_RABOFT_RAB_OFT0_BIT_LSB) )
#define CMIF_MCD_RABOFT_RAB_OFT0_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_RABOFT_RAB_OFT0_BIT_LSB)
#define CMIF_MCD_RABOFT_RAB_OFT0_FLD_RD()                             ((M_CMIF_MCD_RABOFT_RD() & CMIF_MCD_RABOFT_RAB_OFT0_BIT_MASK) >> CMIF_MCD_RABOFT_RAB_OFT0_BIT_LSB)

#define CMIF_MCD_RAC_GAIN_RAGC5_BIT_LSB                               (10)
#define CMIF_MCD_RAC_GAIN_RAGC5_BIT_WIDTH                             (2)
#define CMIF_MCD_RAC_GAIN_RAGC5_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAC_GAIN_RAGC5_BIT_WIDTH)-1) << CMIF_MCD_RAC_GAIN_RAGC5_BIT_LSB) )
#define CMIF_MCD_RAC_GAIN_RAGC5_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAC_GAIN_RAGC5_BIT_LSB)
#define CMIF_MCD_RAC_GAIN_RAGC5_FLD_RD()                              ((M_CMIF_MCD_RAC_GAIN_RD() & CMIF_MCD_RAC_GAIN_RAGC5_BIT_MASK) >> CMIF_MCD_RAC_GAIN_RAGC5_BIT_LSB)

#define CMIF_MCD_RAC_GAIN_RAGC4_BIT_LSB                               (8)
#define CMIF_MCD_RAC_GAIN_RAGC4_BIT_WIDTH                             (2)
#define CMIF_MCD_RAC_GAIN_RAGC4_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAC_GAIN_RAGC4_BIT_WIDTH)-1) << CMIF_MCD_RAC_GAIN_RAGC4_BIT_LSB) )
#define CMIF_MCD_RAC_GAIN_RAGC4_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAC_GAIN_RAGC4_BIT_LSB)
#define CMIF_MCD_RAC_GAIN_RAGC4_FLD_RD()                              ((M_CMIF_MCD_RAC_GAIN_RD() & CMIF_MCD_RAC_GAIN_RAGC4_BIT_MASK) >> CMIF_MCD_RAC_GAIN_RAGC4_BIT_LSB)

#define CMIF_MCD_RAC_GAIN_RAGC3_BIT_LSB                               (6)
#define CMIF_MCD_RAC_GAIN_RAGC3_BIT_WIDTH                             (2)
#define CMIF_MCD_RAC_GAIN_RAGC3_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAC_GAIN_RAGC3_BIT_WIDTH)-1) << CMIF_MCD_RAC_GAIN_RAGC3_BIT_LSB) )
#define CMIF_MCD_RAC_GAIN_RAGC3_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAC_GAIN_RAGC3_BIT_LSB)
#define CMIF_MCD_RAC_GAIN_RAGC3_FLD_RD()                              ((M_CMIF_MCD_RAC_GAIN_RD() & CMIF_MCD_RAC_GAIN_RAGC3_BIT_MASK) >> CMIF_MCD_RAC_GAIN_RAGC3_BIT_LSB)

#define CMIF_MCD_RAC_GAIN_RAGC2_BIT_LSB                               (4)
#define CMIF_MCD_RAC_GAIN_RAGC2_BIT_WIDTH                             (2)
#define CMIF_MCD_RAC_GAIN_RAGC2_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAC_GAIN_RAGC2_BIT_WIDTH)-1) << CMIF_MCD_RAC_GAIN_RAGC2_BIT_LSB) )
#define CMIF_MCD_RAC_GAIN_RAGC2_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAC_GAIN_RAGC2_BIT_LSB)
#define CMIF_MCD_RAC_GAIN_RAGC2_FLD_RD()                              ((M_CMIF_MCD_RAC_GAIN_RD() & CMIF_MCD_RAC_GAIN_RAGC2_BIT_MASK) >> CMIF_MCD_RAC_GAIN_RAGC2_BIT_LSB)

#define CMIF_MCD_RAC_GAIN_RAGC1_BIT_LSB                               (2)
#define CMIF_MCD_RAC_GAIN_RAGC1_BIT_WIDTH                             (2)
#define CMIF_MCD_RAC_GAIN_RAGC1_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAC_GAIN_RAGC1_BIT_WIDTH)-1) << CMIF_MCD_RAC_GAIN_RAGC1_BIT_LSB) )
#define CMIF_MCD_RAC_GAIN_RAGC1_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAC_GAIN_RAGC1_BIT_LSB)
#define CMIF_MCD_RAC_GAIN_RAGC1_FLD_RD()                              ((M_CMIF_MCD_RAC_GAIN_RD() & CMIF_MCD_RAC_GAIN_RAGC1_BIT_MASK) >> CMIF_MCD_RAC_GAIN_RAGC1_BIT_LSB)

#define CMIF_MCD_RAC_GAIN_RAGC0_BIT_LSB                               (0)
#define CMIF_MCD_RAC_GAIN_RAGC0_BIT_WIDTH                             (2)
#define CMIF_MCD_RAC_GAIN_RAGC0_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAC_GAIN_RAGC0_BIT_WIDTH)-1) << CMIF_MCD_RAC_GAIN_RAGC0_BIT_LSB) )
#define CMIF_MCD_RAC_GAIN_RAGC0_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAC_GAIN_RAGC0_BIT_LSB)
#define CMIF_MCD_RAC_GAIN_RAGC0_FLD_RD()                              ((M_CMIF_MCD_RAC_GAIN_RD() & CMIF_MCD_RAC_GAIN_RAGC0_BIT_MASK) >> CMIF_MCD_RAC_GAIN_RAGC0_BIT_LSB)

#define CMIF_MCD_PCG_PCG5_BIT_LSB                                     (15)
#define CMIF_MCD_PCG_PCG5_BIT_WIDTH                                   (3)
#define CMIF_MCD_PCG_PCG5_BIT_MASK                                    ((UINT32) (((1<<CMIF_MCD_PCG_PCG5_BIT_WIDTH)-1) << CMIF_MCD_PCG_PCG5_BIT_LSB) )
#define CMIF_MCD_PCG_PCG5_FLD_WR(reg, val)                            (reg |= (val) << CMIF_MCD_PCG_PCG5_BIT_LSB)
#define CMIF_MCD_PCG_PCG5_FLD_RD()                                    ((M_CMIF_MCD_PCG_RD() & CMIF_MCD_PCG_PCG5_BIT_MASK) >> CMIF_MCD_PCG_PCG5_BIT_LSB)

#define CMIF_MCD_PCG_PCG4_BIT_LSB                                     (12)
#define CMIF_MCD_PCG_PCG4_BIT_WIDTH                                   (3)
#define CMIF_MCD_PCG_PCG4_BIT_MASK                                    ((UINT32) (((1<<CMIF_MCD_PCG_PCG4_BIT_WIDTH)-1) << CMIF_MCD_PCG_PCG4_BIT_LSB) )
#define CMIF_MCD_PCG_PCG4_FLD_WR(reg, val)                            (reg |= (val) << CMIF_MCD_PCG_PCG4_BIT_LSB)
#define CMIF_MCD_PCG_PCG4_FLD_RD()                                    ((M_CMIF_MCD_PCG_RD() & CMIF_MCD_PCG_PCG4_BIT_MASK) >> CMIF_MCD_PCG_PCG4_BIT_LSB)

#define CMIF_MCD_PCG_PCG3_BIT_LSB                                     (9)
#define CMIF_MCD_PCG_PCG3_BIT_WIDTH                                   (3)
#define CMIF_MCD_PCG_PCG3_BIT_MASK                                    ((UINT32) (((1<<CMIF_MCD_PCG_PCG3_BIT_WIDTH)-1) << CMIF_MCD_PCG_PCG3_BIT_LSB) )
#define CMIF_MCD_PCG_PCG3_FLD_WR(reg, val)                            (reg |= (val) << CMIF_MCD_PCG_PCG3_BIT_LSB)
#define CMIF_MCD_PCG_PCG3_FLD_RD()                                    ((M_CMIF_MCD_PCG_RD() & CMIF_MCD_PCG_PCG3_BIT_MASK) >> CMIF_MCD_PCG_PCG3_BIT_LSB)

#define CMIF_MCD_PCG_PCG2_BIT_LSB                                     (6)
#define CMIF_MCD_PCG_PCG2_BIT_WIDTH                                   (3)
#define CMIF_MCD_PCG_PCG2_BIT_MASK                                    ((UINT32) (((1<<CMIF_MCD_PCG_PCG2_BIT_WIDTH)-1) << CMIF_MCD_PCG_PCG2_BIT_LSB) )
#define CMIF_MCD_PCG_PCG2_FLD_WR(reg, val)                            (reg |= (val) << CMIF_MCD_PCG_PCG2_BIT_LSB)
#define CMIF_MCD_PCG_PCG2_FLD_RD()                                    ((M_CMIF_MCD_PCG_RD() & CMIF_MCD_PCG_PCG2_BIT_MASK) >> CMIF_MCD_PCG_PCG2_BIT_LSB)

#define CMIF_MCD_PCG_PCG1_BIT_LSB                                     (3)
#define CMIF_MCD_PCG_PCG1_BIT_WIDTH                                   (3)
#define CMIF_MCD_PCG_PCG1_BIT_MASK                                    ((UINT32) (((1<<CMIF_MCD_PCG_PCG1_BIT_WIDTH)-1) << CMIF_MCD_PCG_PCG1_BIT_LSB) )
#define CMIF_MCD_PCG_PCG1_FLD_WR(reg, val)                            (reg |= (val) << CMIF_MCD_PCG_PCG1_BIT_LSB)
#define CMIF_MCD_PCG_PCG1_FLD_RD()                                    ((M_CMIF_MCD_PCG_RD() & CMIF_MCD_PCG_PCG1_BIT_MASK) >> CMIF_MCD_PCG_PCG1_BIT_LSB)

#define CMIF_MCD_PCG_PCG0_BIT_LSB                                     (0)
#define CMIF_MCD_PCG_PCG0_BIT_WIDTH                                   (3)
#define CMIF_MCD_PCG_PCG0_BIT_MASK                                    ((UINT32) (((1<<CMIF_MCD_PCG_PCG0_BIT_WIDTH)-1) << CMIF_MCD_PCG_PCG0_BIT_LSB) )
#define CMIF_MCD_PCG_PCG0_FLD_WR(reg, val)                            (reg |= (val) << CMIF_MCD_PCG_PCG0_BIT_LSB)
#define CMIF_MCD_PCG_PCG0_FLD_RD()                                    ((M_CMIF_MCD_PCG_RD() & CMIF_MCD_PCG_PCG0_BIT_MASK) >> CMIF_MCD_PCG_PCG0_BIT_LSB)

#define CMIF_MCD_SERV_PCG5_IN_BIT_LSB                                 (5)
#define CMIF_MCD_SERV_PCG5_IN_BIT_WIDTH                               (1)
#define CMIF_MCD_SERV_PCG5_IN_BIT_MASK                                ((UINT32) (((1<<CMIF_MCD_SERV_PCG5_IN_BIT_WIDTH)-1) << CMIF_MCD_SERV_PCG5_IN_BIT_LSB) )
#define CMIF_MCD_SERV_PCG5_IN_FLD_WR(reg, val)                        (reg |= (val) << CMIF_MCD_SERV_PCG5_IN_BIT_LSB)
#define CMIF_MCD_SERV_PCG5_IN_FLD_RD()                                ((M_CMIF_MCD_SERV_RD() & CMIF_MCD_SERV_PCG5_IN_BIT_MASK) >> CMIF_MCD_SERV_PCG5_IN_BIT_LSB)

#define CMIF_MCD_SERV_PCG4_IN_BIT_LSB                                 (4)
#define CMIF_MCD_SERV_PCG4_IN_BIT_WIDTH                               (1)
#define CMIF_MCD_SERV_PCG4_IN_BIT_MASK                                ((UINT32) (((1<<CMIF_MCD_SERV_PCG4_IN_BIT_WIDTH)-1) << CMIF_MCD_SERV_PCG4_IN_BIT_LSB) )
#define CMIF_MCD_SERV_PCG4_IN_FLD_WR(reg, val)                        (reg |= (val) << CMIF_MCD_SERV_PCG4_IN_BIT_LSB)
#define CMIF_MCD_SERV_PCG4_IN_FLD_RD()                                ((M_CMIF_MCD_SERV_RD() & CMIF_MCD_SERV_PCG4_IN_BIT_MASK) >> CMIF_MCD_SERV_PCG4_IN_BIT_LSB)

#define CMIF_MCD_SERV_PCG3_IN_BIT_LSB                                 (3)
#define CMIF_MCD_SERV_PCG3_IN_BIT_WIDTH                               (1)
#define CMIF_MCD_SERV_PCG3_IN_BIT_MASK                                ((UINT32) (((1<<CMIF_MCD_SERV_PCG3_IN_BIT_WIDTH)-1) << CMIF_MCD_SERV_PCG3_IN_BIT_LSB) )
#define CMIF_MCD_SERV_PCG3_IN_FLD_WR(reg, val)                        (reg |= (val) << CMIF_MCD_SERV_PCG3_IN_BIT_LSB)
#define CMIF_MCD_SERV_PCG3_IN_FLD_RD()                                ((M_CMIF_MCD_SERV_RD() & CMIF_MCD_SERV_PCG3_IN_BIT_MASK) >> CMIF_MCD_SERV_PCG3_IN_BIT_LSB)

#define CMIF_MCD_SERV_PCG2_IN_BIT_LSB                                 (2)
#define CMIF_MCD_SERV_PCG2_IN_BIT_WIDTH                               (1)
#define CMIF_MCD_SERV_PCG2_IN_BIT_MASK                                ((UINT32) (((1<<CMIF_MCD_SERV_PCG2_IN_BIT_WIDTH)-1) << CMIF_MCD_SERV_PCG2_IN_BIT_LSB) )
#define CMIF_MCD_SERV_PCG2_IN_FLD_WR(reg, val)                        (reg |= (val) << CMIF_MCD_SERV_PCG2_IN_BIT_LSB)
#define CMIF_MCD_SERV_PCG2_IN_FLD_RD()                                ((M_CMIF_MCD_SERV_RD() & CMIF_MCD_SERV_PCG2_IN_BIT_MASK) >> CMIF_MCD_SERV_PCG2_IN_BIT_LSB)

#define CMIF_MCD_SERV_PCG1_IN_BIT_LSB                                 (1)
#define CMIF_MCD_SERV_PCG1_IN_BIT_WIDTH                               (1)
#define CMIF_MCD_SERV_PCG1_IN_BIT_MASK                                ((UINT32) (((1<<CMIF_MCD_SERV_PCG1_IN_BIT_WIDTH)-1) << CMIF_MCD_SERV_PCG1_IN_BIT_LSB) )
#define CMIF_MCD_SERV_PCG1_IN_FLD_WR(reg, val)                        (reg |= (val) << CMIF_MCD_SERV_PCG1_IN_BIT_LSB)
#define CMIF_MCD_SERV_PCG1_IN_FLD_RD()                                ((M_CMIF_MCD_SERV_RD() & CMIF_MCD_SERV_PCG1_IN_BIT_MASK) >> CMIF_MCD_SERV_PCG1_IN_BIT_LSB)

#define CMIF_MCD_SERV_PCG0_IN_BIT_LSB                                 (0)
#define CMIF_MCD_SERV_PCG0_IN_BIT_WIDTH                               (1)
#define CMIF_MCD_SERV_PCG0_IN_BIT_MASK                                ((UINT32) (((1<<CMIF_MCD_SERV_PCG0_IN_BIT_WIDTH)-1) << CMIF_MCD_SERV_PCG0_IN_BIT_LSB) )
#define CMIF_MCD_SERV_PCG0_IN_FLD_WR(reg, val)                        (reg |= (val) << CMIF_MCD_SERV_PCG0_IN_BIT_LSB)
#define CMIF_MCD_SERV_PCG0_IN_FLD_RD()                                ((M_CMIF_MCD_SERV_RD() & CMIF_MCD_SERV_PCG0_IN_BIT_MASK) >> CMIF_MCD_SERV_PCG0_IN_BIT_LSB)

#define CMIF_MCD_DRCL_PERIOD_DRCLPER_BIT_LSB                          (0)
#define CMIF_MCD_DRCL_PERIOD_DRCLPER_BIT_WIDTH                        (1)
#define CMIF_MCD_DRCL_PERIOD_DRCLPER_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_DRCL_PERIOD_DRCLPER_BIT_WIDTH)-1) << CMIF_MCD_DRCL_PERIOD_DRCLPER_BIT_LSB) )
#define CMIF_MCD_DRCL_PERIOD_DRCLPER_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_DRCL_PERIOD_DRCLPER_BIT_LSB)
#define CMIF_MCD_DRCL_PERIOD_DRCLPER_FLD_RD()                         ((M_CMIF_MCD_DRCL_PERIOD_RD() & CMIF_MCD_DRCL_PERIOD_DRCLPER_BIT_MASK) >> CMIF_MCD_DRCL_PERIOD_DRCLPER_BIT_LSB)

#define CMIF_MCD_DRCL_LEN_DRCLEN_BIT_LSB                              (0)
#define CMIF_MCD_DRCL_LEN_DRCLEN_BIT_WIDTH                            (3)
#define CMIF_MCD_DRCL_LEN_DRCLEN_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_DRCL_LEN_DRCLEN_BIT_WIDTH)-1) << CMIF_MCD_DRCL_LEN_DRCLEN_BIT_LSB) )
#define CMIF_MCD_DRCL_LEN_DRCLEN_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_DRCL_LEN_DRCLEN_BIT_LSB)
#define CMIF_MCD_DRCL_LEN_DRCLEN_FLD_RD()                             ((M_CMIF_MCD_DRCL_LEN_RD() & CMIF_MCD_DRCL_LEN_DRCLEN_BIT_MASK) >> CMIF_MCD_DRCL_LEN_DRCLEN_BIT_LSB)

#define CMIF_MCD_ARQ_MODE_OOK_BIT_LSB                                 (0)
#define CMIF_MCD_ARQ_MODE_OOK_BIT_WIDTH                               (1)
#define CMIF_MCD_ARQ_MODE_OOK_BIT_MASK                                ((UINT32) (((1<<CMIF_MCD_ARQ_MODE_OOK_BIT_WIDTH)-1) << CMIF_MCD_ARQ_MODE_OOK_BIT_LSB) )
#define CMIF_MCD_ARQ_MODE_OOK_FLD_WR(reg, val)                        (reg |= (val) << CMIF_MCD_ARQ_MODE_OOK_BIT_LSB)
#define CMIF_MCD_ARQ_MODE_OOK_FLD_RD()                                ((M_CMIF_MCD_ARQ_MODE_RD() & CMIF_MCD_ARQ_MODE_OOK_BIT_MASK) >> CMIF_MCD_ARQ_MODE_OOK_BIT_LSB)

#define CMIF_MCD_ARQ_TYPE_TYPE_LHP_BIT_LSB                            (0)
#define CMIF_MCD_ARQ_TYPE_TYPE_LHP_BIT_WIDTH                          (2)
#define CMIF_MCD_ARQ_TYPE_TYPE_LHP_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_ARQ_TYPE_TYPE_LHP_BIT_WIDTH)-1) << CMIF_MCD_ARQ_TYPE_TYPE_LHP_BIT_LSB) )
#define CMIF_MCD_ARQ_TYPE_TYPE_LHP_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_ARQ_TYPE_TYPE_LHP_BIT_LSB)
#define CMIF_MCD_ARQ_TYPE_TYPE_LHP_FLD_RD()                           ((M_CMIF_MCD_ARQ_TYPE_RD() & CMIF_MCD_ARQ_TYPE_TYPE_LHP_BIT_MASK) >> CMIF_MCD_ARQ_TYPE_TYPE_LHP_BIT_LSB)

#define CMIF_MCD_TC_FRAB_TC_FRAB_BIT_LSB                              (0)
#define CMIF_MCD_TC_FRAB_TC_FRAB_BIT_WIDTH                            (2)
#define CMIF_MCD_TC_FRAB_TC_FRAB_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_TC_FRAB_TC_FRAB_BIT_WIDTH)-1) << CMIF_MCD_TC_FRAB_TC_FRAB_BIT_LSB) )
#define CMIF_MCD_TC_FRAB_TC_FRAB_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_TC_FRAB_TC_FRAB_BIT_LSB)
#define CMIF_MCD_TC_FRAB_TC_FRAB_FLD_RD()                             ((M_CMIF_MCD_TC_FRAB_RD() & CMIF_MCD_TC_FRAB_TC_FRAB_BIT_MASK) >> CMIF_MCD_TC_FRAB_TC_FRAB_BIT_LSB)

#define CMIF_MCD_TC_QRAB_TC_QRAB_BIT_LSB                              (0)
#define CMIF_MCD_TC_QRAB_TC_QRAB_BIT_WIDTH                            (1)
#define CMIF_MCD_TC_QRAB_TC_QRAB_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_TC_QRAB_TC_QRAB_BIT_WIDTH)-1) << CMIF_MCD_TC_QRAB_TC_QRAB_BIT_LSB) )
#define CMIF_MCD_TC_QRAB_TC_QRAB_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_TC_QRAB_TC_QRAB_BIT_LSB)
#define CMIF_MCD_TC_QRAB_TC_QRAB_FLD_RD()                             ((M_CMIF_MCD_TC_QRAB_RD() & CMIF_MCD_TC_QRAB_TC_QRAB_BIT_MASK) >> CMIF_MCD_TC_QRAB_TC_QRAB_BIT_LSB)

#define CMIF_MCD_RPC_RPC_ACK_BIT_LSB                                  (0)
#define CMIF_MCD_RPC_RPC_ACK_BIT_WIDTH                                (1)
#define CMIF_MCD_RPC_RPC_ACK_BIT_MASK                                 ((UINT32) (((1<<CMIF_MCD_RPC_RPC_ACK_BIT_WIDTH)-1) << CMIF_MCD_RPC_RPC_ACK_BIT_LSB) )
#define CMIF_MCD_RPC_RPC_ACK_FLD_WR(reg, val)                         (reg |= (val) << CMIF_MCD_RPC_RPC_ACK_BIT_LSB)
#define CMIF_MCD_RPC_RPC_ACK_FLD_RD()                                 ((M_CMIF_MCD_RPC_RD() & CMIF_MCD_RPC_RPC_ACK_BIT_MASK) >> CMIF_MCD_RPC_RPC_ACK_BIT_LSB)

#define CMIF_MCD_DONE_DONE_BIT_LSB                                    (0)
#define CMIF_MCD_DONE_DONE_BIT_WIDTH                                  (1)
#define CMIF_MCD_DONE_DONE_BIT_MASK                                   ((UINT32) (((1<<CMIF_MCD_DONE_DONE_BIT_WIDTH)-1) << CMIF_MCD_DONE_DONE_BIT_LSB) )
#define CMIF_MCD_DONE_DONE_FLD_WR(reg, val)                           (reg |= (val) << CMIF_MCD_DONE_DONE_BIT_LSB)
#define CMIF_MCD_DONE_DONE_FLD_RD()                                   ((M_CMIF_MCD_DONE_RD() & CMIF_MCD_DONE_DONE_BIT_MASK) >> CMIF_MCD_DONE_DONE_BIT_LSB)

#define CMIF_MCD_MAXFRAB_MAXFRABSE_BIT_LSB                            (11)
#define CMIF_MCD_MAXFRAB_MAXFRABSE_BIT_WIDTH                          (21)
#define CMIF_MCD_MAXFRAB_MAXFRABSE_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_MAXFRAB_MAXFRABSE_BIT_WIDTH)-1) << CMIF_MCD_MAXFRAB_MAXFRABSE_BIT_LSB) )
#define CMIF_MCD_MAXFRAB_MAXFRABSE_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_MAXFRAB_MAXFRABSE_BIT_LSB)
#define CMIF_MCD_MAXFRAB_MAXFRABSE_FLD_RD()                           ((M_CMIF_MCD_MAXFRAB_RD() & CMIF_MCD_MAXFRAB_MAXFRABSE_BIT_MASK) >> CMIF_MCD_MAXFRAB_MAXFRABSE_BIT_LSB)

#define CMIF_MCD_MAXFRAB_MAXFRAB_BIT_LSB                              (0)
#define CMIF_MCD_MAXFRAB_MAXFRAB_BIT_WIDTH                            (11)
#define CMIF_MCD_MAXFRAB_MAXFRAB_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_MAXFRAB_MAXFRAB_BIT_WIDTH)-1) << CMIF_MCD_MAXFRAB_MAXFRAB_BIT_LSB) )
#define CMIF_MCD_MAXFRAB_MAXFRAB_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_MAXFRAB_MAXFRAB_BIT_LSB)
#define CMIF_MCD_MAXFRAB_MAXFRAB_FLD_RD()                             ((M_CMIF_MCD_MAXFRAB_RD() & CMIF_MCD_MAXFRAB_MAXFRAB_BIT_MASK) >> CMIF_MCD_MAXFRAB_MAXFRAB_BIT_LSB)

#define CMIF_MCD_HLARQ_DET_DET_HLALL_BIT_LSB                          (6)
#define CMIF_MCD_HLARQ_DET_DET_HLALL_BIT_WIDTH                        (1)
#define CMIF_MCD_HLARQ_DET_DET_HLALL_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_HLARQ_DET_DET_HLALL_BIT_WIDTH)-1) << CMIF_MCD_HLARQ_DET_DET_HLALL_BIT_LSB) )
#define CMIF_MCD_HLARQ_DET_DET_HLALL_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_HLARQ_DET_DET_HLALL_BIT_LSB)
#define CMIF_MCD_HLARQ_DET_DET_HLALL_FLD_RD()                         ((M_CMIF_MCD_HLARQ_DET_RD() & CMIF_MCD_HLARQ_DET_DET_HLALL_BIT_MASK) >> CMIF_MCD_HLARQ_DET_DET_HLALL_BIT_LSB)

#define CMIF_MCD_HLARQ_DET_DET_HLARQ_BIT_LSB                          (0)
#define CMIF_MCD_HLARQ_DET_DET_HLARQ_BIT_WIDTH                        (6)
#define CMIF_MCD_HLARQ_DET_DET_HLARQ_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_HLARQ_DET_DET_HLARQ_BIT_WIDTH)-1) << CMIF_MCD_HLARQ_DET_DET_HLARQ_BIT_LSB) )
#define CMIF_MCD_HLARQ_DET_DET_HLARQ_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_HLARQ_DET_DET_HLARQ_BIT_LSB)
#define CMIF_MCD_HLARQ_DET_DET_HLARQ_FLD_RD()                         ((M_CMIF_MCD_HLARQ_DET_RD() & CMIF_MCD_HLARQ_DET_DET_HLARQ_BIT_MASK) >> CMIF_MCD_HLARQ_DET_DET_HLARQ_BIT_LSB)

#define CMIF_MCD_DRC_LOCK_DRCLOCK_BIT_LSB                             (0)
#define CMIF_MCD_DRC_LOCK_DRCLOCK_BIT_WIDTH                           (1)
#define CMIF_MCD_DRC_LOCK_DRCLOCK_BIT_MASK                            ((UINT32) (((1<<CMIF_MCD_DRC_LOCK_DRCLOCK_BIT_WIDTH)-1) << CMIF_MCD_DRC_LOCK_DRCLOCK_BIT_LSB) )
#define CMIF_MCD_DRC_LOCK_DRCLOCK_FLD_WR(reg, val)                    (reg |= (val) << CMIF_MCD_DRC_LOCK_DRCLOCK_BIT_LSB)
#define CMIF_MCD_DRC_LOCK_DRCLOCK_FLD_RD(i)                           ((M_CMIF_MCD_DRC_LOCK_RD(i) & CMIF_MCD_DRC_LOCK_DRCLOCK_BIT_MASK) >> CMIF_MCD_DRC_LOCK_DRCLOCK_BIT_LSB)

#define CMIF_MCD_SLOTQRAB_FRABSE_BIT_LSB                              (27)
#define CMIF_MCD_SLOTQRAB_FRABSE_BIT_WIDTH                            (5)
#define CMIF_MCD_SLOTQRAB_FRABSE_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_SLOTQRAB_FRABSE_BIT_WIDTH)-1) << CMIF_MCD_SLOTQRAB_FRABSE_BIT_LSB) )
#define CMIF_MCD_SLOTQRAB_FRABSE_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_SLOTQRAB_FRABSE_BIT_LSB)
#define CMIF_MCD_SLOTQRAB_FRABSE_FLD_RD(i)                            ((M_CMIF_MCD_SLOTQRAB_RD(i) & CMIF_MCD_SLOTQRAB_FRABSE_BIT_MASK) >> CMIF_MCD_SLOTQRAB_FRABSE_BIT_LSB)

#define CMIF_MCD_SLOTQRAB_FRAB_BIT_LSB                                (16)
#define CMIF_MCD_SLOTQRAB_FRAB_BIT_WIDTH                              (11)
#define CMIF_MCD_SLOTQRAB_FRAB_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_SLOTQRAB_FRAB_BIT_WIDTH)-1) << CMIF_MCD_SLOTQRAB_FRAB_BIT_LSB) )
#define CMIF_MCD_SLOTQRAB_FRAB_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_SLOTQRAB_FRAB_BIT_LSB)
#define CMIF_MCD_SLOTQRAB_FRAB_FLD_RD(i)                              ((M_CMIF_MCD_SLOTQRAB_RD(i) & CMIF_MCD_SLOTQRAB_FRAB_BIT_MASK) >> CMIF_MCD_SLOTQRAB_FRAB_BIT_LSB)

#define CMIF_MCD_SLOTQRAB_SLOTQRAB_BIT_LSB                            (0)
#define CMIF_MCD_SLOTQRAB_SLOTQRAB_BIT_WIDTH                          (1)
#define CMIF_MCD_SLOTQRAB_SLOTQRAB_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_SLOTQRAB_SLOTQRAB_BIT_WIDTH)-1) << CMIF_MCD_SLOTQRAB_SLOTQRAB_BIT_LSB) )
#define CMIF_MCD_SLOTQRAB_SLOTQRAB_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_SLOTQRAB_SLOTQRAB_BIT_LSB)
#define CMIF_MCD_SLOTQRAB_SLOTQRAB_FLD_RD(i)                          ((M_CMIF_MCD_SLOTQRAB_RD(i) & CMIF_MCD_SLOTQRAB_SLOTQRAB_BIT_MASK) >> CMIF_MCD_SLOTQRAB_SLOTQRAB_BIT_LSB)

#define CMIF_MCD_RAB0_RAB0_ST2_BIT_LSB                                (16)
#define CMIF_MCD_RAB0_RAB0_ST2_BIT_WIDTH                              (16)
#define CMIF_MCD_RAB0_RAB0_ST2_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB0_RAB0_ST2_BIT_WIDTH)-1) << CMIF_MCD_RAB0_RAB0_ST2_BIT_LSB) )
#define CMIF_MCD_RAB0_RAB0_ST2_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB0_RAB0_ST2_BIT_LSB)
#define CMIF_MCD_RAB0_RAB0_ST2_FLD_RD()                               ((M_CMIF_MCD_RAB0_RD() & CMIF_MCD_RAB0_RAB0_ST2_BIT_MASK) >> CMIF_MCD_RAB0_RAB0_ST2_BIT_LSB)

#define CMIF_MCD_RAB0_RAB0_ST01_BIT_LSB                               (0)
#define CMIF_MCD_RAB0_RAB0_ST01_BIT_WIDTH                             (16)
#define CMIF_MCD_RAB0_RAB0_ST01_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAB0_RAB0_ST01_BIT_WIDTH)-1) << CMIF_MCD_RAB0_RAB0_ST01_BIT_LSB) )
#define CMIF_MCD_RAB0_RAB0_ST01_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAB0_RAB0_ST01_BIT_LSB)
#define CMIF_MCD_RAB0_RAB0_ST01_FLD_RD()                              ((M_CMIF_MCD_RAB0_RD() & CMIF_MCD_RAB0_RAB0_ST01_BIT_MASK) >> CMIF_MCD_RAB0_RAB0_ST01_BIT_LSB)

#define CMIF_MCD_HARQMET0_HARQMETSE0_BIT_LSB                          (22)
#define CMIF_MCD_HARQMET0_HARQMETSE0_BIT_WIDTH                        (10)
#define CMIF_MCD_HARQMET0_HARQMETSE0_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_HARQMET0_HARQMETSE0_BIT_WIDTH)-1) << CMIF_MCD_HARQMET0_HARQMETSE0_BIT_LSB) )
#define CMIF_MCD_HARQMET0_HARQMETSE0_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_HARQMET0_HARQMETSE0_BIT_LSB)
#define CMIF_MCD_HARQMET0_HARQMETSE0_FLD_RD()                         ((M_CMIF_MCD_HARQMET0_RD() & CMIF_MCD_HARQMET0_HARQMETSE0_BIT_MASK) >> CMIF_MCD_HARQMET0_HARQMETSE0_BIT_LSB)

#define CMIF_MCD_HARQMET0_HARQMET0_BIT_LSB                            (0)
#define CMIF_MCD_HARQMET0_HARQMET0_BIT_WIDTH                          (22)
#define CMIF_MCD_HARQMET0_HARQMET0_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_HARQMET0_HARQMET0_BIT_WIDTH)-1) << CMIF_MCD_HARQMET0_HARQMET0_BIT_LSB) )
#define CMIF_MCD_HARQMET0_HARQMET0_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_HARQMET0_HARQMET0_BIT_LSB)
#define CMIF_MCD_HARQMET0_HARQMET0_FLD_RD()                           ((M_CMIF_MCD_HARQMET0_RD() & CMIF_MCD_HARQMET0_HARQMET0_BIT_MASK) >> CMIF_MCD_HARQMET0_HARQMET0_BIT_LSB)

#define CMIF_MCD_PARQMET0_PARQMETSE0_BIT_LSB                          (22)
#define CMIF_MCD_PARQMET0_PARQMETSE0_BIT_WIDTH                        (10)
#define CMIF_MCD_PARQMET0_PARQMETSE0_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_PARQMET0_PARQMETSE0_BIT_WIDTH)-1) << CMIF_MCD_PARQMET0_PARQMETSE0_BIT_LSB) )
#define CMIF_MCD_PARQMET0_PARQMETSE0_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_PARQMET0_PARQMETSE0_BIT_LSB)
#define CMIF_MCD_PARQMET0_PARQMETSE0_FLD_RD()                         ((M_CMIF_MCD_PARQMET0_RD() & CMIF_MCD_PARQMET0_PARQMETSE0_BIT_MASK) >> CMIF_MCD_PARQMET0_PARQMETSE0_BIT_LSB)

#define CMIF_MCD_PARQMET0_PARQMET0_BIT_LSB                            (0)
#define CMIF_MCD_PARQMET0_PARQMET0_BIT_WIDTH                          (22)
#define CMIF_MCD_PARQMET0_PARQMET0_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_PARQMET0_PARQMET0_BIT_WIDTH)-1) << CMIF_MCD_PARQMET0_PARQMET0_BIT_LSB) )
#define CMIF_MCD_PARQMET0_PARQMET0_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_PARQMET0_PARQMET0_BIT_LSB)
#define CMIF_MCD_PARQMET0_PARQMET0_FLD_RD()                           ((M_CMIF_MCD_PARQMET0_RD() & CMIF_MCD_PARQMET0_PARQMET0_BIT_MASK) >> CMIF_MCD_PARQMET0_PARQMET0_BIT_LSB)

#define CMIF_MCD_CIMET0_CIMETSE0_BIT_LSB                              (22)
#define CMIF_MCD_CIMET0_CIMETSE0_BIT_WIDTH                            (10)
#define CMIF_MCD_CIMET0_CIMETSE0_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_CIMET0_CIMETSE0_BIT_WIDTH)-1) << CMIF_MCD_CIMET0_CIMETSE0_BIT_LSB) )
#define CMIF_MCD_CIMET0_CIMETSE0_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_CIMET0_CIMETSE0_BIT_LSB)
#define CMIF_MCD_CIMET0_CIMETSE0_FLD_RD()                             ((M_CMIF_MCD_CIMET0_RD() & CMIF_MCD_CIMET0_CIMETSE0_BIT_MASK) >> CMIF_MCD_CIMET0_CIMETSE0_BIT_LSB)

#define CMIF_MCD_CIMET0_CIMET0_BIT_LSB                                (0)
#define CMIF_MCD_CIMET0_CIMET0_BIT_WIDTH                              (22)
#define CMIF_MCD_CIMET0_CIMET0_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_CIMET0_CIMET0_BIT_WIDTH)-1) << CMIF_MCD_CIMET0_CIMET0_BIT_LSB) )
#define CMIF_MCD_CIMET0_CIMET0_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_CIMET0_CIMET0_BIT_LSB)
#define CMIF_MCD_CIMET0_CIMET0_FLD_RD()                               ((M_CMIF_MCD_CIMET0_RD() & CMIF_MCD_CIMET0_CIMET0_BIT_MASK) >> CMIF_MCD_CIMET0_CIMET0_BIT_LSB)

#define CMIF_MCD_RAB1_RAB1_ST2_BIT_LSB                                (16)
#define CMIF_MCD_RAB1_RAB1_ST2_BIT_WIDTH                              (16)
#define CMIF_MCD_RAB1_RAB1_ST2_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB1_RAB1_ST2_BIT_WIDTH)-1) << CMIF_MCD_RAB1_RAB1_ST2_BIT_LSB) )
#define CMIF_MCD_RAB1_RAB1_ST2_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB1_RAB1_ST2_BIT_LSB)
#define CMIF_MCD_RAB1_RAB1_ST2_FLD_RD()                               ((M_CMIF_MCD_RAB1_RD() & CMIF_MCD_RAB1_RAB1_ST2_BIT_MASK) >> CMIF_MCD_RAB1_RAB1_ST2_BIT_LSB)

#define CMIF_MCD_RAB1_RAB1_ST01_BIT_LSB                               (0)
#define CMIF_MCD_RAB1_RAB1_ST01_BIT_WIDTH                             (16)
#define CMIF_MCD_RAB1_RAB1_ST01_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAB1_RAB1_ST01_BIT_WIDTH)-1) << CMIF_MCD_RAB1_RAB1_ST01_BIT_LSB) )
#define CMIF_MCD_RAB1_RAB1_ST01_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAB1_RAB1_ST01_BIT_LSB)
#define CMIF_MCD_RAB1_RAB1_ST01_FLD_RD()                              ((M_CMIF_MCD_RAB1_RD() & CMIF_MCD_RAB1_RAB1_ST01_BIT_MASK) >> CMIF_MCD_RAB1_RAB1_ST01_BIT_LSB)

#define CMIF_MCD_HARQMET1_HARQMETSE1_BIT_LSB                          (22)
#define CMIF_MCD_HARQMET1_HARQMETSE1_BIT_WIDTH                        (10)
#define CMIF_MCD_HARQMET1_HARQMETSE1_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_HARQMET1_HARQMETSE1_BIT_WIDTH)-1) << CMIF_MCD_HARQMET1_HARQMETSE1_BIT_LSB) )
#define CMIF_MCD_HARQMET1_HARQMETSE1_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_HARQMET1_HARQMETSE1_BIT_LSB)
#define CMIF_MCD_HARQMET1_HARQMETSE1_FLD_RD()                         ((M_CMIF_MCD_HARQMET1_RD() & CMIF_MCD_HARQMET1_HARQMETSE1_BIT_MASK) >> CMIF_MCD_HARQMET1_HARQMETSE1_BIT_LSB)

#define CMIF_MCD_HARQMET1_HARQMET1_BIT_LSB                            (0)
#define CMIF_MCD_HARQMET1_HARQMET1_BIT_WIDTH                          (22)
#define CMIF_MCD_HARQMET1_HARQMET1_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_HARQMET1_HARQMET1_BIT_WIDTH)-1) << CMIF_MCD_HARQMET1_HARQMET1_BIT_LSB) )
#define CMIF_MCD_HARQMET1_HARQMET1_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_HARQMET1_HARQMET1_BIT_LSB)
#define CMIF_MCD_HARQMET1_HARQMET1_FLD_RD()                           ((M_CMIF_MCD_HARQMET1_RD() & CMIF_MCD_HARQMET1_HARQMET1_BIT_MASK) >> CMIF_MCD_HARQMET1_HARQMET1_BIT_LSB)

#define CMIF_MCD_PARQMET1_PARQMETSE1_BIT_LSB                          (22)
#define CMIF_MCD_PARQMET1_PARQMETSE1_BIT_WIDTH                        (10)
#define CMIF_MCD_PARQMET1_PARQMETSE1_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_PARQMET1_PARQMETSE1_BIT_WIDTH)-1) << CMIF_MCD_PARQMET1_PARQMETSE1_BIT_LSB) )
#define CMIF_MCD_PARQMET1_PARQMETSE1_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_PARQMET1_PARQMETSE1_BIT_LSB)
#define CMIF_MCD_PARQMET1_PARQMETSE1_FLD_RD()                         ((M_CMIF_MCD_PARQMET1_RD() & CMIF_MCD_PARQMET1_PARQMETSE1_BIT_MASK) >> CMIF_MCD_PARQMET1_PARQMETSE1_BIT_LSB)

#define CMIF_MCD_PARQMET1_PARQMET1_BIT_LSB                            (0)
#define CMIF_MCD_PARQMET1_PARQMET1_BIT_WIDTH                          (22)
#define CMIF_MCD_PARQMET1_PARQMET1_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_PARQMET1_PARQMET1_BIT_WIDTH)-1) << CMIF_MCD_PARQMET1_PARQMET1_BIT_LSB) )
#define CMIF_MCD_PARQMET1_PARQMET1_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_PARQMET1_PARQMET1_BIT_LSB)
#define CMIF_MCD_PARQMET1_PARQMET1_FLD_RD()                           ((M_CMIF_MCD_PARQMET1_RD() & CMIF_MCD_PARQMET1_PARQMET1_BIT_MASK) >> CMIF_MCD_PARQMET1_PARQMET1_BIT_LSB)

#define CMIF_MCD_CIMET1_CIMETSE1_BIT_LSB                              (22)
#define CMIF_MCD_CIMET1_CIMETSE1_BIT_WIDTH                            (10)
#define CMIF_MCD_CIMET1_CIMETSE1_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_CIMET1_CIMETSE1_BIT_WIDTH)-1) << CMIF_MCD_CIMET1_CIMETSE1_BIT_LSB) )
#define CMIF_MCD_CIMET1_CIMETSE1_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_CIMET1_CIMETSE1_BIT_LSB)
#define CMIF_MCD_CIMET1_CIMETSE1_FLD_RD()                             ((M_CMIF_MCD_CIMET1_RD() & CMIF_MCD_CIMET1_CIMETSE1_BIT_MASK) >> CMIF_MCD_CIMET1_CIMETSE1_BIT_LSB)

#define CMIF_MCD_CIMET1_CIMET1_BIT_LSB                                (0)
#define CMIF_MCD_CIMET1_CIMET1_BIT_WIDTH                              (22)
#define CMIF_MCD_CIMET1_CIMET1_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_CIMET1_CIMET1_BIT_WIDTH)-1) << CMIF_MCD_CIMET1_CIMET1_BIT_LSB) )
#define CMIF_MCD_CIMET1_CIMET1_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_CIMET1_CIMET1_BIT_LSB)
#define CMIF_MCD_CIMET1_CIMET1_FLD_RD()                               ((M_CMIF_MCD_CIMET1_RD() & CMIF_MCD_CIMET1_CIMET1_BIT_MASK) >> CMIF_MCD_CIMET1_CIMET1_BIT_LSB)

#define CMIF_MCD_RAB2_RAB2_ST2_BIT_LSB                                (16)
#define CMIF_MCD_RAB2_RAB2_ST2_BIT_WIDTH                              (16)
#define CMIF_MCD_RAB2_RAB2_ST2_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB2_RAB2_ST2_BIT_WIDTH)-1) << CMIF_MCD_RAB2_RAB2_ST2_BIT_LSB) )
#define CMIF_MCD_RAB2_RAB2_ST2_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB2_RAB2_ST2_BIT_LSB)
#define CMIF_MCD_RAB2_RAB2_ST2_FLD_RD()                               ((M_CMIF_MCD_RAB2_RD() & CMIF_MCD_RAB2_RAB2_ST2_BIT_MASK) >> CMIF_MCD_RAB2_RAB2_ST2_BIT_LSB)

#define CMIF_MCD_RAB2_RAB2_ST01_BIT_LSB                               (0)
#define CMIF_MCD_RAB2_RAB2_ST01_BIT_WIDTH                             (16)
#define CMIF_MCD_RAB2_RAB2_ST01_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAB2_RAB2_ST01_BIT_WIDTH)-1) << CMIF_MCD_RAB2_RAB2_ST01_BIT_LSB) )
#define CMIF_MCD_RAB2_RAB2_ST01_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAB2_RAB2_ST01_BIT_LSB)
#define CMIF_MCD_RAB2_RAB2_ST01_FLD_RD()                              ((M_CMIF_MCD_RAB2_RD() & CMIF_MCD_RAB2_RAB2_ST01_BIT_MASK) >> CMIF_MCD_RAB2_RAB2_ST01_BIT_LSB)

#define CMIF_MCD_HARQMET2_HARQMETSE2_BIT_LSB                          (22)
#define CMIF_MCD_HARQMET2_HARQMETSE2_BIT_WIDTH                        (10)
#define CMIF_MCD_HARQMET2_HARQMETSE2_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_HARQMET2_HARQMETSE2_BIT_WIDTH)-1) << CMIF_MCD_HARQMET2_HARQMETSE2_BIT_LSB) )
#define CMIF_MCD_HARQMET2_HARQMETSE2_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_HARQMET2_HARQMETSE2_BIT_LSB)
#define CMIF_MCD_HARQMET2_HARQMETSE2_FLD_RD()                         ((M_CMIF_MCD_HARQMET2_RD() & CMIF_MCD_HARQMET2_HARQMETSE2_BIT_MASK) >> CMIF_MCD_HARQMET2_HARQMETSE2_BIT_LSB)

#define CMIF_MCD_HARQMET2_HARQMET2_BIT_LSB                            (0)
#define CMIF_MCD_HARQMET2_HARQMET2_BIT_WIDTH                          (22)
#define CMIF_MCD_HARQMET2_HARQMET2_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_HARQMET2_HARQMET2_BIT_WIDTH)-1) << CMIF_MCD_HARQMET2_HARQMET2_BIT_LSB) )
#define CMIF_MCD_HARQMET2_HARQMET2_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_HARQMET2_HARQMET2_BIT_LSB)
#define CMIF_MCD_HARQMET2_HARQMET2_FLD_RD()                           ((M_CMIF_MCD_HARQMET2_RD() & CMIF_MCD_HARQMET2_HARQMET2_BIT_MASK) >> CMIF_MCD_HARQMET2_HARQMET2_BIT_LSB)

#define CMIF_MCD_PARQMET2_PARQMETSE2_BIT_LSB                          (22)
#define CMIF_MCD_PARQMET2_PARQMETSE2_BIT_WIDTH                        (10)
#define CMIF_MCD_PARQMET2_PARQMETSE2_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_PARQMET2_PARQMETSE2_BIT_WIDTH)-1) << CMIF_MCD_PARQMET2_PARQMETSE2_BIT_LSB) )
#define CMIF_MCD_PARQMET2_PARQMETSE2_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_PARQMET2_PARQMETSE2_BIT_LSB)
#define CMIF_MCD_PARQMET2_PARQMETSE2_FLD_RD()                         ((M_CMIF_MCD_PARQMET2_RD() & CMIF_MCD_PARQMET2_PARQMETSE2_BIT_MASK) >> CMIF_MCD_PARQMET2_PARQMETSE2_BIT_LSB)

#define CMIF_MCD_PARQMET2_PARQMET2_BIT_LSB                            (0)
#define CMIF_MCD_PARQMET2_PARQMET2_BIT_WIDTH                          (22)
#define CMIF_MCD_PARQMET2_PARQMET2_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_PARQMET2_PARQMET2_BIT_WIDTH)-1) << CMIF_MCD_PARQMET2_PARQMET2_BIT_LSB) )
#define CMIF_MCD_PARQMET2_PARQMET2_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_PARQMET2_PARQMET2_BIT_LSB)
#define CMIF_MCD_PARQMET2_PARQMET2_FLD_RD()                           ((M_CMIF_MCD_PARQMET2_RD() & CMIF_MCD_PARQMET2_PARQMET2_BIT_MASK) >> CMIF_MCD_PARQMET2_PARQMET2_BIT_LSB)

#define CMIF_MCD_CIMET2_CIMETSE2_BIT_LSB                              (22)
#define CMIF_MCD_CIMET2_CIMETSE2_BIT_WIDTH                            (10)
#define CMIF_MCD_CIMET2_CIMETSE2_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_CIMET2_CIMETSE2_BIT_WIDTH)-1) << CMIF_MCD_CIMET2_CIMETSE2_BIT_LSB) )
#define CMIF_MCD_CIMET2_CIMETSE2_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_CIMET2_CIMETSE2_BIT_LSB)
#define CMIF_MCD_CIMET2_CIMETSE2_FLD_RD()                             ((M_CMIF_MCD_CIMET2_RD() & CMIF_MCD_CIMET2_CIMETSE2_BIT_MASK) >> CMIF_MCD_CIMET2_CIMETSE2_BIT_LSB)

#define CMIF_MCD_CIMET2_CIMET2_BIT_LSB                                (0)
#define CMIF_MCD_CIMET2_CIMET2_BIT_WIDTH                              (22)
#define CMIF_MCD_CIMET2_CIMET2_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_CIMET2_CIMET2_BIT_WIDTH)-1) << CMIF_MCD_CIMET2_CIMET2_BIT_LSB) )
#define CMIF_MCD_CIMET2_CIMET2_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_CIMET2_CIMET2_BIT_LSB)
#define CMIF_MCD_CIMET2_CIMET2_FLD_RD()                               ((M_CMIF_MCD_CIMET2_RD() & CMIF_MCD_CIMET2_CIMET2_BIT_MASK) >> CMIF_MCD_CIMET2_CIMET2_BIT_LSB)

#define CMIF_MCD_RAB3_RAB3_ST2_BIT_LSB                                (16)
#define CMIF_MCD_RAB3_RAB3_ST2_BIT_WIDTH                              (16)
#define CMIF_MCD_RAB3_RAB3_ST2_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB3_RAB3_ST2_BIT_WIDTH)-1) << CMIF_MCD_RAB3_RAB3_ST2_BIT_LSB) )
#define CMIF_MCD_RAB3_RAB3_ST2_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB3_RAB3_ST2_BIT_LSB)
#define CMIF_MCD_RAB3_RAB3_ST2_FLD_RD()                               ((M_CMIF_MCD_RAB3_RD() & CMIF_MCD_RAB3_RAB3_ST2_BIT_MASK) >> CMIF_MCD_RAB3_RAB3_ST2_BIT_LSB)

#define CMIF_MCD_RAB3_RAB3_ST01_BIT_LSB                               (0)
#define CMIF_MCD_RAB3_RAB3_ST01_BIT_WIDTH                             (16)
#define CMIF_MCD_RAB3_RAB3_ST01_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAB3_RAB3_ST01_BIT_WIDTH)-1) << CMIF_MCD_RAB3_RAB3_ST01_BIT_LSB) )
#define CMIF_MCD_RAB3_RAB3_ST01_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAB3_RAB3_ST01_BIT_LSB)
#define CMIF_MCD_RAB3_RAB3_ST01_FLD_RD()                              ((M_CMIF_MCD_RAB3_RD() & CMIF_MCD_RAB3_RAB3_ST01_BIT_MASK) >> CMIF_MCD_RAB3_RAB3_ST01_BIT_LSB)

#define CMIF_MCD_HARQMET3_HARQMETSE3_BIT_LSB                          (22)
#define CMIF_MCD_HARQMET3_HARQMETSE3_BIT_WIDTH                        (10)
#define CMIF_MCD_HARQMET3_HARQMETSE3_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_HARQMET3_HARQMETSE3_BIT_WIDTH)-1) << CMIF_MCD_HARQMET3_HARQMETSE3_BIT_LSB) )
#define CMIF_MCD_HARQMET3_HARQMETSE3_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_HARQMET3_HARQMETSE3_BIT_LSB)
#define CMIF_MCD_HARQMET3_HARQMETSE3_FLD_RD()                         ((M_CMIF_MCD_HARQMET3_RD() & CMIF_MCD_HARQMET3_HARQMETSE3_BIT_MASK) >> CMIF_MCD_HARQMET3_HARQMETSE3_BIT_LSB)

#define CMIF_MCD_HARQMET3_HARQMET3_BIT_LSB                            (0)
#define CMIF_MCD_HARQMET3_HARQMET3_BIT_WIDTH                          (22)
#define CMIF_MCD_HARQMET3_HARQMET3_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_HARQMET3_HARQMET3_BIT_WIDTH)-1) << CMIF_MCD_HARQMET3_HARQMET3_BIT_LSB) )
#define CMIF_MCD_HARQMET3_HARQMET3_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_HARQMET3_HARQMET3_BIT_LSB)
#define CMIF_MCD_HARQMET3_HARQMET3_FLD_RD()                           ((M_CMIF_MCD_HARQMET3_RD() & CMIF_MCD_HARQMET3_HARQMET3_BIT_MASK) >> CMIF_MCD_HARQMET3_HARQMET3_BIT_LSB)

#define CMIF_MCD_PARQMET3_PARQMETSE3_BIT_LSB                          (22)
#define CMIF_MCD_PARQMET3_PARQMETSE3_BIT_WIDTH                        (10)
#define CMIF_MCD_PARQMET3_PARQMETSE3_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_PARQMET3_PARQMETSE3_BIT_WIDTH)-1) << CMIF_MCD_PARQMET3_PARQMETSE3_BIT_LSB) )
#define CMIF_MCD_PARQMET3_PARQMETSE3_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_PARQMET3_PARQMETSE3_BIT_LSB)
#define CMIF_MCD_PARQMET3_PARQMETSE3_FLD_RD()                         ((M_CMIF_MCD_PARQMET3_RD() & CMIF_MCD_PARQMET3_PARQMETSE3_BIT_MASK) >> CMIF_MCD_PARQMET3_PARQMETSE3_BIT_LSB)

#define CMIF_MCD_PARQMET3_PARQMET3_BIT_LSB                            (0)
#define CMIF_MCD_PARQMET3_PARQMET3_BIT_WIDTH                          (22)
#define CMIF_MCD_PARQMET3_PARQMET3_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_PARQMET3_PARQMET3_BIT_WIDTH)-1) << CMIF_MCD_PARQMET3_PARQMET3_BIT_LSB) )
#define CMIF_MCD_PARQMET3_PARQMET3_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_PARQMET3_PARQMET3_BIT_LSB)
#define CMIF_MCD_PARQMET3_PARQMET3_FLD_RD()                           ((M_CMIF_MCD_PARQMET3_RD() & CMIF_MCD_PARQMET3_PARQMET3_BIT_MASK) >> CMIF_MCD_PARQMET3_PARQMET3_BIT_LSB)

#define CMIF_MCD_CIMET3_CIMETSE3_BIT_LSB                              (22)
#define CMIF_MCD_CIMET3_CIMETSE3_BIT_WIDTH                            (10)
#define CMIF_MCD_CIMET3_CIMETSE3_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_CIMET3_CIMETSE3_BIT_WIDTH)-1) << CMIF_MCD_CIMET3_CIMETSE3_BIT_LSB) )
#define CMIF_MCD_CIMET3_CIMETSE3_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_CIMET3_CIMETSE3_BIT_LSB)
#define CMIF_MCD_CIMET3_CIMETSE3_FLD_RD()                             ((M_CMIF_MCD_CIMET3_RD() & CMIF_MCD_CIMET3_CIMETSE3_BIT_MASK) >> CMIF_MCD_CIMET3_CIMETSE3_BIT_LSB)

#define CMIF_MCD_CIMET3_CIMET3_BIT_LSB                                (0)
#define CMIF_MCD_CIMET3_CIMET3_BIT_WIDTH                              (22)
#define CMIF_MCD_CIMET3_CIMET3_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_CIMET3_CIMET3_BIT_WIDTH)-1) << CMIF_MCD_CIMET3_CIMET3_BIT_LSB) )
#define CMIF_MCD_CIMET3_CIMET3_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_CIMET3_CIMET3_BIT_LSB)
#define CMIF_MCD_CIMET3_CIMET3_FLD_RD()                               ((M_CMIF_MCD_CIMET3_RD() & CMIF_MCD_CIMET3_CIMET3_BIT_MASK) >> CMIF_MCD_CIMET3_CIMET3_BIT_LSB)

#define CMIF_MCD_RAB4_RAB4_ST2_BIT_LSB                                (16)
#define CMIF_MCD_RAB4_RAB4_ST2_BIT_WIDTH                              (16)
#define CMIF_MCD_RAB4_RAB4_ST2_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB4_RAB4_ST2_BIT_WIDTH)-1) << CMIF_MCD_RAB4_RAB4_ST2_BIT_LSB) )
#define CMIF_MCD_RAB4_RAB4_ST2_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB4_RAB4_ST2_BIT_LSB)
#define CMIF_MCD_RAB4_RAB4_ST2_FLD_RD()                               ((M_CMIF_MCD_RAB4_RD() & CMIF_MCD_RAB4_RAB4_ST2_BIT_MASK) >> CMIF_MCD_RAB4_RAB4_ST2_BIT_LSB)

#define CMIF_MCD_RAB4_RAB4_ST01_BIT_LSB                               (0)
#define CMIF_MCD_RAB4_RAB4_ST01_BIT_WIDTH                             (16)
#define CMIF_MCD_RAB4_RAB4_ST01_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAB4_RAB4_ST01_BIT_WIDTH)-1) << CMIF_MCD_RAB4_RAB4_ST01_BIT_LSB) )
#define CMIF_MCD_RAB4_RAB4_ST01_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAB4_RAB4_ST01_BIT_LSB)
#define CMIF_MCD_RAB4_RAB4_ST01_FLD_RD()                              ((M_CMIF_MCD_RAB4_RD() & CMIF_MCD_RAB4_RAB4_ST01_BIT_MASK) >> CMIF_MCD_RAB4_RAB4_ST01_BIT_LSB)

#define CMIF_MCD_HARQMET4_HARQMETSE4_BIT_LSB                          (22)
#define CMIF_MCD_HARQMET4_HARQMETSE4_BIT_WIDTH                        (10)
#define CMIF_MCD_HARQMET4_HARQMETSE4_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_HARQMET4_HARQMETSE4_BIT_WIDTH)-1) << CMIF_MCD_HARQMET4_HARQMETSE4_BIT_LSB) )
#define CMIF_MCD_HARQMET4_HARQMETSE4_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_HARQMET4_HARQMETSE4_BIT_LSB)
#define CMIF_MCD_HARQMET4_HARQMETSE4_FLD_RD()                         ((M_CMIF_MCD_HARQMET4_RD() & CMIF_MCD_HARQMET4_HARQMETSE4_BIT_MASK) >> CMIF_MCD_HARQMET4_HARQMETSE4_BIT_LSB)

#define CMIF_MCD_HARQMET4_HARQMET4_BIT_LSB                            (0)
#define CMIF_MCD_HARQMET4_HARQMET4_BIT_WIDTH                          (22)
#define CMIF_MCD_HARQMET4_HARQMET4_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_HARQMET4_HARQMET4_BIT_WIDTH)-1) << CMIF_MCD_HARQMET4_HARQMET4_BIT_LSB) )
#define CMIF_MCD_HARQMET4_HARQMET4_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_HARQMET4_HARQMET4_BIT_LSB)
#define CMIF_MCD_HARQMET4_HARQMET4_FLD_RD()                           ((M_CMIF_MCD_HARQMET4_RD() & CMIF_MCD_HARQMET4_HARQMET4_BIT_MASK) >> CMIF_MCD_HARQMET4_HARQMET4_BIT_LSB)

#define CMIF_MCD_PARQMET4_PARQMETSE4_BIT_LSB                          (22)
#define CMIF_MCD_PARQMET4_PARQMETSE4_BIT_WIDTH                        (10)
#define CMIF_MCD_PARQMET4_PARQMETSE4_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_PARQMET4_PARQMETSE4_BIT_WIDTH)-1) << CMIF_MCD_PARQMET4_PARQMETSE4_BIT_LSB) )
#define CMIF_MCD_PARQMET4_PARQMETSE4_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_PARQMET4_PARQMETSE4_BIT_LSB)
#define CMIF_MCD_PARQMET4_PARQMETSE4_FLD_RD()                         ((M_CMIF_MCD_PARQMET4_RD() & CMIF_MCD_PARQMET4_PARQMETSE4_BIT_MASK) >> CMIF_MCD_PARQMET4_PARQMETSE4_BIT_LSB)

#define CMIF_MCD_PARQMET4_PARQMET4_BIT_LSB                            (0)
#define CMIF_MCD_PARQMET4_PARQMET4_BIT_WIDTH                          (22)
#define CMIF_MCD_PARQMET4_PARQMET4_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_PARQMET4_PARQMET4_BIT_WIDTH)-1) << CMIF_MCD_PARQMET4_PARQMET4_BIT_LSB) )
#define CMIF_MCD_PARQMET4_PARQMET4_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_PARQMET4_PARQMET4_BIT_LSB)
#define CMIF_MCD_PARQMET4_PARQMET4_FLD_RD()                           ((M_CMIF_MCD_PARQMET4_RD() & CMIF_MCD_PARQMET4_PARQMET4_BIT_MASK) >> CMIF_MCD_PARQMET4_PARQMET4_BIT_LSB)

#define CMIF_MCD_CIMET4_CIMETSE4_BIT_LSB                              (22)
#define CMIF_MCD_CIMET4_CIMETSE4_BIT_WIDTH                            (10)
#define CMIF_MCD_CIMET4_CIMETSE4_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_CIMET4_CIMETSE4_BIT_WIDTH)-1) << CMIF_MCD_CIMET4_CIMETSE4_BIT_LSB) )
#define CMIF_MCD_CIMET4_CIMETSE4_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_CIMET4_CIMETSE4_BIT_LSB)
#define CMIF_MCD_CIMET4_CIMETSE4_FLD_RD()                             ((M_CMIF_MCD_CIMET4_RD() & CMIF_MCD_CIMET4_CIMETSE4_BIT_MASK) >> CMIF_MCD_CIMET4_CIMETSE4_BIT_LSB)

#define CMIF_MCD_CIMET4_CIMET4_BIT_LSB                                (0)
#define CMIF_MCD_CIMET4_CIMET4_BIT_WIDTH                              (22)
#define CMIF_MCD_CIMET4_CIMET4_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_CIMET4_CIMET4_BIT_WIDTH)-1) << CMIF_MCD_CIMET4_CIMET4_BIT_LSB) )
#define CMIF_MCD_CIMET4_CIMET4_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_CIMET4_CIMET4_BIT_LSB)
#define CMIF_MCD_CIMET4_CIMET4_FLD_RD()                               ((M_CMIF_MCD_CIMET4_RD() & CMIF_MCD_CIMET4_CIMET4_BIT_MASK) >> CMIF_MCD_CIMET4_CIMET4_BIT_LSB)

#define CMIF_MCD_RAB5_RAB5_ST2_BIT_LSB                                (16)
#define CMIF_MCD_RAB5_RAB5_ST2_BIT_WIDTH                              (16)
#define CMIF_MCD_RAB5_RAB5_ST2_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RAB5_RAB5_ST2_BIT_WIDTH)-1) << CMIF_MCD_RAB5_RAB5_ST2_BIT_LSB) )
#define CMIF_MCD_RAB5_RAB5_ST2_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RAB5_RAB5_ST2_BIT_LSB)
#define CMIF_MCD_RAB5_RAB5_ST2_FLD_RD()                               ((M_CMIF_MCD_RAB5_RD() & CMIF_MCD_RAB5_RAB5_ST2_BIT_MASK) >> CMIF_MCD_RAB5_RAB5_ST2_BIT_LSB)

#define CMIF_MCD_RAB5_RAB5_ST01_BIT_LSB                               (0)
#define CMIF_MCD_RAB5_RAB5_ST01_BIT_WIDTH                             (16)
#define CMIF_MCD_RAB5_RAB5_ST01_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_RAB5_RAB5_ST01_BIT_WIDTH)-1) << CMIF_MCD_RAB5_RAB5_ST01_BIT_LSB) )
#define CMIF_MCD_RAB5_RAB5_ST01_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_RAB5_RAB5_ST01_BIT_LSB)
#define CMIF_MCD_RAB5_RAB5_ST01_FLD_RD()                              ((M_CMIF_MCD_RAB5_RD() & CMIF_MCD_RAB5_RAB5_ST01_BIT_MASK) >> CMIF_MCD_RAB5_RAB5_ST01_BIT_LSB)

#define CMIF_MCD_HARQMET5_HARQMETSE5_BIT_LSB                          (22)
#define CMIF_MCD_HARQMET5_HARQMETSE5_BIT_WIDTH                        (10)
#define CMIF_MCD_HARQMET5_HARQMETSE5_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_HARQMET5_HARQMETSE5_BIT_WIDTH)-1) << CMIF_MCD_HARQMET5_HARQMETSE5_BIT_LSB) )
#define CMIF_MCD_HARQMET5_HARQMETSE5_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_HARQMET5_HARQMETSE5_BIT_LSB)
#define CMIF_MCD_HARQMET5_HARQMETSE5_FLD_RD()                         ((M_CMIF_MCD_HARQMET5_RD() & CMIF_MCD_HARQMET5_HARQMETSE5_BIT_MASK) >> CMIF_MCD_HARQMET5_HARQMETSE5_BIT_LSB)

#define CMIF_MCD_HARQMET5_HARQMET5_BIT_LSB                            (0)
#define CMIF_MCD_HARQMET5_HARQMET5_BIT_WIDTH                          (22)
#define CMIF_MCD_HARQMET5_HARQMET5_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_HARQMET5_HARQMET5_BIT_WIDTH)-1) << CMIF_MCD_HARQMET5_HARQMET5_BIT_LSB) )
#define CMIF_MCD_HARQMET5_HARQMET5_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_HARQMET5_HARQMET5_BIT_LSB)
#define CMIF_MCD_HARQMET5_HARQMET5_FLD_RD()                           ((M_CMIF_MCD_HARQMET5_RD() & CMIF_MCD_HARQMET5_HARQMET5_BIT_MASK) >> CMIF_MCD_HARQMET5_HARQMET5_BIT_LSB)

#define CMIF_MCD_PARQMET5_PARQMETSE5_BIT_LSB                          (22)
#define CMIF_MCD_PARQMET5_PARQMETSE5_BIT_WIDTH                        (10)
#define CMIF_MCD_PARQMET5_PARQMETSE5_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_PARQMET5_PARQMETSE5_BIT_WIDTH)-1) << CMIF_MCD_PARQMET5_PARQMETSE5_BIT_LSB) )
#define CMIF_MCD_PARQMET5_PARQMETSE5_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_PARQMET5_PARQMETSE5_BIT_LSB)
#define CMIF_MCD_PARQMET5_PARQMETSE5_FLD_RD()                         ((M_CMIF_MCD_PARQMET5_RD() & CMIF_MCD_PARQMET5_PARQMETSE5_BIT_MASK) >> CMIF_MCD_PARQMET5_PARQMETSE5_BIT_LSB)

#define CMIF_MCD_PARQMET5_PARQMET5_BIT_LSB                            (0)
#define CMIF_MCD_PARQMET5_PARQMET5_BIT_WIDTH                          (22)
#define CMIF_MCD_PARQMET5_PARQMET5_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_PARQMET5_PARQMET5_BIT_WIDTH)-1) << CMIF_MCD_PARQMET5_PARQMET5_BIT_LSB) )
#define CMIF_MCD_PARQMET5_PARQMET5_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_PARQMET5_PARQMET5_BIT_LSB)
#define CMIF_MCD_PARQMET5_PARQMET5_FLD_RD()                           ((M_CMIF_MCD_PARQMET5_RD() & CMIF_MCD_PARQMET5_PARQMET5_BIT_MASK) >> CMIF_MCD_PARQMET5_PARQMET5_BIT_LSB)

#define CMIF_MCD_CIMET5_CIMETSE5_BIT_LSB                              (22)
#define CMIF_MCD_CIMET5_CIMETSE5_BIT_WIDTH                            (10)
#define CMIF_MCD_CIMET5_CIMETSE5_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_CIMET5_CIMETSE5_BIT_WIDTH)-1) << CMIF_MCD_CIMET5_CIMETSE5_BIT_LSB) )
#define CMIF_MCD_CIMET5_CIMETSE5_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_CIMET5_CIMETSE5_BIT_LSB)
#define CMIF_MCD_CIMET5_CIMETSE5_FLD_RD()                             ((M_CMIF_MCD_CIMET5_RD() & CMIF_MCD_CIMET5_CIMETSE5_BIT_MASK) >> CMIF_MCD_CIMET5_CIMETSE5_BIT_LSB)

#define CMIF_MCD_CIMET5_CIMET5_BIT_LSB                                (0)
#define CMIF_MCD_CIMET5_CIMET5_BIT_WIDTH                              (22)
#define CMIF_MCD_CIMET5_CIMET5_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_CIMET5_CIMET5_BIT_WIDTH)-1) << CMIF_MCD_CIMET5_CIMET5_BIT_LSB) )
#define CMIF_MCD_CIMET5_CIMET5_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_CIMET5_CIMET5_BIT_LSB)
#define CMIF_MCD_CIMET5_CIMET5_FLD_RD()                               ((M_CMIF_MCD_CIMET5_RD() & CMIF_MCD_CIMET5_CIMET5_BIT_MASK) >> CMIF_MCD_CIMET5_CIMET5_BIT_LSB)

#define CMIF_MCD_STAT_REG_ARQ_V_BIT_LSB                               (8)
#define CMIF_MCD_STAT_REG_ARQ_V_BIT_WIDTH                             (1)
#define CMIF_MCD_STAT_REG_ARQ_V_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_STAT_REG_ARQ_V_BIT_WIDTH)-1) << CMIF_MCD_STAT_REG_ARQ_V_BIT_LSB) )
#define CMIF_MCD_STAT_REG_ARQ_V_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_STAT_REG_ARQ_V_BIT_LSB)
#define CMIF_MCD_STAT_REG_ARQ_V_FLD_RD()                              ((M_CMIF_MCD_STAT_REG_RD() & CMIF_MCD_STAT_REG_ARQ_V_BIT_MASK) >> CMIF_MCD_STAT_REG_ARQ_V_BIT_LSB)

#define CMIF_MCD_STAT_REG_RAB_V_BIT_LSB                               (2)
#define CMIF_MCD_STAT_REG_RAB_V_BIT_WIDTH                             (6)
#define CMIF_MCD_STAT_REG_RAB_V_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_STAT_REG_RAB_V_BIT_WIDTH)-1) << CMIF_MCD_STAT_REG_RAB_V_BIT_LSB) )
#define CMIF_MCD_STAT_REG_RAB_V_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_STAT_REG_RAB_V_BIT_LSB)
#define CMIF_MCD_STAT_REG_RAB_V_FLD_RD()                              ((M_CMIF_MCD_STAT_REG_RD() & CMIF_MCD_STAT_REG_RAB_V_BIT_MASK) >> CMIF_MCD_STAT_REG_RAB_V_BIT_LSB)

#define CMIF_MCD_STAT_REG_DRCLOCK_V_BIT_LSB                           (1)
#define CMIF_MCD_STAT_REG_DRCLOCK_V_BIT_WIDTH                         (1)
#define CMIF_MCD_STAT_REG_DRCLOCK_V_BIT_MASK                          ((UINT32) (((1<<CMIF_MCD_STAT_REG_DRCLOCK_V_BIT_WIDTH)-1) << CMIF_MCD_STAT_REG_DRCLOCK_V_BIT_LSB) )
#define CMIF_MCD_STAT_REG_DRCLOCK_V_FLD_WR(reg, val)                  (reg |= (val) << CMIF_MCD_STAT_REG_DRCLOCK_V_BIT_LSB)
#define CMIF_MCD_STAT_REG_DRCLOCK_V_FLD_RD()                          ((M_CMIF_MCD_STAT_REG_RD() & CMIF_MCD_STAT_REG_DRCLOCK_V_BIT_MASK) >> CMIF_MCD_STAT_REG_DRCLOCK_V_BIT_LSB)

#define CMIF_MCD_STAT_REG_RPC_V_BIT_LSB                               (0)
#define CMIF_MCD_STAT_REG_RPC_V_BIT_WIDTH                             (1)
#define CMIF_MCD_STAT_REG_RPC_V_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_STAT_REG_RPC_V_BIT_WIDTH)-1) << CMIF_MCD_STAT_REG_RPC_V_BIT_LSB) )
#define CMIF_MCD_STAT_REG_RPC_V_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_STAT_REG_RPC_V_BIT_LSB)
#define CMIF_MCD_STAT_REG_RPC_V_FLD_RD()                              ((M_CMIF_MCD_STAT_REG_RD() & CMIF_MCD_STAT_REG_RPC_V_BIT_MASK) >> CMIF_MCD_STAT_REG_RPC_V_BIT_LSB)

#define CMIF_MCD_DRCVAL_DRCVALSE_BIT_LSB                              (25)
#define CMIF_MCD_DRCVAL_DRCVALSE_BIT_WIDTH                            (7)
#define CMIF_MCD_DRCVAL_DRCVALSE_BIT_MASK                             ((UINT32) (((1<<CMIF_MCD_DRCVAL_DRCVALSE_BIT_WIDTH)-1) << CMIF_MCD_DRCVAL_DRCVALSE_BIT_LSB) )
#define CMIF_MCD_DRCVAL_DRCVALSE_FLD_WR(reg, val)                     (reg |= (val) << CMIF_MCD_DRCVAL_DRCVALSE_BIT_LSB)
#define CMIF_MCD_DRCVAL_DRCVALSE_FLD_RD(i)                            ((M_CMIF_MCD_DRCVAL_RD(i) & CMIF_MCD_DRCVAL_DRCVALSE_BIT_MASK) >> CMIF_MCD_DRCVAL_DRCVALSE_BIT_LSB)

#define CMIF_MCD_DRCVAL_DRCVAL_BIT_LSB                                (0)
#define CMIF_MCD_DRCVAL_DRCVAL_BIT_WIDTH                              (25)
#define CMIF_MCD_DRCVAL_DRCVAL_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_DRCVAL_DRCVAL_BIT_WIDTH)-1) << CMIF_MCD_DRCVAL_DRCVAL_BIT_LSB) )
#define CMIF_MCD_DRCVAL_DRCVAL_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_DRCVAL_DRCVAL_BIT_LSB)
#define CMIF_MCD_DRCVAL_DRCVAL_FLD_RD(i)                              ((M_CMIF_MCD_DRCVAL_RD(i) & CMIF_MCD_DRCVAL_DRCVAL_BIT_MASK) >> CMIF_MCD_DRCVAL_DRCVAL_BIT_LSB)

#define CMIF_MCD_RPC_TC_RPC_TC_BIT_LSB                                (0)
#define CMIF_MCD_RPC_TC_RPC_TC_BIT_WIDTH                              (3)
#define CMIF_MCD_RPC_TC_RPC_TC_BIT_MASK                               ((UINT32) (((1<<CMIF_MCD_RPC_TC_RPC_TC_BIT_WIDTH)-1) << CMIF_MCD_RPC_TC_RPC_TC_BIT_LSB) )
#define CMIF_MCD_RPC_TC_RPC_TC_FLD_WR(reg, val)                       (reg |= (val) << CMIF_MCD_RPC_TC_RPC_TC_BIT_LSB)
#define CMIF_MCD_RPC_TC_RPC_TC_FLD_RD()                               ((M_CMIF_MCD_RPC_TC_RD() & CMIF_MCD_RPC_TC_RPC_TC_BIT_MASK) >> CMIF_MCD_RPC_TC_RPC_TC_BIT_LSB)

#define CMIF_MCD_HL_DMET_DMETSE_BIT_LSB                               (31)
#define CMIF_MCD_HL_DMET_DMETSE_BIT_WIDTH                             (1)
#define CMIF_MCD_HL_DMET_DMETSE_BIT_MASK                              ((UINT32) (((1<<CMIF_MCD_HL_DMET_DMETSE_BIT_WIDTH)-1) << CMIF_MCD_HL_DMET_DMETSE_BIT_LSB) )
#define CMIF_MCD_HL_DMET_DMETSE_FLD_WR(reg, val)                      (reg |= (val) << CMIF_MCD_HL_DMET_DMETSE_BIT_LSB)
#define CMIF_MCD_HL_DMET_DMETSE_FLD_RD(i)                             ((M_CMIF_MCD_HL_DMET_RD(i) & CMIF_MCD_HL_DMET_DMETSE_BIT_MASK) >> CMIF_MCD_HL_DMET_DMETSE_BIT_LSB)

#define CMIF_MCD_HL_DMET_DMET_BIT_LSB                                 (0)
#define CMIF_MCD_HL_DMET_DMET_BIT_WIDTH                               (31)
#define CMIF_MCD_HL_DMET_DMET_BIT_MASK                                ((UINT32) (((1<<CMIF_MCD_HL_DMET_DMET_BIT_WIDTH)-1) << CMIF_MCD_HL_DMET_DMET_BIT_LSB) )
#define CMIF_MCD_HL_DMET_DMET_FLD_WR(reg, val)                        (reg |= (val) << CMIF_MCD_HL_DMET_DMET_BIT_LSB)
#define CMIF_MCD_HL_DMET_DMET_FLD_RD(i)                               ((M_CMIF_MCD_HL_DMET_RD(i) & CMIF_MCD_HL_DMET_DMET_BIT_MASK) >> CMIF_MCD_HL_DMET_DMET_BIT_LSB)

#define CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_BIT_LSB                  (0)
#define CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_BIT_WIDTH                (22)
#define CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_BIT_MASK                 ((UINT32) (((1<<CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_BIT_WIDTH)-1) << CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_BIT_LSB) )
#define CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_FLD_WR(reg, val)         (reg |= (val) << CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_BIT_LSB)
#define CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_FLD_RD()                 ((M_CMIF_MCD_HARQ_REL_TH_RD() & CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_BIT_MASK) >> CMIF_MCD_HARQ_REL_TH_MCD_HARQ_REL_TH_BIT_LSB)

#define CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_BIT_LSB                          (0)
#define CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_BIT_WIDTH                        (1)
#define CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_BIT_MASK                         ((UINT32) (((1<<CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_BIT_WIDTH)-1) << CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_BIT_LSB) )
#define CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_FLD_WR(reg, val)                 (reg |= (val) << CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_BIT_LSB)
#define CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_FLD_RD()                         ((M_CMIF_MCD_ARQ_SEL_RD() & CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_BIT_MASK) >> CMIF_MCD_ARQ_SEL_MCD_ARQ_SEL_BIT_LSB)

#define CMIF_MCD_MRC_MODE_MRC_MODE_BIT_LSB                            (0)
#define CMIF_MCD_MRC_MODE_MRC_MODE_BIT_WIDTH                          (1)
#define CMIF_MCD_MRC_MODE_MRC_MODE_BIT_MASK                           ((UINT32) (((1<<CMIF_MCD_MRC_MODE_MRC_MODE_BIT_WIDTH)-1) << CMIF_MCD_MRC_MODE_MRC_MODE_BIT_LSB) )
#define CMIF_MCD_MRC_MODE_MRC_MODE_FLD_WR(reg, val)                   (reg |= (val) << CMIF_MCD_MRC_MODE_MRC_MODE_BIT_LSB)
#define CMIF_MCD_MRC_MODE_MRC_MODE_FLD_RD()                           ((M_CMIF_MCD_MRC_MODE_RD() & CMIF_MCD_MRC_MODE_MRC_MODE_BIT_MASK) >> CMIF_MCD_MRC_MODE_MRC_MODE_BIT_LSB)

#define CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_BIT_LSB           (1)
#define CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_BIT_WIDTH         (1)
#define CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_BIT_MASK          ((UINT32) (((1<<CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_BIT_WIDTH)-1) << CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_BIT_LSB) )
#define CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_FLD_WR(reg, val)  (reg |= (val) << CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_BIT_LSB)
#define CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_FLD_RD()          ((M_CMIF_MCD_RPC_DEBUG_MODE_RD() & CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_BIT_MASK) >> CMIF_MCD_RPC_DEBUG_MODE_RPC_ACK_FIXED_VALUE_BIT_LSB)

#define CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_BIT_LSB            (0)
#define CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_BIT_WIDTH          (1)
#define CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_BIT_MASK           ((UINT32) (((1<<CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_BIT_WIDTH)-1) << CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_BIT_LSB) )
#define CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_FLD_WR(reg, val)   (reg |= (val) << CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_BIT_LSB)
#define CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_FLD_RD()           ((M_CMIF_MCD_RPC_DEBUG_MODE_RD() & CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_BIT_MASK) >> CMIF_MCD_RPC_DEBUG_MODE_MCD_RPC_FIXED_MODE_BIT_LSB)

#define CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_BIT_LSB         (1)
#define CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_BIT_WIDTH       (1)
#define CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_BIT_MASK        ((UINT32) (((1<<CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_BIT_WIDTH)-1) << CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_BIT_LSB) )
#define CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_FLD_WR(reg, val) (reg |= (val) << CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_BIT_LSB)
#define CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_FLD_RD()        ((M_CMIF_MCD_ARQ_DEBUG_MODE_RD() & CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_BIT_MASK) >> CMIF_MCD_ARQ_DEBUG_MODE_DET_HLALL_FIXED_VALUE_BIT_LSB)

#define CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_BIT_LSB            (0)
#define CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_BIT_WIDTH          (1)
#define CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_BIT_MASK           ((UINT32) (((1<<CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_BIT_WIDTH)-1) << CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_BIT_LSB) )
#define CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_FLD_WR(reg, val)   (reg |= (val) << CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_BIT_LSB)
#define CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_FLD_RD()           ((M_CMIF_MCD_ARQ_DEBUG_MODE_RD() & CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_BIT_MASK) >> CMIF_MCD_ARQ_DEBUG_MODE_MCD_ARQ_FIXED_MODE_BIT_LSB)

#endif /* __MCD_CMIF_H__ */
