#ifndef __CUIF_LTE_RX_SF_CC_CMD_H__
#define __CUIF_LTE_RX_SF_CC_CMD_H__

// ----------------- CUIF_LTE_RX_SF_CC_CMD Register Definition -------------------
typedef volatile struct {
    kal_uint32 CC_INFO0;                                                                  // 0x0000
    kal_uint32 CC_INFO1;                                                                  // 0x0004
    kal_uint32 TIME_INFO0[2];                                                             // 0x0008..0x000C
    kal_uint32 TIME_INFO1[2];                                                             // 0x0010..0x0014
    kal_uint32 LOW_POW_CTRL;                                                              // 0x0018
    kal_uint32 MOD_EN;                                                                    // 0x001C
    kal_uint32 RST_SCENARIO;                                                              // 0x0020
    kal_uint32 AFC_INFO0;                                                                 // 0x0024
    kal_uint32 AFC_INFO1;                                                                 // 0x0028
    kal_uint32 AFC_INFO2;                                                                 // 0x002C
    kal_uint32 AFC_INFO3;                                                                 // 0x0030
    kal_uint32 DUMP_BITMAP_INFO;                                                          // 0x0034
    kal_uint32 MIB_COMM_INFO;                                                             // 0x0038
    kal_uint32 BRP_INFO0;                                                                 // 0x003C
    kal_uint32 BRP_INFO1;                                                                 // 0x0040
    kal_uint32 BRP_INFO;                                                                  // 0x0044
    kal_uint32 RRM_INFO;                                                                  // 0x0048
    kal_uint32 PI_INFO;                                                                   // 0x004C
    kal_uint32 SIB_INFO;                                                                  // 0x0050
    kal_uint32 NBI_SPUR_IDX_RX0_0;                                                        // 0x0054
    kal_uint32 NBI_SPUR_IDX_RX0_1;                                                        // 0x0058
    kal_uint32 NBI_SPUR_IDX_RX1_0;                                                        // 0x005C
    kal_uint32 NBI_SPUR_IDX_RX1_1;                                                        // 0x0060
    kal_uint32 SRV_INFO0;                                                                 // 0x0064
    kal_uint32 SRV_INFO1;                                                                 // 0x0068
    kal_uint32 SRV_INFO2;                                                                 // 0x006C
    kal_uint32 CSI_CTRL;                                                                  // 0x0070
    kal_uint32 CSI_CC_INFO;                                                               // 0x0074
    kal_uint32 PMI_CONFIRM_INFO0;                                                         // 0x0078
    kal_uint32 PMI_CONFIRM_INFO1;                                                         // 0x007C
    kal_uint32 PMI_CONFIRM_INFO2;                                                         // 0x0080
    kal_uint32 PMI_CONFIRM_INFO3;                                                         // 0x0084
    kal_uint32 HST_INFO0;                                                                 // 0x0088
    kal_uint32 RX_SINR_ITF;                                                               // 0x008C
    kal_uint32 BRP_RESERVED_1;                                                            // 0x0090
    kal_uint32 CRSNE_CTRL_INFO_0;                                                         // 0x0094
    kal_uint32 F4L_PATCH_INFO;                                                            // 0x0098
} CUIF_LTE_RX_SF_CC_CMD_REGS, *PCUIF_LTE_RX_SF_CC_CMD_REGS;

// ---------- CUIF_LTE_RX_SF_CC_CMD word-offset  ----------
#define O_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0                                                  (0)
#define O_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1                                                  (1)
#define O_CUIF_LTE_RX_SF_CC_CMD_TIME_INFO0(i)                                             (2 + (i))
#define O_CUIF_LTE_RX_SF_CC_CMD_TIME_INFO1(i)                                             (4 + (i))
#define O_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL                                              (6)
#define O_CUIF_LTE_RX_SF_CC_CMD_MOD_EN                                                    (7)
#define O_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO                                              (8)
#define O_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO0                                                 (9)
#define O_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO1                                                 (10)
#define O_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO2                                                 (11)
#define O_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3                                                 (12)
#define O_CUIF_LTE_RX_SF_CC_CMD_DUMP_BITMAP_INFO                                          (13)
#define O_CUIF_LTE_RX_SF_CC_CMD_MIB_COMM_INFO                                             (14)
#define O_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0                                                 (15)
#define O_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1                                                 (16)
#define O_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO                                                  (17)
#define O_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO                                                  (18)
#define O_CUIF_LTE_RX_SF_CC_CMD_PI_INFO                                                   (19)
#define O_CUIF_LTE_RX_SF_CC_CMD_SIB_INFO                                                  (20)
#define O_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_0                                        (21)
#define O_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_1                                        (22)
#define O_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_0                                        (23)
#define O_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_1                                        (24)
#define O_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0                                                 (25)
#define O_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1                                                 (26)
#define O_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2                                                 (27)
#define O_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL                                                  (28)
#define O_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO                                               (29)
#define O_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0                                         (30)
#define O_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1                                         (31)
#define O_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2                                         (32)
#define O_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3                                         (33)
#define O_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0                                                 (34)
#define O_CUIF_LTE_RX_SF_CC_CMD_RX_SINR_ITF                                               (35)
#define O_CUIF_LTE_RX_SF_CC_CMD_BRP_RESERVED_1                                            (36)
#define O_CUIF_LTE_RX_SF_CC_CMD_CRSNE_CTRL_INFO_0                                         (37)
#define O_CUIF_LTE_RX_SF_CC_CMD_F4L_PATCH_INFO                                            (38)

// ---------- CC_INFO0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_CC_VLD                                           (31)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_CC_VLD                                           (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_CC_VLD                                           (0x80000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_FLAG_SUPPORT_256_QAM                             (29)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_FLAG_SUPPORT_256_QAM                             (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_FLAG_SUPPORT_256_QAM                             (0x20000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_MBSFN_TYPE                                       (27)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_MBSFN_TYPE                                       (2)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_MBSFN_TYPE                                       (0x18000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_IC_LST_STATUS                                    (24)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_IC_LST_STATUS                                    (3)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_IC_LST_STATUS                                    (0x07000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBCH_IC_MODE                                     (22)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBCH_IC_MODE                                     (2)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBCH_IC_MODE                                     (0x00C00000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBCH_BUF_IDX                                     (20)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBCH_BUF_IDX                                     (2)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBCH_BUF_IDX                                     (0x00300000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PDCCH_EN                                         (19)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PDCCH_EN                                         (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PDCCH_EN                                         (0x00080000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PCFICH_EN                                        (18)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PCFICH_EN                                        (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PCFICH_EN                                        (0x00040000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_P_RNTI_EN                                        (17)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_P_RNTI_EN                                        (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_P_RNTI_EN                                        (0x00020000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_SI_RNTI_EN                                       (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_SI_RNTI_EN                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_SI_RNTI_EN                                       (0x00010000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBC_MODE_SEL                                     (15)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBC_MODE_SEL                                     (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_PBC_MODE_SEL                                     (0x00008000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_DL_SYM_BITMAP                                    (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_DL_SYM_BITMAP                                    (14)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO0_DL_SYM_BITMAP                                    (0x00003FFF)

// ---------- CC_INFO1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_TAR_SFN                                          (22)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_TAR_SFN                                          (10)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_TAR_SFN                                          (0xFFC00000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_TAR_SUBFRAME_NUM                                 (18)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_TAR_SUBFRAME_NUM                                 (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_TAR_SUBFRAME_NUM                                 (0x003C0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_RX_EN_MSK                                        (14)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_RX_EN_MSK                                        (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_RX_EN_MSK                                        (0x0003C000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_RX_MODE                                          (10)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_RX_MODE                                          (3)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_RX_MODE                                          (0x00001C00)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_PRS_BW                                           (7)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_PRS_BW                                           (3)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_PRS_BW                                           (0x00000380)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_PRS_VLD                                          (6)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_PRS_VLD                                          (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_PRS_VLD                                          (0x00000040)
#define P_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_WK_PA_MIS_FLAG                                   (5)
#define L_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_WK_PA_MIS_FLAG                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CC_INFO1_WK_PA_MIS_FLAG                                   (0x00000020)

// ---------- TIME_INFO0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_TIME_INFO0_SFBD                                           (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_TIME_INFO0_SFBD                                           (20)
#define M_CUIF_LTE_RX_SF_CC_CMD_TIME_INFO0_SFBD                                           (0x000FFFFF)

// ---------- TIME_INFO1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_TIME_INFO1_TIMING_SF_POS                                  (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_TIME_INFO1_TIMING_SF_POS                                  (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_TIME_INFO1_TIMING_SF_POS                                  (0x0000FFFF)

// ---------- LOW_POW_CTRL bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_TAS_SWAP                                     (28)
#define L_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_TAS_SWAP                                     (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_TAS_SWAP                                     (0x10000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_LIGHT_SYNC_FLAG                              (26)
#define L_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_LIGHT_SYNC_FLAG                              (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_LIGHT_SYNC_FLAG                              (0x04000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_WIN_OFF_TYPE                                 (20)
#define L_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_WIN_OFF_TYPE                                 (2)
#define M_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_WIN_OFF_TYPE                                 (0x00300000)
#define P_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_CRS_CE_TYPE                                  (18)
#define L_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_CRS_CE_TYPE                                  (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_CRS_CE_TYPE                                  (0x00040000)
#define P_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_MIN_ON_SYM_LEN                               (14)
#define L_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_MIN_ON_SYM_LEN                               (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_MIN_ON_SYM_LEN                               (0x0003C000)
#define P_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_MIN_ON_SYM_BITMAP                            (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_MIN_ON_SYM_BITMAP                            (14)
#define M_CUIF_LTE_RX_SF_CC_CMD_LOW_POW_CTRL_MIN_ON_SYM_BITMAP                            (0x00003FFF)

// ---------- MOD_EN bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_PIRC                                               (30)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_PIRC                                               (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_PIRC                                               (0x40000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_PBC                                                (29)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_PBC                                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_PBC                                                (0x20000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TDE                                                (28)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TDE                                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TDE                                                (0x10000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RTP                                                (27)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RTP                                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RTP                                                (0x08000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TRACK_CSI                                          (26)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TRACK_CSI                                          (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TRACK_CSI                                          (0x04000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TURBO_MIMO_MI                                      (25)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TURBO_MIMO_MI                                      (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_TURBO_MIMO_MI                                      (0x02000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_CSIRS_CE                                           (22)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_CSIRS_CE                                           (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_CSIRS_CE                                           (0x00400000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RRM_MRS                                            (21)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RRM_MRS                                            (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RRM_MRS                                            (0x00200000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RRM_CRS                                            (20)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RRM_CRS                                            (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RRM_CRS                                            (0x00100000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RLM                                                (19)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RLM                                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RLM                                                (0x00080000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_DMRS                                               (18)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_DMRS                                               (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_DMRS                                               (0x00040000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_NBI                                                (17)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_NBI                                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_NBI                                                (0x00020000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RSP                                                (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RSP                                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RSP                                                (0x00010000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RS_COMP                                            (15)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RS_COMP                                            (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RS_COMP                                            (0x00008000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_SP_CTRL                                            (12)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_SP_CTRL                                            (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_SP_CTRL                                            (0x00001000)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_SD                                                 (7)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_SD                                                 (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_SD                                                 (0x00000080)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_FWS                                                (6)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_FWS                                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_FWS                                                (0x00000040)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_NE                                                 (5)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_NE                                                 (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_NE                                                 (0x00000020)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_CE                                                 (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_CE                                                 (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_CE                                                 (0x00000010)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_IPD                                                (3)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_IPD                                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_IPD                                                (0x00000008)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_MD                                                 (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_MD                                                 (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_MD                                                 (0x00000004)
#define P_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RSFOE                                              (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RSFOE                                              (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_MOD_EN_RSFOE                                              (0x00000001)

// ---------- RST_SCENARIO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_PAGING_REUSE_RESET                           (15)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_PAGING_REUSE_RESET                           (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_PAGING_REUSE_RESET                           (0x00008000)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NBI_RESET                                    (14)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NBI_RESET                                    (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NBI_RESET                                    (0x00004000)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SIM_AR_RESET                                 (13)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SIM_AR_RESET                                 (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SIM_AR_RESET                                 (0x00002000)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SIM_CHG                                      (12)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SIM_CHG                                      (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SIM_CHG                                      (0x00001000)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MRS_RELIABILITY                              (11)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MRS_RELIABILITY                              (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MRS_RELIABILITY                              (0x00000800)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_ARX_CHANGE                                   (10)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_ARX_CHANGE                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_ARX_CHANGE                                   (0x00000400)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_TM_CHANGE                                    (9)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_TM_CHANGE                                    (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_TM_CHANGE                                    (0x00000200)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_UDC_SSP_CHANGE                               (8)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_UDC_SSP_CHANGE                               (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_UDC_SSP_CHANGE                               (0x00000100)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MIB_CHANGE                                   (7)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MIB_CHANGE                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MIB_CHANGE                                   (0x00000080)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MBSFN_TYPE_CHANGE                            (6)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MBSFN_TYPE_CHANGE                            (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MBSFN_TYPE_CHANGE                            (0x00000040)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MBSFN_AREA_CHANGE                            (5)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MBSFN_AREA_CHANGE                            (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_MBSFN_AREA_CHANGE                            (0x00000020)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_ANY2NBR                                      (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_ANY2NBR                                      (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_ANY2NBR                                      (0x00000010)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NONNBR2SRV                                   (3)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NONNBR2SRV                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NONNBR2SRV                                   (0x00000008)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NBR2SRV                                      (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NBR2SRV                                      (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_NBR2SRV                                      (0x00000004)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_RXD2SA                                       (1)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_RXD2SA                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_RXD2SA                                       (0x00000002)
#define P_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SA2RXD                                       (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SA2RXD                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RST_SCENARIO_SA2RXD                                       (0x00000001)

// ---------- AFC_INFO0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO0_FE_RXNCO_LOAD                                   (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO0_FE_RXNCO_LOAD                                   (32)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO0_FE_RXNCO_LOAD                                   (0xFFFFFFFF)

// ---------- AFC_INFO1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO1_FE_RXNCO_MBSFN_LOAD                             (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO1_FE_RXNCO_MBSFN_LOAD                             (32)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO1_FE_RXNCO_MBSFN_LOAD                             (0xFFFFFFFF)

// ---------- AFC_INFO2 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO2_FE_TXNCO_LOAD                                   (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO2_FE_TXNCO_LOAD                                   (32)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO2_FE_TXNCO_LOAD                                   (0xFFFFFFFF)

// ---------- AFC_INFO3 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_OPER_FC                                         (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_OPER_FC                                         (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_OPER_FC                                         (0xFFFF0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_PROG                                         (5)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_PROG                                         (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_PROG                                         (0x00000020)
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_TX_VLD                                       (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_TX_VLD                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_TX_VLD                                       (0x00000010)
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_PRE_SYNC                                     (3)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_PRE_SYNC                                     (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_PRE_SYNC                                     (0x00000008)
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_TXNCO_LOAD                                   (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_TXNCO_LOAD                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_TXNCO_LOAD                                   (0x00000004)
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_RXNCO_LOAD                                   (1)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_RXNCO_LOAD                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_RXNCO_LOAD                                   (0x00000002)
#define P_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_MBSFN_LOAD                                   (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_MBSFN_LOAD                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_AFC_INFO3_FG_MBSFN_LOAD                                   (0x00000001)

// ---------- DUMP_BITMAP_INFO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_DUMP_BITMAP_INFO_DUMP_MODE_2ND_BITMAP                     (14)
#define L_CUIF_LTE_RX_SF_CC_CMD_DUMP_BITMAP_INFO_DUMP_MODE_2ND_BITMAP                     (14)
#define M_CUIF_LTE_RX_SF_CC_CMD_DUMP_BITMAP_INFO_DUMP_MODE_2ND_BITMAP                     (0x0FFFC000)
#define P_CUIF_LTE_RX_SF_CC_CMD_DUMP_BITMAP_INFO_DUMP_MODE_1ST_BITMAP                     (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_DUMP_BITMAP_INFO_DUMP_MODE_1ST_BITMAP                     (14)
#define M_CUIF_LTE_RX_SF_CC_CMD_DUMP_BITMAP_INFO_DUMP_MODE_1ST_BITMAP                     (0x00003FFF)

// ---------- MIB_COMM_INFO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_MIB_COMM_INFO_MIB_INFO_REB                                (8)
#define L_CUIF_LTE_RX_SF_CC_CMD_MIB_COMM_INFO_MIB_INFO_REB                                (24)
#define M_CUIF_LTE_RX_SF_CC_CMD_MIB_COMM_INFO_MIB_INFO_REB                                (0xFFFFFF00)
#define P_CUIF_LTE_RX_SF_CC_CMD_MIB_COMM_INFO_MB_BIN_NUM                                  (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_MIB_COMM_INFO_MB_BIN_NUM                                  (5)
#define M_CUIF_LTE_RX_SF_CC_CMD_MIB_COMM_INFO_MB_BIN_NUM                                  (0x0000001F)

// ---------- BRP_INFO0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_BRP_CC_EN                                       (31)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_BRP_CC_EN                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_BRP_CC_EN                                       (0x80000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_NDI                                             (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_NDI                                             (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_NDI                                             (0x00010000)
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_SFN_START                                       (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_SFN_START                                       (10)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_SFN_START                                       (0x00003FF0)
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_SF_START                                        (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_SF_START                                        (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO0_SF_START                                        (0x0000000F)

// ---------- BRP_INFO1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_PI_TID                                          (22)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_PI_TID                                          (10)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_PI_TID                                          (0xFFC00000)
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_BUF_IDX                                      (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_BUF_IDX                                      (2)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_BUF_IDX                                      (0x00030000)
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_TID                                          (6)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_TID                                          (10)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_TID                                          (0x0000FFC0)
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_TYPE                                         (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_TYPE                                         (6)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO1_SI_TYPE                                         (0x0000003F)

// ---------- BRP_INFO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_SUBFRAME_TYPE                                    (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_SUBFRAME_TYPE                                    (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_SUBFRAME_TYPE                                    (0x000000F0)
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_SIB_DESTINATION                                  (1)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_SIB_DESTINATION                                  (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_SIB_DESTINATION                                  (0x00000002)
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_PI_DESTINATION                                   (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_PI_DESTINATION                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_INFO_PI_DESTINATION                                   (0x00000001)

// ---------- RRM_INFO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_MEAS_RSRP_OS_FLAG                                (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_MEAS_RSRP_OS_FLAG                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_MEAS_RSRP_OS_FLAG                                (0x00000004)
#define P_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_All_SYM_RSSI                                     (1)
#define L_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_All_SYM_RSSI                                     (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_All_SYM_RSSI                                     (0x00000002)
#define P_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_CRS_RSSI                                         (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_CRS_RSSI                                         (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_RRM_INFO_CRS_RSSI                                         (0x00000001)

// ---------- PI_INFO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_PI_INFO_PI_EMI_BASE_ADDR                                  (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_PI_INFO_PI_EMI_BASE_ADDR                                  (32)
#define M_CUIF_LTE_RX_SF_CC_CMD_PI_INFO_PI_EMI_BASE_ADDR                                  (0xFFFFFFFF)

// ---------- SIB_INFO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_SIB_INFO_SIB_EMI_BASE_ADDR                                (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_SIB_INFO_SIB_EMI_BASE_ADDR                                (32)
#define M_CUIF_LTE_RX_SF_CC_CMD_SIB_INFO_SIB_EMI_BASE_ADDR                                (0xFFFFFFFF)

// ---------- NBI_SPUR_IDX_RX0_0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_0_NBI_SPUR_IDX_RX0_1                     (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_0_NBI_SPUR_IDX_RX0_1                     (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_0_NBI_SPUR_IDX_RX0_1                     (0xFFFF0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_0_NBI_SPUR_IDX_RX0_0                     (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_0_NBI_SPUR_IDX_RX0_0                     (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_0_NBI_SPUR_IDX_RX0_0                     (0x0000FFFF)

// ---------- NBI_SPUR_IDX_RX0_1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_1_NBI_SPUR_IDX_RX0_3                     (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_1_NBI_SPUR_IDX_RX0_3                     (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_1_NBI_SPUR_IDX_RX0_3                     (0xFFFF0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_1_NBI_SPUR_IDX_RX0_2                     (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_1_NBI_SPUR_IDX_RX0_2                     (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX0_1_NBI_SPUR_IDX_RX0_2                     (0x0000FFFF)

// ---------- NBI_SPUR_IDX_RX1_0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_0_NBI_SPUR_IDX_RX1_1                     (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_0_NBI_SPUR_IDX_RX1_1                     (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_0_NBI_SPUR_IDX_RX1_1                     (0xFFFF0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_0_NBI_SPUR_IDX_RX1_0                     (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_0_NBI_SPUR_IDX_RX1_0                     (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_0_NBI_SPUR_IDX_RX1_0                     (0x0000FFFF)

// ---------- NBI_SPUR_IDX_RX1_1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_1_NBI_SPUR_IDX_RX1_3                     (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_1_NBI_SPUR_IDX_RX1_3                     (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_1_NBI_SPUR_IDX_RX1_3                     (0xFFFF0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_1_NBI_SPUR_IDX_RX1_2                     (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_1_NBI_SPUR_IDX_RX1_2                     (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_NBI_SPUR_IDX_RX1_1_NBI_SPUR_IDX_RX1_2                     (0x0000FFFF)

// ---------- SRV_INFO0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_DLHARQ_REL_EN                                   (12)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_DLHARQ_REL_EN                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_DLHARQ_REL_EN                                   (0x00001000)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_C_RNTI_EN                                       (11)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_C_RNTI_EN                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_C_RNTI_EN                                       (0x00000800)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_DL_C_SPS_EN                                     (10)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_DL_C_SPS_EN                                     (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_DL_C_SPS_EN                                     (0x00000400)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_PHICH1_EN                                       (9)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_PHICH1_EN                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_PHICH1_EN                                       (0x00000200)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_PHICH0_EN                                       (8)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_PHICH0_EN                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_PHICH0_EN                                       (0x00000100)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TC_RNTI_EN                                      (5)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TC_RNTI_EN                                      (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TC_RNTI_EN                                      (0x00000020)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_SPS_RNTI_EN                                     (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_SPS_RNTI_EN                                     (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_SPS_RNTI_EN                                     (0x00000010)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_RA_RNTI_EN                                      (3)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_RA_RNTI_EN                                      (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_RA_RNTI_EN                                      (0x00000008)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TP_CCH_RNTI_EN                                  (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TP_CCH_RNTI_EN                                  (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TP_CCH_RNTI_EN                                  (0x00000004)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TP_SCH_RNTI_EN                                  (1)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TP_SCH_RNTI_EN                                  (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_TP_SCH_RNTI_EN                                  (0x00000002)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_M_RNTI_EN                                       (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_M_RNTI_EN                                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO0_M_RNTI_EN                                       (0x00000001)

// ---------- SRV_INFO1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_FLAG_SUPPORT_256_QAM                       (18)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_FLAG_SUPPORT_256_QAM                       (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_FLAG_SUPPORT_256_QAM                       (0x00040000)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_MCS                                        (13)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_MCS                                        (5)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_MCS                                        (0x0003E000)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_VLD                                        (12)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_VLD                                        (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_PMCH_VLD                                        (0x00001000)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_CTRL_REG_NUM                              (11)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_CTRL_REG_NUM                              (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_CTRL_REG_NUM                              (0x00000800)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_AREA_IDX                                  (8)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_AREA_IDX                                  (3)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_AREA_IDX                                  (0x00000700)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_ID                                        (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_ID                                        (8)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO1_MBSFN_ID                                        (0x000000FF)

// ---------- SRV_INFO2 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH1_GRP_NUM                                   (24)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH1_GRP_NUM                                   (7)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH1_GRP_NUM                                   (0x7F000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH0_GRP_NUM                                   (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH0_GRP_NUM                                   (7)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH0_GRP_NUM                                   (0x007F0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH1_SEQ_NUM                                   (5)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH1_SEQ_NUM                                   (3)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH1_SEQ_NUM                                   (0x000000E0)
#define P_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH0_SEQ_NUM                                   (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH0_SEQ_NUM                                   (3)
#define M_CUIF_LTE_RX_SF_CC_CMD_SRV_INFO2_HICH0_SEQ_NUM                                   (0x0000001C)

// ---------- CSI_CTRL bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_DRS_CSIRS_ZERO_POWER_BITMAP                      (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_DRS_CSIRS_ZERO_POWER_BITMAP                      (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_DRS_CSIRS_ZERO_POWER_BITMAP                      (0xFFFF0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_FLAG_SCELL_DEACT_ACT                             (5)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_FLAG_SCELL_DEACT_ACT                             (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_FLAG_SCELL_DEACT_ACT                             (0x00000020)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_FLAG_IC_5_6_RESET                                (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_FLAG_IC_5_6_RESET                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_FLAG_IC_5_6_RESET                                (0x00000010)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_DRS_CSIRS_ZP_VLD                                 (3)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_DRS_CSIRS_ZP_VLD                                 (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_DRS_CSIRS_ZP_VLD                                 (0x00000008)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_CSIRS_ZP_VLD                                     (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_CSIRS_ZP_VLD                                     (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_CSIRS_ZP_VLD                                     (0x00000004)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_TKCSI_RST                                        (1)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_TKCSI_RST                                        (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_TKCSI_RST                                        (0x00000002)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_CSI_RESET                                        (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_CSI_RESET                                        (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CTRL_CSI_RESET                                        (0x00000001)

// ---------- CSI_CC_INFO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_FLAG_FREEZE_TK                                (24)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_FLAG_FREEZE_TK                                (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_FLAG_FREEZE_TK                                (0x01000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_RI_CONFIGINDEX                                (14)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_RI_CONFIGINDEX                                (10)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_RI_CONFIGINDEX                                (0x00FFC000)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_CQI_PMI_CONFIGINDEX                           (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_CQI_PMI_CONFIGINDEX                           (10)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_CQI_PMI_CONFIGINDEX                           (0x00003FF0)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_BUF_SET                                       (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_BUF_SET                                       (2)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_BUF_SET                                       (0x0000000C)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_VALID_DL_SF                                   (1)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_VALID_DL_SF                                   (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_VALID_DL_SF                                   (0x00000002)
#define P_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_IS_ALT_CQI_TABLE                              (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_IS_ALT_CQI_TABLE                              (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_CSI_CC_INFO_IS_ALT_CQI_TABLE                              (0x00000001)

// ---------- PMI_CONFIRM_INFO0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_ACSI_REPORT_MODE                        (28)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_ACSI_REPORT_MODE                        (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_ACSI_REPORT_MODE                        (0xF0000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_PAIR_PMI_VLD                            (27)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_PAIR_PMI_VLD                            (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_PAIR_PMI_VLD                            (0x08000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_PMI                                  (23)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_PMI                                  (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_PMI                                  (0x07800000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_MSB_PMI                                 (19)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_MSB_PMI                                 (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_MSB_PMI                                 (0x00780000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_1ST_PMI                              (15)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_1ST_PMI                              (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_1ST_PMI                              (0x00078000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_2ND_PMI                              (11)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_2ND_PMI                              (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_WB_2ND_PMI                              (0x00007800)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_RI                                      (10)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_RI                                      (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO0_RI                                      (0x00000400)

// ---------- PMI_CONFIRM_INFO1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX0_PMI                             (28)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX0_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX0_PMI                             (0xF0000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX1_PMI                             (24)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX1_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX1_PMI                             (0x0F000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX2_PMI                             (20)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX2_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX2_PMI                             (0x00F00000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX3_PMI                             (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX3_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX3_PMI                             (0x000F0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX4_PMI                             (12)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX4_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX4_PMI                             (0x0000F000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX5_PMI                             (8)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX5_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX5_PMI                             (0x00000F00)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX6_PMI                             (4)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX6_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX6_PMI                             (0x000000F0)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX7_PMI                             (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX7_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO1_SB_IDX7_PMI                             (0x0000000F)

// ---------- PMI_CONFIRM_INFO2 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX8_PMI                             (28)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX8_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX8_PMI                             (0xF0000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX9_PMI                             (24)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX9_PMI                             (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX9_PMI                             (0x0F000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX10_PMI                            (20)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX10_PMI                            (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX10_PMI                            (0x00F00000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX11_PMI                            (16)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX11_PMI                            (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX11_PMI                            (0x000F0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX12_PMI                            (12)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX12_PMI                            (4)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO2_SB_IDX12_PMI                            (0x0000F000)

// ---------- PMI_CONFIRM_INFO3 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_0                               (27)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_0                               (5)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_0                               (0xF8000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_1                               (22)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_1                               (5)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_1                               (0x07C00000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_2                               (17)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_2                               (5)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_2                               (0x003E0000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_3                               (12)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_3                               (5)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_3                               (0x0001F000)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_4                               (7)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_4                               (5)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_4                               (0x00000F80)
#define P_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_5                               (2)
#define L_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_5                               (5)
#define M_CUIF_LTE_RX_SF_CC_CMD_PMI_CONFIRM_INFO3_MSB_IDX_5                               (0x0000007C)

// ---------- HST_INFO0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_HST_FORCE_MD_EN                                 (25)
#define L_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_HST_FORCE_MD_EN                                 (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_HST_FORCE_MD_EN                                 (0x02000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_HST_EN                                          (24)
#define L_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_HST_EN                                          (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_HST_EN                                          (0x01000000)
#define P_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_FQ_ERR_AVG_L1                                   (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_FQ_ERR_AVG_L1                                   (24)
#define M_CUIF_LTE_RX_SF_CC_CMD_HST_INFO0_FQ_ERR_AVG_L1                                   (0x00FFFFFF)

// ---------- RX_SINR_ITF bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_RX_SINR_ITF_SNR_ITF_AVG                                   (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_RX_SINR_ITF_SNR_ITF_AVG                                   (16)
#define M_CUIF_LTE_RX_SF_CC_CMD_RX_SINR_ITF_SNR_ITF_AVG                                   (0x0000FFFF)

// ---------- BRP_RESERVED_1 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_BRP_RESERVED_1_RESERVED_BITS                              (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_BRP_RESERVED_1_RESERVED_BITS                              (32)
#define M_CUIF_LTE_RX_SF_CC_CMD_BRP_RESERVED_1_RESERVED_BITS                              (0xFFFFFFFF)

// ---------- CRSNE_CTRL_INFO_0 bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_CRSNE_CTRL_INFO_0_SIR_FOR_DYNAMIC_SCALE                   (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_CRSNE_CTRL_INFO_0_SIR_FOR_DYNAMIC_SCALE                   (32)
#define M_CUIF_LTE_RX_SF_CC_CMD_CRSNE_CTRL_INFO_0_SIR_FOR_DYNAMIC_SCALE                   (0xFFFFFFFF)

// ---------- F4L_PATCH_INFO bit-field ----------
#define P_CUIF_LTE_RX_SF_CC_CMD_F4L_PATCH_INFO_F4F_PATCH_ENABLE                           (0)
#define L_CUIF_LTE_RX_SF_CC_CMD_F4L_PATCH_INFO_F4F_PATCH_ENABLE                           (1)
#define M_CUIF_LTE_RX_SF_CC_CMD_F4L_PATCH_INFO_F4F_PATCH_ENABLE                           (0x00000001)

#endif // __CUIF_LTE_RX_SF_CC_CMD_H__
