#ifndef __CUIF_LTE_CSI_CC_RPT_H__
#define __CUIF_LTE_CSI_CC_RPT_H__

// ----------------- CUIF_LTE_CSI_CC_RPT Register Definition -------------------
typedef volatile struct {
    kal_uint32 CSI_RPT;                                                                   // 0x0000
    kal_uint32 CSI_RPT0;                                                                  // 0x0004
    kal_uint32 CSI_RPT1;                                                                  // 0x0008
    kal_uint32 CSI_RPT2;                                                                  // 0x000C
    kal_uint32 CSI_RPT3;                                                                  // 0x0010
    kal_uint32 CSI_RPT4;                                                                  // 0x0014
    kal_uint32 CSI_RPT5;                                                                  // 0x0018
    kal_uint32 CSI_RPT6;                                                                  // 0x001C
    kal_uint32 CSI_RPT7;                                                                  // 0x0020
    kal_uint32 CSI_RPT8;                                                                  // 0x0024
    kal_uint32 CSI_RPT9;                                                                  // 0x0028
} CUIF_LTE_CSI_CC_RPT_REGS, *PCUIF_LTE_CSI_CC_RPT_REGS;

// ---------- CUIF_LTE_CSI_CC_RPT word-offset  ----------
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT                                                     (0)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT0                                                    (1)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT1                                                    (2)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT2                                                    (3)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT3                                                    (4)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT4                                                    (5)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT5                                                    (6)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT6                                                    (7)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT7                                                    (8)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT8                                                    (9)
#define O_CUIF_LTE_CSI_CC_RPT_CSI_RPT9                                                    (10)

// ---------- CSI_RPT bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT_CC_VLD                                              (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT_CC_VLD                                              (1)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT_CC_VLD                                              (0x00000001)

// ---------- CSI_RPT0 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_TX_SFN                                             (22)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_TX_SFN                                             (10)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_TX_SFN                                             (0xFFC00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_TX_SF_IDX                                          (18)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_TX_SF_IDX                                          (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_TX_SF_IDX                                          (0x003C0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_MODE                                           (14)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_MODE                                           (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_MODE                                           (0x0003C000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_TYPE                                           (5)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_TYPE                                           (9)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_TYPE                                           (0x00003FE0)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_SF_SET                                         (3)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_SF_SET                                         (2)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RPT_SF_SET                                         (0x00000018)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_PTI                                                (2)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_PTI                                                (1)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_PTI                                                (0x00000004)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RI                                                 (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RI                                                 (2)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT0_RI                                                 (0x00000003)

// ---------- CSI_RPT1 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_CQI_CW0                                         (28)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_CQI_CW0                                         (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_CQI_CW0                                         (0xF0000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_CQI_CW1                                         (24)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_CQI_CW1                                         (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_CQI_CW1                                         (0x0F000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_PMI                                             (20)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_PMI                                             (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_PMI                                             (0x00F00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_1ST_PMI                                         (12)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_1ST_PMI                                         (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_1ST_PMI                                         (0x0000F000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_2ND_PMI                                         (8)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_2ND_PMI                                         (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_WB_2ND_PMI                                         (0x00000F00)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_FLAG_NO_VALID_SF_SET                               (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_FLAG_NO_VALID_SF_SET                               (1)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT1_FLAG_NO_VALID_SF_SET                               (0x00000001)

// ---------- CSI_RPT2 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX0_PMI                                        (28)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX0_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX0_PMI                                        (0xF0000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX1_PMI                                        (24)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX1_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX1_PMI                                        (0x0F000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX2_PMI                                        (20)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX2_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX2_PMI                                        (0x00F00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX3_PMI                                        (16)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX3_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX3_PMI                                        (0x000F0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX4_PMI                                        (12)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX4_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX4_PMI                                        (0x0000F000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX5_PMI                                        (8)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX5_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX5_PMI                                        (0x00000F00)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX6_PMI                                        (4)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX6_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX6_PMI                                        (0x000000F0)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX7_PMI                                        (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX7_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT2_SB_IDX7_PMI                                        (0x0000000F)

// ---------- CSI_RPT3 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX8_PMI                                        (28)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX8_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX8_PMI                                        (0xF0000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX9_PMI                                        (24)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX9_PMI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX9_PMI                                        (0x0F000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX10_PMI                                       (20)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX10_PMI                                       (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX10_PMI                                       (0x00F00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX11_PMI                                       (16)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX11_PMI                                       (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX11_PMI                                       (0x000F0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX12_PMI                                       (12)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX12_PMI                                       (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_IDX12_PMI                                       (0x0000F000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_PMI                                             (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_PMI                                             (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT3_SB_PMI                                             (0x0000000F)

// ---------- CSI_RPT4 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX0                                           (27)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX0                                           (5)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX0                                           (0xF8000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX1                                           (22)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX1                                           (5)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX1                                           (0x07C00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX2                                           (17)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX2                                           (5)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX2                                           (0x003E0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX3                                           (12)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX3                                           (5)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX3                                           (0x0001F000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX4                                           (7)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX4                                           (5)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX4                                           (0x00000F80)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX5                                           (2)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX5                                           (5)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT4_MSB_IDX5                                           (0x0000007C)

// ---------- CSI_RPT5 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX0_CQI_CW0                                    (28)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX0_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX0_CQI_CW0                                    (0xF0000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX1_CQI_CW0                                    (24)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX1_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX1_CQI_CW0                                    (0x0F000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX2_CQI_CW0                                    (20)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX2_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX2_CQI_CW0                                    (0x00F00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX3_CQI_CW0                                    (16)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX3_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX3_CQI_CW0                                    (0x000F0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX4_CQI_CW0                                    (12)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX4_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX4_CQI_CW0                                    (0x0000F000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX5_CQI_CW0                                    (8)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX5_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX5_CQI_CW0                                    (0x00000F00)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX6_CQI_CW0                                    (4)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX6_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX6_CQI_CW0                                    (0x000000F0)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX7_CQI_CW0                                    (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX7_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT5_SB_IDX7_CQI_CW0                                    (0x0000000F)

// ---------- CSI_RPT6 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX8_CQI_CW0                                    (28)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX8_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX8_CQI_CW0                                    (0xF0000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX9_CQI_CW0                                    (24)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX9_CQI_CW0                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX9_CQI_CW0                                    (0x0F000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX10_CQI_CW0                                   (20)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX10_CQI_CW0                                   (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX10_CQI_CW0                                   (0x00F00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX11_CQI_CW0                                   (16)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX11_CQI_CW0                                   (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX11_CQI_CW0                                   (0x000F0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX12_CQI_CW0                                   (12)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX12_CQI_CW0                                   (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_IDX12_CQI_CW0                                   (0x0000F000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_CQI_CW0                                         (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_CQI_CW0                                         (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT6_SB_CQI_CW0                                         (0x0000000F)

// ---------- CSI_RPT7 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX0_CQI_CW1                                    (28)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX0_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX0_CQI_CW1                                    (0xF0000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX1_CQI_CW1                                    (24)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX1_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX1_CQI_CW1                                    (0x0F000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX2_CQI_CW1                                    (20)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX2_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX2_CQI_CW1                                    (0x00F00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX3_CQI_CW1                                    (16)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX3_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX3_CQI_CW1                                    (0x000F0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX4_CQI_CW1                                    (12)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX4_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX4_CQI_CW1                                    (0x0000F000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX5_CQI_CW1                                    (8)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX5_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX5_CQI_CW1                                    (0x00000F00)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX6_CQI_CW1                                    (4)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX6_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX6_CQI_CW1                                    (0x000000F0)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX7_CQI_CW1                                    (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX7_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT7_SB_IDX7_CQI_CW1                                    (0x0000000F)

// ---------- CSI_RPT8 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX8_CQI_CW1                                    (28)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX8_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX8_CQI_CW1                                    (0xF0000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX9_CQI_CW1                                    (24)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX9_CQI_CW1                                    (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX9_CQI_CW1                                    (0x0F000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX10_CQI_CW1                                   (20)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX10_CQI_CW1                                   (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX10_CQI_CW1                                   (0x00F00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX11_CQI_CW1                                   (16)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX11_CQI_CW1                                   (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX11_CQI_CW1                                   (0x000F0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX12_CQI_CW1                                   (12)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX12_CQI_CW1                                   (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_IDX12_CQI_CW1                                   (0x0000F000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_CQI_CW1                                         (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_CQI_CW1                                         (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT8_SB_CQI_CW1                                         (0x0000000F)

// ---------- CSI_RPT9 bit-field ----------
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP1_SB_CQI                                        (28)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP1_SB_CQI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP1_SB_CQI                                        (0xF0000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP2_SB_CQI                                        (24)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP2_SB_CQI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP2_SB_CQI                                        (0x0F000000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP3_SB_CQI                                        (20)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP3_SB_CQI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP3_SB_CQI                                        (0x00F00000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP4_SB_CQI                                        (16)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP4_SB_CQI                                        (4)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_TOP4_SB_CQI                                        (0x000F0000)
#define P_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_VLD_TOP4_NUM                                       (0)
#define L_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_VLD_TOP4_NUM                                       (3)
#define M_CUIF_LTE_CSI_CC_RPT_CSI_RPT9_VLD_TOP4_NUM                                       (0x00000007)

#endif // __CUIF_LTE_CSI_CC_RPT_H__
