#ifndef L1TRC_EL1D_RXDMP_DEF_H
#define L1TRC_EL1D_RXDMP_DEF_H

/******************************/
/* String category definition */
/******************************/
#define EL1D_TRC_RXDMP_HW_PATH(v1)  (unsigned char)(v1+0)
#define EL1D_TRC_RXDMP_IRQ(v1)  (unsigned char)(v1+4)
#define EL1D_TRC_RXDMP_CC(v1)  (unsigned char)(v1+9)
#define EL1D_TRC_RXDMP_BW(v1)  (unsigned char)(v1+14)


/****************************/
/* Message macro definition */
/****************************/
#include "L1Trc.h"
#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 2) )
	#define EL1D_TRC_RXDMP_POWER_CONTROL_L(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x005F,0x005F);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x01);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_POWER_CONTROL_L(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define EL1D_TRC_RXDMP_CLOCK_ON_CONTROL_L(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x02);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x015F,0x015F);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x02);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_CLOCK_ON_CONTROL_L(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define EL1D_TRC_RXDMP_CLOCK_OFF_CONTROL_L(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x02);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x025F,0x025F);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x02);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_CLOCK_OFF_CONTROL_L(v1)
#endif

#if defined(L1_CATCHER)
	#define EL1D_TRC_RXDMP_IRQ_HANDLER_START_H(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 1, 0x04);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x035F,0x035F);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 1, 0x04);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_IRQ_HANDLER_START_H(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 2) )
	#define EL1D_TRC_RXDMP_IRQ_STATUS_H(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 1, 0x08);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x045F,0x045F);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 1, 0x08);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_IRQ_STATUS_H(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 2) )
	#define EL1D_TRC_RXDMP_IRQ_HANDLER_END_H() do {\
		{\
			TRC_START_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 1, 0x08);\
			TRC_START_FILL_L1();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1(0x055F,0x055F);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 1, 0x08);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_IRQ_HANDLER_END_H()
#endif

#if defined(L1_CATCHER)
	#define EL1D_TRC_RXDMP_MAIN_TICK_H(v1, v2) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x10);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x065F,0x065F);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x10);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_MAIN_TICK_H(v1, v2)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 2) )
	#define EL1D_TRC_RXDMP_TAS_SWAP_INFO_L(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x40);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x075F,0x075F);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x40);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_TAS_SWAP_INFO_L(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 2) )
	#define EL1D_TRC_RXDMP_POS_REQUEST_L(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x40);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x085F,0x085F);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x40);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_POS_REQUEST_L(v1)
#endif

#if defined(L1_CATCHER)
	#define EL1D_TRC_RXDMP_POS_DUMP_START_1_H(v1, v2, v3, v4, v5, v6) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v6,v6);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v6,v6);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x095F,0x095F);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v5,v5);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_NON_SMP(cgen_local_v6,v6);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_POS_DUMP_START_1_H(v1, v2, v3, v4, v5, v6)
#endif

#if defined(L1_CATCHER)
	#define EL1D_TRC_RXDMP_POS_DUMP_START_2_H(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x0A5F,0x0A5F);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_POS_DUMP_START_2_H(v1, v2, v3, v4)
#endif

#if defined(L1_CATCHER)
	#define EL1D_TRC_RXDMP_CS_DUMP_START_H(v1, v2, v3, v4, v5, v6, v7, v8) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v7,v7);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v8,v8);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v5,v5);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v6,v6);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v7,v7);\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v8,v8);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x0B5F,0x0B5F);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v2,v2);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v3,v3);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v4,v4);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v5,v5);\
			TRC_OUTPUT_32_MID_WRAPPER_L1_NON_SMP(cgen_local_v6,v6);\
			TRC_OUTPUT_8_MID_WRAPPER_L1_NON_SMP(cgen_local_v7,v7);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1_NON_SMP(cgen_local_v8,v8);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_CS_DUMP_START_H(v1, v2, v3, v4, v5, v6, v7, v8)
#endif

#if defined(L1_CATCHER)
	#define EL1D_TRC_RXDMP_POS_ABORT_H() do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_OUTPUT_16_SINGLE_WRAPPER_L1_NON_SMP(0x0C5F,0x0C5F);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_POS_ABORT_H()
#endif

#if defined(L1_CATCHER)
	#define EL1D_TRC_RXDMP_CS_ABORT_H(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x0D5F,0x0D5F);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x20);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_CS_ABORT_H(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 2) )
	#define EL1D_TRC_RXDMP_CS_REQUEST_L(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x40);\
			TRC_PREPROCESS_DATA_SECTION1_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_START_FILL_L1_NON_SMP();\
			TRC_PREPROCESS_DATA_SECTION2_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1_NON_SMP(0x0E5F,0x0E5F);\
			TRC_OUTPUT_8_LAST_WRAPPER_L1_NON_SMP(cgen_local_v1,v1);\
			TRC_END_FILL_L1_NON_SMP();\
			TRC_END_FILTER_CHECK_L1_NON_SMP(EL1D_RXDMP_Trace_Filter, 1, 0x40);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_CS_REQUEST_L(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define EL1D_TRC_RXDMP_COSIM_WRITE_L(v1) do {\
		{\
			TRC_START_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 2, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x0F5F,0x0F5F);\
			TRC_OUTPUT_32_LAST_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 2, 0x01);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_COSIM_WRITE_L(v1)
#endif

#if defined(L1_CATCHER) && ( !defined(_L1_DISABLE_TRACE_LEVEL_) || (_L1_DISABLE_TRACE_LEVEL_ < 1) )
	#define EL1D_TRC_RXDMP_COSIM_DEBUG_WRITE_L(v1, v2, v3, v4) do {\
		{\
			TRC_START_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 2, 0x01);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION1_L1(cgen_local_v4,v4);\
			TRC_START_FILL_L1();\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v1,v1);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v2,v2);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v3,v3);\
			TRC_PREPROCESS_DATA_SECTION2_L1(cgen_local_v4,v4);\
			TRC_OUTPUT_16_FIRST_WRAPPER_L1(0x105F,0x105F);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v1,v1);\
			TRC_OUTPUT_32_MID_WRAPPER_L1(cgen_local_v2,v2);\
			TRC_OUTPUT_16_MID_WRAPPER_L1(cgen_local_v3,v3);\
			TRC_OUTPUT_16_LAST_WRAPPER_L1(cgen_local_v4,v4);\
			TRC_END_FILL_L1();\
			TRC_END_FILTER_CHECK_L1(EL1D_RXDMP_Trace_Filter, 2, 0x01);\
		}\
	} while(0)
#else
	#define EL1D_TRC_RXDMP_COSIM_DEBUG_WRITE_L(v1, v2, v3, v4)
#endif



/*******************************/
/* declaration of filter array */
/*******************************/
EXTERN_TMD_FILTER(unsigned char, EL1D_RXDMP_Trace_Filter, 5);
/*************************/
/* Function declarations */
/*************************/
#ifdef L1_CATCHER

void Set_EL1D_RXDMP_Filter(unsigned char *setting);

#endif

/************************************/
/* Filter checking API declarations */
/************************************/

#define ChkL1ModFltr_EL1D_RXDMP()	(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 0, 1))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_CLOCK_M()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 1, 0x01)))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_CLOCK_L()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 1, 0x02)))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_IRQ_H()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 1, 0x04)))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_IRQ_M()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 1, 0x08)))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_MAIN_H()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 1, 0x10)))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_H()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 1, 0x20)))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_M()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 1, 0x40)))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_L()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 1, 0x80)))
#define ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_COSIM_L()	(ChkL1ModFltr_EL1D_RXDMP()&&(FILTER_CHECK(EL1D_RXDMP_Trace_Filter, 2, 0x01)))
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_POWER_CONTROL_L()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_CLOCK_M()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_CLOCK_ON_CONTROL_L()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_CLOCK_L()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_CLOCK_OFF_CONTROL_L()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_CLOCK_L()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_IRQ_HANDLER_START_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_IRQ_H()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_IRQ_STATUS_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_IRQ_M()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_IRQ_HANDLER_END_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_IRQ_M()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_MAIN_TICK_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_MAIN_H()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_TAS_SWAP_INFO_L()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_M()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_POS_REQUEST_L()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_M()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_POS_DUMP_START_1_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_H()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_POS_DUMP_START_2_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_H()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_CS_DUMP_START_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_H()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_POS_ABORT_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_H()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_CS_ABORT_H()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_H()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_CS_REQUEST_L()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_REQUEST_M()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_COSIM_WRITE_L()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_COSIM_L()
#define ChkL1MsgFltr_EL1D_TRC_RXDMP_COSIM_DEBUG_WRITE_L()	ChkL1ClsFltr_EL1D_RXDMP_EL1D_TRC_RXDMP_COSIM_L()


#endif
