/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 *
 * Filename:
 * ---------
 * cl1_nvram_id.h
 *
 * Project:
 * --------
 * 93
 *
 * Description:
 * ------------
 * C2K NVRAM item infomation provided to NVRAM, MMRF, and C2K itself.
 *
 *               
 * Author:
 * -------
 * 
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/

#define MIPI_RX_EVENT_MAX_NUM                   (9  +1)
#define MIPI_RX_DATA_MAX_NUM                    (18 +1)
#define MIPI_TX_EVENT_MAX_NUM                   (12 +1)
#define MIPI_TX_DATA_MAX_NUM                    (36 +1)
#define MIPI_TPC_EVENT_MAX_NUM                  (9  +1)
#define MIPI_TPC_DATA_MAX_NUM                   (5  +1)
#define MIPI_PA_SECTION_DATA_MAX_NUM            C2K_MIPI_SUBBAND_NUM
#define MIPI_ETM_TX_EVENT_MAX_NUM               MIPI_TX_EVENT_MAX_NUM
#define MIPI_ETM_TX_DATA_MAX_NUM                MIPI_TX_DATA_MAX_NUM
#define MIPI_ETM_TPC_EVENT_MAX_NUM              MIPI_TPC_EVENT_MAX_NUM
#define MIPI_ETM_TPC_DATA_MAX_NUM               MIPI_TPC_DATA_MAX_NUM
#define MIPI_ETM_PA_SECTION_DATA_MAX_NUM        C2K_MIPI_SUBBAND_NUM

#define MIPI_TAS_EVENT_MAX_NUM					(10)
#define MIPI_TAS_DATA_MAX_NUM					(20)

#define MIPI_ELNA_EVENT_MAX_NUM					(10)
#define MIPI_ELNA_DATA_MAX_NUM					(20)

#define MIPI_DAT_EVENT_MAX_NUM					MIPI_TAS_EVENT_MAX_NUM
#define MIPI_DAT_DATA_MAX_NUM					MIPI_TAS_DATA_MAX_NUM
/* NVRAM ID definition of items in C2K RF custom file */
/* Common Parameters */
/* 0 */NVRAM_ITEM_RF_CUST(CUST_PARAM, , 1, CUST_PARAM_T, 1, NULL)
/* BPI Configurations */
/* 1 */NVRAM_ITEM_RF_CUST(CUST_BPI_CFG, BAND_A, MAX_BAND_NUM, CUST_BPI_CFG_T, 1, NULL)
/* 2 */NVRAM_ITEM_RF_CUST(CUST_BPI_CFG, BAND_B, MAX_BAND_NUM, CUST_BPI_CFG_T, 1, NULL)
/* 3 */NVRAM_ITEM_RF_CUST(CUST_BPI_CFG, BAND_C, MAX_BAND_NUM, CUST_BPI_CFG_T, 1, NULL)
/* 4 */NVRAM_ITEM_RF_CUST(CUST_BPI_CFG, BAND_D, MAX_BAND_NUM, CUST_BPI_CFG_T, 1, NULL)
/* 5 */NVRAM_ITEM_RF_CUST(CUST_BPI_CFG, BAND_E, MAX_BAND_NUM, CUST_BPI_CFG_T, 1, NULL)

/* TAS Configurations */
//NVRAM_ITEM_RF_CUST(RF_CUST_TAS, DBM_RF_CUST_TAS_SIZE, hwdRfCustomTas, hwdRfCustTasInput, HwdRfCustTasProcess)
//NVRAM_ITEM_RF_CUST(RF_CUST_TAS_BY_RAT, DBM_RF_CUST_TAS_BY_RAT_SIZE, C2K_TAS_FEATURE_BY_RAT, C2K_TAS_FEATURE_BY_RAT_INPUT, HwdRfCustTasByRatProcess)

/////////////////////// GENARAL_NAME,  RF_BAND, REC,  TYPE,                    , TYPE NUM,              FUNC

/* MIPI Configurations */
/* 6 */ NVRAM_ITEM_MIPI(MIPI_PARAM, , 1, MIPI_PARAM_T, 1, NULL)

/* 7 */ NVRAM_ITEM_MIPI(MIPI_RX_EVENT, BAND_A, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_RX_EVENT_MAX_NUM, NULL)
/* 8 */ NVRAM_ITEM_MIPI(MIPI_RX_EVENT, BAND_B, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_RX_EVENT_MAX_NUM, NULL)
/* 9 */ NVRAM_ITEM_MIPI(MIPI_RX_EVENT, BAND_C, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_RX_EVENT_MAX_NUM, NULL)
/* 10 */NVRAM_ITEM_MIPI(MIPI_RX_EVENT, BAND_D, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_RX_EVENT_MAX_NUM, NULL)
/* 11 */NVRAM_ITEM_MIPI(MIPI_RX_EVENT, BAND_E, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_RX_EVENT_MAX_NUM, NULL)

/* 12 */NVRAM_ITEM_MIPI(MIPI_RX_DATA, BAND_A, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_RX_DATA_MAX_NUM, NULL)
/* 13 */NVRAM_ITEM_MIPI(MIPI_RX_DATA, BAND_B, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_RX_DATA_MAX_NUM, NULL)
/* 14 */NVRAM_ITEM_MIPI(MIPI_RX_DATA, BAND_C, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_RX_DATA_MAX_NUM, NULL)
/* 15 */NVRAM_ITEM_MIPI(MIPI_RX_DATA, BAND_D, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_RX_DATA_MAX_NUM, NULL)
/* 16 */NVRAM_ITEM_MIPI(MIPI_RX_DATA, BAND_E, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_RX_DATA_MAX_NUM, NULL)

/* 17 */NVRAM_ITEM_MIPI(MIPI_TX_EVENT, BAND_A, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TX_EVENT_MAX_NUM, NULL)
/* 18 */NVRAM_ITEM_MIPI(MIPI_TX_EVENT, BAND_B, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TX_EVENT_MAX_NUM, NULL)
/* 19 */NVRAM_ITEM_MIPI(MIPI_TX_EVENT, BAND_C, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TX_EVENT_MAX_NUM, NULL)
/* 20 */NVRAM_ITEM_MIPI(MIPI_TX_EVENT, BAND_D, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TX_EVENT_MAX_NUM, NULL)
/* 21 */NVRAM_ITEM_MIPI(MIPI_TX_EVENT, BAND_E, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TX_EVENT_MAX_NUM, NULL)

/* 22 */NVRAM_ITEM_MIPI(MIPI_TX_DATA, BAND_A, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TX_DATA_MAX_NUM, NULL)
/* 23 */NVRAM_ITEM_MIPI(MIPI_TX_DATA, BAND_B, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TX_DATA_MAX_NUM, NULL)
/* 24 */NVRAM_ITEM_MIPI(MIPI_TX_DATA, BAND_C, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TX_DATA_MAX_NUM, NULL)
/* 25 */NVRAM_ITEM_MIPI(MIPI_TX_DATA, BAND_D, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TX_DATA_MAX_NUM, NULL)
/* 26 */NVRAM_ITEM_MIPI(MIPI_TX_DATA, BAND_E, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TX_DATA_MAX_NUM, NULL)

/* 27 */NVRAM_ITEM_MIPI(MIPI_TPC_EVENT, BAND_A, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TPC_EVENT_MAX_NUM, NULL)
/* 28 */NVRAM_ITEM_MIPI(MIPI_TPC_EVENT, BAND_B, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TPC_EVENT_MAX_NUM, NULL)
/* 29 */NVRAM_ITEM_MIPI(MIPI_TPC_EVENT, BAND_C, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TPC_EVENT_MAX_NUM, NULL)
/* 30 */NVRAM_ITEM_MIPI(MIPI_TPC_EVENT, BAND_D, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TPC_EVENT_MAX_NUM, NULL)
/* 31 */NVRAM_ITEM_MIPI(MIPI_TPC_EVENT, BAND_E, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TPC_EVENT_MAX_NUM, NULL)

/* 32 */NVRAM_ITEM_MIPI(MIPI_TPC_DATA, BAND_A, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_TPC_DATA_MAX_NUM, NULL)
/* 33 */NVRAM_ITEM_MIPI(MIPI_TPC_DATA, BAND_B, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_TPC_DATA_MAX_NUM, NULL)
/* 34 */NVRAM_ITEM_MIPI(MIPI_TPC_DATA, BAND_C, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_TPC_DATA_MAX_NUM, NULL)
/* 35 */NVRAM_ITEM_MIPI(MIPI_TPC_DATA, BAND_D, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_TPC_DATA_MAX_NUM, NULL)
/* 36 */NVRAM_ITEM_MIPI(MIPI_TPC_DATA, BAND_E, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_TPC_DATA_MAX_NUM, NULL)

/* 37 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_1XRTT, BAND_A, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 38 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_1XRTT, BAND_B, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 39 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_1XRTT, BAND_C, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 40 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_1XRTT, BAND_D, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 41 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_1XRTT, BAND_E, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)

/* 42 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_EVDO, BAND_A, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 43 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_EVDO, BAND_B, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 44 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_EVDO, BAND_C, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 45 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_EVDO, BAND_D, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 46 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DATA_EVDO, BAND_E, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)

/* MIPI Configuration -- ETM */
/* 47 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_EVENT, BAND_A, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TX_EVENT_MAX_NUM, NULL)
/* 48 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_EVENT, BAND_B, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TX_EVENT_MAX_NUM, NULL)
/* 49 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_EVENT, BAND_C, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TX_EVENT_MAX_NUM, NULL)
/* 50 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_EVENT, BAND_D, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TX_EVENT_MAX_NUM, NULL)
/* 51 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_EVENT, BAND_E, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TX_EVENT_MAX_NUM, NULL)

/* 52 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_DATA, BAND_A, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ETM_TX_DATA_MAX_NUM, NULL)
/* 53 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_DATA, BAND_B, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ETM_TX_DATA_MAX_NUM, NULL)
/* 54 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_DATA, BAND_C, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ETM_TX_DATA_MAX_NUM, NULL)
/* 55 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_DATA, BAND_D, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ETM_TX_DATA_MAX_NUM, NULL)
/* 56 */NVRAM_ITEM_MIPI(MIPI_ETM_TX_DATA, BAND_E, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ETM_TX_DATA_MAX_NUM, NULL)

/* 57 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_EVENT, BAND_A, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TPC_EVENT_MAX_NUM, NULL)
/* 58 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_EVENT, BAND_B, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TPC_EVENT_MAX_NUM, NULL)
/* 59 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_EVENT, BAND_C, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TPC_EVENT_MAX_NUM, NULL)
/* 60 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_EVENT, BAND_D, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TPC_EVENT_MAX_NUM, NULL)
/* 61 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_EVENT, BAND_E, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_ETM_TPC_EVENT_MAX_NUM, NULL)

/* 62 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_DATA, BAND_A, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_ETM_TPC_DATA_MAX_NUM, NULL)
/* 63 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_DATA, BAND_B, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_ETM_TPC_DATA_MAX_NUM, NULL)
/* 64 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_DATA, BAND_C, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_ETM_TPC_DATA_MAX_NUM, NULL)
/* 65 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_DATA, BAND_D, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_ETM_TPC_DATA_MAX_NUM, NULL)
/* 66 */NVRAM_ITEM_MIPI(MIPI_ETM_TPC_DATA, BAND_E, MAX_BAND_NUM, MIPI_DATA_TABLE_T, MIPI_ETM_TPC_DATA_MAX_NUM, NULL)

/* 67 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_1XRTT, BAND_A, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)
/* 68 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_1XRTT, BAND_B, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)
/* 69 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_1XRTT, BAND_C, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)
/* 70 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_1XRTT, BAND_D, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)
/* 71 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_1XRTT, BAND_E, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)


/* 72 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_EVDO, BAND_A, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)
/* 73 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_EVDO, BAND_B, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)
/* 74 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_EVDO, BAND_C, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)
/* 75 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_EVDO, BAND_D, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)
/* 76 */NVRAM_ITEM_MIPI(MIPI_ETM_PA_SECTION_DATA_EVDO, BAND_E, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_ETM_PA_SECTION_DATA_MAX_NUM, NULL)

/* Calibration Data */
/* 77 */NVRAM_ITEM_RF_CAL(AFC_DATA, , 1,  AFC_DATA_T, 1, NULL)

/* 78 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_1XRTT, BAND_A, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)
/* 79 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_1XRTT, BAND_B, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)
/* 80 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_1XRTT, BAND_C, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)
/* 81 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_1XRTT, BAND_D, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)
/* 82 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_1XRTT, BAND_E, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)

/* 83 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_EVDO, BAND_A, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)
/* 84 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_EVDO, BAND_B, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)
/* 85 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_EVDO, BAND_C, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)
/* 86 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_EVDO, BAND_D, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)
/* 87 */NVRAM_ITEM_RF_CAL(TX_APT_PA_CONTEXT_EVDO, BAND_E, MAX_BAND_NUM, TX_APT_PA_CONTEXT_T, 1, NULL)

/* 88 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_1XRTT, BAND_A, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)
/* 89 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_1XRTT, BAND_B, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)
/* 90 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_1XRTT, BAND_C, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)
/* 91 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_1XRTT, BAND_D, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)
/* 92 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_1XRTT, BAND_E, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)

/* 93 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_EVDO, BAND_A, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)
/* 94 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_EVDO, BAND_B, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)
/* 95 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_EVDO, BAND_C, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)
/* 96 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_EVDO, BAND_D, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)
/* 97 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_CONTEXT_EVDO, BAND_E, MAX_BAND_NUM, TX_DPD_PA_CONTEXT_T, 1, NULL)

        /** Tx PA gain frequency and temperature compensation cal data*/
/* 98 */ NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_1XRTT, BAND_A, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 99 */ NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_1XRTT, BAND_B, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 100 */NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_1XRTT, BAND_C, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 101 */NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_1XRTT, BAND_D, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 102 */NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_1XRTT, BAND_E, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 103 */NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_EVDO, BAND_A, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 104 */NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_EVDO, BAND_B, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 105 */NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_EVDO, BAND_C, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 106 */NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_EVDO, BAND_D, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)
/* 107 */NVRAM_ITEM_RF_CAL(TX_APT_PA_GAIN_COMP_EVDO, BAND_E, MAX_BAND_NUM, TX_APT_PA_GAIN_COMP_T, 1, NULL)

/* 108 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_1XRTT, BAND_A, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 109 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_1XRTT, BAND_B, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 110 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_1XRTT, BAND_C, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 111 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_1XRTT, BAND_D, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 112 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_1XRTT, BAND_E, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 113 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_EVDO, BAND_A, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 114 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_EVDO, BAND_B, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 115 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_EVDO, BAND_C, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 116 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_EVDO, BAND_D, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)
/* 117 */NVRAM_ITEM_RF_CAL(TX_DPD_PA_GAIN_COMP_EVDO, BAND_E, MAX_BAND_NUM, TX_DPD_PA_GAIN_COMP_T, 1, NULL)


/* 118 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_1XRTT, BAND_A, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 119 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_1XRTT, BAND_B, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 120 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_1XRTT, BAND_C, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 121 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_1XRTT, BAND_D, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 122 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_1XRTT, BAND_E, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 123 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_EVDO, BAND_A, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 124 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_EVDO, BAND_B, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 125 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_EVDO, BAND_C, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 126 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_EVDO, BAND_D, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)
/* 127 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_EVDO, BAND_E, MAX_BAND_NUM, DET_COUPLE_LOSS_T, 1, NULL)

/* 128 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_1XRTT, BAND_A, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 129 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_1XRTT, BAND_B, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 130 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_1XRTT, BAND_C, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 131 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_1XRTT, BAND_D, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 132 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_1XRTT, BAND_E, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 133 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_EVDO, BAND_A, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 134 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_EVDO, BAND_B, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 135 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_EVDO, BAND_C, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 136 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_EVDO, BAND_D, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)
/* 137 */NVRAM_ITEM_RF_CAL(DET_COUPLE_LOSS_COMP_EVDO, BAND_E, MAX_BAND_NUM, DET_COUPLE_LOSS_COMP_T, 1, NULL)

        /** Rx pathloss compensation cal data in high power mode*/
/* 148 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_HPM, BAND_A, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 149 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_HPM, BAND_B, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 150 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_HPM, BAND_C, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 151 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_HPM, BAND_D, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 152 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_HPM, BAND_E, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 153 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_LPM, BAND_A, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 154 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_LPM, BAND_B, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 155 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_LPM, BAND_C, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 156 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_LPM, BAND_D, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 157 */NVRAM_ITEM_RF_CAL(MAIN_RX_PATH_LOSS_LPM, BAND_E, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)

/* 168 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_HPM, BAND_A, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 169 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_HPM, BAND_B, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 170 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_HPM, BAND_C, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 171 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_HPM, BAND_D, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 172 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_HPM, BAND_E, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 173 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_LPM, BAND_A, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 174 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_LPM, BAND_B, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 175 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_LPM, BAND_C, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 176 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_LPM, BAND_D, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 177 */NVRAM_ITEM_RF_CAL(DIV_RX_PATH_LOSS_LPM, BAND_E, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)

/* 188 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_HPM, BAND_A, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 189 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_HPM, BAND_B, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 190 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_HPM, BAND_C, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 191 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_HPM, BAND_D, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 192 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_HPM, BAND_E, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 193 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_LPM, BAND_A, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 194 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_LPM, BAND_B, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 195 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_LPM, BAND_C, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 196 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_LPM, BAND_D, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)
/* 197 */NVRAM_ITEM_RF_CAL(SHDR_RX_PATH_LOSS_LPM, BAND_E, MAX_BAND_NUM, RX_PATH_LOSS_COMP_T, 1, NULL)

/* 198 */NVRAM_ITEM_RF_CAL(AGPS_GROUP_DELAY, BAND_A, MAX_BAND_NUM, AGPS_GROUP_DELAY_T, 1, NULL)
/* 199 */NVRAM_ITEM_RF_CAL(AGPS_GROUP_DELAY, BAND_B, MAX_BAND_NUM, AGPS_GROUP_DELAY_T, 1, NULL)
/* 200 */NVRAM_ITEM_RF_CAL(AGPS_GROUP_DELAY, BAND_C, MAX_BAND_NUM, AGPS_GROUP_DELAY_T, 1, NULL)
/* 201 */NVRAM_ITEM_RF_CAL(AGPS_GROUP_DELAY, BAND_D, MAX_BAND_NUM, AGPS_GROUP_DELAY_T, 1, NULL)
/* 202 */NVRAM_ITEM_RF_CAL(AGPS_GROUP_DELAY, BAND_E, MAX_BAND_NUM, AGPS_GROUP_DELAY_T, 1, NULL)

/* 213 */NVRAM_ITEM_RF_POC(POC_FINAL, BAND_A, MAX_BAND_NUM, POC_FINAL_T, 1, NULL)
/* 214 */NVRAM_ITEM_RF_POC(POC_FINAL, BAND_B, MAX_BAND_NUM, POC_FINAL_T, 1, NULL)
/* 215 */NVRAM_ITEM_RF_POC(POC_FINAL, BAND_C, MAX_BAND_NUM, POC_FINAL_T, 1, NULL)
/* 216 */NVRAM_ITEM_RF_POC(POC_FINAL, BAND_D, MAX_BAND_NUM, POC_FINAL_T, 1, NULL)
/* 217 */NVRAM_ITEM_RF_POC(POC_FINAL, BAND_E, MAX_BAND_NUM, POC_FINAL_T, 1, NULL)

///TODO: TAS
/***
C2K_CUSTOM_TAS_FEATURE_BY_RAT_T			CL1D_RF_	TAS_FEATURE_BY_RAT_T
C2K_CUSTOM_TAS_FE_ROUTE_DATABASE_T		CL1D_RF_	TAS_FE_ROUTE_DATABASE_T
C2K_CUSTOM_TAS_FE_CAT_A_T					CL1D_RF_	TAS_FE_CAT_A_T
C2K_CUSTOM_TAS_FE_CAT_B_T					CL1D_RF_	TAS_FE_CAT_B_T
C2K_CUSTOM_TAS_FE_CAT_C_T					CL1D_RF_	TAS_FE_CAT_C_T
C2K_TUNER_FE_ROUTE_TABLE					CL1D_RF_	TUNER_FE_ROUTE_TABLE
C2K_CUSTOM_TUNER_BAND_T						CL1D_RF_	TUNER_BAND_T
C2K_CUSTOM_TAS_CFG_T

MIPI_EVENT_TABLE_T
MIPI_DATA_SUBBAND_TABLE_T
***/
/*** TAS BPI ***//* VAR */
/* 218 */NVRAM_ITEM_RF_TAS_VAR(CUST_TAS_FEATURE, , 1, TAS_FEATURE_BY_RAT_T, 1, NULL)
/* 219 */NVRAM_ITEM_RF_TAS_VAR(CUST_TAS_FE_ROUTE_DATABASE, , 1, TAS_FE_ROUTE_DATABASE_T, 1, NULL)
/* 220 */NVRAM_ITEM_RF_TAS_VAR(CUST_TAS_FE_CAT_A, , 1, TAS_FE_CAT_A_T, 1, NULL)
/* 221 */NVRAM_ITEM_RF_TAS_VAR(CUST_TAS_FE_CAT_B, , 1, TAS_FE_CAT_B_T, 1, NULL)
/* 222 */NVRAM_ITEM_RF_TAS_VAR(CUST_TAS_FE_CAT_C, , 1, TAS_FE_CAT_C_T, 1, NULL)
/* 223 */NVRAM_ITEM_RF_TAS_VAR(CUST_TUNER_FE_ROUTE_TABLE, , 1, TUNER_FE_ROUTE_TABLE, 1, NULL)
/* 224 */NVRAM_ITEM_RF_TAS_VAR(CUST_TUNER, BAND_A, MAX_BAND_NUM, TUNER_BAND_T, 1, NULL)
/* 225 */NVRAM_ITEM_RF_TAS_VAR(CUST_TUNER, BAND_B, MAX_BAND_NUM, TUNER_BAND_T, 1, NULL)
/* 226 */NVRAM_ITEM_RF_TAS_VAR(CUST_TUNER, BAND_C, MAX_BAND_NUM, TUNER_BAND_T, 1, NULL)
/* 227 */NVRAM_ITEM_RF_TAS_VAR(CUST_TUNER, BAND_D, MAX_BAND_NUM, TUNER_BAND_T, 1, NULL)
/* 228 */NVRAM_ITEM_RF_TAS_VAR(CUST_TUNER, BAND_E, MAX_BAND_NUM, TUNER_BAND_T, 1, NULL)

/*** TAS MIPI ***//* ARRAY */
/* 229 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_EVENT, BAND_A, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 230 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_EVENT, BAND_B, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 231 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_EVENT, BAND_C, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 232 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_EVENT, BAND_D, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 233 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_EVENT, BAND_E, MAX_BAND_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 234 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_DATA, BAND_A, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 235 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_DATA, BAND_B, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 236 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_DATA, BAND_C, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 237 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_DATA, BAND_D, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 238 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TUNER_ROUTE_DATA, BAND_E, MAX_BAND_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)

/* 239 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_A, Route0, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 240 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_A, Route1, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 241 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_A, Route2, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 242 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_A, Route3, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 243 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_A, Route0, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 244 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_A, Route1, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 245 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_A, Route2, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 246 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_A, Route3, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)

/* 247 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_B, Route0, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 248 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_B, Route1, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 249 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_B, Route2, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 250 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_B, Route3, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 251 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_B, Route0, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 252 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_B, Route1, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 253 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_B, Route2, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 254 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_B, Route3, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)

/* 255 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_C, Route0, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 256 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_C, Route1, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 257 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_C, Route2, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 258 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_EVENT_CAT_C, Route3, MAX_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_TAS_EVENT_MAX_NUM, NULL)
/* 259 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_C, Route0, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 260 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_C, Route1, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 261 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_C, Route2, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)
/* 262 */NVRAM_ITEM_RF_TAS_ARRAY(CUST_TAS_DATA_CAT_C, Route3, MAX_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_TAS_DATA_MAX_NUM, NULL)

/**ELNA**/
/*ELNA config&bpi data*/
/* 264 */NVRAM_ITEM_ELNA_VAR(CUST_ELNA_CFG, , 1, CUST_ELNA_CFG_T, 1, NULL)

/* 265 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA1, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 266 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA2, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 267 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA3, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 268 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA4, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 269 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA5, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 270 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA6, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 271 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA7, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 272 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA8, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 273 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA9, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 274 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_EVENT, ELNA10, MAX_ELNA_NUM, MIPI_EVENT_TABLE_T, MIPI_ELNA_EVENT_MAX_NUM, NULL)
/* 275 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA1, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 276 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA2, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 277 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA3, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 278 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA4, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 279 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA5, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 280 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA6, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 281 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA7, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 282 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA8, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 283 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA9, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)
/* 284 */NVRAM_ITEM_ELNA_ARRAY(CUST_ELNA_DATA, ELNA10, MAX_ELNA_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_ELNA_DATA_MAX_NUM, NULL)

/**TX POWER**/
/* TX power back off */
/* 285 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_BACK_OFF,BAND_A, MAX_BAND_NUM, TX_POWER_BACK_OFF_T,1,NULL)
/* 286 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_BACK_OFF,BAND_B, MAX_BAND_NUM, TX_POWER_BACK_OFF_T,1,NULL)
/* 287 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_BACK_OFF,BAND_C, MAX_BAND_NUM, TX_POWER_BACK_OFF_T,1,NULL)
/* 288 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_BACK_OFF,BAND_D, MAX_BAND_NUM, TX_POWER_BACK_OFF_T,1,NULL)
/* 289 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_BACK_OFF,BAND_E, MAX_BAND_NUM, TX_POWER_BACK_OFF_T,1,NULL)
/* TX power offset */
#if defined(__TX_POWER_OFFSET_SUPPORT__)  
/* 290 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_OFFSET,BAND_A, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
/* 291 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_OFFSET,BAND_B, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
/* 292 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_OFFSET,BAND_C, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
/* 293 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_OFFSET,BAND_D, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
/* 294 */NVRAM_ITEM_TX_POWER_VAR(TX_POWER_OFFSET,BAND_E, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
#endif
/*TAS TST*/
/* 295 */NVRAM_ITEM_RF_TAS_TST(TAS_TST_CONFIG, , 1, TAS_TST_CONFIG_T, 1, NULL)
#if IS_C2K_DAT_RFD_CTRL_EN
/* DAT */
/* 296 */NVRAM_ITEM_RF_TAS_VAR(DAT_FE_ROUTE_DATABASE, , 1, DAT_FE_ROUTE_DATABASE_T, 1, NULL)
/* 297 */NVRAM_ITEM_RF_TAS_VAR(DAT_FE_CAT_A_DATABASE, , 1, DAT_FE_CAT_A_T, 1, NULL)
/* 298 */NVRAM_ITEM_RF_TAS_VAR(DAT_FE_CAT_B_DATABASE, , 1, DAT_FE_CAT_B_T, 1, NULL)

/* 299 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route0, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 300 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route1, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 301 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route2, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 302 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route3, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 303 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route4, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 304 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route5, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 305 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route6, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 306 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route7, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 307 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route8, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 308 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_A, DAT_CAT_A_Route9, MAX_DAT_CAT_A_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)

/* 309 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route0, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 310 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route1, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 311 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route2, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 312 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route3, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 313 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route4, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 314 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route5, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 315 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route6, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 316 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route7, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 317 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route8, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 318 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_A, DAT_CAT_A_Route9, MAX_DAT_CAT_A_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)

/* 319 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route0, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 320 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route1, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 321 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route2, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 322 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route3, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 323 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route4, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 324 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route5, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 325 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route6, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 326 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route7, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 327 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route8, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 328 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route9, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 329 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route10, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 330 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route11, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 331 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route12, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 332 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route13, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 333 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route14, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 334 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route15, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 335 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route16, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 336 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route17, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 337 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route18, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 338 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route19, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 339 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route20, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 340 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route21, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 341 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route22, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 342 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route23, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 343 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route24, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 344 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route25, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 345 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route26, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 346 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route27, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 347 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route28, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 348 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route29, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 349 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route30, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 350 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route31, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 351 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route32, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 352 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route33, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 353 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route34, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 354 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route35, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 355 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route36, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 356 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route37, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 357 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route38, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)
/* 358 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_EVENT_CAT_B, DAT_CAT_B_Route39, MAX_DAT_CAT_B_Route_NUM, MIPI_EVENT_TABLE_T, MIPI_DAT_EVENT_MAX_NUM, NULL)

/* 369 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route0, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 370 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route1, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 371 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route2, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 372 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route3, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 373 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route4, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 374 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route5, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 375 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route6, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 376 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route7, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 377 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route8, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 378 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route9, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 379 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route10, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 380 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route11, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 381 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route12, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 382 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route13, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 383 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route14, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 384 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route15, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 385 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route16, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 386 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route17, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 387 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route18, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 388 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route19, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 389 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route20, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 390 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route21, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 391 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route22, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 392 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route23, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 393 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route24, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 394 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route25, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 395 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route26, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 396 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route27, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 397 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route28, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 398 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route29, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 399 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route30, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 400 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route31, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 401 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route32, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 402 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route33, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 403 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route34, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 404 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route35, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 405 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route36, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 406 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route37, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 407 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route38, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
/* 408 */NVRAM_ITEM_RF_TAS_ARRAY(DAT_MIPI_DATA_CAT_B, DAT_CAT_B_Route39, MAX_DAT_CAT_B_Route_NUM, MIPI_DATA_SUBBAND_TABLE_T, MIPI_DAT_DATA_MAX_NUM, NULL)
#endif 
/* SAR TX power offset */
#if defined(__SAR_TX_POWER_BACKOFF_SUPPORT__)   
/* 409 */NVRAM_ITEM_TX_POWER_VAR(SAR_TX_POWER_OFFSET,BAND_A, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
/* 410 */NVRAM_ITEM_TX_POWER_VAR(SAR_TX_POWER_OFFSET,BAND_B, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
/* 411 */NVRAM_ITEM_TX_POWER_VAR(SAR_TX_POWER_OFFSET,BAND_C, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
/* 412 */NVRAM_ITEM_TX_POWER_VAR(SAR_TX_POWER_OFFSET,BAND_D, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
/* 413 */NVRAM_ITEM_TX_POWER_VAR(SAR_TX_POWER_OFFSET,BAND_E, MAX_BAND_NUM, SAR_TX_POWER_OFFSET_T,1,NULL)
#endif
/*DPD*/
/* 414 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_1XRTT, BAND_A, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 415 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_1XRTT, BAND_B, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 416 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_1XRTT, BAND_C, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 417 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_1XRTT, BAND_D, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 418 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_1XRTT, BAND_E, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 419 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_EVDO, BAND_A, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 420 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_EVDO, BAND_B, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 421 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_EVDO, BAND_C, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 422 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_EVDO, BAND_D, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 423 */NVRAM_ITEM_RF_POC(TX_DPD_AM_PM_COMP_EVDO, BAND_E, MAX_BAND_NUM, TX_DPD_AM_PM_LUT_DATA_T, 1, NULL)
/* 424 */NVRAM_ITEM_RF_CUST(DPD_COMMON_CTRL, BAND_A, MAX_BAND_NUM, DPD_COMMON_CTRL_T, 1, NULL)
/* 425 */NVRAM_ITEM_RF_CUST(DPD_COMMON_CTRL, BAND_B, MAX_BAND_NUM, DPD_COMMON_CTRL_T, 1, NULL)
/* 426 */NVRAM_ITEM_RF_CUST(DPD_COMMON_CTRL, BAND_C, MAX_BAND_NUM, DPD_COMMON_CTRL_T, 1, NULL)
/* 427 */NVRAM_ITEM_RF_CUST(DPD_COMMON_CTRL, BAND_D, MAX_BAND_NUM, DPD_COMMON_CTRL_T, 1, NULL)
/* 428 */NVRAM_ITEM_RF_CUST(DPD_COMMON_CTRL, BAND_E, MAX_BAND_NUM, DPD_COMMON_CTRL_T, 1, NULL)
/* 429 */NVRAM_ITEM_RF_CUST(PCFE_DPD_OTFC_CUSTOM_PARA, , 1,	PCFE_DPD_OTFC_CUSTOM_PARA_T, 1, NULL)

/* 430 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_1XRTT, BAND_A, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 431 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_1XRTT, BAND_B, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 432 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_1XRTT, BAND_C, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 433 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_1XRTT, BAND_D, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 434 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_1XRTT, BAND_E, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)

/* 435 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_EVDO, BAND_A, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 436 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_EVDO, BAND_B, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 437 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_EVDO, BAND_C, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 438 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_EVDO, BAND_D, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
/* 439 */NVRAM_ITEM_MIPI(MIPI_PA_SECTION_DPD_DATA_EVDO, BAND_E, MAX_BAND_NUM, TPC_SECTION_TABLE_T, MIPI_PA_SECTION_DATA_MAX_NUM, NULL)
