   /* RR */
   /* Begin of RR EM INFO Request enum */
   RR_EM_CELL_SELECT_PARA_INFO = 0, RR_EM_INFO_BEGIN = RR_EM_CELL_SELECT_PARA_INFO,
   RR_EM_CHANNEL_DESCR_INFO = 1,
   RR_EM_CTRL_CHANNEL_DESCR_INFO = 2,
   RR_EM_RACH_CTRL_PARA_INFO = 3,
   RR_EM_LAI_INFO = 4,
   RR_EM_RADIO_LINK_COUNTER_INFO = 5,
   RR_EM_MEASUREMENT_REPORT_INFO = 6,
   /* ZY : Temp solution : Cell allocation list*/
   RR_EM_CA_LIST_INFO = 7,
   /* RR new structure */
   RR_EM_CONTROL_MSG_INFO = 8,
   RR_EM_SI2Q_INFO_STRUCT_INFO = 9,
   RR_EM_MI_INFO_STRUCT_INFO = 10,
   RR_EM_BLK_INFO = 11,
   RR_EM_TBF_INFO = 12,
   RR_EM_GPRS_GENERAL_INFO = 13,
   /* GAS MM EM INFO */
   RRM_EM_FDD_IR_PARAMETER_STATUS_IND_STRUCT_INFO = 14,
   RRM_EM_IR_RESELECT_STATUS_IND_STRUCT_INFO = 15,
   RRM_EM_IR_3G_NEIGHBOR_MEAS_STATUS_IND_STRUCT_INFO = 16,
   RRM_EM_IR_3G_NEIGHBOR_MEAS_INFO_IND_STRUCT_INFO = 17,
   RRM_EM_IR_4G_NEIGHBOR_MEAS_STATUS_IND_STRUCT_INFO = 18,
   RRM_EM_IR_4G_NEIGHBOR_MEAS_INFO_IND_STRUCT_INFO = 19,
   RRM_EM_SERV_CELL_POWER_STATUS_IND_STRUCT_INFO = 20,
   RRM_EM_IR_3G_NEIGHBOR_CELL_STATUS_IND_STRUCT_INFO = 21,
   RRM_EM_IR_4G_NEIGHBOR_CELL_STATUS_IND_STRUCT_INFO = 22,
   RRM_EM_TDD_IR_PARAMETER_STATUS_IND_STRUCT_INFO = 23,
   RRM_EM_SUCCESS_RATE_KPI_INFO = 24,
   RRM_EM_MT_T3126_TIMEOUT_INFO = 25,
   RRM_EM_CS_RLF_INFO = 26,
   RRM_EM_RR_STATE_INFO = 27,
   RRM_EM_GAS_SEARCH_INFO = 28,
   RRM_EM_DOWNLINK_SIGNALLING_COUNTER_INFO = 29,
   RRM_EM_RACH_FAIL = 30,
   RRM_EM_N200_EXP = 31,
   RRM_EM_HO_FAIL = 32,
   RRM_EM_OOS_IND = 33,
   RR_EM_INFO_END = RR_EM_INFO_BEGIN + 49,

   /*End of RR EM INFO Request enum*/

   /* CC */
   CC_EM_CHANNEL_INFO = 50,
   CC_EM_CALL_INFO = 51,

   /* SS */
   SS_EM_INFO = 52,

   /* MM */
   MM_EM_INFO = 53,
   /*EM ehancement for RR new structure*/
   MMRR_EM_PLMN_INFO_STRUCT_INFO = 54,

   /* UEM */
   UEM_EM_BATTERY_INFO = 55,

   /* gprs em begins */
   GMM_EM_INFO = 56,
//   TCM_EM_EXT_PDP_INFO,
//   TCM_EM_INT_PDP_INFO,
//   TCM_EM_CONTEXT_INFO, //new
//   SNDCP_EM_INFO,
   LLC_EM_INFO = 57,
   /* PPP , removed because of no use*/
   //PPP_EM_INFO,
   SM_EM_INFO = 58,
   EM_TCM_INFO_IND = 59,

   MMRR_EM_PLMN_LIST_REQ_STRUCT_INFO = 60,
   MMRR_EM_PLMN_LIST_CNF_STRUCT_INFO = 61,
   MMRR_EM_PLMN_SEARCH_REQ_STRUCT_INFO = 62,
   MMRR_EM_PLMN_SEARCH_CNF_STRUCT_INFO = 63,
   MMRR_EM_HPLMN_LIST_INFO = 64,
   MMRR_EM_OPLMN_LIST_INFO = 65,
   MMRR_EM_STATIC_APPLMN_LIST_INFO = 66,
   MMRR_EM_DYNAMIC_APPLMN_LIST_INFO = 67,

    /* VT EM Display, 2007/11/30 */
    /* VT owner comments VT EM enum is not needed in WR8 */
    //VT_EM_CALL_STATE_INFO = 50, VT_EM_BEGIN = VT_EM_CALL_STATE_INFO,/* vt_em_call_state_choice */
    //VT_EM_MASTER_SLAVE_STATUS_INFO,     /* vt_em_master_slave_status_choice */
    //VT_EM_RETRANSMISSION_PROTOCOL_INFO, /* vt_em_retransmission_protocol_choice */
    //VT_EM_INCOMING_AUDIO_CHANNEL_INFO,  /* vt_em_audio_channel_info_struct */
    //VT_EM_OUTGOING_AUDIO_CHANNEL_INFO,  /* vt_em_audio_channel_info_struct */
    //VT_EM_INCOMING_VIDEO_CHANNEL_INFO,  /* vt_em_video_channel_info_struct */
    //VT_EM_OUTGOING_VIDEO_CHANNEL_INFO,  /* vt_em_video_channel_info_struct */
    //VT_EM_ADM_MEM_MAX_USED_INFO,        /* kal_uint32 */
    //VT_EM_STATISTIC_INFO,               /* vt_em_statistic_info_struct */
    //VT_EM_ROUND_TRIP_DELAY_INFO,        /* kal_uint32 */
    //VT_EM_INCOMING_XSRP_INFO,           /* vt_em_incoming_xSRP */
    //VT_EM_OUTGOING_XSRP_INFO,           /* vt_em_outgoing_xSRP */
	//VT_EM_END = VT_EM_OUTGOING_XSRP_INFO,

   /**
    * Gibran 20061228
    * UAS MEME/CSCE measuremnt and cell status structure
    */
   MMRR_EM_PLMN_LOSS_INFO_STRUCT_INFO = 68,
   MMRR_EM_PLMN_SEARCH_CNF_INFO_STRUCT_INFO = 69,
   /* URR common Range 1, from enum 70 to 169.
      it's used for both FDD and TDD */
   FDD_EM_URR_3G_GENERAL_STATUS_IND = 70, URR_EM_INFO_BEGIN = FDD_EM_URR_3G_GENERAL_STATUS_IND,
   /* Put 1st XXX_STATUS_IND_STRUCT_INFO in front of XXX_EM_INFO_BEGIN
      in order to show enum_name in XXX_STATUS_IND_STRUCT_INFO not in XXX_EM_INFO_BEGIN. */

   EM_SIBE_3G_SIB_IND_STRUCT_INFO = 71,
   TDD_EM_URR_3G_GENERAL_STATUS_IND = 72,
   FDD_EM_CSCE_SERV_CELL_IND_STRUCT_INFO = 75,
   FDD_EM_CSCE_NEIGH_CELL_IND_STRUCT_INFO = 76,
   FDD_EM_CSCE_R_STATUS_IND_STRUCT_INFO = 77,
   FDD_EM_CSCE_H_STATUS_IND_STRUCT_INFO = 78,
   FDD_EM_CSCE_APBCR_STATUS_IND_STRUCT_INFO = 79,
   FDD_EM_CSCE_MEAS_RULE_STATUS_IND_STRUCT_INFO = 80,
   FDD_EM_CSCE_MULTIPLE_PLMN_IND_STRUCT_INFO = 81,
   TDD_EM_CSCE_SERV_CELL_IND_STRUCT_INFO = 82,
   TDD_EM_CSCE_NEIGH_CELL_IND_STRUCT_INFO = 83,
   TDD_EM_CSCE_R_STATUS_IND_STRUCT_INFO = 84,
   TDD_EM_CSCE_H_STATUS_IND_STRUCT_INFO = 85,
   TDD_EM_CSCE_APBCR_STATUS_IND_STRUCT_INFO = 86,
   TDD_EM_CSCE_MEAS_RULE_STATUS_IND_STRUCT_INFO = 87,
   TDD_EM_CSCE_MULTIPLE_PLMN_IND_STRUCT_INFO = 88,

    /*SIM*/
   EM_SIM_MONITOR_EVENT_INFO = 89,

   EM_TDD_MEME_INFO_DCH_UMTS_CELL_INFO = 90, TDD_MEME_EM_INFO_BEGIN = EM_TDD_MEME_INFO_DCH_UMTS_CELL_INFO,
   EM_TDD_MEME_INFO_DCH_GSM_CELL_INFO = 91,
   EM_TDD_MEME_INFO_DCH_LTE_CELL_INFO = 92,
   EM_TDD_MEME_INFO_EVENT_TYPE_1_PARAMETER_STRUCT_INFO = 93,
   EM_TDD_MEME_INFO_EVENT_TYPE_2_PARAMETER_STRUCT_INFO = 94,
   EM_TDD_MEME_INFO_EVENT_TYPE_3_PARAMETER_STRUCT_INFO =95,
//   EM_MEME_INFO_EVENT_TYPE_4_PARAMETER_STRUCT_INFO,
//   EM_MEME_INFO_EVENT_TYPE_5_PARAMETER_STRUCT_INFO,
//   EM_MEME_INFO_EVENT_TYPE_6_PARAMETER_STRUCT_INFO,
//   EM_MEME_INFO_DCH_H_SERVING_CELL_INFO,
//   EM_TDD_MEME_INFO_DCH_3G_BLER_INFO = 96,
   EM_TDD_MEME_INFO_GSM_CELL_INFO =97, //for CMCC FT Tool
   EM_TDD_MEME_INFO_LTE_CELL_INFO =98, //for CMCC FT Tool
//   EM_MEME_INFO_FACH_LTE_CELL_INFO = 100,
   EM_TDD_MEME_INFO_REPORT_INFO = 99,
   TDD_MEME_EM_INFO_END = TDD_MEME_EM_INFO_BEGIN + 15,

   /* Call Information */
   EM_CALL_INFO_IND = 106,

   /* SIP Information */
   EM_IMC_SIP_INFO_IND = 107,

   MMRF_EM_MIPI_HW_INFO = 108,

   EM_RRCE_TGPS_STATUS_IND= 110,
   EM_SLCE_SRNCID_STATUS_IND= 111,

   /* WO: 112 ~ 129 */
   EM_WO_INFO_BEGIN = 112,
   EM_WO_IKE_SRCPORT_INFO = EM_WO_INFO_BEGIN,
   EM_WO_IKE_NATT_SRCPORT_INFO = 113,
   EM_WO_IKE_DECRYPT_INFO_ADD = 114,
   EM_WO_IKE_DECRYPT_INFO_DEL = 115,
   EM_WO_ESP_DECRYPT_INFO_ADD = 116,
   EM_WO_ESP_DECRYPT_INFO_DEL = 117,
   EM_WO_DPD_INTERVAL_INFO = 118,
   EM_WO_INFO_END = EM_WO_INFO_BEGIN + 17,

   EM_UAS_3G_TDD128_HANDOVER_SEQUENCE_IND = 130,

   EM_RRCE_3G4_REDIR_EVENT = 131,
   EM_RRCE_KPI_STATUS_IND = 132,
   TDD_EM_RRCE_CONN_STATUS_IND = 133,

   /* SIM */
   EM_SIM_APDU_INFO = 135,

   EM_SLCE_PS_DATA_RATE_STATUS_IND = 140,
   EM_RRCE_NW_PEER_MSG_INFO = 150,
   EM_RRCE_RACH_FAIL_IND = 151,
   EM_RRCE_MO_RLF_IND = 152,
   EM_RRCE_3G3_HO_FAIL_IND = 153,
   EM_RRCE_3G2_HO_FAIL_IND = 154,
   EM_RRCE_DCH_STATE_CONFIGURATION_STATUS_IND = 155,
   EM_RRCE_FACH_STATE_CONFIGURATION_STATUS_IND = 156,
   EM_RRCE_CS_OVER_HSPA_STATUS_IND = 157,
   EM_RRCE_3G_SECURITY_CONFIGURATION_INFO_IND = 158,
   EM_RRCE_FD_CONFIGURATION_STATUS_IND = 159,
   EM_RRCE_HSPA_CONFIG_IND = 160,   /* MOLY00100048, Jack Chu,  EM_RRCE_HSPA_CONFIG_IND == 160 */
   EM_RRCE_RLF_IND = 161,  /* __ALPS02506878_SUPPORT__ */
   EM_RRCE_3G_CELL_UARFCN_DL_UL_INFO_IND = 162,
   URR_EM_INFO_END = EM_RRCE_3G_CELL_UARFCN_DL_UL_INFO_IND,

   /* LBS: 163 ~ 169 */
   EM_LBS_BEGIN = 163,
   EM_LBS_GPS_OPEN_STATISTIC = EM_LBS_BEGIN,
   EM_LBS_LR_STATISTIC = 164,
   EM_LBS_AP_SETTING = 165,
   EM_LBS_END = 169,

   /* __UL1_EM_MODE__ */
   UL1_EM_HS_DSCH_CONFIGURATION_INFO = 170, UL1_EM_INFO_BEGIN = UL1_EM_HS_DSCH_CONFIGURATION_INFO,
   UL1_EM_EDCH_CONFIGURATION_INFO = 171,
   UL1_EM_CPC_CONFIGURATION_INFO = 172,
   UL1_EM_SECONDARY_HS_CONFIGURATION_STATUS_INFO = 173,
   UL1_EM_PRIMARY_HS_DSCH_BLER_INFO = 174,
   UL1_EM_SECONDARY_HS_DSCH_BLER_INFO = 175,
   UL1_EM_EDCH_ACK_RATE_INFO = 176,   UL1_EM_INFO_END = UL1_EM_EDCH_ACK_RATE_INFO,  /* for backward compatibility */
   UL1_EM_PRX_DRX_MEASUREMENT_INFO = 177,
   /* HSDSCH info group  */
   UL1_EM_HSPA_INFO_GROUP = 178,
   UL1_EM_TAS_INFO = 179,
   UL1_EM_RADIO_LINK_SYNC_STATUS = 180,
   UL1_EM_UL1_RXD_STATUS = 181, /* already ported */
   UL1_EM_UL1_RAS_INFO = 182,
   UL1_EM_FS_UARFCN_INFO = 184,
   

   /* __UL2_EM_MODE__ */
   UL2_EM_ADM_POOL_STATUS_IND_STRUCT_INFO = 185, UL2_EM_INFO_BEGIN = UL2_EM_ADM_POOL_STATUS_IND_STRUCT_INFO,
   UL2_EM_PS_DATA_RATE_STATUS_IND_STRUCT_INFO = 186,
   UL2_EM_HSDSCH_RECONFIG_STATUS_IND_STRUCT_INFO = 187,
   UL2_EM_URLC_EVENT_STATUS_IND_STRUCT_INFO = 188,
   UL2_EM_3G_BLER_IND_STRUCT_INFO = 189,
   UL2_EM_WCDMA_RLC_STATS_STRUCT_INFO = 190,
   UL2_EM_URLC_LAYER_TPUT_INFO = 191,
   /* UMAC new EM Arch */
   /***HSUPA SI***/
   UL2_EM_HSUPA_SI_IND_STRUCT_INFO = 192,
   /***HSUPA SI***/

   /* UMAC EM 2015 */
   UL2_EM_UMAC_DCH_INFO = 193,
   UL2_EM_UMAC_EDCH_INFO = 194,
   UL2_EM_UMAC_HSDSCH_INFO = 195,
   UL2_EM_URLC_ATT_RLC_STATISTICS_INFO = 196,
   UL2_EM_URLC_ATT_RLC_RESET_INFO = 197,
   UL2_EM_UMAC_PCH_CRC_ERR_INFO = 198,
   UL2_EM_UMAC_PCH_INFO = 199,
   UL2_EM_UMAC_LCHID_TRCH_MAPPING_INFO = 200,
   UL2_EM_INFO_END = UL2_EM_UMAC_LCHID_TRCH_MAPPING_INFO,

   /*ERRC_EM_MODE, here is the start of errc em info definition*/
   ERRC_EM_MOB_MEAS_INTRARAT_INFO = 210, ERRC_EM_INFO_BEGIN = ERRC_EM_MOB_MEAS_INTRARAT_INFO,
   ERRC_EM_MOB_MEAS_INTERRAT_UTRAN_INFO = 211,
   ERRC_EM_MOB_MEAS_INTERRAT_GERAN_INFO = 212,
   ERRC_EM_AUTOS_CSG_INFO = 213,
   ERRC_EM_CARRS_EVENT_IND = 214,
   ERRC_EM_SIB_EVENT_IND = 215,
   ERRC_EM_MOB_EVENT_IND = 216,
   ERRC_EM_SEC_PARAM = 217,
   ERRC_EM_REEST_INFO = 218,
   ERRC_EM_RECONF_INFO = 219,
   ERRC_EM_RCM_SIM_STS_INFO = 220,
   ERRC_EM_SYS_SIB_RX_STS_INFO = 221,
   ERRC_EM_ERRC_STATE_IND = 222,
   ERRC_EM_OVER_PROC_DELAY_WARNING = 223,
   ERRC_EM_LTE_SUPPORTED_BAND_INFO = 224,
   ERRC_EM_ERRC_KPI_INFO = 225,
   ERRC_EM_ERRC_CONFIG_INFO = 226,

   ERRC_EM_CONN_INFO = 227,

   ERRC_EM_INFO_END = ERRC_EM_CONN_INFO,

   /* __ESM_EM_MODE__ */
   ESM_ESM_INFO = 228,
   ESM_L4C_ESM_INFO = 229,

   /* __EMM_EM_MODE__*/
   EMM_EM_SEC_INFO = 230, EMM_EM_INFO_BEGIN = EMM_EM_SEC_INFO,
   EMM_EM_PLMNSEL_INFO = 231,
   EMM_EM_CONN_INFO = 232,
   EMM_EM_NASMSG_INFO = 233,
   EMM_EM_CALL_INFO = 234,
   EMM_EM_REG_ATTACH_INFO = 235,
   EMM_EM_REG_DETACH_INFO = 236,
   EMM_EM_REG_TAU_INFO = 237,
   EMM_EM_REG_COMMON_INFO = 238,
   EMM_EM_SV_INFO = 239,
   EMM_EM_RATBAND_INFO = 240,
   EMM_EM_TIMERSRV_INFO = 241,
   EMM_EM_USIMSRV_INFO = 242,
   EMM_EM_NVMSRV_INFO = 243,
   EMM_EM_INFO_END = EMM_EM_NVMSRV_INFO,

   EMM_L4C_EMM_INFO = 244,

   EM_EL2_OV_STATUS = 245,
   EM_EL1_OV_STATUS = 246,
   EM_QBM_STATUS = 247,
   EM_UPCM_STATUS = 248,

   /* EL1 */
   EM_EL1_INFO = 249,

   EM_CSR_STATUS_IND = 250,

   RAC_EM_INFO = 251,

   /* EL2 public status */
   EM_EL2_PUB_STATUS = 252,

   EMM_L4C_LAI_CHANGE_INFO = 253,

   /*RATCM*/
   RATCM_EM_23G_RAT_CHANGE_IND = 254, RATCM_EM_INFO_BEGIN = RATCM_EM_23G_RAT_CHANGE_IND,

   EM_EL1_B3B39_INFO = 255,

   RATCM_EM_INFO_END = RATCM_EM_INFO_BEGIN + 20,

   /* L4C */
   EM_L4C_RAT_CHANGE_IND = 275,

   /* EMAC RACH */
   EM_EMAC_RACH_TRIGGER = 276,
   EM_EMAC_RACH_FINISH = 277,
   EM_EMAC_MSG2_REPORT = 278,
   EM_EMAC_MSG4_REPORT = 279,

   /* EMAC 500MS */
   EM_EMAC_OV_STATUS_500 = 280,

   /* EMAC TIMER EXPIRE */
   EM_EMAC_TIMER_EXPIRE = 281,

   EM_L4C_MDMI_RAT_INFO_IND = 282,

   /* EMAC CONFIG REPORT */
   EM_EMAC_CONFIG_REPORT = 283,

   /* MD EVENT INFO */
   EM_L4C_MD_EVENT_INFO = 284,

  /*EMAC RACH for Innowireless EM*/
   EM_EMAC_RACH_SUCCESS = 285,
   EM_EMAC_RACH_FAILURE = 286,

   /* EMAC EMBMS */
   EM_EMAC_EMBMS_REPORT = 287,

   /* EMAC DL TBS REPORT */
   EM_EMAC_DL_TBS_REPORT = 288,

   /* EMM CSFB status */
   EMM_L4C_CSFB_INFO = 289,

   /* EL1 CIQ for ATT*/
   EM_EL1_CIQ_RLF_STATUS_INFO        = 290, EM_EL1_CIQ_INFO_BEGIN = EM_EL1_CIQ_RLF_STATUS_INFO,
   EM_EL1_CIQ_PUSCH_INFO             = 291,
   EM_EL1_CIQ_INFO_END               = EM_EL1_CIQ_INFO_BEGIN + 10,

   /* L4C EM to report ECSQ params */
   EM_L4C_ECSQ_IND = 301,
  

   /*SMS EM to indicate MT SMS is received over  LTE/IMS domain*/
    EM_MT_SMS_OVER_IMS_INFO = 303,
    MM_EM_MOCS_MOCSFB_STATUS = 306,
     /* MM/GMM */
    MM_EM_MM_GMM_PROC_REJ_INFO = 307,
    EM_MO_SMS_OVER_IMS_INFO = 310,
   /* RAC EM to report REG state */
   RAC_EM_REG_STATE_INFO = 311,

   /* As UL2 EM space is exhausted in common file */
   UL2_EM_UMAC_RACH_FAILURE_INFO = 312,



   /* IPCORE */
   IPC_EM_UL_THROTTLE_STATUS = 326,

   /*ERRC_EM_MODE, here is the start of errc em info definition of Range 2*/
   ERRC_EM_SERV_IR_NEIGHBOR_INFO = 327, ERRC_EM_INFO_BEGIN_R2 = ERRC_EM_SERV_IR_NEIGHBOR_INFO,
   ERRC_EM_IR_REDIR_EVENT = 328,
   ERRC_EM_IRAT_MEAS_CFG = 329,
   ERRC_EM_MOB_MEAS_CONFIG_INFO_IND = 330,
   ERRC_EM_MOB_MEAS_REPORT_INFO_IND = 331,
   ERRC_EM_MOB_MEAS_INTERRAT_C2K_INFO = 332,
   ERRC_EM_LTE_RRC_STATE_IND = 333,
   ERRC_EM_SERVING_INFO = 334,
   ERRC_EM_PAGING_FAIL = 335,
   ERRC_EM_RLF_EVENT = 336,
   ERRC_EM_TIMER_EXPIRY_EVENT = 337,
   ERRC_EM_HO_EVENT = 338,
   ERRC_EM_ERRC_SYS_MIB_SIB_READEVENT_INFO = 339,
   ERRC_EM_SRVCC_BSIC_INFO = 340,
   ERRC_EM_MFROM_INFO = 341,
   ERRC_EM_FEATURE_DETECTION = 342,
   ERRC_EM_SEARCHING_STATE = 343,
   ERRC_EM_CA_INFO = 344,
   ERRC_EM_EUTRA_RRC_MESSAGE_S = 345,
   ERRC_EM_EUTRA_RRC_MESSAGE_M = 346,
   ERRC_EM_EUTRA_RRC_MESSAGE_L = 347,
   ERRC_EM_LTE_BAND_TIME = 348,
   ERRC_EM_REEST_BY_L2 = 349,
   ERRC_EM_EL1_CONFIG_INFO = 350,
   ERRC_EM_SRVCC_CELL_INFO = 351, 
   ERRC_EM_SRVCC_HO_FAIL_EVENT =352,
   ERRC_EM_OOS_EVENT = 353,
   ERRC_EM_CELL_BLACK_LIST_EVENT = 354,
   ERRC_EM_HO_FAIL_EVENT = 357,
   ERRC_EM_INFO_END_R2 = ERRC_EM_HO_FAIL_EVENT,
   ERRC_EM_INFO_END_RESERVED = ERRC_EM_INFO_BEGIN_R2 + 30,

   /* UPCM */
   EM_UPCM_PS_TPUT_INFO = 358,

   MM_EM_MTC_TIMER_INFO = 359,
   MM_EM_LU_INFO = 360,
   MM_EM_RAU_INFO = 361,

   /* USIME capability */
   USIME_EM_INFO_CAPABILITY = 362, USIME_EM_INFO_BEGIN = USIME_EM_INFO_CAPABILITY,
   USIME_EM_INFO_END = USIME_EM_INFO_BEGIN + 30,

   MM_EM_MT_CSFB_INFO = 393,
   MM_EM_REG_REJ_INFO = 394,        // LU, Attach, RAU reject info
   MM_EM_AUTH_REJ_INFO = 395,       // Auth reject info for MM/GMM
   MM_EM_AS_FAIL_INFO = 396,    	// AS fail info during REG proc

   /* EL2 feature detection */
   EM_EL2_FEATURE_DETECTION = 397,

   MM_EM_CSFB_STATUS = 398,         // CSFB START /SUCCESSFUL /FAIL 
   MM_EM_MTCS_MTCSFB_STATUS = 399,  //MTCS MT CSFB FAILURES
   
   /*ERRC_EM_MODE, here is the start of errc em info definition of Range 3*/
   ERRC_EM_CONNECTTIME_EVENT = 406, ERRC_EM_INFO_BEGIN_R3 = ERRC_EM_CONNECTTIME_EVENT,
   ERRC_EM_CONNECTFAIL_EVENT = 407,
   ERRC_EM_INFO_END_R3 = ERRC_EM_CONNECTFAIL_EVENT,
   ERRC_EM_INFO_END_RESERVED_R3 = ERRC_EM_INFO_BEGIN_R3 + 23,
 

   /* FDD URR common Range 2, the range should be 430 ~ 599 */
   /* FDD CSCE Range 2 */
   FDD_CSCE_EM_INFO_BEGIN_R2 = 430, FDD_URR_EM_INFO_BEGIN_R2 = FDD_CSCE_EM_INFO_BEGIN_R2,
   FDD_CSCE_EM_INFO_END_R2 = 449,
   /* FDD RRCE Range 2 */
   FDD_RRCE_EM_INFO_BEGIN_R2 = 450,
   FDD_RRCE_EM_INFO_END_R2 = 499,
   /* FDD MEME Range 2 */
   EM_FDD_MEME_INFO_DCH_UMTS_CELL_INFO = 500, FDD_MEME_EM_INFO_BEGIN_R2 = EM_FDD_MEME_INFO_DCH_UMTS_CELL_INFO,
   EM_FDD_MEME_INFO_DCH_GSM_CELL_INFO = 501,
   EM_FDD_MEME_INFO_DCH_LTE_CELL_INFO = 502,
   EM_FDD_MEME_INFO_DCH_H_SERVING_CELL_INFO = 503,
   EM_FDD_MEME_INFO_DCH_3G_BLER_INFO = 504,
   EM_FDD_MEME_INFO_FACH_LTE_CELL_INFO = 505,
   EM_FDD_MEME_INFO_EVENT_TYPE_3_PARAMETER_INFO = 506,        // For NVIOT EM MeasCtrl E3x
   EM_FDD_MEME_INFO_REPORT_INFO = 507,                        // For NVIOT EM MEasRpt E3x
   FDD_MEME_EM_INFO_END_R2 = 549,

   /* FDD SLCE Range 2 */
   FDD_SLCE_EM_INFO_BEGIN_R2 = 550,
   FDD_SLCE_EM_INFO_END_R2 = 559,

   /* FDD SIBE Range 2 */
   FDD_SIBE_EM_INFO_BEGIN_R2 = 560,
   FDD_SIBE_EM_INFO_END_R2 = 569,

   /* for other FDD URR modules, 569 ~ 599 */

   FDD_URR_EM_INFO_END_R2 = 599,


   /* VDM */
   EM_VDM_CALL_INFO_IND = 601,

   /* IMC */
   IMC_EM_IPSEC_INFO_IND = 602, IMC_EM_INFO_BEGIN = IMC_EM_IPSEC_INFO_IND,
   IMC_EM_IMC_INFO_IND = 603,
   IMC_EM_BEARER_INFO_IND = 604,
   IMC_EM_REG_INFO_IND = 605,
   IMC_EM_SMS_INFO_IND = 606,
   IMC_EM_CALL_INFO_IND = 607,
   IMC_EM_CONF_INFO_IND = 608,
   IMC_EM_SRVCC_INFO_IND = 609,
   IMC_EM_PCSCF_INFO_IND = 610,
   IMC_EM_MEDIA_INFO_IND = 611,
   IMC_EM_CALL_DROP_IND = 613,
   IMC_EM_IMS_EVENT_INFO_IND = 615,
   IMC_EM_INFO_END = IMC_EM_INFO_BEGIN + 20,

   /* __EMM_EM_MODE__ Range 2, the range should be 625 ~ 629*/
   EMM_EM_REG_EVENT_INFO = 625, EMM_EM_INFO_RANGE_2_BEGIN = EMM_EM_REG_EVENT_INFO,
   EMM_EM_TIMER_EXPIRY_INFO = 626,
   EMM_EM_EMM_STATE_INFO = 627,
   EMM_EM_SEC_EVENT_INFO = 628,
   EMM_EM_TIMERSRV_TIMER_START_INFO = 629,
   EMM_EM_INFO_RANGE_2_END = EMM_EM_TIMERSRV_TIMER_START_INFO,

   EM_SPEECH_INFO_BEGIN = 630,  EM_SPEECH_INFO_SPH_CODEC = EM_SPEECH_INFO_BEGIN,
   EM_SPEECH_INFO_END = 649,

   /* NWSEL */
   NWSEL_EM_TIMER_INFO = 650,
   NWSEL_EM_INFO_BEGIN = NWSEL_EM_TIMER_INFO,
   NWSEL_EM_PLMN_LIST_REQ_INFO = 651,
   NWSEL_EM_PLMN_LIST_CNF_INFO = 652,
   NWSEL_EM_PLMN_SEARCH_REQ_INFO = 653,
   NWSEL_EM_HPLMN_INFO_INFO = 654,
   NWSEL_EM_OPLMN_INFO_INFO = 655,
   NWSEL_EM_STATIC_APPLMN_INFO = 656,
   NWSEL_EM_DYNAMIC_APPLMN_INFO = 657,
   NWSEL_EM_EUTRAN_DISABLE_INFO = 658,
   NWSEL_EM_INFO_END = NWSEL_EM_INFO_BEGIN+30,

   /* Abnormal event for smart logging phase2 */
   /* Naming format: EM_ABNORMAL_EVENT_(MOD)_(NAME) */
   EM_ABNORMAL_EVENT_RAC_NO_SERVICE = 681,

   /* LTECSR */
   LTECSR_EM_RTP_CODEC = 682,
   LTECSR_EM_RTP_PACKET_LOSS = 683,
   LTECSR_EM_RTP_ONE_WAY_DELAY = 684,
   LTECSR_EM_RTP_JITTER = 685,
   LTECSR_EM_RTP_JITTER_BUFFER_DELAY = 686,
   LTECSR_EM_RTP_OTA_MSG = 687,
   LTECSR_EM_SESSION_STAT = 688,
   LTECSR_EM_XMIT_PKT = 689,
   LTECSR_EM_RECV_PKT = 690,
   LTECSR_EM_XMIT_STAT = 691,
   LTECSR_EM_RECV_STAT = 692,
   LTECSR_EM_RTP_INFO = 693,
   LTECSR_EM_RTCP_INFO = 694,
   LTECSR_EM_RTP_EVENT = 695,

   /* LPP 696 ~699 */
   LPP_EM_MSG_STATUS_STATISTICS = 696,
   LPP_EM_MSG_INFO = 697,
   LPP_EM_INFO_END = 699,
   
   /* TDD URR common Range 2, the range should be 700 ~ 899
      before put TDD URR EM enum below, please make sure relative function already consider the enum range,
      e.g. TDD_RRC_HandleEmUpdateReq() should cover enum 700 ~ 899. */
   TDD_URR_EM_INFO_BEGIN_R2 = 700,
   TDD_URR_EM_INFO_END_R2 = 749,

   /* C2K: 750 ~ 899 */
   EM_C2K_INFO_BEGIN = 750,

   /* C2K EVDO L1 750~769 */
   EM_EVL1_INFO_BEGIN = EM_C2K_INFO_BEGIN,
   EM_EVL1_GENERAL_INFO = EM_EVL1_INFO_BEGIN,
   EM_EVL1_TXAGC_POWER_INFO = 751,
   EM_EVL1_CELL_SWITCH_INFO = 752,
   EM_EVL1_RXAGC_INFO = 753,
   EM_EVL1_AFC_INFO = 754,
   EM_EVL1_MBP_SECTOR_INFO = 755,
   EM_EVL1_FMP_FINGER_INFO = 756,
   EM_EVL1_TIMING_TRACK_STATUS = 757,
   EM_EVL1_SCH_STATUS = 758,
   EM_EVL1_ACC_DATA_RATE_INFO = 759,
   EM_EVL1_TRAFFIC_RRI_VALUE_INFO = 760,
   EM_EVL1_FMP_SECTOR_INFO = 761,
   EM_EVL1_SCH_PILOT_UPDATE_INFO = 762,
   EM_EVL1_SCH_RESULT_INFO = 763,
   EM_EVL1_INFO_END = EM_EVL1_INFO_BEGIN + 19,

   /* XL1: 770 ~ 789 */
   EM_XL1_INFO_BEGIN = 770,
   EM_XL1_STATUS_INFO = EM_XL1_INFO_BEGIN,
   EM_XL1_MEAS_INFO = 771,
   EM_XL1_MAIN_RXAGC_INFO = 772,
   EM_XL1_DIV_RXAGC_INFO = 773,
   EM_XL1_RAKE_INFO = 774,
   EM_XL1_CRC_INFO = 775,
   EM_XL1_TX_PATH_INFO = 776,
   EM_XL1_TX_AGC_INFO = 777,
   EM_XL1_AFC_INFO = 778,
   EM_XL1_MMAFC_INIT_FOE_INFO = 779,
   EM_XL1_TAS_INFO = 780,
   EM_XL1_TIMING_LOOP_INFO = 781,
   EM_XL1_INFO_END = EM_XL1_INFO_BEGIN + 19,

   /* HSC: 790 ~ 809 */
   EM_C2K_HSC_INFO_BEGIN = 790,
   EM_C2K_RTBA_CHANNEL_STATUS_INFO = EM_C2K_HSC_INFO_BEGIN,
   EM_C2K_DO_SPAGE_STATE_INFO = 791,
   EM_C2K_HSC_MPA_STATUS_INFO = 792,
   EM_C2K_LL1A_STATE_MODE_INFO = 793,
   EM_C2K_LL1A_STANDBY_GAP_INFO = 794,
   EM_C2K_LL1A_ACTIVE_GAP_INFO = 795,
   EM_C2K_HSC_INFO_END = EM_C2K_HSC_INFO_BEGIN + 19,

   /* XL3: 810 ~ 824 */
   EM_XL3_INFO_BEGIN = 810,
   EM_XL3_CP_STATUS = EM_XL3_INFO_BEGIN,
   EM_XL3_SLOTTED_MODE_INFO = 811,
   EM_XL3_CP_EVENTS = 812,
   EM_1XRTT_CALL_EVENTS = 813,
   EM_C2K_RSVAS_INFO = 814,
   EM_XL3_PAGING_INFO = 815,
   EM_XL3_SET_INFO = 816,
   EM_XL3_SYSTEM_SEARCH_INFO = 817,
   EM_XL3_CALL_FAIL_REASON = 818,
   EM_XL3_INFO_END = EM_XL3_INFO_BEGIN + 14,

   /* EVL3: 825 ~ 839 */
   EM_EVL3_INFO_BEGIN = 825,
   EM_EVL3_STATE = EM_EVL3_INFO_BEGIN,
   EM_EVL3_SERVING_CELL_INFO = 826,
   EM_EVL3_SLOTTED_MODE_INFO = 827,
   EM_EVL3_ACCESS_PROCEDURE_INFO = 828,
   EM_EVL3_CP_EVENTS = 829,
   EM_EVL3_SYSTEM_SEARCH_INFO = 830,   
   EM_EVL3_INFO_END = EM_EVL3_INFO_BEGIN + 14,

   /* EVL2: 840~849 */
   EM_EVL2_INFO_BEGIN = 840,
   EM_EVL2_FWD_CHANNEL_INFO = EM_EVL2_INFO_BEGIN,
   EM_EVL2_REV_TRAFFIC_INFO = 841,
   EM_EVL2_ACCESS_STATE_INFO = 842,
   EM_EVL2_RTM3_T2P_INFO = 843,
   EM_EVL2_INFO_END = EM_EVL2_INFO_BEGIN + 9,

   /* XL2 :850~859*/
   EM_XL2_INFO_BEGIN = 850,
   EM_XL2_REV_STATE  = EM_XL2_INFO_BEGIN,
   EM_XL2_ACH_PROBE_INFO = 851,
   EM_XL2_VOICE_RATE_INFO = 852,
   EM_XL2_RLP_INFO = 853,
   EM_XL2_PS_RATE_INFO = 854,
   EM_XL2_SCH_ASSIGNED_RATE = 855,
   EM_XL2_INFO_END = EM_XL2_INFO_BEGIN + 9,

   /* C2K HLP: 860 ~ 879*/
   EM_C2K_HLP_INFO_BEGIN = 860,
   EM_C2K_HLP_TIMER_STATUS = EM_C2K_HLP_INFO_BEGIN,
   EM_C2K_HLP_CAM_STATE = 861,
   EM_C2K_HLP_NSPE_STATE = 862,
   EM_C2K_HLP_PDN_STATUS = 863,
   EM_C2K_HLP_PPPHA_STATUS = 864,
   EM_C2K_HLP_PPP_STATUS = 865,
   EM_C2K_HLP_RM_BUFQ_INFO = 866,
   EM_C2K_HLP_UM_BUFQ_INFO = 867,
   EM_C2K_HLP_PACKET_INFO = 868,
   EM_C2K_HLP_ABNORMAL_EVENT_INFO = 869,
   EM_C2K_HLP_INFO_END = EM_C2K_HLP_INFO_BEGIN + 19,

   /* C2K_L4(CVAL): 880 ~ 899 */
   EM_C2K_L4_INFO_BEGIN = 880,
   EM_C2K_L4_RTT_RADIO_INFO = EM_C2K_L4_INFO_BEGIN,
   EM_C2K_L4_RTT_INFO = 881,
   EM_C2K_L4_RTT_SCH_INFO = 882,
   EM_C2K_L4_RTT_STAT_INFO = 883,
   EM_C2K_L4_RTT_SERVING_NEIGHBR_SET_INFO = 884,
   EM_C2K_L4_EVDO_SERVING_INFO = 885,
   EM_C2K_L4_EVDO_ACTIVE_SET_INFO = 886,
   EM_C2K_L4_EVDO_CAND_SET_INFO = 887,
   EM_C2K_L4_EVDO_NGHDR_SET_INFO = 888,
   EM_C2K_L4_EVDO_FL_INFO = 889,
   EM_C2K_L4_EVDO_RL_INFO = 890,
   EM_C2K_L4_EVDO_STATE_INFO = 891,
   EM_C2K_L4_SPRINT_XRTT_INFO = 892,
   EM_C2K_L4_SPRINT_EVDO_INFO = 893,
   EM_C2K_L4_INFO_END = 899,
   EM_C2K_INFO_END = EM_C2K_L4_INFO_END,

   /* GMSS: 900 ~ 919 */
   GMSS_EM_INFO_BEGIN = 900,
   GMSS_EM_WORLD_PHONE_INFO = GMSS_EM_INFO_BEGIN,
   GMSS_EM_INFO_END = GMSS_EM_WORLD_PHONE_INFO+19,

   /* EL1 MDMI for VzW*/
   EM_EL1_STATUS_CSR_RPT_INFO        = 921, EM_EL1_MDMI_INFO_BEGIN = EM_EL1_STATUS_CSR_RPT_INFO,
   EM_EL1_STATUS_SRV_MEAS_RPT_INFO   = 922,
   EM_EL1_STATUS_PBCH_RPT_INFO       = 923,
   EM_EL1_STATUS_PCFICH_RPT_INFO     = 924,
   EM_EL1_STATUS_PDCCH_RPT_INFO      = 925,
   EM_EL1_STATUS_PDSCH_RPT_INFO      = 926,
   EM_EL1_STATUS_PHICH_RPT_INFO      = 927,
   EM_EL1_STATUS_PMCH_RPT_INFO       = 928,
   EM_EL1_STATUS_DCI_RPT_INFO        = 929,
   EM_EL1_STATUS_PUCCH_RPT_INFO      = 930,
   EM_EL1_STATUS_PUCCH_CSI_RPT_INFO  = 931,
   EM_EL1_STATUS_PUSCH_RPT_INFO      = 932,
   EM_EL1_STATUS_PUSCH_CSI_RPT_INFO  = 933,
   EM_EL1_STATUS_SRS_RPT_INFO        = 934,
   EM_EL1_STATUS_CELLTIME_RPT_INFO   = 935,
   EM_EL1_STATUS_SR_CFG_INFO         = 936,
   EM_EL1_STATUS_PRACH_INFO          = 937,
   EM_EL1_STATUS_RACH_INFO           = 938,
   EM_EL1_STATUS_PCH_INFO            = 939,
   EM_EL1_STATUS_TA_INFO             = 940,
   EM_EL1_STATUS_PHR_INFO            = 941,
   EM_EL1_STATUS_DL_TPUT_INFO        = 942,
   EM_EL1_STATUS_UL_TPUT_INFO        = 943,
   EM_EL1_STATUS_CSR_INFO            = 944,
   EM_EL1_MDMI_INFO_END              = EM_EL1_MDMI_INFO_BEGIN + 25,

   /* EPDCP */
   EM_EPDCP_DATA_INACTV_IND = 947,

   /* GL1: 950 ~ 959 */
   GL1_EM_TAS_INFO = 950,
   GL1_EM_RXD_INFO = 951,

   /* TDD L1 */
   TDD_EM_L1_TAS_INFO = 960, TDD_EM_L1_INFO_BEGIN = TDD_EM_L1_TAS_INFO,
   TDD_EM_L1_INFO_END = TDD_EM_L1_TAS_INFO + 4,

   EMM_L4C_REJECT_INFO = 965,
   EMM_L4C_TIMER_INFO = 966,
   EMM_L4C_CALL_INFO = 967,

   /*EL1*/
   EM_EL1_STATUS_PDSCH_INFO = 970,

   RAC_EM_NETWORK_TYPE_INFO = 971,

   /* ERLC */
   EM_ERLC_DATA_STALL = 972,

   /* LTECSR Range 2, the range should be 975 ~ 979 */
   LTECSR_EM_RTP_PERIODIC_RPT = 975,

/*================C2K_XCAL start====================*/
  /* C2K XCAL related EMs, maximum 30 EMs supported. */
  EM_C2K_XCAL_INFO_BEGIN = 980,
  EM_C2K_XCAL_OTA_EVENT_INFO = EM_C2K_XCAL_INFO_BEGIN,
  EM_C2K_XCAL_OTA_FDSCH_INFO = 981,
  EM_C2K_XCAL_OTA_RDSCH_INFO = 982,
  /* New C2K EMs should be added before  EM_C2K_XCAL_INFO_LAST, */
  EM_C2K_XCAL_INFO_LAST = EM_C2K_XCAL_OTA_RDSCH_INFO,
  EM_C2K_XCAL_INFO_END = EM_C2K_XCAL_INFO_BEGIN + 29,
  /*================C2K_XCAL end====================*/   

   /* D2/DDM: 1016-1023 */
   EM_DDM_INFO_BEGIN = 1016,
   EM_DDM_W2LHO_EVENT_INFO = EM_DDM_INFO_BEGIN,
   EM_DDM_L2WHO_EVENT_INFO = 1017,
   EM_DDM_IP_INFO = 1020,
   EM_DDM_LAST_ERROR_CODE_INFO = 1021,
   EM_DDM_PDN_EVENT_INFO = 1022,
   EM_DDM_INFO_END = EM_DDM_INFO_BEGIN + 7, /* 1023 */


